### ISSUE TITLE
Request Discord tutorial or example files

### ISSUE THREAD

**Issue by StrangerGithuber** [hybridauth/hybridauth#1000]
## Bug, feature or question?

Is this a bug, a feature request or a question?
Question

Give us a short description.
I can see many twitter, google, github tutorials and example files but I can't see Discord tutorials and example files. It would be nice if there will be some tutorial and example files for Discord too. I tried to create to Discord a php file help of hybridauth but I failed everytime. It seems that I am not smart enough for this but I need this for my little project. Can someone upload an example and/or create a tutorial for Discord?

### Version and provider

What version of Hybrid Auth does this relates to?
2.12

Is this an issue with a provider? If yes, which one?
No
### Reproduction

How can we replicate this issue?
N/A

**Comment by cookieman768** [comment]
What do you have so far? Do you have a configuration file? The only thing that would make Discord different than the others is the name in the configuration file.

**Comment by StrangerGithuber** [comment]
Ohh I see now. Thank you.
