### ISSUE TITLE
Google Provider returns 403 Error

### ISSUE THREAD

**Issue by Abolfazl** [hybridauth/hybridauth#1001]
### Bug, feature or question?

Bug

### Version and provider

V2 and V3
Problems with Google provider

### Reproduction

Was using [Opauth](https://github.com/opauth/opauth) until today because Google login would throw a 403. I did not change any code/credentials so I assumed it was the Oauth wrappers fault. I installed Hybridauth V3 and found that I was getting the same issue with Hybridauth where the page would return a 403 right after I gave it access to my Google account.

Has anyone been experiencing this problem with Google provider? I already have Google+ as an installed API so not sure where issue lies.

**Comment by ApacheEx** [comment]
just tried on production site where I have installed v2.12 and it works well.
Are you sure it's related to HA?

**Comment by Abolfazl** [comment]
Found it that it was messing with my apache mod_security because `.profile` was matched as a malicious URL. Ended up disabling that one and now everything works. No issue with Hybridauth :)
