### ISSUE TITLE
Twitter photoURL in http and not in https

### ISSUE THREAD

**Issue by steoo** [hybridauth/hybridauth#1004]
## Bug, feature or question?

Question

Twitter is responding `photoURL ` in `http` and not in `https`

### Version and provider

Version: 2.10.0 

Provider: Twitter

### Reproduction

Try authenticate with Twitter and print the `photoURL` field

**Comment by cookieman768** [comment]
It looks like that provider hasn’t been updated to support the https profile picture URL. It looks like a simple fix, I’ll make a pull request when I get the chance later today. You could manually fix this by editing the provider file for Twitter. Just change `profile_image_url` to `profile_image_url_https` in the profile section. In the future you can always do some simple troubleshooting by looking at the code and documentation of the provider. For your reference, [here](
https://developer.twitter.com/en/docs/accounts-and-users/user-profile-images-and-banners) is Twitter’s documentation.

**Comment by bologer** [comment]
@steoo it seems like Twitter returns URLs in http rather then https, you can't really do anything about it, unless replace it with https on the prover level. 

What do you @cookieman768 think?

**Comment by cookieman768** [comment]
> @steoo it seems like Twitter returns URLs in http rather then https, you can't really do anything about it, unless replace it with https on the prover level.
> 
> What do you @cookieman768 think?

It is just a simple change as I stated above. I could upload the change when I get access to my development computer.

**Comment by ApacheEx** [comment]
released in latest v3 and v2.
