### ISSUE TITLE
[provider] ORCID

### ISSUE THREAD

**Issue by filips123** [hybridauth/hybridauth#1006]
Add support for [ORCID](https://orcid.org/) provider. It uses RESTful API and OAuth 2.0.

Documentation for APIs: https://members.orcid.org/api/
Difference between APIs: https://orcid.org/about/membership/comparison/

Public API introduction: https://support.orcid.org/hc/en-us/articles/360006897174/
Public API documentation: https://members.orcid.org/api/about-public-api/

**Comment by pietsch** [comment]
Research communities would love to see this happen. In the long run, every researcher will have an ORCID iD and thus would be able to use this login method. Even today, any researcher can register with orcid.org for free and use their OAuth service, among other things.

**Comment by filips123** [comment]
I will create ORCID provider.

The problem is that [records](https://members.orcid.org/api/tutorial/read-orcid-records) are returned as [XML](https://github.com/ORCID/ORCID-Source/blob/master/orcid-model/src/main/resources/record_2.1/samples/read_samples/record-2.1.xml), but the parser will parse them as JSON so it will fail.

How to fix this?

**Comment by filips123** [comment]
I created #1054.
