### ISSUE TITLE
Authentication from subdomains

### ISSUE THREAD

**Issue by Engineer-UA** [hybridauth/hybridauth#1011]
## Bug, feature or question?

Hello.
I use this library in drupal 7 multi-site environment for allowing users to be logged in via google+. I have the main domain domain.com and subdomains: domain1.com, domain2.com, domain3.com,....
This library works great for the main domain, but it refuses to work while trying to log in from subdomains.

Any ideas, how to resolve the issue?

### Version and provider

The version of Hybrid Auth is 2.8.2

**Comment by ApacheEx** [comment]
> domain1.com, domain2.com, domain3.com

for me it's a list of domains. There is nothing related to domain.com (So, auth should be done via SSO)

or did you mean: domain1.domain.com, domain2.domain.com, domain3.domain.com, etc..?

**Comment by Engineer-UA** [comment]
Thanks for your answers, guys. 
I meant that domain1.com, domain2.com, domain3.com,.... are aliases of the domain.com. 
We encounter such problem just from time to time. Most likely it appears when we reach our quotas for using the service by Google.
