### ISSUE TITLE
Facebook: redirect_uri mismatch during exchanging code to access token

### ISSUE THREAD

**Issue by abolabo** [hybridauth/hybridauth#1017]
## Bug, feature or question?

Hi, i found a bug when i tried to use callback URI with some parameter contains slash.

### Version and provider
v3.0.0 RC 8 
Facebook

### Reproduction
Just set callback url like this
https://www.domain.com/index.php?rt=account/login&provider=facebook

On facebook app settings side you will see that it converts into 
https://www.domain.com/index.php?rt=account%2Flogin&provider=facebook

On hybridauth side facebook provider do 2 requests to api.
1. dialog by GET
url was https://www.facebook.com/dialog/oauth?response_type=code&client_id=***********&redirect_uri=https%3A%2F%2Fwww.domain.com%2Findex.php%3Frt%3Daccount%2Flogin%26provider%3Dfacebook&scope=email%2C+public_profile&state=***********

2. then we got code from facebook redirect and do second request but by POST method.
see debug info:
    [request] => Array
        (
            [uri] => https://graph.facebook.com/oauth/access_token
            [method] => POST
            [parameters] => Array
                (
                    [client_id] => *************
                    [client_secret] => ***********************************
                    [grant_type] => authorization_code
                    [redirect_uri] => https://www.domain.com/index.php?rt=account/login&provider=facebook
                    [code] => AQDEipAWVowETOSBtApG-LhflPQdFh4LCNnTwRTPvEog79JqgOzO5rF6kcalYOdPc1bkmw58Gg_-MRcHDOJBotFXDfefWcVDMJorA2PhlI9tmokhWYmX9YkX_ie6hchV9B1Cuo7-qHaVH2K_PnHYlI-LevZ9aN-T8kzE2Y2xecNx-IVjTNwGsv4a9WZpFz_pCOvfSgNKMdzDTcJNDJ3jEw4qxlTG-pi2JZ5_IgsjMDa0gYCAobaOn_SrxpDyRKHco8bcGktomz1zQg8Ks7vXpZsLasdlhW2YgWgwPJlEC1Y3FyQUeg9JJbXJVYatnnwJhcsAFs-k3Nv1aEcpi1TwwxV6
                )

            [headers] => Array
                (
                    [Accept] => */*
                    [Cache-Control] => max-age=0
                    [Connection] => keep-alive
                    [Expect] => 
                    [Pragma] => 
                )

        )

    [response] => Array
        (
            [code] => 400
            [headers] => Array
                (
                    [vary] => Accept-Encoding
                    [www_authenticate] => OAuth "Facebook Platform" "invalid_code" "Error validating verification code. Please make sure your redirect_uri is identical to the one you used in the OAuth dialog request"
                    [content_type] => application/json; charset=UTF-8
                    [facebook_api_version] => v2.8
                    [x_fb_rev] => 4595560
                    [access_control_allow_origin] => *
                    [cache_control] => no-store
                    [x_fb_trace_id] => H5qBL2zCxOw
                    [expires] => Sat, 01 Jan 2000 00:00:00 GMT
                    [strict_transport_security] => max-age=15552000; preload
                    [pragma] => no-cache
                    [x_fb_debug] => edpbkqu6cbdrxCo3TBRiFX/MFkCuHknvIBFLna3m6UZ55DSi3KTZ+LOgc8p8YNG2axvOGXrg66OmnRN20HpQTg==
                    [date] => Tue, 04 Dec 2018 15:08:12 GMT
                    [connection] => keep-alive
                    [content_length] => 217
                )

            [body] => {"error":{"message":"Error validating verification code. Please make sure your redirect_uri is identical to the one you used in the OAuth dialog request","type":"OAuthException","code":100,"fbtrace_id":"H5qBL2zCxOw"}}
        )

**Comment by chrisgraham** [comment]
I think redirect URIs using query strings are strongly discouraged in OAuth2, for security reasons. Some providers don't allow them.
I'd suggest using PHP sessions to store the provider, that's what I'm doing.

Perhaps the docs can therefore explain this and then this issue can be closed?
