### ISSUE TITLE
LinkedIn resource is no longer available

### ISSUE THREAD

**Issue by RazaGR** [hybridauth/hybridauth#1020]
## Bug, feature or question?
BUG
Short description.
By using linkedIn provider I received below error:

> Signed API request has returned an error. HTTP error 410. Raw Provider API response: { "errorCode": 0, "message": "This resource is no longer available under v1 APIs", "requestId": "U9LYRBTISK", "status": 410, "timestamp": 1544923836099 }.

### Version and provider

What version of Hybrid Auth does this relates to? **3.0.0-rc.8**

Is this an issue with a provider? If yes, which one? **LinkedIn**

### Reproduction

How can we replicate this issue?

>         $config = [
>             'callback' => 'hauth/login/'.$provider,
>             'providers' => [
>                 'LinkedIn' => [
>                     'enabled' => true,
>                     'keys'    => [ 'id' => '', 'secret' => '' ],
>                 ]
>             ],
>         ];
>             $hybridauth = new Hybridauth\Hybridauth($config);
>             $service = $hybridauth->authenticate($provider);
>             $isConnected = $service->isConnected();
>             $user_profile = $service->getUserProfile();
>             $provider_uid = $user_profile->identifier;

**Comment by ApacheEx** [comment]
@Divxtaman, thanks for reporting. 
Could you please upgrade and check if everything works?

**Comment by ApacheEx** [comment]
thanks for more details. I will check tomorrow, seems need to migrate to api v2 with new endpoints

**Comment by klausi** [comment]
I think this is relevant: https://github.com/thephpleague/oauth2-linkedin/pull/15/files#diff-9afbe6be64e29468bf8463b4b219e0f5

https://api.linkedin.com/v1/people/~:(' . $fields . ')?format=json' changed to https://api.linkedin.com/v2/me?fields='.$fields

**Comment by ApacheEx** [comment]
seems we should migrate v1 to v2 by this guide:
https://docs.microsoft.com/en-us/linkedin/consumer/integrations/self-serve/migration-faq?context=linkedin/consumer/context

so, it's share + login functionality.

**Comment by ApacheEx** [comment]
I give it more priority, because of:
> Starting March 1, 2019, LinkedIn will deprecate use of its v1 APIs

**Comment by klausi** [comment]
Pull request is in #1048

**Comment by RazaGR** [comment]
@klausi that PR #1048 isn't for V3 of HybridAuth, but it did help me to find the issues
@ApacheEx you can check the below and push changes, I have tested it and it works 

```
<?php
/*!
 * Hybridauth
 * https://hybridauth.github.io | https://github.com/hybridauth/hybridauth
 *  (c) 2017 Hybridauth authors | https://hybridauth.github.io/license.html
 */

namespace Hybridauth\Provider;

use Hybridauth\Adapter\OAuth2;
use Hybridauth\Data;
use Hybridauth\Exception\UnexpectedApiResponseException;
use Hybridauth\User;

/**
 * LinkedIn OAuth2 provider adapter.
 */
class LinkedIn extends OAuth2
{
    /**
     * {@inheritdoc}
     */
    public $scope = 'r_liteprofile r_emailaddress w_member_social';

    /**
     * {@inheritdoc}
     */
    protected $apiBaseUrl = 'https://api.linkedin.com/v2/';

    /**
     * {@inheritdoc}
     */
    protected $authorizeUrl = 'https://www.linkedin.com/oauth/v2/authorization';

    /**
     * {@inheritdoc}
     */
    protected $accessTokenUrl = 'https://www.linkedin.com/oauth/v2/accessToken';

    /**
     * {@inheritdoc}
     */
    protected $apiDocumentation = 'https://developer.linkedin.com/docs/oauth2';

    /**
     * {@inheritdoc}
     */
    public function getUserProfile()
    {
        $fields = [
            "id",
            "firstName",
            "lastName",
            "profilePicture(displayImage~:playableStreams)",
        ];

        if ($this->config->get('photo_size') === 'original') {
            $fields[] = 'picture-urls::(original)';
        }

        $response = $this->apiRequest('me?projection=(' . implode(',', $fields) . ')');
        $data     = new Data\Collection($response);

        if (!$data->exists('id')) {
            throw new UnexpectedApiResponseException('Provider API returned an unexpected response.');
        }

        $userProfile = new User\Profile();

        $userProfile->identifier  = $data->get('id');
        $userProfile->firstName   = $data->filter('firstName')->filter('localized')->get('en_US');
        $userProfile->lastName    = $data->filter('lastName')->filter('localized')->get('en_US');
        $userProfile->photoURL    = $this->getUserPhotoUrl($data->filter('profilePicture')->filter('displayImage~')->get('elements'));
        $userProfile->email       = $this->getUserEmail();

        if ($this->config->get('photo_size') === 'original') {
            $originals = $data->get('pictureUrls');
            if (!empty($originals->values)) {
                $userProfile->photoURL = $originals->values[0];
            }
        }

        $userProfile->emailVerified = $userProfile->email;

        $userProfile->displayName = trim($userProfile->firstName . ' ' . $userProfile->lastName);

        return $userProfile;
    }

    /**
     * {@inheritdoc}
     */
    public function getUserPhotoUrl($elements)
    {
        $photoURL = '';
        if(is_array($elements)){
            // I need the largest picture that's why I am choosing end
            $element = end($elements);
            $photoURL = $element->identifiers[0]->identifier;
        }
        return $photoURL;
    }
    /**
     * {@inheritdoc}
     */
    public function getUserEmail()
    {
        $response = $this->apiRequest('emailAddress?q=members&projection=(elements*(handle~))');
        return isset($response->elements[0]->{'handle~'}->emailAddress) ? $response->elements[0]->{'handle~'}->emailAddress : "";
    }
    /**
     * {@inheritdoc}
     *
     * @see https://developer.linkedin.com/docs/share-on-linkedin
     */
    public function setUserStatus($status, $companyId = null)
    {
        $status = is_string($status) ? ['comment' => $status] : $status;
        if (!isset($status['visibility'])) {
            $status['visibility']['code'] = 'anyone';
        }

        $headers = [
            'Content-Type' => 'application/json',
            'x-li-format'  => 'json',
        ];

        $url = $companyId ? "companies/{$companyId}/shares?format=json" : "people/~/shares?format=json";
        $response = $this->apiRequest($url, 'POST', $status, $headers);

        return $response;
    }
}

```

**Comment by RazaGR** [comment]
Got some time and updated `setUserStatus` code, it works now
updated above code @ApacheEx  all good to push

**Comment by jaimin-vitapio** [comment]
Its work fine but not getting other information like **birthdate** , **gender**  , **address** etc not getting its work fine in V1. but not get response in V2

so please help me :)

**Comment by RazaGR** [comment]
@jaimin-vitapio linkedIn deosn't provide those details in v2 r_liteprofile
https://docs.microsoft.com/en-us/linkedin/shared/references/v2/profile/lite-profile?context=linkedin/consumer/context

to access additional fields requires that you apply for and are granted access to this information from LinkedIn.  https://docs.microsoft.com/en-us/linkedin/shared/references/v2/profile/full-profile?context=linkedin/consumer/context

**Comment by ApacheEx** [comment]
Finally, released in https://github.com/hybridauth/hybridauth/releases/tag/v3.0.0-rc.10

A huge thanks to everyone for helping (especially @RazaGR) 🥇 

For v2 there is PR and it will be released soon 😏

**Comment by jaimin-hothi** [comment]
@RazaGR  Thanks for information.
 but when $scope change **r_liteprofile** to **r_fullprofile**   so give error 

> User profile request failed! LinkedIn returned an invalid response: stdClass::__set_state(array( 'serviceErrorCode' => 100, 'message' => 'Not enough permissions to access: GET /me', 'status' => 403, ))

can you help me how i can fix that

**Comment by ApacheEx** [comment]
@jaimin-hothi  -


For getting permission to access r_fullprofile, you will have to apply to become a member of a relevant [Partner Program](https://developer.linkedin.com/partner-programs).

**Comment by jaimin-hothi** [comment]
@ApacheEx  Okay, Thanks You very much for information.

**Comment by Dacesilian** [comment]
Now I think, it's not possible to use profile API anymore for non-authorized apps, is it? I get error for https://api.linkedin.com/v2/me and on docs page, there is a note for whole Profile API.

> The use of this API is restricted to those developers approved by LinkedIn and subject to applicable data restrictions in their agreements. 

`Signed API request has returned an error. HTTP error 403. Raw Provider API response: {"serviceErrorCode":100,"message":"Not enough permissions to access: GET /me","status":403}.`

**Comment by danieldhz** [comment]
Hi all!
Does anyone know whether LinkedIn still allows POST message and connection request API calls? even though the [documentation](https://developer.linkedin.com/docs/v1/communications/messaging-between-connections-api) for it still exist

**Comment by suneelkumarsk** [comment]
https://api.linkedin.com/v2/me This linkedin api is giving me this error  -> Not enough permissions to access: GET /me.
while i am calling this api with loged in user access token. Does anyone  anyone know why this is happening  with this linkedin api ??
