### ISSUE TITLE
Bug/Question Discord Authorization Header Issue

### ISSUE THREAD

**Issue by Jaffa-Cakes** [hybridauth/hybridauth#1023]
## Bug, feature or question?

**Is this a bug, a feature request or a question?**

This may just be my fault, but I may have also found a bug.

**Give us a short description.**

Discord provides a 401 error when responding to an authorised login attempt.
`Oops, we ran into an issue! Unable to exchange code for API access token. HTTP error 401. Raw Provider API response: {"error": "access_denied"}.`
401 Corresponds to the following: _https://discordapp.com/developers/docs/topics/opcodes-and-status-codes#http_
> 401 (UNAUTHORIZED) - The Authorization header was missing or invalid

### Version and provider

**What version of Hybrid Auth does this relate to?**

3.0.0-rc.8

**Is this an issue with a provider? If yes, which one?**

Discord

### Reproduction

**How can we replicate this issue?**

```
$configha = [
	'callback' => ($domain . $_SERVER['REQUEST_URI']),
	'keys' => [
			'id' => ($discord["clientID"]),
			'secret' => ($discord["secretKey"])
	],
];

try {
	$adapter = new Hybridauth\Provider\Discord($configha);
	$adapter->authenticate("Discord");
	$userProfile = $adapter->getUserProfile();
	$adapter->disconnect();
}
catch(\Exception $e) {
	die('Oops, we ran into an issue! ' . $e->getMessage());
}
```
Testing with the Client Credentials Grant seems to work normally, but can only be used for testing. _https://discordapp.com/developers/docs/topics/oauth2#client-credentials-grant_

**Comment by Jaffa-Cakes** [comment]
I have discovered the problem, the REQUEST_URI variable does not play nice with discord, replacing this with the URI in quotes seems to work.
 
I still do not know why this is as the URI is the exact same as when it is manually entered.

**Comment by chrisgraham** [comment]
`$_SERVER['REQUEST_URI']` contains the query string (the bit after "?"). I think you probably got confused during debugging sometimes with a query string.
Query strings are a bad idea with OAuth, and regardless it would likely of not matched strictly against one of the approved redirect URIs.

I think this issue can be closed.
