### ISSUE TITLE
Login with google+ going deprecated ?

### ISSUE THREAD

**Issue by zorn-v** [hybridauth/hybridauth#1024]
https://github.com/zorn-v/nextcloud-social-login/issues/69

**Comment by AbhishekDas** [comment]
+1 from side. On March 7, 2019, all Google+ APIs and Google+ Sign-in will be shut down completely.

**Comment by jinjie** [comment]
My application is using hybridauth and I'm hesitant to change to another method of login with Google. Is there a workaround for hybridauth to move to Google Sign-in with minimal code changes?

**Comment by zorn-v** [comment]
I think there is only need to remove some scopes (and maybe functionality related to it) in hybridauth lib.
https://cloud.google.com/blog/products/g-suite/elevating-user-trust-in-our-api-ecosystems

**Comment by e-motiv** [comment]
> I think there is only need to remove some scopes (and maybe functionality related to it) in hybridauth lib.
> https://cloud.google.com/blog/products/g-suite/elevating-user-trust-in-our-api-ecosystems

It indeed looks like it's that simple and only work on the hybridauth developers' side, not on their user-developers side. It looks like G+ to G Sign in will use the same client id etc and nothing has to be changed on the project in Google.
I got these impression from this page: https://developers.google.com/identity/sign-in/web/quick-migration-guide#migrate_a_hybrid_server-side_flow

**Comment by e-motiv** [comment]
Though on this page (https://developers.google.com/identity/sign-in/web/sign-in#before_you_begin) "Configure a project" button, it seems I can configure my existing project as new. I'm afraid to go through with it as it may block my current google logins on my site.
As usual, Google help & support is seriously lacking clear explanations..

**Comment by stratege1401** [comment]
i have tried to used Oauth google, and it failed.

check this https://developers.google.com/identity/sign-in/web/

**Comment by stratege1401** [comment]
Yes.

When I first received the warning email, I didn't saw the new option for creating a new Oauth key v2 on my Google Dev console https://console.developers.google.com/apis/credentials?project=my-projec-YOURIDHERE

Easy fix is to create v2 key, to change it in nextcloud and then delete the v1 key to avoid receiving Google warning emails.

**Comment by duartegarin** [comment]
@stratege1401 Not sure how that will fix the problem? Hybridauth is currently depending on Google Plus API, so when it gets shutdown it will stop working. Just trying to understand if there is a working fix for this in this lib?

**Comment by stratege1401** [comment]
The app is sending the api key to google server for auth.

If your apikey is a v1 Aouth key, you will fall on the deprecated problem next march
the v1 format is looking like that:  AIzaSyxxxxxxLyqMRcivb_gg6tcxxxxxxLmAg

If your apikey is a v2 Aouth key, your problem is fixed.
The v2 format is like: 8368xxxxxx23-uke25fmjdxxxxxxxx9a8r2iur302joa2.apps.googleusercontent.com

**Comment by tszming** [comment]
According to the Google email I received, the api call will start stop working at the end of this month, not March

> On March 7, 2019, all Google+ APIs and Google+ Sign-in will be shut down completely. This will be a progressive shutdown beginning in late January, with calls to these APIs starting to intermittently fail as early as January 28, 2019.

**Comment by stratege1401** [comment]
It is not Google api Shutting down. It is the V1 key been discontinued...

**Comment by tszming** [comment]
> It is not Google api Shutting down. It is the V1 key been discontinued... But as always with Google, they do what they want

Google+ API Shutdown
On March 7, 2019, all Google+ APIs will be shut down. This will be a progressive shutdown beginning in late January, with calls to these APIs starting to intermittently fail as early as January 28, 2019.

https://developers.google.com/+/api-shutdown

**Comment by duartegarin** [comment]
Yes, the API **is** being shutdown, or at least that is what their emails are saying. Calls such as people.get won't work anymore. I stress the fact that is going to start causing problems as of the end of this month so it's as critical as should be.
Does anyone have at least a workaround?

**Comment by ApacheEx** [comment]
Thanks @miled for fix. I've checked locally, works well for me.

Released in RC9. 🥇

**Comment by e-motiv** [comment]
Can we get some update doc on this?  Like, is there anything else to do but to download? It's very unclear by this thread. Also, none of the proposed key changes listed here are available to me ór I'm too scared to go ahead with some of them, as they might break my logins if not done at the right time...
Thank you already for the fix. I love you, developers!

**Comment by ApacheEx** [comment]
There are no docs to update 😄 
Everything is the same. We just remove dependency from the Google+ Sign-in.

- if you are already on HA 3.x, you just need to pull (upgrade) the newest changes.
- not sure if it's required step but if you are still use v1 key, just recreate it to v2 (e.g `[CLIENT_ID].apps.googleusercontent.com`)

**Comment by jinjie** [comment]
> Released in RC9. 🥇

I am still not ready to use HA v3. Will the update go into v2 stable release? Since the api is going to be deprecated fast.

**Comment by PowerKiKi** [comment]
This works well for me too, thank you.

**Comment by ApacheEx** [comment]
https://github.com/hybridauth/hybridauth/releases/tag/v2.13.0

from now, v2 supports Google Sign-in as well 🎉

**Comment by e-motiv** [comment]
> 
> 
> There are no docs to update 😄
> Everything is the same. We just remove dependency from the Google+ Sign-in and replace it to Google Sign-in.
> 
>     * if you are already on HA 3.x, you just need to pull (upgrade) the newest changes.
> 
>     * not sure if it's required step but if you are still use v1 key, just recreate it to v2 (e.g `[CLIENT_ID].apps.googleusercontent.com`)

I didn't mean like the HA documentation or something if you thought that.. Just some document or at least warning for developers using HA and who might not read this thread. But yeah, I'm not sure if it's really necessary as all of them might end here after reading the official google e-mail, right? Anyway, you guys decide. No answer needed. ;) I, myself am settled with your answer here and the one above showing the difference between v1 and v2 keys. Thanks.

**Comment by elyobo** [comment]
Thanks for the fixes @ApacheEx :+1:
