### ISSUE TITLE
Support Microsoft authentication via tenant endpoints

### ISSUE THREAD

**Issue by vboctor** [hybridauth/hybridauth#1025]
## Bug, feature or question?

feature request

The MicrosoftGraph authenticator at the moment always uses the common tenant endpoint to authenticate a user.  This is useful to authenticate users from any tenant or ones from MSA consumer users.  However, in some cases it is desired to limited authentication to users that belong to a specific tenant.  In such cases, instead of using "common" in the authorization URL, using the tenant domain would scope such authentication, helps with selecting account if multiple are signed in, and helps the application to scope auth to a single source tenant.

### Version and provider

What version of Hybrid Auth does this relates to?

v3.0.0-rc.8

Is this an issue with a provider? If yes, which one?

MicrosoftGraph

### Reproduction

How can we replicate this issue?

In my application I just use the MicrosoftGraph for authentication and authorization for scopes openid and user.read.  The scenario is really an authentication scenario rather than an authorization scenario.  I'm planning to look into getting user information via openid rather than by calling `/me` on the graph, but haven't done that yet.  So the requirements for the app is to scope users for a specific tenant for the app rather than any user to access Microsoft Graph APIs and get access to their data.

There is no really steps to reproduce since this is more of a feature request than a bug.

**Comment by chrisgraham** [comment]
Related to this, I think most users will want the 'consumers' tenant. I'm about to make a pull request which fixes this and some other issues with the provider.
