### ISSUE TITLE
Add v2.13.0 on Packagist

### ISSUE THREAD

**Issue by gsgwebdev** [hybridauth/hybridauth#1032]
I'd like to install the v2.13.0 using composer, but I cannot find the version on Packagist.

Can you please add the latest version?

**Comment by ApacheEx** [comment]
@StorytellerCZ can you please check? it seems I don't have access to manage Packagist.

**Comment by ivanmunozruiz** [comment]
Ey, I can't install it using composer, can you please enable it?

**Comment by pavs94** [comment]
Can't install it via composer too.

**Comment by ivanmunozruiz** [comment]
any news about it? I need it please

**Comment by Carobit** [comment]
Now v2.13.0 is available on packaginst, however it seems something's wrong with the tag versioning. The v2.13 points to the v2.12 version. eg. https://github.com/hybridauth/hybridauth/tree/v2.13.0
Thus installing ^2.13 via composer actually installs v2.12

**Comment by ApacheEx** [comment]
should be good now with v2.14.0

**Comment by ApacheEx** [comment]
finally works well here: https://packagist.org/packages/hybridauth/hybridauth#v2.15.1
