### ISSUE TITLE
Duplicate milestones for v3

### ISSUE THREAD

**Issue by filips123** [hybridauth/hybridauth#1035]
For the HybridAuth issues on GitHub, there are three milestones (`2.x`, `3.x` and `3.0.0`).

It looks like milestones `3.x` and `3.0.0` represent same thing (version 3). Because of that, it is harder to organize issues, so I would recommend to delete (close) one of them.

I would recommend to close milestone `3.x` (because it has less issues that `3.0.0`), transfer all it's issues to `3.0.0` and rename it back to `3.x (because there is already `2.x` and names should be standardized).

**Comment by StorytellerCZ** [comment]
Wrong. `3.0.0` is about releasing the initial `v3.0.0`. `3.x` is for everything after that.

**Comment by filips123** [comment]
Ok, this makes sense.
