### ISSUE TITLE
Bypass HYBRIDAUTH::STORAGE using own session/cache handler

### ISSUE THREAD

**Issue by Yamakasi** [hybridauth/hybridauth#1036]
## Bug, feature or question?

Question

### Version and provider

All, All

### Reproduction

The provider "credentials", so access_token, token_type, expires_in, expires_at are default stored using the default PHP session handler and I'm using my own where I can get and set.

Is it possible to not store by default and use your own ?

**Comment by Yamakasi** [comment]
Hi,

Indeed v3, I was not 100% sure if I could do it some way like in #872 but it seems sane.

My question here remains, is this PSR, I think not fully, might be good to make it that way ?

It helps ;) Thanks!

**Comment by chrisgraham** [comment]
I think this issue can be closed.
#828 already covers the final part of it.
