### ISSUE TITLE
[RESOLVED] Unable to exchange code for API access token

### ISSUE THREAD

**Issue by gabrielferreiraa** [hybridauth/hybridauth#1038]
## Bug/question

I have successfully implemented Facebook / LinkedIn Login in my local environment. However, in production when executing the `(new Hybridauth ($config))->authenticate($provider)` method, the code goes to catch and this error is displayed:

```Unable to exchange code for API access token. HTTP client error: Operation timed out after 0 milliseconds with 0 out of 0 bytes received.```

I already double checked the app IDs and callback URLs and they are all correct.

In my local environment communication with the social network is fast, but in production environment there is a delay for the response and then the above error appears.

PHP version: `7.1`

### Version and provider

Version of HybridAuth: `hybridauth / hybridauth ':" ~ 3.0`

All providers

https://stackoverflow.com/questions/54295549/hybridauth-unable-to-exchange-code-for-api-access-token

**Comment by Yamakasi** [comment]
Sounds like some early/overwritten headers ? Have you checked those and saw what kind of requests are on done on the same time this issue occures ?

**Comment by gabrielferreiraa** [comment]
The problem was solved, it was a block on the outgoing requests in the server firewall.
