### ISSUE TITLE
Google timout on 2.5.1

### ISSUE THREAD

**Issue by kaverna** [hybridauth/hybridauth#1041]
## Bug, feature or question?

Is this a bug, a feature request or a question?
-> Bug.

Give us a short description.

-> If After a timeout, the Google auth does not recover nicely, breaking with an error. Facebook and LinkeIn seem to not present this error with the same implementation.

### Version and provider

What version of Hybrid Auth does this relates to?
-> 2.5.1

Is this an issue with a provider? If yes, which one?
-> Google. I didn't see this happening on any other provider.

### Reproduction

How can we replicate this issue?

-> Auth with Google 

-> Wait for google to timeout (not sure how many minutes). See the error below being thrown:

Fatal error: Uncaught Hybridauth\Exception\HttpRequestFailedException: Unable to refresh the access token. HTTP error 400. Raw Provider API response: { "error": "invalid_request", "error_description": "Missing required parameter: refresh_token" }. in /var/www/gonna/vendor/hybridauth/hybridauth/src/Adapter/AbstractAdapter.php:360 Stack trace: #0 /var/www/gonna/vendor/hybridauth/hybridauth/src/Adapter/OAuth2.php(587): Hybridauth\Adapter\AbstractAdapter->validateApiResponse('Unable to refre...') #1 /var/www/gonna/vendor/hybridauth/hybridauth/src/Adapter/OAuth2.php(665): Hybridauth\Adapter\OAuth2->refreshAccessToken() #2 /var/www/gonna/vendor/hybridauth/hybridauth/src/Provider/Google.php(99): Hybridauth\Adapter\OAuth2->apiRequest('oauth2/v3/useri...') #3 /var/www/gonna/bdados.php(96): Hybridauth\Provider\Google->getUserProfile() #4 /var/www/gonna/index.php(2): require_once('/var/www/gonna/...') #5 {main} thrown in /var/www/gonna/vendor/hybridauth/hybridauth/src/Adapter/AbstractAdapter.php on line 360

**Comment by ApacheEx** [comment]
2.5.1 ? there is already 2.13. Please upgrade
