### ISSUE TITLE
Google Timeout

### ISSUE THREAD

**Issue by kaverna** [hybridauth/hybridauth#1044]
## Bug, feature or question?

Is this a bug, a feature request or a question?

**Bug**

Give us a short description.

**Google timeout after some period of time. Probably around 1h** 

### Version and provider

What version of Hybrid Auth does this relates to?
** Lastest dev-master (36e92a0)  **

Is this an issue with a provider? If yes, which one?
Google

### Reproduction

How can we replicate this issue?

-> Use Google to Login
-> Keep google logged-in for about 1h (not sure the real time)
-> the following error will be thrown upon calling getUserProfile() :

** Fatal error: Uncaught Hybridauth\Exception\HttpRequestFailedException: Unable to refresh the access token. HTTP error 400. Raw Provider API response: { "error": "invalid_request", "error_description": "Missing required parameter: refresh_token" }. in /vendor/hybridauth/hybridauth/src/Adapter/AbstractAdapter.php:363 Stack trace: #0 /vendor/hybridauth/hybridauth/src/Adapter/OAuth2.php(587): Hybridauth\Adapter\AbstractAdapter->validateApiResponse('Unable to refre...') #1 /vendor/hybridauth/hybridauth/src/Adapter/OAuth2.php(665): Hybridauth\Adapter\OAuth2->refreshAccessToken() #2 /vendor/hybridauth/hybridauth/src/Provider/Google.php(99): Hybridauth\Adapter\OAuth2->apiRequest('oauth2/v3/useri...') #3 
Hybridauth\Provider\Google->getUserProfile() #4  **

**Comment by REJack** [comment]
This sounds like your session is removed/destroyed after 1h, if you use PHP with default settings this should appears after 24 minutes without moving on the page.

**Comment by ApacheEx** [comment]
sounds like @REJack is totally right. It's related to session issue.
