### ISSUE TITLE
CHANGELOG has not been updated since 2.12.0 release

### ISSUE THREAD

**Issue by TyIsI** [hybridauth/hybridauth#1047]
## Bug

While I am updating from from 2.10.0 to 2.13.0, I noticed that the CHANGELOG file was not updated in any of the releases after 2.11.0.

### Version and provider

- 2.12.0
- 2.13.0

### Reproduction

Download the following files:
- https://github.com/hybridauth/hybridauth/archive/v2.10.0.zip
- https://github.com/hybridauth/hybridauth/archive/v2.11.0.zip
- https://github.com/hybridauth/hybridauth/archive/v2.12.0.zip
- https://github.com/hybridauth/hybridauth/archive/v2.13.0.zip

Unpack the files:
```
unzip v2.10.0.zip
unzip v2.11.0.zip
unzip v2.12.0.zip
unzip v2.13.0.zip
```

Compare the CHANGELOG files:
```
diff hybridauth-2.10.0/CHANGELOG hybridauth-2.11.0/CHANGELOG
diff hybridauth-2.11.0/CHANGELOG hybridauth-2.12.0/CHANGELOG
diff hybridauth-2.12.0/CHANGELOG hybridauth-2.13.0/CHANGELOG
```

**Comment by ApacheEx** [comment]
fixed, see https://github.com/hybridauth/hybridauth/commit/f37b28a2e67d62951aa8f4ef978ea83d388e8cd7.
