### ISSUE TITLE
Error when serializing exception in php 5.3

### ISSUE THREAD

**Issue by ADmad** [hybridauth/hybridauth#105]
In 5.3 [this](https://github.com/hybridauth/hybridauth/blob/v2.0.10/hybridauth/Hybrid/Error.php#L26) particular statement causes an error `Serialization of 'Closure' is not allowed` in `Storage` class when trying to serialize the previous exception instance.

I got it when using OpenID provider for google and on the google page selecting "No thanks" instead of allowing access.

**Comment by karthikeyan-manivasagam** [comment]
Can be fixed by these steps. 

http://monkpal.com/exception-serialization-closure-not-allowed-hybridauth-linkedin-phalcon
