### ISSUE TITLE
Twitter login fail

### ISSUE THREAD

**Issue by nightw0lv** [hybridauth/hybridauth#1051]
## Bug, feature or question?

Is this a bug, a feature request or a question?
bug, it was working fine a week ago that last tried to use twitter
Give us a short description.
login error
### Version and provider

What version of Hybrid Auth does this relates to?
3
Is this an issue with a provider? If yes, which one?
twitter
### Reproduction

How can we replicate this issue?
just login with twitter

Fatal error: Uncaught Hybridauth\Exception\InvalidOauthTokenException: Expecting a non-null oauth_token to continue the authorization flow. in C:\xampp\htdocs\server\third_party\hybridauth\src\Adapter\OAuth1.php:279 Stack trace: #0 C:\xampp\htdocs\server\third_party\hybridauth\src\Adapter\OAuth1.php(214): Hybridauth\Adapter\OAuth1->authenticateFinish() #1 C:\xampp\htdocs\server\third_party\hybridauth\src\Hybridauth.php(103): Hybridauth\Adapter\OAuth1->authenticate() #2 C:\xampp\htdocs\server\public\app\LoginService.php(113): Hybridauth\Hybridauth->authenticate('Twitter') #3 C:\xampp\htdocs\server\public\app\LoginService.php(88): LoginService->login() #4 C:\xampp\htdocs\server\public\app\LoginService.php(175): LoginService->__construct() #5 {main} thrown in C:\xampp\htdocs\server\third_party\hybridauth\src\Adapter\OAuth1.php on line 279

**Comment by nightw0lv** [comment]
http://prntscr.com/mmsmya

**Comment by ApacheEx** [comment]
instead of query you can use own callback for each social netowrk. Or use session variable as described here: https://github.com/hybridauth/hybridauth/tree/master/examples/example_06
