### ISSUE TITLE
Install Hybridauth via composer

### ISSUE THREAD

**Issue by cirolaferrara** [hybridauth/hybridauth#1053]
According [documentation](https://hybridauth.github.io/install.html):
`{
    "require" : {
        "hybridauth/hybridauth" : "~3.0"
    }
}`

I have:

> Loading composer repositories with package information
> Updating dependencies (including require-dev)
> Your requirements could not be resolved to an installable set of packages.
> 
>   Problem 1
>     - The requested package hybridauth/hybridauth ~3.0 is satisfiable by hybrida
> uth/hybridauth[3.0.x-dev, v3.0.0-beta.1, v3.0.0-beta.2, v3.0.0-beta.3, v3.0.0-be
> ta.4, v3.0.0-rc.1, v3.0.0-rc.2, v3.0.0-rc.3, v3.0.0-rc.4, v3.0.0-rc.5, v3.0.0-rc
> .6, v3.0.0-rc.7, v3.0.0-rc.8, v3.0.0-rc.9] but these conflict with your requirem
> ents or minimum-stability.

**Comment by filips123** [comment]
This is because 3.0 is currently RC.

You should use
```
{ "require" : { "hybridauth/hybridauth" : "~3.0@rc" } }
```

**Comment by jbostoen** [comment]
I've also installed HybridAuth rc9 using composer, but the autoload doesn't seem to work? Known issue?

It only works if I use 
`
require 'vendor/hybridauth/hybridauth/src/autoload.php';
`

Composer's vendor/autoload.php doens't seem to contain anything.

**Comment by ApacheEx** [comment]
pls use `composer require 'hybridauth/hybridauth:3.x'` for now. It generates autoload correctly.

**Comment by jbostoen** [comment]
Weird, I tried using `composer require 'hybridauth/hybridauth:3.x'`

I still get this:

```

./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package hybridauth/hybridauth 3.x is satisfiable by hybridauth/hybridauth[3.0.x-dev, v3.0.0-beta.1, v3.0.0-beta.2, v3.0.0-beta.3, v3.0.0-beta.4, v3.0.0-rc.1, v3.0.0-rc.10, v3.0.0-rc.2, v3.0.0-rc.3, v3.0.0-rc.4, v3.0.0-rc.5, v3.0.0-rc.6, v3.0.0-rc.7, v3.0.0-rc.8, v3.0.0-rc.9] but these conflict with your requirements or minimum-stability.

```

**Comment by filips123** [comment]
This is probably because v3 is still RC.

Try:

```
composer require 'hybridauth/hybridauth:3.x@rc'
```
