### ISSUE TITLE
Can't login yahoo. Retrieving email failed

### ISSUE THREAD

**Issue by monsterMidhun** [hybridauth/hybridauth#1055]
## Bug
I have created a yahoo app and added to my site
. 
I want to retrieve user email address when they login..

But both email & email verified field seems too be empty

**Comment by ApacheEx** [comment]
should be fixed in #986. and released in 3.0-RC10 today

**Comment by malakaisbest** [comment]
hi all,
I'm facing the same issue on the yahoo provider.
not retrieve the user's email address. but can retrieve names, profile pictures and other data.

my yahoo app
![image](https://user-images.githubusercontent.com/12796396/178635609-116e40c8-3e9f-4056-9da1-bd14c9f64623.png)

my hybridauth version is 3.8.0

I have already tried with adding the following scopes. but nothing changed.
 "scope"   => ['openid','sdpp-r', 'sdps-r']

any suggestions?
thanks

**Comment by malakaisbest** [comment]
i change vendor/hybridauth/hybridauth/src/Provider/Yahoo.php line 28

protected $scope =**'profile';**   to    protected $scope = **'openid';**

after that when user log in through yahoo, it asks for new permission to view email address.
after granting access, I can retrieve the user's email address.
![image](https://user-images.githubusercontent.com/12796396/178642217-b015d284-cb26-46a2-a206-210a3a4719be.png)
