### ISSUE TITLE
LinkedIn user profile firstname and lastname localized

### ISSUE THREAD

**Issue by Luca-Extera** [hybridauth/hybridauth#1063]
Linkedin provider doesn't retrieve firstname and lastname if the user's preferred locale is different from en_US. I suggest to change these lines:

$userProfile->firstName   = $data->filter('firstName')->filter('localized')->get('en_US');
$userProfile->lastName    = $data->filter('lastName')->filter('localized')->get('en_US');

with this **patch**

$firstName = $data->filter('firstName');
$firstNameLocale = $firstName->filter('preferredLocale');
$userProfile->firstName   = $data->filter('firstName')->filter('localized')->get($firstNameLocale->get('language').'_'.$firstNameLocale->get('country'));

$lastName = $data->filter('lastName');
$lastNameLocale = $lastName->filter('preferredLocale');
$userProfile->lastName   = $data->filter('firstName')->filter('localized')->get($lastNameLocale->get('language').'_'.$lastNameLocale->get('country'));

**Comment by Yamakasi** [comment]
Do you have this working with r_liteprofile ?

I get a 403 not enough rights every time using the Linkedin V2 API
