### ISSUE TITLE
Twitter auth problem

### ISSUE THREAD

**Issue by nuryagdym** [hybridauth/hybridauth#1064]
Hello, 
I am trying to tweet using access_token and access_token_secret that I get from Twitter.
here is my configs:
`$config['hybrid_auth'] = array(
    'callback' => '/callback',
    'providers' => [
        'Twitter' => [ 
            'authorize' => true,
            'keys'    => [ 'id' => 'id', 'secret' => secret'' ],
            'tokens'  => [ 'access_token' => 'access_token', 'access_token_secret' => 'access_token_secret' ]
        ]
    ],
    'debug_model' => true
);`

here is my php code:
`$this->load->library('hybrid_auth_lib');

		try {
			$adapter = $this->hybrid_auth_lib->authenticate('Twitter');
			$userProfile = $adapter->getUserProfile();
			print_r($userProfile);
		}catch( Exception $e ){
			echo $e->getMessage();
		}`
I am getting 
`Exception: Call to a member function deleteMatch() on null /home/invalert/public_html/ci/application/third_party/hybridauth-3.0/src/Adapter/DataStoreTrait.php 72`
When I run authenticate() function

Can anybody help me please?

**Comment by nuryagdym** [comment]
I think I solved problem:
problem is AbstractAdapter.php __construct method
[    public function __construct(
        $config = [],
        HttpClientInterface $httpClient = null,
        StorageInterface    $storage = null,
        LoggerInterface     $logger = null
    ) {
        $this->providerId = (new \ReflectionClass($this))->getShortName();

        $this->config = new Data\Collection($config);

        $this->configure();

        $this->setHttpClient($httpClient);

        $this->setStorage($storage);

        $this->setLogger($logger);

        $this->logger->debug(sprintf('Initialize %s, config: ', get_class($this)), $config);

        $this->initialize();
    }
](url)
when there we give tokens in configs, we need to call $this->setStorage($storage); before $this->configure();

**Comment by ApacheEx** [comment]
check it out the documentation how to use custom access token.

https://hybridauth.github.io/developer-ref-user-authentication.html#authenticating-user-using-access-tokens
