### ISSUE TITLE
LinkedIn Broken with v2.14

### ISSUE THREAD

**Issue by Ratief** [hybridauth/hybridauth#1067]
## Bug, feature or question?

Is this a bug, a feature request or a question?
bug

Give us a short description.
The fix for the LinkedIn V2 API still hasn't made it into the v2.x branch and now LinkedIn is no longer working. This is a huge issue with anyone using this with Drupal as the Drupal module only supports v2.x of the hybridauth library.

This bug report talks about this issue, but I don't see the changes in the v2.14 release.
https://github.com/hybridauth/hybridauth/pull/1049

### Version and provider
2.14, LinkedIn

What version of Hybrid Auth does this relates to?
v2.x

Is this an issue with a provider? If yes, which one?
LinkedIn

### Reproduction

How can we replicate this issue?

**Comment by ApacheEx** [comment]
v2.15 will contain a fix for LinkedIn v2. 

btw, it will be released during this week.

**Comment by ApacheEx** [comment]
Released as https://github.com/hybridauth/hybridauth/releases/tag/v2.15.0
