### ISSUE TITLE
How to set user status in linkedin v2 API

### ISSUE THREAD

**Issue by asheeshn** [hybridauth/hybridauth#1072]
## Bug, feature or question?
question

Is this a bug, a feature request or a question?
question

Give us a short description.
How to set user status in linkedin v2 API

### Version and provider
v2 and Linkedin

What version of Hybrid Auth does this relates to?
3

**Comment by ApacheEx** [comment]
you can find this information in docs: https://github.com/hybridauth/hybridauth/blob/master/docs/developer-ref-user-status.md

also setUserStatus accepts an array with extra params (see https://docs.microsoft.com/en-us/linkedin/consumer/integrations/self-serve/share-on-linkedin)
