### ISSUE TITLE
Can't install v3.0.0 stable release via Composer

### ISSUE THREAD

**Issue by ryanprager** [hybridauth/hybridauth#1084]
When attempting to install the v3.0.0 stable release that was released on 5/31/19 using the following composer command, the v3.0.0-rc.10 version is installed.
`composer require 'hybridauth/hybridauth:~3.0'`

It looks like v3.0.0-rc.10 is the latest version in Packagist.
https://packagist.org/packages/hybridauth/hybridauth

Please include the v3.0.0 stable release in Packagist so it can be installed via Composer.

Thanks!

**Comment by ApacheEx** [comment]
yeah, sorry for that. We have an issue with https://packagist.org, we will solve it as soon as possible.

**Comment by alystair** [comment]
Looking forward to this as well

**Comment by ApacheEx** [comment]
finally, it's released here: https://packagist.org/packages/hybridauth/hybridauth#v3.0.0


thanks @miled for helping out!
