### ISSUE TITLE
What's wrong with my code?

### ISSUE THREAD

**Issue by singhritesh628** [hybridauth/hybridauth#1085]
HybridauthSocial.zip is my application file on localhost.

[hybridauthSocial.zip](https://github.com/hybridauth/hybridauth/files/3280784/hybridauthSocial.zip)

Please suggest to me what I'm doing wrong with my code and please help me to fix all the bugs are generating it's my humble request.

When I'm put id and secret key of LinkedIn and other providers then, suppose in case of Linkedin
I'm getting this URL  ( http://localhost/hybridauthSocial/hauth/endpoint?hauth.start=LinkedIn&hauth.time=1560334407 ) and on the view page always shows this ( HybridAuth
Open Source Social Sign On PHP Library. 
hybridauth.sourceforge.net/ ).

And also suggest me files of hybrid auth is on the right place or not.

**Comment by ApacheEx** [comment]
this has nothing to do with with project.

**Comment by singhritesh628** [comment]
So, why I'm only getting this message ( HybridAuth
Open Source Social Sign On PHP Library.
hybridauth.sourceforge.net/ ) instead of the login page of any providers.

**Comment by ApacheEx** [comment]
it's related to another porject, so this issue is locked here and discussion will be moved to https://github.com/ApacheEx/CodeIgniter-HybridAuth/issues/9
