### ISSUE TITLE
hybridauth authentification issue

### ISSUE THREAD

**Issue by mohamed-fouad-biqaa** [hybridauth/hybridauth#1087]
Hello Dear,
We are experiencing some authentification issues, whenever the visitor is asked to log in via (google,facebook.....) we have a denied access error.
This same error is not there when we deactivate our caching system (litespeed).
Plz can you confirm if there's any conflict with caching systems we might have to know about.
Thank you.

**Comment by ApacheEx** [comment]
Hello, which version do you use? and what kind pf caching is applied?

**Comment by mohamed-fouad-biqaa** [comment]
Hello, thanks for your feedback .
Actually we are using HybridAuth Social Login 7.x-2.16  and Litespeed for caching

**Comment by mohamed-fouad-biqaa** [comment]
Hi,
Is there any further information you need to help solve our problem please.
Thank you.

**Comment by ApacheEx** [comment]
I'm closing this issue since v2 is under Maintenance mode.
