### ISSUE TITLE
Twitter follower and friends counts are reversed

### ISSUE THREAD

**Issue by jkuster** [hybridauth/hybridauth#1089]
## Bug, feature or question?

Is this a bug, a feature request or a question?
Bug.

Give us a short description.
The followers and following numbers are reversed in the Twitter provider. I have 15 followers and am following 35 people on Twitter. Hybridauth is reporting I'm followed by 35 people and I'm following 15.

### Version and provider

What version of Hybrid Auth does this relates to?
v3.0.0
Is this an issue with a provider? If yes, which one?
Twitter

### Reproduction

How can we replicate this issue?
Login to a Twitter account that has a follower and following count that are different and check $adapter->getUserProfile()->data.

I believe the solution to be as simple as changing:
```
        $userProfile->data = [
          'followed_by' => $data->get('friends_count'),
          'follows' => $data->get('followers_count'),
        ];
```
to:
```
        $userProfile->data = [
          'followed_by' => $data->get('followers_count'),
          'follows' => $data->get('friends_count'),
        ];
```
In hybridauth/src/Provider/Twitter.php

**Comment by ApacheEx** [comment]
good catch, would you like to provide PR?

**Comment by jkuster** [comment]
Pull request submitted.
