### ISSUE TITLE
Vkontakte provider error

### ISSUE THREAD

**Issue by andryshok** [hybridauth/hybridauth#1092]
I use login Vkontakte and library response error
User profile request failed! Vkontakte returned an error #8: Invalid request: versions below 5.00 are deprecated. Version param should be passed as "v". "version" param is invalid and not supported. For more information go to https://vk.com/dev/version_update_2.0

**Comment by ApacheEx** [comment]
there is already PR: #1086 

I plan to release fix till next week.

**Comment by andryshok** [comment]
Thanks
