### ISSUE TITLE
Can I do multiple things such as share our post, like, comments and e.t.c. with version 2.15.1 in any platform.

### ISSUE THREAD

**Issue by RiteshSinghApache** [hybridauth/hybridauth#1093]
Can I do multiple things such as share our post, like, comments and also get all types of data such as shared content, how many like, dislike, and comments on this shared post in my application with version 2.15.1 in any platform.

Or the written code is only for logged in data means to say that get user data.

**Comment by RiteshSinghApache** [comment]
Please replay me what can I do?

**Comment by ApacheEx** [comment]
- you can share post via Hybridauth (it's available for some providers). Read documentation for this.

- like / comments / etc.. there is no support of it in HA. But you can do it via provider API. 
-- See for 2.x https://hybridauth.github.io/hybridauth/userguide/Access_IDps_APIs.html
-- See for 3.x https://hybridauth.github.io/developer-ref-providers-apis.html

**Comment by ApacheEx** [comment]
hopefully I've answered on your question
