### ISSUE TITLE
Question about Yahoo App (hybridauth v2)

### ISSUE THREAD

**Issue by Vyvi** [hybridauth/hybridauth#1096]
I want to ask about Oauth2 Yahoo.
I use version 2.x of Hybridauth and I can't use Yahoo login anymore. I go and check on the developer page and see app not request `Callback domain` anymore, it's changed to `Redirect URI(s)(Required)`.
How can I use Yahoo's functionality?
Sorry for my bad English. Thank you very much!

**Comment by StorytellerCZ** [comment]
Hello, sorry for the delay. Can't say from just that. To start of with:

Please check that your settings follow what is in the documentation: https://hybridauth.github.io/hybridauth/userguide/IDProvider_info_Yahoo.html
Check that there weren't any changes or additions at the provider.
Check updates to the Yahoo provider file here on Github.
See if there are any additional messages in logs.
Copy here the full text (screenshot) of the error with any relevant logs.

Bonus:
If feasible upgrade to HybridAuth 3.

**Comment by ApacheEx** [comment]
latest fixes for Yahoo provider are available in HA v3
