### ISSUE TITLE
[BUG][3.0.0][Facebook] : gender from an user with a non english language

### ISSUE THREAD

**Issue by Issiel** [hybridauth/hybridauth#1097]
Hello,

I have a trouble recovering the gender from Facebook. It works very well when I get an english user profile, which return male, female or null (as specified in the documentation), but in case my user is french, for exemple, the Hybridauth UserProfile will contain "homme" or "femme".

Is it a bug or does a solution exists for my problem ?

Thanks.

**Comment by kapil-infobeans** [comment]
Hi @Issiel ,

I would like to address this issue, For that I need more details about your facebook social app that you must have created for obtaining the key and secure id. Could you please how do you manage to setup those?

Thanks

**Comment by Issiel** [comment]
Hello @kapil-infobeans . It's an application in development that will never be available in production.
To see this bug, I created a test user in the facebook's app backoffice. I clicked on the "edit" button and chose "Log in as this test user". Once on the test user facebook page, i managed to change his nationality and choose french. 

When I'm loging with hybridauth, the gender returned is now "homme" or "femme".
You need something else ?
