### ISSUE TITLE
There are no issues for milestone 2.16, yet the v2 branch has fixes for VKontakte ready

### ISSUE THREAD

**Issue by unfulvio** [hybridauth/hybridauth#1098]
There is a 2.16 milestone, but no release yet. 
However branch in https://github.com/hybridauth/hybridauth/tree/v2 contains fixes for VKontakte to support v5 API. When is that going to be released?

thank you

**Comment by StorytellerCZ** [comment]
@ApacheEx Can we merge some other things for the v2 branch and release it?

**Comment by ApacheEx** [comment]
released as 2.16
