### ISSUE TITLE
Example 7 : popup not close

### ISSUE THREAD

**Issue by oitsuki** [hybridauth/hybridauth#1100]
I do not know what's happen but when I try to use the example 7, a pop up appears but it stays open, not close. Consequence, the content appears inside the pop-up. 
It seems this code does not work

`        echo "
            <script>
                window.opener.location.reload();
                window.close();
            </script>";
`
Do you have the same problem ?

**Comment by ApacheEx** [comment]
can you please try to change `window.close()` to `window.open('', 'authWindow').close();`

because we need to refer to window which was opened in the `function auth_popup`

**Comment by oitsuki** [comment]
@ApacheEx I tried your new approach, the result is the same thing.

**Comment by chrisgraham** [comment]
My guess is the popup is not in the same browser origin. E.g. a different domain, or https vs http not consistent.
If this is true, the `window.opener.location.reload` will fail with:
`
Uncaught DOMException: Permission denied to access property "reload" on cross-origin object
`
And JS will stop executing at that line.

I think this issue can be closed.

**Comment by ApacheEx** [comment]
pls take a look on this comment - I've feeling this solution should work:
https://github.com/hybridauth/hybridauth/issues/1230#issuecomment-696308983
