### ISSUE TITLE
Fatal error on Facebook: You cannot access this page directly

### ISSUE THREAD

**Issue by dupenna** [hybridauth/hybridauth#1105]
Hi everyone.

I don't think it's a bug, at least, not from HybridAuth
Version 2.9.6
Provider: Facebook
Unfortunately, there is no way to send instructions to replicate the issue.

I have a web application (php) using HybridAuth so users can connect with Facebook, Google and Instagram.

This solution is running over almost 2 years with no modifications, but since last week, Face and Insta is broken only for mobile!

It seems like Facebook is trying to responde to my redirect uri using it's own browser, not with the browser wich origin the request (chrome, safari, etc).

> Fatal error: Uncaught exception 'Hybrid_Exception' with message 'You cannot access this page directly.' in /var/www/html/hybridauth-2.9.6/hybridauth/Hybrid/Endpoint.php:211 Stack trace: #0 /var/www/html/hybridauth-2.9.6/hybridauth/Hybrid/Endpoint.php(157): Hybrid_Endpoint->authInit() #1 /var/www/html/hybridauth-2.9.6/hybridauth/Hybrid/Endpoint.php(55): Hybrid_Endpoint->processAuthDone() #2 /var/www/html/hybridauth-2.9.6/hybridauth/Hybrid/Endpoint.php(72): Hybrid_Endpoint->__construct(NULL) #3 /var/www/html/hybridauth-2.9.6/hybridauth/index.php(15): Hybrid_Endpoint::process() #4 {main} Next exception 'Hybrid_Exception' with message 'Endpoint: Error while trying to init Hybrid_Auth: You cannot access this page directly.' in /var/www/html/hybridauth-2.9.6/hybridauth/Hybrid/Endpoint.php:217 Stack trace: #0 /var/www/html/hybridauth-2.9.6/hybridauth/Hybrid/Endpoint.php(157): Hybrid_Endpoint->authInit() #1 /var/www/html/hybridauth-2.9.6/hybridauth/Hybrid/Endpoint.php(55): Hybrid_Endpoint->processAuthDone() #2 /var/www/html/hybr in /var/www/html/hybridauth-2.9.6/hybridauth/Hybrid/Endpoint.php on line 217

If, from this error message, I went to menu and click "Open in Chrome", it works!

Does anyone is facing the same problem and/or know how to solve it?

I'm on panic mode! Thanks!

**Comment by ApacheEx** [comment]
I'm closing this issue since v2 is under Maintenance mode.
