### ISSUE TITLE
 Instagram API breaking changes

### ISSUE THREAD

**Issue by champsupertramp** [hybridauth/hybridauth#1114]
## Bug, feature or question?

This is a question about the Instagram API roadmap.

According to the Instagram App:
```
These capabilities will be disabled immediately (previously set for July 31, 2018 or December 11, 2018 deprecation). The following will be deprecated according to the timeline we shared previously:

Public Content - all remaining capabilities to read public media on a user's behalf on December 11, 2018
Basic - to read a user’s own profile info and media in early 2020
```

I would like to know if there's a plan to migrate to Instagram Graph API? 
https://developers.facebook.com/docs/instagram-api/guides/business-discovery

Any timeline on the API migration?

### Version and provider

Latest version
Instagram

**Comment by champsupertramp** [comment]
Am I too early to discuss this future breaking-changes?

**Comment by champsupertramp** [comment]
I am closing this issue as I've integrated Instagram Graph API ( Facebook ).

**Comment by jcambien** [comment]
Can you give us more informations ? did you built a provider by yourself ?
Thank you

**Comment by champsupertramp** [comment]
Hi @jcambien  i did create the provider in the link: https://github.com/hybridauth/hybridauth/issues/1118#issuecomment-548377664

By the way, Facebook is discouraging the usage of Instagram Basic API for Login authentication.  Please the "Limitation" section in the link: https://developers.facebook.com/docs/instagram-basic-display-api#Limitations

Regards,
