### ISSUE TITLE
Possible to pass state through hybridauth and get it back?

### ISSUE THREAD

**Issue by tmetzger** [hybridauth/hybridauth#1122]
This is a question.

Background: I have hundreds of domains all running the same product, too many to whitelist them all through facebook or google. What I'd like to do is set the callback for all of them to a common login relay server. In order to do that, I need a generic way to pass state through the authentication flow, so I can tell the login relay server what site they're trying to log in to.

Is this possible?

Alternatively, I could call the relay server first and create a mapping from something (like the state variable) to a login target. Then when the relay callback gets called, I could look up the real site and forward the browser there.

Any input most welcome!

**Comment by tmetzger** [comment]
Turns out this was probably a silly question. Looking at the source code, it becomes clear that I can set the "state" variable to whatever I want. I thought it was always auto-generated. That solves my problem. :)

`//Build configuration array
  $config = [
    'callback' => 'https://dev.g4/login_relay',
    'keys' => [
        'id'     => 'ID',
        'secret' => 'SECRET',
    ],
    'authorize_url_parameters' => [
      'state'    => base64_encode(MY REAL CALLBACK URL),
    ],
  ];`

**Comment by araneta** [comment]
@tmetzger How do i get the state variable from the $adapter ? thanks

`$adapter = $hybridauth->authenticate('Google'); `

**Comment by jonyen** [comment]
@araneta You don't get the state variable from the adapter. You get it out of the config. In the example above, it'd be `$config['authorize_url_parameters']['state']`. But more pertinently, you'd want to get it from the callback, which would essentially be in `$_GET['state']`.
