### ISSUE TITLE
migration from 2.x Hybrid_Endpoint::process

### ISSUE THREAD

**Issue by elcreator** [hybridauth/hybridauth#1125]
## Bug, feature or question?

Request for docs update

### Version and provider

3.x

### Reproduction

Previously I used \Hybrid_Endpoint::process() in the method that is calling when user authenticates. Now I haven't such method in v3 and any info about this in upgrade manuals.

**Comment by ApacheEx** [comment]
you have, now it's part of OAuth2::authenticate, OAuth1::authenticate, OpenID::authenticate.

so, 

```php
$twitter = new Hybridauth\Provider\Twitter($config);
$twitter->authenticate();
```

should be called when user authenticates.

**Comment by elcreator** [comment]
It works the next way but it's not too clear from docs:

```php
// Twitter login page
/auth/twitter
$hybridauth = new Hybridauth\Provider\Twitter($config);
$hybridauth->authenticate();
$session->set('provider', 'Twitter');

// Facebook login page
/auth/facebook
$hybridauth = new Hybridauth\Provider\Facebook($config);
$hybridauth->authenticate();
$session->set('provider', 'Facebook');

// Page specified as endpoint specified in all social networks Oauth settings
/auth/social/endpoint
$hybridauth->authenticate($session->get('provider')); 
```

**Comment by ApacheEx** [comment]
I agree, that's what shown in example 06. But again, it's just one example how to do it. So, you can use session, query parameter or different paths. Somehow we need to mention it in documentation. Contribution is welcome.
