### ISSUE TITLE
Blank Screen for GitHub and LinkedIn after CallBack

### ISSUE THREAD

**Issue by harshalone** [hybridauth/hybridauth#1126]
## Bug 

I have configured HybridAuth 3 into my codeigniter 3 project.

I am able to approve with both
LinkedIn
Github

But after approval when user get redirected to callback url I see only a blank page

### Version and provider
HybridAuth 3
Codeigniter 3
 

### Reproduction

Use this link to reproduce this error:
https://www.blognow.org/auth/auth2

Here is the code I am using

```

<?php
//Include Hybridauth's basic autoloader
include APPPATH.'libraries/hybridauth/src/autoload.php';

//Import Hybridauth's namespace
use Hybridauth\Hybridauth; 
use Hybridauth\Exception\Exception; 
use Hybridauth\HttpClient;
use Hybridauth\Storage\Session;
//And so on

class Auth extends CI_Controller{
	 
	public function __construct(){
		parent:: __construct();
		$this->load->helper('form');
		$this->load->library('form_validation'); 
	}
	  
	public function auth2(){
		
		//First step is to build a configuration array to pass to `Hybridauth\Hybridauth`
				
		try{
			$config = [ 
							    'callback' => 'https://www.blognow.org/auth/oauth2', 
							
							    //Providers specifics
							    'providers' => [
							        'LinkedIn'   => 
							        ['enabled' => true, 'keys' => 
							        						[ 'id'  => LINKEDIN_CLIENT_ID, 'secret' => LINKEDIN_CLIENT_SECRET]],
							        'Google'   => 
							        ['enabled' => true, 'keys' => 
							        						[ 'id'  => GOOGLE_SIGNIN_CLIENT_ID, 'secret' => GOOGLE_SIGNIN_CLIENT_SECRET]], 
							        'GitHub' => ['enabled' => true, 'keys' => 
															[ 'id'  => GITHUB_SIGNIN_CLIENT_ID, 'secret' => GOOGLE_SIGNIN_CLIENT_SECRET]]
							    ]
							];
		    //Feed configuration array to Hybridauth
		    $data       		= array();
		    $hybridauth 	= new Hybridauth($config);
		    $data['adapters']   = $hybridauth->getConnectedAdapters();
		    
		     
		    
		    $data['providers']  = $hybridauth->getProviders();
			$data['config']     = $config;
		     
		}
		catch(\Exception $e){
		    echo 'Oops, we ran into an issue! ' . $e->getMessage();
		}
		
		$data['content_view'] = 'auth/auth2_v';
		$this->template->core_template($data);
		
 
	}
	
	public function oauth2(){
		  
		
		try {
		    
		    
		   $config = [ 
							    'callback' => 'https://www.blognow.org/auth/oauth2', 
							
							    //Providers specifics
							    'providers' => [
							        'LinkedIn'   => 
							        ['enabled' => true, 'keys' => 
							        						[ 'id'  => LINKEDIN_CLIENT_ID, 'secret' => LINKEDIN_CLIENT_SECRET]],
							        'Google'   => 
							        ['enabled' => true, 'keys' => 
							        						[ 'id'  => GOOGLE_SIGNIN_CLIENT_ID, 'secret' => GOOGLE_SIGNIN_CLIENT_SECRET]], 
							        'GitHub' => ['enabled' => true, 'keys' => 
															[ 'id'  => GITHUB_SIGNIN_CLIENT_ID, 'secret' => GOOGLE_SIGNIN_CLIENT_SECRET]]
							    ]
							];
							
		   $hybridauth = new Hybridauth($config);
		    $storage    = new Session();
		    $error      = false;				
		     
		    if (isset($_GET['provider'])) {
		        // Validate provider exists in the $config
		        if (in_array($_GET['provider'], $hybridauth->getProviders())) {
		            // Store the provider for the callback event
		            $storage->set('provider', $_GET['provider']);
					
		        } else {
		            $error = $_GET['provider'];
		        }
		    } 
		     
		    if ($error) {
		        error_log('HybridAuth Error: Provider '. json_encode($error) .' not found or not enabled in $config');
		         
		    }
		    
			
		    
		    if ($provider = $storage->get('provider')) {
		        
                        // I think after callback this is where the code is stuck
		        $hybridauth->authenticate($provider);
				 
		        $storage->set('provider', null);
		        // Retrieve the provider record
		        $adapter = $hybridauth->getAdapter($provider);
		        $userProfile = $adapter->getUserProfile();
		        $accessToken = $adapter->getAccessToken();
		        // add your custom AUTH functions (if any) here
		        // ...
		        $data = [
		            'token'         => $accessToken,
		            'identifier'    => $userProfile->identifier,
		            'email'         => $userProfile->email,
		            'first_name'    => $userProfile->firstName,
		            'last_name'     => $userProfile->lastName,
		            'photoURL'      => strtok($userProfile->photoURL,'?'),
		            ];
		        // ...
		        // Close pop-up window
				print_r($data);
		        echo "i am here";
		    }else{
				$provider = $storage->get('provider');
				print_r($provider); //die();
			}
		} catch (Exception $e) {
		    error_log( $e->getMessage());
		    echo $e->getMessage();
		}
	}
}

```

**Comment by harshalone** [comment]
@ApacheEx I have copied exactly same code you provided in example 7

**Comment by simmonspaul** [comment]
I've got a similar setup and problem. Codeigniter 3.1.10, Hybridauth 3.0, php73.
(Session library is loaded.)

The authenticate function works. Proceeds to social media page and logs in.

At the endpoint, the session looks like:

[HYBRIDAUTH::STORAGE] => Array
        (
            [facebook.authorization_state] => HA-UQLVKYZ63GJHCEST7BD14NM92I5OAWRF0XP8
        )

Everything looks like it worked so far. However any call thereafter provides no output (session or post data) eg. getUserProfile, getConnectedAdapters(), etc

(I suspect that something is not being written correctly to session data on the return leg of these functions due to the way that code igniter is handling the session input - however confirmations or work arounds would be appreciated)

**Comment by mdsupport** [comment]
Would appreciate any suggestions for troubleshooting similar problem.

Seems to be something specifically introduced by PHP - **code that works on PHP 7.2 systems stops working on 7.3**.  Symptom is authenticate() calls get state and invoke callback.  But any use of adapter object returns 

> General error: The authorization state [state=HA-CD9FWN6POVX0L2E3B7AQJI54MSYZ81URGHTK] of this page is either invalid or has already been consumed.

The logger is of no help.  Here is the output : 
debug -- 172.17.0.1 -- 2020-04-21T00:48:18+00:00 -- Initialize Hybridauth\Provider\GitHub, config: 
Array
(
    [enabled] => 1
    [keys] => Array
        (
            [key] => 8bf86db4e61c4ca365e6
            [secret] => c0d82207599cf4b6e4bd1f180ecf5bcde2a1e2a8
        )

    [debug_mode] => 1
    [debug_file] => ./hauth.log
    [callback] => http://serv1.domain.com/site1/hauth_check.php
)

> 
> info -- 172.17.0.1 -- 2020-04-21T00:48:18+00:00 -- Hybridauth\Provider\GitHub::authenticate()
> debug -- 172.17.0.1 -- 2020-04-21T00:48:18+00:00 -- Hybridauth\Provider\GitHub::authenticateBegin(), redirecting user to:
> Array
> (
>     [0] => https://github.com/login/oauth/authorize?response_type=code&client_id=8bf86db4e61c4ca365e6&redirect_uri=http%3A%2F%2Fserv1.domain.com%2Fsite1%2Fhauth_check.php&scope=user%3Aemail&state=HA-78S0YK3B5PCXHA1E2DOWVQT9JRNMLZGU46IF
> )
> 
> debug -- 172.17.0.1 -- 2020-04-21T00:48:19+00:00 -- Initialize Hybridauth\Provider\GitHub, config: 
> Array
> (
>     [enabled] => 1
>     [keys] => Array
>         (
>             [key] => 8bf86db4e61c4ca365e6
>             [secret] => c0d82207599cf4b6e4bd1f180ecf5bcde2a1e2a8
>         )
> 
>     [debug_mode] => 1
>     [debug_file] => ./hauth.log
>     [callback] => http://serv1.domain.com/site1/hauth_check.php
> )
> 
> info -- 172.17.0.1 -- 2020-04-21T00:48:19+00:00 -- Hybridauth\Provider\GitHub::authenticate()
> debug -- 172.17.0.1 -- 2020-04-21T00:48:19+00:00 -- Hybridauth\Provider\GitHub::authenticateFinish(), callback url:
> Array
> (
>     [0] => http://serv1.domain.com/hauth_check.php?code=6e923ea3ceb4f427d9c7&state=HA-78S0YK3B5PCXHA1E2DOWVQT9JRNMLZGU46IF
> )
> 
>

**Comment by chrisgraham** [comment]
Blank screens are a common problem in PHP.
Doing something like this usually makes it a lot easier to debug (not on a live site, or at least behind something like an IP check)...

```
restore_error_handler(); // Remove any framework error handler that may be eating the error or itself crashing
error_reporting(E_ALL); // Do not suppress any errors
ini_set('display_errors', '1'); // Show errors directly
```

OR use something like xdebug with PHPStorm to step through the code.

OR keep putting in temporary exits to step through the code manually.


Anyway, I doubt anyone can help other than the generic advice I've just given, until there's an error message. I think this issue should be closed, and then if an error message suggests a bug, open a new issue.

**Comment by ApacheEx** [comment]
fully agree with @chrisgraham 💯
