### ISSUE TITLE
PHP 7.4 deprecation 

### ISSUE THREAD

**Issue by nightw0lv** [hybridauth/hybridauth#1127]
## Bug, feature or question?
Bug?
Is this a bug, a feature request or a question?
<b>Deprecated</b>:  Array and string offset access syntax with curly braces is deprecated in <b>/var/www/html/third_party/hybridauth/src/Thirdparty/OAuth/OAuthSignatureMethod.php</b> on line <b>62</b><br />

### Version and provider
lastest
What version of Hybrid Auth does this relates to?
Is this an issue with a provider? If yes, which one?

### Reproduction

How can we replicate this issue?
i have using php 7.4

**Comment by nightw0lv** [comment]
change this 
`$result |= ord($built {$i}) ^ ord($signature {$i});`
to
`$result |= ord($built [$i]) ^ ord($signature [$i]);`

**Comment by ApacheEx** [comment]
Hello, welcome to contribute :)
