### ISSUE TITLE
Seems to be missing closing bracket.

### ISSUE THREAD

**Issue by armandojs** [hybridauth/hybridauth#1132]
I downloaded a copy of the library because I need to make some changes to another section. However I ran into this issue:

> "Parse error: syntax error, unexpected '=>' (T_DOUBLE_ARROW), expecting ')' in /var/www/html/sbdev.sheepbuy.com/application/libraries/custom/Hybridauth/HttpClient/Guzzle.php on line 162"

If I install the the library using composer, the error in the code is still there but I don't get any exceptions.

https://github.com/hybridauth/hybridauth/blob/ba98676cc088e2cd5aad411fad7c4b70472bc6d5/src/HttpClient/Guzzle.php#L161

**Comment by ApacheEx** [comment]
Oh, good catch

**Comment by ApacheEx** [comment]
released as 3.1.1
