### ISSUE TITLE
Invalid scope & Invalid access_token issue with latest Instagram graph API

### ISSUE THREAD

**Issue by dev-sayem** [hybridauth/hybridauth#1139]
## Bug
This is the first error which throws invalid scope. 

`{"error_type": "OAuthException", "code": 400, "error_message": "Invalid scope: ['basic']"}`

Trying to fix this issue and got a solution for this Invalid scope.
This is your code
<pre>
class Instagram extends OAuth2
{
protected $scope = 'basic';
.........
</pre>

I changed this code to

<pre>
class Instagram extends OAuth2
{
protected $scope = 'user_profile,user_media';
.............
</pre>

These changes fixed that invalid scope issue. 

But after fixing that issue I got another issue which is Invalid access_token.

`{"meta": {"code": 400, "error_type": "OAuthAccessTokenException", "error_message": "The access_token provided is invalid."}}`

### Version and provider
I used hybridauth 3.1.1. I faced an issue with Instagram login.

### Reproduction
Those error is occurring in general. Maybe it's for the latest Instagram graph API. 

Looking forward to helping.

**Comment by runexes** [comment]
Hi,

It seems that according to the official documentation [here](https://developers.facebook.com/docs/instagram-basic-display-api) the Instagram not supported for auth any more.

> Instagram Basic Display **not an authentication tool**. Data returned by the API cannot be used to authenticate your app users or log them into your app. If your app uses API data to authenticate users, it will be rejected during App Review. If you need an authentication solution, use [Facebook Login](https://developers.facebook.com/docs/facebook-login) instead.

**Comment by dev-sayem** [comment]
Isn't there any option to use it?
https://developers.facebook.com/docs/instagram-basic-display-api/overview#authentication-window
See here. It shows authentication is possible with Instagram.  
Looking forward reply.

**Comment by bologer** [comment]
@runexes well, it is supported, was just moved to Graph API: 

```
Hi Instagram Developer,

As we previously shared, we will be disabling the final Instagram Legacy API permission ("Basic Permission") next month. To provide you with more time to make changes, we will now be shutting down the Instagram Legacy API Platform on March 31, 2020 instead of March 2, 2020 as originally communicated.

As of March 31, 2020, all Legacy API capabilities will be fulfilled by the Instagram Graph API and the Instagram Basic Display API. Any apps that remain on the Legacy API as of March 31, 2020 will no longer have access. We encourage you to apply for permissions to Instagram Basic Display API via App Review and migrate Legacy API calls before March 31 to avoid disruption of service to your app and business. Note that App Review submissions can take up to a week or longer to process.

If you’re using the Legacy API to simply display your personal Instagram Feed on your personal website, you may use the User Token Generator on the Instagram Basic Display API. The User Token Generator does not require App Review, but it will only work for your owned Instagram accounts (i.e. accounts for which you know the login credentials). Please refer to the developer documentation to learn more.

Thanks,
The Instagram Platform Team
```

- https://developers.facebook.com/docs/instagram-api/
- https://developers.facebook.com/docs/instagram-basic-display-api/overview#user-token-generator

**Comment by runexes** [comment]
Yes, it's moved to Facebook Graph API, but:

_To use Instagram platform, your app needs to be approved for **instagram_graph_user_profile** and **instagram_graph_user_media** permission._

And as soon as you sent it to review by Facebook, they look that you try to use it for authentication -> **Reject**

<img width="1179" alt="Instagram_-_Facebook_for_Developers" src="https://user-images.githubusercontent.com/1163222/77918590-613be000-729c-11ea-9916-dae449efe3e2.png">

**BTW:** The PR #1139 solve the problem with "scope & tokens" but you will not get an email of the user; as for me this is important data for authorization.

---

@jcambien says:
> Our business is using it on a real application, it's working well so far.

Can you give us more information so? how your business uses the Instagram provider?
Thank you

**Comment by runexes** [comment]
Allowed usage of the **Instagram Basic Display API** is:

- Creating physical or digital books from the app user's photos, including exporting photos for printing
- Displaying the app users photos to other app users within the app (e.g, for Dating or Social Network Applications)
- Editing or creating new photos or videos based on the app user's existing photos and videos (Photo/Video Editing Apps)
- Displaying the app user's photos and videos in an external device such as a TV or digital photo frame

source: https://developers.facebook.com/docs/instagram-basic-display-api/overview/permissions/

**Comment by ApacheEx** [comment]
@runexes, yeah there is no way to get email address even if you have all permissions approved.

**Comment by jcambien** [comment]
We're using the API for photos contests, where users can choose a photo from their Instagram feed to participate.
We are still waiting for the permissions being approved (third request sent today, meh.).
To bo clear, what I was saying is that the provider made in my PR is successfully working with the new Graph API on a "real" application, not a testing thing.

About the email, the new API indeed does not provides it and will likely never do.

**Comment by ApacheEx** [comment]
@jcambien 
sometimes it helps to write directly to "Facebook App Review Support" 🤞

but also, they can reject it because authorization is not directly called when you click on sign in button.

**Comment by runexes** [comment]
Yep.
So, this issue is closed for me but anyway thanks guys for the PR #1139 it's will help in other cases.
