### ISSUE TITLE
Discord Token Requests require client ID & secret in tokenRefreshParameters | update initialize()

### ISSUE THREAD

**Issue by CyprezzPMC** [hybridauth/hybridauth#1142]
Bug
Discord token requests require client_id & client_secret in tokenRefreshParameters

Hybridauth: 3.1.1
Provider: Discord.

Reproduction:
Can reproduce by calling refreshAccessToken() or attempting to send a revoke request without passing client_id & client_secret into $params of apiRequest('oauth2/token/revoke','POST',$params).

Solution:
Add initialize() to /Provider/Discord.php:
/**
    * {@inheritdoc}
    */
    protected function initialize()
    {
        parent::initialize();

        $this->tokenRefreshParameters += [
            'client_id' => $this->clientId,
            'client_secret' => $this->clientSecret
        ];
    }

**Comment by ApacheEx** [comment]
Thanks for reporting. Will be released in v3.2
