### ISSUE TITLE
How can I get a user education from Vkontakte?

### ISSUE THREAD

**Issue by XIOLog** [hybridauth/hybridauth#1148]
This is a question.

Hello. I use v.3.

I connected to Vkontakte and got User Profile. But I don`t understood how can I get a user education?

Tell me please.

**Comment by ApacheEx** [comment]
Hello,
There is no way to get it with current implementation. 

I see it's available in response but not stored anywhere.
Feel free to provide PR to store it as `$userProfile->data['education']`

**Comment by XIOLog** [comment]
Ok. Thank you :)

**Comment by XIOLog** [comment]
```php
$userProfile = $adapter->getUserProfile();
print $userProfile->data['education'];
```
right?

**Comment by XIOLog** [comment]
How can I store education to $userProfile->data['education']?

**Comment by ApacheEx** [comment]
pls try to upgrade to the latest version (it's pushed to the master).

should be available as `$userProfile->data['education']`

**Comment by XIOLog** [comment]
This version available on Composer?

**Comment by ApacheEx** [comment]
yeah (dev-master), see https://packagist.org/packages/hybridauth/hybridauth#dev-master

**Comment by XIOLog** [comment]
Ok. Thank you very much! :)

**Comment by XIOLog** [comment]
I updated to v.3.2. But I have a problem...

I`m using a configuration file like at Example 6 with multiple social networks.

First I use:

```php
$hybridauth = new Hybridauth($socialConfig);
$adapters   = $hybridauth->getConnectedAdapters();
```

Then

```php
<?php if ($adapters) : ?>
    <h1>You are logged in:</h1>
    <ul>
	<?php foreach ($adapters as $name => $adapter) : ?>
	    <li>
	        <strong><?php print $adapter->getUserProfile()->displayName; ?></strong> from
	        <i><?php print $name; ?></i>
	        <span>(<a href="<?php print $socialConfig['callback'] . "?logout={$name}"; ?>">Log Out</a>)</span>
	    </li>
	    <li>
                <pre>
	            <?php print_r($adapter->getUserProfile()->data['sex']); ?>
	        </pre>
            </li>
        <?php endforeach; ?>
    </ul>
<?php endif; ?>
```

![TroubleVK](https://i.paste.pics/61370e47334b1540eeb2451279099e0c.png)

What am I doing wrong?

**Comment by XIOLog** [comment]
I have a problem.

Some fields are not displayed. The date, city fields and others are missing.

![troubleVK2](https://user-images.githubusercontent.com/1305838/77356123-8c3ba680-6d67-11ea-9fea-61bed75711ce.jpg)

**Comment by XIOLog** [comment]
I found a remporary solution. I could not add push, so I am writing here.

I added:

```php
$this->storeData('bdate', $data->get('bdate'));
```
to **validateAccessTokenExchange()**

And

```php
$response = $this->apiRequest('users.get', 'GET', [
     'fields' => 'screen_name,sex,education,bdate,has_photo,' . $photoField,
 ]);

$userProfile->data = [
    'education' => $data->get('education'),
    'bdate' => $data->get('bdate')
];
```
to **getUserProfile()**

**Comment by XIOLog** [comment]
Fields are [birthDay], [birthMonth] and [birthYear] not filled in with values.
