### ISSUE TITLE
Hybrid_Endpoint::process();

### ISSUE THREAD

**Issue by shobhit421** [hybridauth/hybridauth#1159]
In HybridAuth version 2 we have 
Hybrid_Endpoint::process();
in file hybridauth\hybridauth\index,php 

but now there is no Endpoint function in HybridAuth3

## Bug, feature or question?

Is this a bug, a feature request or a question?
Give us a short description.

### Version and provider

What version of Hybrid Auth does this relates to?
Is this an issue with a provider? If yes, which one?

### Reproduction

How can we replicate this issue?

**Comment by ApacheEx** [comment]
here it is: https://github.com/hybridauth/hybridauth/blob/master/src/Adapter/AdapterInterface.php#L24


check it out how it's used in our examples or documentation.

for example README.md:

```php
$config = [
    'callback' => 'https://example.com/path/to/script.php',
    'keys' => [ 'key' => 'your-twitter-consumer-key', 'secret' => 'your-twitter-consumer-secret' ]
];

try {
    $twitter = new Hybridauth\Provider\Twitter($config);

    $twitter->authenticate();

    $accessToken = $twitter->getAccessToken();
    $userProfile = $twitter->getUserProfile();
    $apiResponse = $twitter->apiRequest('statuses/home_timeline.json');
}
catch (\Exception $e) {
    echo 'Oops, we ran into an issue! ' . $e->getMessage();
}
```
