### ISSUE TITLE
Facebook Graph API v2.12 deprecation on 5th May 2020

### ISSUE THREAD

**Issue by coling** [hybridauth/hybridauth#1160]
The Facebook Graph API v2.12 which is currently used by HybridAuth v3.2.0 will be deprecated on 5th May 2020.

I've updated the code locally (in src/Provider/Facebook.php - $apiBaseUrl) to v6.0 (the latest one appearing in FB's developer portal) and was able to login with an existing user to an existing app. I've not in anyway read the docs so don't know if it will cause wider problems, but the minimal test passes :-p

### Version and provider

What version of Hybrid Auth does this relates to?
**v3.2.0**

Is this an issue with a provider? If yes, which one?
**Facebook**

**Comment by ApacheEx** [comment]
I've nothing against to update it right now :) 

you're welcome to create a PR.
