### ISSUE TITLE
Composer and Instagram fix

### ISSUE THREAD

**Issue by motorlesha** [hybridauth/hybridauth#1162]
## Bug, feature or question?

Thank you for really cool project! We have one issue with installing library with composer. Please look at this file https://github.com/hybridauth/hybridauth/blob/3.2.0/src/Provider/Instagram.php in version 3.2 it is different with master https://github.com/hybridauth/hybridauth/blob/master/src/Provider/Instagram.php it is really strange. could you please upgrade version and include insta fix into package? Thanks!

### Version and provider

What version of Hybrid Auth does this relates to?
Is this an issue with a provider? If yes, which one?

### Reproduction

How can we replicate this issue?

**Comment by ApacheEx** [comment]
Thanks!

I just released [v3.3.0](https://github.com/hybridauth/hybridauth/releases/tag/3.3.0)
with the latest changes from master 😎
