### ISSUE TITLE
getting error in composer install

### ISSUE THREAD

**Issue by flik** [hybridauth/hybridauth#1164]
## Bug, feature or question?

Composer install is not installing it properly when we try to run composer install
It is saying It has stored token in specific location and when we visit the location nothing found.

### Version and provider

What version of Hybrid Auth does this relates to?  
Version 3

### Reproduction

just run the composer install 
You will get this type of problem.
 - Installing doctrine/instantiator (1.3.0): Downloading (failed)
Downloading (failed)
Downloading (failed)    Failed to download doctrine/instantiator from dist: The "https://api.github.com/repos/doctrine/instantiator/zipball/ae466f726242e637cebdd526a7d991b9433bacf1" file could not be downloaded: php_network_getaddresses: getaddrinfo failed: No such host is known.
failed to open stream: php_network_getaddresses: getaddrinfo failed: No such host is known.
    Now trying to download from source
  - Installing doctrine/instantiator (1.3.0): Cloning failed using an ssh key for authentication, enter your GitHub credentials to access private repos
Head to https://github.com/settings/tokens/new?scopes=repo&description=Composer+on+DESKTOP-QDJ6UTA+2020-04-28+0934
to retrieve a token. It will be stored in "C:/Users/xAdmin/AppData/Roaming/Composer/auth.json" for future use by Composer.
Token (hidden):

**Comment by ApacheEx** [comment]
as you can see from logs - this has nothing to do with hybridauth.

I've just tried to install it locally via composer and all works fine.
![image](https://user-images.githubusercontent.com/1918108/80466828-b6bfe700-8945-11ea-8f07-30b05265f508.png)
