### ISSUE TITLE
Deprecated Yahoo scope parameter

### ISSUE THREAD

**Issue by ozsvar66** [hybridauth/hybridauth#1165]
Yahoo bug.
(I use Hybridauth ver. 3.3)
In class Yahoo extends OAuth2 (file src/Provider/Yahoo.php) I had to rewrite the value protected **$scope** from **'sdpp-w'** to new value: **'profile'**, because the $scope parameter 'sdpp-w' is depretacted in Yahoo APPs (OAuth 2.0).
You can find more details about that here: https://developer.yahoo.com/oauth2/guide/yahoo_scopes/#scope-identifiers

**Comment by ApacheEx** [comment]
Thanks for report

p.s Feel free to create PR with needed changes.
