### ISSUE TITLE
Twitter error : code":32,"message":"Could not authenticate you."

### ISSUE THREAD

**Issue by buzzybuzza** [hybridauth/hybridauth#1167]
## Bug

When using the Twitter provider, the error
code":32,"message":"Could not authenticate you."
is returned when getUserProfile is called.

### Version and provider

Version 3.3 with Twitter provider

### Reproduction

I get that error whenever I use that provider.

**Comment by buzzybuzza** [comment]
I found a fix for this. The problem is with the include_email parameter.

If the master branch, the value for this parameter is always True. Is there a reason for that?
$response = $this->apiRequest('account/verify_credentials.json?include_email=true');

In the v2 branch the parameter depends on the config
$includeEmail = isset($this->config['includeEmail']) ? (bool) $this->config['includeEmail'] : false;
		$response = $this->api->get('account/verify_credentials.json'. ($includeEmail ? '?include_email=true' : ''));

The problem is because the include_email parameter is sent in the query string.
This fix for the master branch solve the problem :
 $response = $this->apiRequest('account/verify_credentials.json', 'GET', [ 'include_email' => 'true']);

**Comment by ApacheEx** [comment]
Hello, thanks for report.

I think this makes sense (+ include_email is configurable now):
```php
$response = $this->apiRequest('account/verify_credentials.json', 'GET', [
    'include_email' => $this->config->get('include_email') === false ? 'false' : 'true',
]);
```

p.s would you like to create PR?

**Comment by buzzybuzza** [comment]
I created a PR.
Have a nice day!

**Comment by ApacheEx** [comment]
good, merged to master. Pls check
