### ISSUE TITLE
Provider TwitchTV broken due to missing request header Client-ID

### ISSUE THREAD

**Issue by NeoVG** [hybridauth/hybridauth#1170]
Version: 3.3.0

**Problem:**

Apparently Twitch now needs the request header `Client-ID` additionally to `Authorization`.

If it's missing, `TwitchTV::apiRequest()` returns the following response:

`{"error":"Unauthorized","status":401,"message":"Client ID and OAuth token do not match"}.`

Here is the official statement on Twitch's developer pages regarding the change, which became active on May 1st: https://discuss.dev.twitch.tv/t/requiring-oauth-for-helix-twitch-api-endpoints/23916

**Solution:**

Just add `$this->clientId` to the appropriate request header.

I will prepare a pull request as soon as I've learned how to do it properly. :)

**Comment by ApacheEx** [comment]
it's merged to master, thx. Will be released as 3.4 later.
