### ISSUE TITLE
Facebook Graph returned an error: Error validating verification code. Please make sure your redirect_uri is identical to the one you used in the OAuth dialog request

### ISSUE THREAD

**Issue by renesansi** [hybridauth/hybridauth#1172]
Kindly ask you to help me to fix my Facebook Login problem. It functioned correctly in 2018. But due to some major changes in Facebook Api, I switched of Facebook Login in 2019. Now need to reactivate it. Already lost 3 days :( could not find the solution. All others providers login works fine!
For info => my host php version 7.4 
I use hybridauth 2.17  with php-graph-sdk VERSION = '5.7.0';

Here is login link in browser after click on login with facebook : 
=https://www.facebook.com/login.php?skip_api_login=1&api_key=*****&kid_directed_site=0&app_id=***&signed_next=1&next=https%3A%2F%2Fwww.facebook.com%2Fv3.2%2Fdialog%2Foauth%3Fauth_type%3Drerequest%26client_id%3D22******%26state%3D******%26response_type%3Dcode%26sdk%3Dphp-sdk-5.7.0%26redirect_uri%3Dhttps%253A%252F%252Fwww.mysite.com%252Fhybridauth%252F%253Fhauth.done%253DFacebook%26scope%3Demail%252Cpublic_profile%26ret%3Dlogin%26fbapp_pres%3D0%26logger_id%3D92011e72-c8d2-4f14-b8e8-8861d1007cf5&cancel_url=https%3A%2F%2Fwww.mysite.com%2Fhybridauth%2F%3Fhauth.done%3DFacebook%26error%3Daccess_denied%26error_code%3D200%26error_description%3DPermissions%2Berror%26error_reason%3Duser_denied%26state%3De0cb516033dbacb599d59564bcefd48b%23_%3D_&display=page&locale=fr_FR&pl_dbl=0

No error shown at Facebook Login Page !  

After login at facebook page, facebook redirect to my website. But I get error from this piece of code in file .../Hybrid/Providers/Facebook.php : 
```
try {
            $accessToken = $helper->getAccessToken($this->params['login_done']);
            
        } catch (Facebook\Exceptions\FacebookResponseException $e) {
            **throw new Hybrid_Exception('Facebook Graph returned an error: ' . $e->getMessage());**
        } catch (Facebook\Exceptions\FacebookSDKException $e) { 
```
**Facebook Graph returned an error: Error validating verification code. Please make sure your redirect_uri is identical to the one you used in the OAuth dialog request**

      echo 'show_url  =>  '.$this->params['login_done'] ;
               show_url  => https://www.mysite.com/hybridauth/?hauth.done=Facebook
 
IN FACEBOOK LOGIN Settings  :     
Valid OAuth Redirect URIs  =>    
https://www.mysite.com/hybridauth/?hauth.done=Facebook
and
https://www.mysite.com/hybridauth/?hauth_done=Facebook

Client OAuth Login ON
Web OAuth Login ON
Enforce HTTPS ON
Embedded Browser OAuth Login ON
Use Strict Mode for Redirect URIs ON 

Any idea ?! MERCI :) 
ps. sorry for my English

**Comment by ApacheEx** [comment]
Hello, thanks for details.

Let's try 2 solutions:

1. Here, in the hybridauth config, you can set `'trustForwarded' => true`.

![image](https://user-images.githubusercontent.com/1918108/81479091-efa36a00-9229-11ea-968d-7fcb31fc7dd2.png)


2. I see your side uses https + www version. So, make sure in `Valid OAuth Redirect URIs` you have full urls:
- https://www.mysite.com/hybridauth/?hauth.done=Facebook
- https://www.mysite.com/hybridauth/?hauth_done=Facebook

**Comment by renesansi** [comment]
Thank you for help OLEG :) 
1 solution does not help. 
2 I already checked them, there are full urls in Facebook Login as I mentioned above in my post.

May be this problem linked with API version in Facebook Developer Dashboard => Settings => Advanced  in Upgrade API Version 
I have 3.2 for Upgrade All Calls and 3.2 for Upgrade Calls for App Roles
it seems 2.x version is already deprecated.

**Comment by renesansi** [comment]
Just for info... in Facebook Login Dev App => My Permissions and Features => Approved Items =>  "email" and "default"
In in file .../Hybrid/Providers/Facebook.php  
public $scope = array('email', 'public_profile'); 
May be this matter ?!

**Comment by ApacheEx** [comment]
scope is fine, otherwise you will see another error.

in hybridauth config you can specify which version of graph api to use:
![image](https://user-images.githubusercontent.com/1918108/81479923-faacc900-922e-11ea-839e-95d0e21b3a41.png)


I see from your 1st comment that it tries to redirect to https://www.mysite.com/hybridauth/?hauth.done=Facebook

but especially for Facebook it should be https://www.mysite.com/hybridauth/?hauth_done=Facebook
I can say this is the root of issue. You need somehow to find out why it uses `hauth.done` instead of `hauth_done` when building this Login URL.

**Comment by renesansi** [comment]
Thank you for advice. I am not sure if this is right way, but I fixed it like this:
in file .../Hybrid/Providers/Facebook.php 
before of this statement (in my case 2 times in 2 functions )
$this->params['login_done'];
I added 
$this->params['login_done'] = str_replace('hauth.done', 'hauth_done', $this->params['login_done']);

**Comment by ApacheEx** [comment]
interesting case:

because here in this file we handle this case
https://github.com/hybridauth/hybridauth/blob/c7a3c11459bba59a6d546e0244aa5ef98f16137b/hybridauth/Hybrid/Provider_Model.php#L219-L222

can you tell me how you exactly login?

for example:
- you click on facebook button and then on this callback you execute `$hybridauth->authenticate("Facebook");`

**Comment by renesansi** [comment]
Now it is little bit more clear ....
If you look in distribution files version 2.17 you can find 
1. in ...../Providers/Facebook.php   this  => public $useSafeUrls = true;
2. in  .../Hybrid/Provider_Model.php this =>  public $useSafeUrls = false; 

is it means that it becomes automatically false when script use Provider_Model.php ?!
