### ISSUE TITLE
Is it safe to save identifier in DB or have to be hashed?

### ISSUE THREAD

**Issue by heathera2016** [hybridauth/hybridauth#1180]
Is it safe to save identifier in DB or have to be hashed?
I stored user's identifier in DB and whenever they sign in using 3rd provider, my backend matches their identifier with the init in my DB.
If matches, my server give login session.
My question is that is it safe to save identifier in DB without hashing or has to be hashed like password?
Any tips are appreciated.
Many thanks :)

Best regards,
Heathera

**Comment by ApacheEx** [comment]
yes, it's safe. I know at least a few modules which implement it in such way:

- one table for users
- another table for identities from HybridAuth library

**Comment by heathera2016** [comment]
@ApacheEx Thank you for your reply!!! I really appreciate it. Have a good one!! 👯‍♀️ 🥇 👍
