### ISSUE TITLE
[Google] V3 API not return displayName, firstName and lastName

### ISSUE THREAD

**Issue by iampick** [hybridauth/hybridauth#1181]
Hi guys,

I use the v.3 version and found that Google doesn't return data for
- displayName
- firstName 
- lastName

Please advise me
Thank you

**Comment by ApacheEx** [comment]
Hello, can you tell us which API do you use exactly?

because HA uses this
![image](https://user-images.githubusercontent.com/1918108/84861567-fe2b3f80-b079-11ea-8c3e-c3f648027268.png)

**Comment by iampick** [comment]
Hi, 
I use HA V.3 and use the default setting for Google scope.
this is the result after logged in.
![Screenshot_610](https://user-images.githubusercontent.com/7637063/84863973-1b730480-b0a0-11ea-85ef-2a9dc36df9c0.png)
![Screenshot_609](https://user-images.githubusercontent.com/7637063/84863985-20d04f00-b0a0-11ea-82c0-7bd6c00f7c96.png)

**Comment by chrisgraham** [comment]
For what it's worth, I just tested with no code changes and it works well for me.

**Comment by ApacheEx** [comment]
thanks for testing @chrisgraham  :+1. If there will be still issue, pls fill a new issue.
