### ISSUE TITLE
VK API below v5.21 will trigger deprecation notice and connection errors

### ISSUE THREAD

**Issue by unfulvio** [hybridauth/hybridauth#1182]
## Bug, feature or question?

Bug in version 2.x of HybridAuth: VK cannot be used

### Version and provider

Tested with v2.17.0 of HybridAuth, that seems to declare version `5.0` of the API for VK.

### Reproduction

- Set up a VK app
- Try to connect with HybridAuth

Result: 

You cannot connect 

My workaround was to override the API version in a child handler, however, I believe something could/should be done at library level as well. Posting this in case others have the same issue, as a useful workaround for them.

### More information

VK seems to have introduced a fast deprecation lifecycle in their API.

See https://vk.com/dev/constant_version_updates for more information:

>  From 1 June 2020, versions 5.20 and lower will be outdated.
>  From 1 August 2020, versions 5.50 and lower will be outdated.
>  From 1 October 2020, versions 5.80 and lower will be outdated.

**Comment by chrisgraham** [comment]
FYI for anyone reading this issue, Hybridauth v3 uses 5.95, so is not affected.

**Comment by ApacheEx** [comment]
I'm closing this issue since v2 is under Maintenance mode.
