### ISSUE TITLE
Facebook login doesn't ask for credentials again in newer version after v2.3

### ISSUE THREAD

**Issue by shubh9457** [hybridauth/hybridauth#1185]

**Comment by ApacheEx** [comment]
- what do you mean by newer version?
- version of what? this library or facebook graph?
- v2.3 - is not clear what it is. Please provide more details

**Comment by shubh9457** [comment]
v2.3 of this library. I am using it as a social login library with Magento2 but unable to reauthorize user via facebook. After searching, I got to know about force parameter but that too is not working.

**Comment by ApacheEx** [comment]
so, which version of hybridauth library do you use? There is no "force" support, where did you find it?

**Comment by shubh9457** [comment]
I am currently using v2.13

**Comment by chrisgraham** [comment]
If you want to force a session reset, so that OAuth flow restarts, you can just call `session_destroy(); session_start();` before the button is clicked as some temporary debug code.
I think this issue can be closed.

**Comment by ApacheEx** [comment]
thanks @chrisgraham for explanation.
