### ISSUE TITLE
Google: getUserProfile() does not return all values

### ISSUE THREAD

**Issue by ffh-webadmin** [hybridauth/hybridauth#1186]
I set up hybrid auth to read some basic info out of the google account. So far I get identifier, photoURL, displayName, firstName, 
email and emailVerified.

Tested in V. 3.4. Already updated the scopes:

'scope'    => 'https://www.googleapis.com/auth/userinfo.profile https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/user.gender.read https://www.googleapis.com/auth/user.birthday.read https://www.googleapis.com/auth/user.addresses.read',

But all the values of getUserProfile() are empty.

This is my code:

//Build configuration array
$config = [
	//Location where to redirect users once they authenticate with Facebook
	//For this example we choose to come back to this same script
	'callback' => 'https://mylogin.com/google.php',

	//Facebook application credentials
	'keys' => [
		'id'     => 'xxx', 
		'secret' => 'xxx'
	],

	'scope'    => 'https://www.googleapis.com/auth/userinfo.profile https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/user.gender.read https://www.googleapis.com/auth/user.birthday.read https://www.googleapis.com/auth/user.addresses.read',
];

$adapter = new Hybridauth\Provider\Google($config);
$adapter->authenticate();
$userProfile = $adapter->getUserProfile();

**Comment by chrisgraham** [comment]
I believe this issue should be closed and #961 should be updated to mention getUserProfile should use the people API. The Google implementation of OpenID Connect (which getUserProfile currently uses) doesn't support anything under the scopes discussed in this issue.

That said, I didn't get any actual bugs when I added these scopes, just expected data holes for what is not supported.
