### ISSUE TITLE
Facebook Long-Lived Token support

### ISSUE THREAD

**Issue by chrisgraham** [hybridauth/hybridauth#1196]
From analyzing the Hybridauth code, I can see that refresh tokens are supported implicitly, by recognizing when the oAuth flow provides them, storing them, and using them to refresh expired tokens based on looking at the token expiry timestamps.

However, from what I understand, Facebook uses a totally different mechanism, kind of a perpetual token exchange system, documented here: https://developers.facebook.com/docs/facebook-login/access-tokens/refreshing.
I believe they do this to stop a service getting an oAuth token once and then using it to spy on users in perpetuity even if the user does not use the service. (That said, it seems to me that a dodgy service could keep exchanging tokens without user interaction anyway).

Essentially you start with a short-lived token, and you exchange it for a long-lived token. And then when users are using your service, you do an exchange to get a new token with an extended future expiry timestamp but on a schedule rather than on every interaction.

This is what I can understand from reading Facebook's confusing docs anyway!

I think we need to have support for this in Hybridauth.

**Comment by ApacheEx** [comment]
I've nothing against to support long-lived token here. Do you think it should be somehow configurable? or by default ON?

**Comment by nightw0lv** [comment]
as a user for me it should be configurable otherwise not really long-lived.

**Comment by chrisgraham** [comment]
I've researched token management more.

Refresh tokens exist to be held privately and securely a server, while lifetimed regular tokens exist to be held less securely.

However, Facebook originally worked (and still prominently works) via a JS SDK, which isn't going to store anything securely - and also in mobile apps with no server, which would have the same issue. So I think Facebook's motivation here is probably also to limit the damage from their tokens being leaked. As long as the hacker didn't have the key secret and keep refreshing the token, it would be useless if not used immediately. Especially if it was the default short-lived token.

From what I understand there is no difference between exchanging a token for a fresh one (bumping expiry), and turning a short-lived token into a long-lived token. The first time you do the exchange a short-lived token will become a long-lived token.

I think given that Hybridauth keeps and manages refresh tokens automatically, server-side, it is reasonable to get as close to this as possible for Facebook too, by default. The long-lived token, held server-side, automatically exchanged for new ones when within a certain timespan of expiry, is as close to the refresh token behavior as we can get.

I think what we could do specifically is implement an 'exchange_within_days' parameter. Hybridauth would look to see if its current token expires within the configured number of days, and if so, it would get a new one automatically. Very similar to now how it uses refresh tokens, but based on soon expiry rather than already expired. Maybe we'd default the config setting to 45, so it exchanges immediately for a short-lived token and half-way through the life of a long-lived token.

If this value was null, no exchange would happen.
