### ISSUE TITLE
Consistent state handling (documentation issue?)

### ISSUE THREAD

**Issue by chrisgraham** [hybridauth/hybridauth#1198]
State handling is commonly necessary for a couple of things, as I see it:
a) Knowing what provider you've just authorized against, for users supporting multiple providers
b) Providing a redirect-back-to-where-you-were feature for the user (i.e. they click a login button and eventually end up at the same URL where they clicked the login button)

It's not reliable to use OAuth2 authorize_uri (callback in Hybridauth) with a query string [source: https://stackoverflow.com/questions/55524480/should-dynamic-query-parameters-be-present-in-the-redirection-uri-for-an-oauth2].
You should use the 'state'.

However, the OpenID adapter does not have 'state', so for that you would need to use a query string within the callback, or to use session storage.

I think Hybridauth needs to handle this somehow, and I have 4 possible solutions...

1) If no 'state' value is given, strip any query string from authorize_uri and include it in the auto-generated 'state' value.
2) Implement a 'state' value for the OpenID adapter that adds it to the callback query string
3) Implement a 'state' value for the OpenID adapter that adds it to the session
4) Just document that the developer should use session storage for app state

Thoughts?

My view is '4' is simplest and best, as it is simply a documentation change. Right now I don't think state management is really documented.

EDIT: This is basically the same issue as #1125, they should be merged

**Comment by ApacheEx** [comment]
it's a good point, we really don't have this documented, so I'd go with 4th point for now.
