### ISSUE TITLE
The authorization state [state=HA-----] of this page is either invalid or has already been consumed.

### ISSUE THREAD

**Issue by Ganofins** [hybridauth/hybridauth#1200]
## Bug, feature or question?

Bug.
I am getting authorization state exception on using the social logins from a subdomain.

### Version and provider

3.2
Google, Facebook

### Reproduction

How can we replicate this issue?

Code

```
<?php
    
     require_once('includes/hybridauth/src/autoload.php');

    use Hybridauth\Exception\Exception;
    use Hybridauth\Hybridauth;
    use Hybridauth\HttpClient;
    
    if($_GET["request"] == "google" || $_GET["request"] == "facebook" || $_GET["request"] == "twitter")
    {
        $provider = $_GET["request"];
        $config = [
            'callback' => "https://homepage.com/callback.php?request=$provider",
            'providers' => [
                'Google' => [
                    'enabled' => true,
                    'keys' => [
                        'id' => 'id',
                        'secret' => 'secret',
                    ]
                ],
                'Facebook' => [
                    'enabled' => true,
                    'keys' => [
                        'id' => 'id',
                        'secret' => 'secret',
                    ]
                ],
                'Twitter' => [
                    'enabled' => true,
                    'keys' => [
                        'key' => 'id',
                        'secret' => 'secret',
                    ],
                    'authorize' => true
                ]
            ]
        ];
    }
    
    else
    {
        HttpClient\Util::redirect('https://homepage.com/');
    }

    try
    {
    
            $hybridauth = new Hybridauth($config);
            
            // to disconnect all adapters
            $hybridauth->disconnectAllAdapters();

        $hybridauth->authenticate(ucfirst($provider));

        $adapters = $hybridauth->getConnectedAdapters();

        $userInfo = $adapters[ucfirst($provider)]->getUserProfile();
        
        /**
        * Redirects the user to home page
        */
        header("location: https://homepage.com/");

    }
    catch (Exception $e)
    {
        echo $e->getMessage();
    }
?>
```

On using the above code from the main domain, it's working perfectly.
But supposedly, I visit the same link (https://homepage.com/callback.php?request=google || https://homepage.com/callback.php?request=facebook) from one of my subdomain (https://example.homepage.com). Then I get this error - The authorization state [state=HA----] of this page is either invalid or has already been consumed.

**Comment by chrisgraham** [comment]
My guess is it's a cookie domain problem.
Hybridauth uses PHP sessions, which will save a session cookie.
Either initially you are saving the session on the main domain and the subdomain cannot access it.
Or,
You have a conflicting session on the main domain taking precedence from earlier debugging.
Or, something similar.

**Comment by Ganofins** [comment]
> My guess is it's a cookie domain problem.
> Hybridauth uses PHP sessions, which will save a session cookie.
> Either initially you are saving the session on the main domain and the subdomain cannot access it.
> Or,
> You have a conflicting session on the main domain taking precedence from earlier debugging.
> Or, something similar.

I tested both cases in incognito browsing mode. So, there's not any conflict issue.

**Comment by chrisgraham** [comment]
If I understand correctly, you are initially calling authenticate() from the subdomain, and the callback is on the main domain.

From the PHP manual...

" session.cookie_domain string
    session.cookie_domain specifies the domain to set in the session cookie. Default is none at all meaning the host name of the server which generated the cookie according to cookies specification. See also session_get_cookie_params() and session_set_cookie_params(). "

So I think the session cookie is being created on the subdomain with strict domain checking. The session therefore does not exist on the domain name. Therefore the session-saved OAuth state can't be retrieved within the callback for comparison against the declared state in the URL.

You need to change the session.cookie_domain setting to something that will capture both domains.

**Comment by Ganofins** [comment]
> If I understand correctly, you are initially calling authenticate() from the subdomain, and the callback is on the main domain.
> 
> From the PHP manual...
> 
> " session.cookie_domain string
> session.cookie_domain specifies the domain to set in the session cookie. Default is none at all meaning the host name of the server which generated the cookie according to cookies specification. See also session_get_cookie_params() and session_set_cookie_params(). "
> 
> So I think the session cookie is being created on the subdomain with strict domain checking. The session therefore does not exist on the domain name. Therefore the session-saved OAuth state can't be retrieved within the callback for comparison against the declared state in the URL.
> 
> You need to change the session.cookie_domain setting to something that will capture both domains.

I even tried.

My subdomain - https://example.homepage.com/
was creating a session initially. I even tried deleting that session and then opening up the links https://homepage.com/callback.php?request=google || https://homepage.com/callback.php?request=facebook

But still didn't work.

**Comment by chrisgraham** [comment]
Deleting the session then opening the callback is just doubling down on the problem.
The session needs to exist before OAuth is initiated and persist until afterwards, across both domains.

Try and step through it methodically.

You mentioned you tried to set the cookie domain properly. It should be ".homepage.com" I think. It's been a while since I worked with cookie domains, but IIRC the leading dot serves as a wildcard.

If you have done this, when OAuth goes off to the provider website for confirmation, go back to both your subdomain and main domain and use the browser developer tools to see what cookies exist. For example, in Firefox you can see the cookies under 'Resources' in the developer tools. This will confirm to you whether the cookies are persisting across both main domain and subdomain like they should be, and if there are any conflicting cookies. Things can get complex in real world scenarios, it could be some other part of your code is creating a competing cookie, for example, so it's best to confirm it.

I strongly suspect you will find it is a cookie issue, but without actually stepping through all the debugging with you, there's not much other help I can offer I'm afraid.

**Comment by nightw0lv** [comment]
try commending this 
//$hybridauth->disconnectAllAdapters();

**Comment by chrisgraham** [comment]
> try commending this
> //$hybridauth->disconnectAllAdapters();

Ah yeah, that's definitely going to break it isn't it!
I wonder if that was added to code when debugging his cookie problem, and then he fixed his cookie problem but that code then stopped that working.

**Comment by Ganofins** [comment]
Thanks for the solutions @chrisgraham and @nightw0lv . I think they will resolve the problem.
