### ISSUE TITLE
Error when trying to authenticate using Yahoo and YahooOpenId providers

### ISSUE THREAD

**Issue by mourjan** [hybridauth/hybridauth#1216]
**## Bug, feature or question?**

Not a bug but more like changes of Yahoo API's which are causing hybriauth to fail when trying to authenticate using Yahoo or YahooOpenId as providers

**### Version and provider**

Latest version: 3.4.0
providers as noted above:

1. Yahoo
2. YahooOpenId

**### Reproduction**

Any standard implementation of Yahoo/YahooOpenId login using Hybridauth->authenticate($provider)

**### Errors**

**YahooOpenId throws the following error:**
HYBRIDAUTH:: No OpenID Server found at https://open.login.yahooapis.com/openid20/www.yahoo.com/xrds

**while Yahoo throws the following:**
HYBRIDAUTH:: Signed API request has returned an error. HTTP error 410. Raw Provider API response: {"error":{"@lang":"en-US","@uri":"https://www.yahoo.com/","description":"No longer available","detail":"Social Directory APIs are no longer supported. Please visit https://developer.yahoo.com/oauth/social-directory-eol/ for more details"}}

**### Support**

I tried to read through and come up with a solution in order to submit a pull request, but Yahoo API's were beyond my expertise.
so any help would be appreciated it.

**Comment by chrisgraham** [comment]
OAuth is fixed in Git as of last week. I don't know about OpenID as I consider that a dead technology personally.
