### ISSUE TITLE
Expired/revoked/corrupt token handling

### ISSUE THREAD

**Issue by chrisgraham** [hybridauth/hybridauth#1218]
## Bug, feature or question?

This could be considered a bug, although it is arguable.

Hybridauth is over-optimistic that it will always be able to make an API request with tokens saved.

If a token is expired, it always tries to get a new one via a refresh token. Even if there is no refresh token stored (maybe a provider doesn't provide refresh tokens).

A token could also conceivably be revoked, say if a provider has a data leak and needs to revoke existing tokens.

A provider may also have changed something to make existing tokens no longer work.

In the case of the new Facebook token exchange mechanism which I just implemented, it may be the exchange would be happening too late 

I couldn't think of a better case for new exceptions.
ExpiredOauthTokenException would be thrown when Hybridauth detects its saved token is expired, before it tries to use that token.
RefusedOauthTokenException would be thrown if an API provides a response indicating a token is invalid. I'd have to research whether that is possible though, as it may not be standardized and too burdensome to implement for each provider's API.

Alternatively to ExpiredOauthTokenException, we could modify isConnected to return false if there is no refresh token and the regular token saved is expired. Actually I might even prefer that approach, because it allows automatic restart of the OAuth authentication flow. So, thoughts?

EDIT:
On reflection, I think just improving isConnected enough will be enough. Then if some code that tries to use an old authentication connection fails to call an API for some reason, it can just do a silent disconnect and the user will need to restart the login flow without being bothered.

EDIT:
On checking the code, I can see that some providers are overriding token refresh with a null-op if they don't support it. And some are re-implementing isConnected as I suggested. But it's real messy and needs a cleanup, so I'm going to make a pull request.

### Version and provider

3.4.

### Reproduction

Use an OAuth service with no refresh tokens, then try and use an API.

**Comment by JeroenBakker** [comment]
Shortly after updating Hybridauth to version 3.4.0 we started getting this error on Google logins:

```
Uncaught Hybridauth\Exception\HttpRequestFailedException: Unable to refresh the access token. HTTP error 400. Raw Provider API response: { "error": "invalid_request", "error_description": "Missing required parameter: refresh_token" }
```

It only appears to affect users who have already logged in with Google through Hybridauth before, if I clear my PHP session the login works as expected.
Downgrading back to 3.3.0 doesn't seem to have fixed this.

Do you think this could be related to what you're describing?

**Comment by chrisgraham** [comment]
Yes, definitely.
Google is not providing OAuth refresh tokens, so no auto-refresh of the token can happen.
Because Hybridauth's base OAuth2 implementation assumes refresh tokens, and the Google provider doesn't override that to not use them, you get an error message about a missing refresh token from Google rather than an expired token.
My pull request should 'fix' it by making isConnected return false for the case of an expired token and no refresh token. So there'd be no error and the user would just need to log back in again (which probably is a single click operation because the scope authorization on Google's end should still exist).

**Comment by JeroenBakker** [comment]
Thanks, that makes sense (I think).

Although I'm unsure why this started happening after our upgrade to 3.4.0 but it doesn't seem to be fixed by a downgrade to 3.3.0, we've been successfully using Hybridauth with the Google provider for quite some time now and I don't recall having this issue before.

I'll give your fork a try tomorrow to see if it really does resolve my issue 👍

**Comment by chrisgraham** [comment]
I would guess that the Google tokens just started to hit expiry, or they changed their implementation to not offer refresh tokens.

**Comment by sputnik73** [comment]
Apple Login does not provide refresh tokens, too. The suggested solution modifying `isConnected()` in OAuth2 is basically the same thing I did in that provider class, so of course I think your solution makes sense to move this to the OAuth2 parent class.

**Comment by chrisgraham** [comment]
> Apple Login does not provide refresh tokens, too. The suggested solution modifying `isConnected()` in OAuth2 is basically the same thing I did in that provider class, so of course I think your solution makes sense to move this to the OAuth2 parent class.

Yes, what I did could be considered a generalization of what you did, and I remember stripping your override in the process as it of course was no longer needed.
