### ISSUE TITLE
Function phpdoc comment alignment (super pedantic)

### ISSUE THREAD

**Issue by chrisgraham** [hybridauth/hybridauth#1221]
This kind of thing is bugging me:
```
    /**
    * Initiate a new session
    *
    * @throws RuntimeException
    */
```
because it should be:
```
    /**
     * Initiate a new session
     *
     * @throws RuntimeException
     */
```

It's obviously a tiny thing, but it looks wrong and it is inconsistent across the code. It's good to get consistency so that contributors can then run with that.

I'm not planning to make a pull request as big search and replaces are against your contribution guidelines (for good reason).

**Comment by ApacheEx** [comment]
I fully aggree that style of comment should be as you purpose. Somehow we need to make one big PR which changes this in all places.

**Comment by chrisgraham** [comment]
As discussed in https://github.com/hybridauth/hybridauth/pull/1214 there are other PSR-2 issues, that I am willing to fix in the same pull request.
