### ISSUE TITLE
clear all permission when user logout in my application

### ISSUE THREAD

**Issue by nandinirouthu** [hybridauth/hybridauth#1227]
i used hybridauth for php when user login from google and other logins user select a specfic account then user logout from email in browswer and at the same time logout from application and try to login again verification window not showing so how to clear logout from my social plugins when user logou

**Comment by chrisgraham** [comment]
It sounds like what is happening is Hybridauth has the OAuth2 token saved in the session, so is just using that session again.

You said the verification window doesn't show - as expected- but what happens next? Is Hybridauth able to get the user's profile details from its existing token? And if not, I would assume it is throwing an error about an invalid key, in which case you can take that as a cue in your code to disconnect the adapter, allowing the user to log in again from fresh.

This is how I did it in our CMS...
https://gitlab.com/composr-foundation/composr/-/blob/v11/sources_custom/hooks/systems/login_providers/hybridauth.php

Obviously there's a lot of CMS-specific stuff there, but it is doing what I said. You can see it catches errors and does a disconnect if it gets them. This is happening within the CMS when it tries to create a new native session from what Hybridauth has saved from previously. So it is a silent disconnect when it happens and it just prepares the way for the user to have to click the Hybridauth-driven login button again.
