### ISSUE TITLE
Hybridauth 3.3 working with Google, Github, Twitter, LinkedIn, but not with Facebook.

### ISSUE THREAD

**Issue by Geepup** [hybridauth/hybridauth#1228]
Hybridauth 3.3 working with Google, Github, Twitter, LinkedIn, but not with Facebook.

This is the testcode:

````
<?php
session_start();
include 'hybridauth/src/autoload.php';

$callback = "https://$_SERVER[HTTP_HOST]" . strtok($_SERVER["REQUEST_URI"], '?'); // callback to this script
$config = ['callback' => $callback, 'keys' => ['id' => 'xxxxxxx', 'secret' => 'xxxxxxxxxxx' ],];
$provider = new Hybridauth\Provider\Facebook($config);

$provider -> authenticate();
$userProfile = $provider -> getUserProfile();
$provider -> disconnect();
echo "<pre>" . print_r($userProfile, true) . "</pre>";
?>
````
FB login page opens and after entering credentials the user is logged in. FB returns a 'code' parameter in the callback URI, but Hybridauth does not return and shows a 500 Internal Server Error page.

**Comment by chrisgraham** [comment]
This implies there is probably some kind of Apache or PHP error happening and your server is set up to not display errors.
Do what you need to do to enable error messages on some kind of development environment (and/or check log files - esp the Apache error log), and then that should tell you a lot more about the situation. If you think it's still a bug in Hybridauth you can bring the error message back to us here.

**Comment by nightw0lv** [comment]
facebook works if you configure the application correctly
