### ISSUE TITLE
deprecation 

### ISSUE THREAD

**Issue by nightw0lv** [hybridauth/hybridauth#1229]
using latest version
using latest php
---------- NEW ERROR MESSAGE ----------
TIME ----> 18:10:14
LEVEL ---> [E_DEPRECATED]
FILE ----> [/var/www/html/vendor/hybridauth/hybridauth/src/Thirdparty/OpenID/LightOpenID.php]
LINE ----> [1100] 
MESSAGE -> Function get_magic_quotes_gpc() is deprecated

**Comment by chrisgraham** [comment]
I think this should be merged with #942.

**Comment by ApacheEx** [comment]
agree, I'm closing this issue in favor of #942

**Comment by ApacheEx** [comment]
I've removed this function - since it's pain to have it when you use php 7.4.
