### ISSUE TITLE
Github API: Deprecating API authentication through query parameters since May 5, 2021 at 16:00 UTC

### ISSUE THREAD

**Issue by abolabo** [hybridauth/hybridauth#1231]
Hi, 
Please note this future problem.
More details here 
https://developer.github.com/changes/2020-02-10-deprecating-auth-through-query-param/

Best regards
Dmitry

**Comment by chrisgraham** [comment]
Thanks. I don't think we're doing that though are we? GitHub is using default OAuth2 api request headers:
```
        $this->apiRequestHeaders = [
            'Authorization' => 'Bearer ' . $this->getStoredData('access_token')
        ];
```
The blog post mentions to say 'token' not bearer, but given I tested it recently it's probably fine.


Let me know if I missed something here.

**Comment by ApacheEx** [comment]
yeah, I just checked. We are good here already.

I'm closing this issue, since nothing to do here.

**Comment by daveagp** [comment]
Do you know if this is dependent on the version of HybridAuth? I am trying to figure out if it is expected that I get this error while running v2 of HybridAuth... trying to figure out if I need to upgrade to v3 by May.

For reference, I think this is the v2 GirHub provider;
https://github.com/hybridauth/hybridauth/blob/v2/additional-providers/hybridauth-github/Providers/GitHub.php

**Comment by daveagp** [comment]
The specific error email I am getting:
===
Hi @daveagp,

On December 26th, 2020 at 04:41 (UTC) your application (Websheets) used an access token (with the User-Agent OAuth/2 Simple PHP Client v0.1.1; HybridAuth http://hybridauth.sourceforge.net/) as part of a query parameter to access an endpoint through the GitHub API:

https://api.github.com/user

Please use the Authorization HTTP header instead as using the `access_token` query parameter is deprecated.
