### ISSUE TITLE
How to grab Facebook user profile URL? 

### ISSUE THREAD

**Issue by bologer** [hybridauth/hybridauth#1232]
## Question 
 
I would like to know if it is possible to get Facebook user profile URL? 

Currently, I am generating it from user's info, but it gives 404.

This is what I have at the moment: 

https://www.facebook.com/profile.php?id={id}

But it doesn't work. 

Is there any better way to do it? Or maybe I missed something?

### Version and provider

Provider: Facebook 
Version: v3.0.0

**Comment by chrisgraham** [comment]
It should work IMO. Can you give an example URL that is a 404?

**Comment by ApacheEx** [comment]
yeah, your URL looks different that exists in the code: https://github.com/hybridauth/hybridauth/blob/bc6215f87ef04c03ef35d8b00abc1903c4985609/src/Provider/Facebook.php#L77

**Comment by ApacheEx** [comment]
if you still face this issue, pls create a new one with more details. Thx
