### ISSUE TITLE
Twitter provider - Direct message {"code":32,"message":"Could not authenticate you."}

### ISSUE THREAD

**Issue by gonzalesc** [hybridauth/hybridauth#1249]
Hi,
I can connect and send a direct message or status using Postman, but when I want to use Hybridauth in my APP it shows error code 32 : "could not authenticate you"

This is my code:

```
$config = [
	'callback'	=> 'http://www.myweb.com/callback',
	'providers' => [
	    'Twitter' => [
			'enabled'		=> true,
			'include_email'	=> true,
			'keys'			=> [
				'key'			=> '##############'
				'secret'		=> '##############'
			],
		],
	],
];

$hybridauth = new Hybridauth\Hybridauth( $config );
$adapter = $hybridauth->authenticate( 'Twitter' );

$accessToken = $adapter->getAccessToken();
$userProfile = $adapter->getUserProfile();

$params = [
	'event' => [
		'type' => 'message_create',
		'message_create'	=> [
			'target'		=> [ 'recipient_id' => '52622829' ],
			'message_data'	=> [ 'text' => 'testing 123 123' ],
		],
	],
	'oauth_callback' => 'http://www.myweb.com/callback',
];

$header = [
	'Content-Type' => 'application/json'
];

$direct = $adapter->apiRequest( 'direct_messages/events/new.json', 'POST', $params, $header );
```

Error:
`{"code":32,"message":"Could not authenticate you."}`

- I've added/removed the oauth_callback param
- I've tried the poststatus method but I get the same error

In Postman it works.

**Comment by gonzalesc** [comment]
Hi.
With POSTMAN, it works, but using this library, no.

I have compared both Curl code and I see that the problem is the nonce, signature and timestamp. If I put the values that POSTMAN generate to the code PHP in Hybrithauth, it works

Regards

**Comment by gonzalesc** [comment]
Hi.
I found the problem! it is when Hybridauth generates the signature to OAuth1 adapter using the "**OAuthSignatureMethodHMACSHA1**" class

The generate this signature, Hybridauth gets the method HTTP, the URL HTTP, and the parameters, in this last is the problem.

The "**get_signable_parameters**" method in **OAuthRequest** class, get the parameters and in those, too are the body parameters, for example, the status message to Twitter or the direct message, but if it is bidimensional is a problem because when it is passed with the "**OAuthUtil::build_http_query**" method, it generates "`event=array&event=message_create....oauth_.....`"

Here it repeats 2 times the "event" param, and the signature is generated incorrectly. I deleted the event param and it works.

Another example is when I use the "setUserStatus" method and it uses a bidimensional array `[ 'status' => , 'media_ids' => ]` , here is the same problem.

Regards

**Comment by reinos** [comment]
Any update on this, and has this been fixed in the latests releases?

**Comment by ApacheEx** [comment]
Hi @reinos 

there is already PR which fixes it. I'll merge it as soon as CI will be green (hopefully in few mins). And then later on this week I'd like to release HA 3.7 with all these fixes.

**Comment by ApacheEx** [comment]
the fix should be available in master branch
