### ISSUE TITLE
v3.5 on packagist does not match current master release

### ISSUE THREAD

**Issue by romain-le-mercier** [hybridauth/hybridauth#1252]
The packagist version is not up to date, it's tagged 3.5 (wich matched the tag on github).
But the problem is that the Facebook graph version is not up to date (V6.0 on packagist vs V8 on github), we need to update to V8 before the 24th of october if i'm not mistaken.

Does the packagist update is planned?

**Comment by ApacheEx** [comment]
here we go: https://github.com/hybridauth/hybridauth/releases/tag/3.6.0
