### ISSUE TITLE
Array and string offset access syntax with curly braces is deprecated

### ISSUE THREAD

**Issue by oviliz** [hybridauth/hybridauth#1260]
## Bug, feature or question?
Bug.

### Version and provider
v2.17.0, Twitter, PHP 7.4

### Reproduction
Configure Twitter, try to sign in and it throws an exception similar to https://github.com/hybridauth/hybridauth/issues/1127:

> [2020-11-05 02:38:10] main.CRITICAL: Deprecated Functionality: Array and string offset access syntax with curly braces is deprecated in vendor/hybridauth/hybridauth/hybridauth/Hybrid/thirdparty/OAuth/OAuth.php on line 106 {"report_id":"bfeb6035f6299171cdacb6f11a36b179acc6e883b307a0ce31249ecdc0dddfe7","exception":"[object] (Exception(code: 0): Deprecated Functionality: Array and string offset access syntax with curly braces is deprecated in vendor/hybridauth/hybridauth/hybridauth/Hybrid/thirdparty/OAuth/OAuth.php on line 106 at vendor/magento/framework/App/ErrorHandler.php:61)"} []
> Array and string offset access syntax with curly braces is deprecated in vendor/hybridauth/hybridauth/hybridauth/Hybrid/thirdparty/OAuth/OAuth.php on line 106

To fix, I've changed line 106 from
`      $result |= ord($built{$i}) ^ ord($signature{$i});`
to
`      $result |= ord($built[$i]) ^ ord($signature[$i]);`

**Comment by chrisgraham** [comment]
Thanks for the report. OAuth.php does not exist anymore, and I linted for up to PHP 8 recently on the master branch. v2 is not maintained.

**Comment by ApacheEx** [comment]
indeed, I'm closing this task since it's not security issue

**Comment by adrianostanley** [comment]
Any chance of this change be released as `2.17.1` so we can update on composer instead of migrating to v3?
