### ISSUE TITLE
Undefined index: oauth_token in vOAuth1Client.php on line 85

### ISSUE THREAD

**Issue by oviliz** [hybridauth/hybridauth#1261]
## Bug, feature or question?
Bug.

### Version and provider
v2.17.0, Twitter, PHP 7.4

### Reproduction
Configure Twitter and try to sign in.

> Ooophs, we got an error: Notice: Undefined index: oauth_token in vendor/hybridauth/hybridauth/hybridauth/Hybrid/thirdparty/OAuth/OAuth1Client.php on line 85

![image](https://user-images.githubusercontent.com/73616/98192283-af8c1e00-1f12-11eb-89d7-9dffd9c6d4eb.png)

**Comment by nightw0lv** [comment]
1 question only to you, why you use latest php and old version of hybridauth?

**Comment by oviliz** [comment]
@nightw0lv , this is installed as a soft requirement for a Magento theme and their documentation says to install v2.

Also, reading the Versions table, I was under the impression that v2 was the stable version while v3 a dev-like (under development) version.
![image](https://user-images.githubusercontent.com/73616/98254355-1857b280-1f74-11eb-8dfc-327bad7b4d7d.png)
I guess now that what is saying is that v2 is still supported with critical security updates only and is about to become EOL while v3 is the current fully supported version.

I've asked the theme developer anyway if the template is compatible with v3:
https://themeforest.net/item/martfury-multipurporse-ecommerce-magento-2-theme/21687089/comments

Thank you.

**Comment by nightw0lv** [comment]
ah for that amount of money he should at least update it to v3 in order to support his customers but anyway, the correct thing to do is go in your template's developer and ask to update.

**Comment by oviliz** [comment]
I've asked the theme's Developer about v3 and hopefully, he will be encouraged to upgrade.

Closing this now as I've figured that I've set a wrong callback URL on Twitter.
