### ISSUE TITLE
Tests are not PHP 5.4 compatible

### ISSUE THREAD

**Issue by szepeviktor** [hybridauth/hybridauth#1264]
## Bug

![kép](https://user-images.githubusercontent.com/952007/99305649-57c7ae00-2854-11eb-843c-f5e0e783191e.png)
https://www.php.net/manual/en/language.oop5.changelog.php

in tests:

https://github.com/hybridauth/hybridauth/blob/edec9a920394bb387a2d2d4b97bfc65793e663d9/tests/User/ActivityTest.php#L18-L21

in action: https://travis-ci.org/github/hybridauth/hybridauth/jobs/744013636

**Comment by tobias-trozowski** [comment]
I'm not a maintainer of this repo but i really recommend stop supporting a language version which got its last fix over 5 years ago and wont ever get an update again, not even a security update.

**Comment by szepeviktor** [comment]
> a language version which got its last fix over 5 years ago

Many project manager decides not to pay back technical debt.

google:banking COBOL

**Comment by ApacheEx** [comment]
https://travis-ci.org/github/hybridauth/hybridauth/builds/744975624 - should work.

**Comment by ApacheEx** [comment]
there will be no support for older versions of php in HA v4
