### ISSUE TITLE
composer issue

### ISSUE THREAD

**Issue by nightw0lv** [hybridauth/hybridauth#1270]
http://prntscr.com/vzk52a
i use latest update this happens on a simple update after installing php 8.0 if you require more information than this, ask.

**Comment by ApacheEx** [comment]
yeah, there is currently no support of php8 - but I hope everything should work and we just need to adapt composer.json file + add it to travis.yml

**Comment by nightw0lv** [comment]
well so far google and tweeter working fine not received any errors but should be tested more

**Comment by nightw0lv** [comment]
is this going to be solved soon because right now i cant update any dependencies on my project and i dont know any alternative way to do so

**Comment by LittleBigBug** [comment]
You can use your own fork of hybridauth with your composer.json changed in the meantime:

```json
{
    "repositories":
    [
        {
            "type": "vcs",
            "url": "https://github.com/Littlebigbug/hybridauth"
        }
    ],
    "require": {
        "php": "^8.0",
        "hybridauth/hybridauth": "dev-master",
    }
}
```

**Comment by nightw0lv** [comment]
i did that before i post here, i am currently using ./composer update --prefer-dist --ignore-platform-reqs but this repository is not updating in any way

**Comment by ApacheEx** [comment]
guys, I just extended it

I'll merge it to master as soon as CI will be green
