### ISSUE TITLE
WeChat problem

### ISSUE THREAD

**Issue by yereth** [hybridauth/hybridauth#1281]
## Bug, feature or question?

It's a bug

### Version and provider

Hybrid Auth 3.6, pulled up from composer. Issue is with the WeChat provider

### Reproduction

I'm getting the following error:

Fatal error: Uncaught Error: Unsupported operand types in /xxx/vendor/hybridauth/hybridauth/src/Provider/WeChat.php on line 85

Here's a snippet of the code at that line:

`
    $this->tokenRefreshParameters += [
        'appid' => $this->clientId
    ];
`

It appears $this->tokenRefreshParameters here is still null and doesn't like the += operation. Not sure why this happens, but it happened on two different servers with different setups. I'm using oauth2 here for WeChat.

Would be great if there's a solution to this!

Thanks,
Yereth

**Comment by ApacheEx** [comment]
Hello, thanks for reporting. It's fixed in master branch and would be released with next version. But probably you can check it out already.

**Comment by yereth** [comment]
Thanks!
