### ISSUE TITLE
Unexpected behavior in Codeigniter 3.x

### ISSUE THREAD

**Issue by ovillafuerte94** [hybridauth/hybridauth#1285]
Hi, I am applying the Hybridauth 3.6 library in Codeigniter 3, while I authenticate using facebook as provider I get the error **ERR_TOO_MANY_REDIRECTS**

I would appreciate any helpful comments

**Comment by ApacheEx** [comment]
Hello,
feel free to check out this repo which works with HA 3.x and Codeigniter 3.x
https://github.com/ApacheEx/CodeIgniter-HybridAuth

**Comment by ovillafuerte94** [comment]
> Hola, no
> dude en consultar este repositorio que funciona con HA 3.xy Codeigniter 3.x
> https://github.com/ApacheEx/CodeIgniter-HybridAuth

Thanks for the recommendation 👋
