### ISSUE TITLE
Problem with the Odnoklassniki provider

### ISSUE THREAD

**Issue by 26Exp** [hybridauth/hybridauth#1290]
### Error
Fatal error: Uncaught Hybridauth\Exception\UnexpectedApiResponseException: Provider API returned an unexpected response. in /home/c77664/public_html/MyDomain.MD/vendor/hybridauth/hybridauth/src/Provider/Odnoklassniki.php:86

**Comment by ApacheEx** [comment]
unfortunately. this is not clear at all. Any other details?

**Comment by ApacheEx** [comment]
closed as no details provided
