### ISSUE TITLE
Sessions path not matching server

### ISSUE THREAD

**Issue by zee3h** [hybridauth/hybridauth#1291]
This is a bug, and I'm not at all a technical person so please excuse the possibly un-technical description.

I currently run into a 'critical error' when trying to execute social login for my websites users. This seems to be due to a misconfiguration in sessions paths between the Wordpress plugin (UsersWP, using https://hybridauth.github.io/) and my server (self-managed on Upcloud). 

This is what shows on the error log:
![Screenshot 2021-03-03 at 19 02 57](https://user-images.githubusercontent.com/80262866/110324578-1549fd00-800e-11eb-9400-0d3597177c12.png)

A friend kindly offered to investigate the issue and got this far. Not sure how accurate this is but he seems to think that the sessions path within HybridAuth is defined incorrectly (hardcoded?) to /var/cpanel/php/sessions when it should be /var/lib/php/sessions:

![Screenshot 2021-03-08 at 12 59 59](https://user-images.githubusercontent.com/80262866/110324721-432f4180-800e-11eb-84c5-b80e5172f0ed.png)

### Version and provider

I'm using Hybrid Auth via the Wordpress plugin UsersWP. As far as I can tell they use Hybrid Auth V3.

### Reproduction

You can replicate the critical error by going to https://300hours.com/login and clicking on either social login option (Google or Twitter).

**Comment by ApacheEx** [comment]
hybrudauth doesn't have any logic related to session path. It inherits it from your server configuration. I'm pretty sure something is on the server side or in your code.

**Comment by zee3h** [comment]
Thanks! Would you be able to shed any clues as to where to look? My server admin has spent quite some time looking but no joy, so any clue or direction could massively help.

**Comment by ApacheEx** [comment]
pls re-open if you still have any questions related to this problem.
