### ISSUE TITLE
Apple Signature verification failed

### ISSUE THREAD

**Issue by AdamchukAndrii** [hybridauth/hybridauth#1292]
## Bug, feature or question?

Bug

### Version and provider

Hybridauth 3.7.0 and Apple provider

### Reproduction

After upgrading Hybridauth to the latest version I received  **Signature verification failed** error.  
After some investigation I found the cause of the error.
#1257  especially https://github.com/hybridauth/hybridauth/commit/d21fe335e68617409015545ded7a9e434171ed82#diff-6dc7b6ec9e3e7b5e2450b6e5671ba6e4de184af36b8449577e552b9aed690fd3L190
I debugged it and found that from Apple I received array $publicKeys of 3 elements and only the third key is valid, all previous ones are invalid and throws exception on JWT::decode. 
Step by step in my case:

- In 3.6.0 version (third iteration) JWT::decode doesn't throws exception - the $error variable is false and execution continues on.
- In 3.7.0 version (third iteration) key is valid but $error variable contains exception message from previous iteration and execution fails on IF after foreach.

I'm not expert with Apple and I don't know is this case with three $publicKeys when only one is good - valid case or it's just my specific case. I will be very appriciate for any help in this question. 
If this is my specific case - I will stay on 3.6.0 version. If this is normal case for Apple, we need to make revert of this two lines of code.

**Comment by ApacheEx** [comment]
Hi, thanks for reporting and investigating the issue, will release a fix as 3.7.1 soon

**Comment by sputnik73** [comment]
Thank you for the report and the quick fix!
