### ISSUE TITLE
LinkedIn scopes

### ISSUE THREAD

**Issue by reinos** [hybridauth/hybridauth#1296]
## Bug, feature or question?
Question and Bug

It seems that the LinkedIn Provider has fixed scopes.

```
// hybridauth/hybridauth/src/Provider/LinkedIn.php
protected $scope = 'r_liteprofile r_emailaddress w_member_social';
```

As `w_member_social` scope belongs to the "Marketing Developer Platform" product it should be optional and we should stick with the default `r_liteprofile r_emailaddress`. If we enable need more scopes, we should add this later on.

Is this a correct assumption, or did I miss something?

### Version and provider
Hybrid Auth Version: 3.6.0
Provider: LinkedIn

### Reproduction

Simply create a LinkedIn app with just the "Sign In with LinkedIn" product enabled and it shows you an error `error=unauthorized_scope_error&error_description=Scope+%26quot%3Bw_member_social%26quot%3B+is+not+authorized+for+your+`

**Comment by ApacheEx** [comment]
Hello,
This makes totally sense for me. Thanks!
Just pushed needed changes to master branch.
