### ISSUE TITLE
HTTP/1.1 200 OK

### ISSUE THREAD

**Issue by yanilove10** [hybridauth/hybridauth#1321]
HTTP/1.1 200 OK
    Content-Type: application/json; charset=utf-8
    Content-Length: 127
    open url[1.1 200 OK     Content-Type: application/json; charset=utf-8     Content-Length: 127     ...      123{"access_token":"ACCESS_TOKEN"}](    HTTP/1.1 200 OK     Content-Type: application/json; charset=utf-8     Content-Length: 127     ...      #123 {"access_token":"ACCESS_TOKEN"}) #1319 

    {"access_token":"ACCESS_TOKEN"}

_Originally posted by @chirejaszy10 in https://github.com/hybridauth/hybridauth/issues/1163#issuecomment-1026685081_

**Comment by ApacheEx** [comment]
well, closing this issue as it doesn't give  any reasonable information.
