### ISSUE TITLE
keycloak.php doesnot work for me

### ISSUE THREAD

**Issue by ilamtap** [hybridauth/hybridauth#1324]
## Bug, feature or question?

Is this a bug, a feature request or a question?
I am trying to integrate question2answer tool with keycloak , i have configured the details but no luck.

### Version and provider

What version of Hybrid Auth does this relates to?
Is this an issue with a provider? If yes, which one? 
keycloak.php
### Reproduction

How can we replicate this issue?
we can re-config if required.

**Comment by ApacheEx** [comment]
after internal discussing, the issue seems not related to HA itself.
