### ISSUE TITLE
How to get storage to work dependably?

### ISSUE THREAD

**Issue by jamminjames** [hybridauth/hybridauth#1334]
## Bug, feature or question?

Seems to be a bug, but maybe I'm doing something wrong. I've seen other issues posted that relate to this, including #1301. They also said what I've noticed: the problem seems intermittent. Sometimes everything works fine, other times not.

Could it be a PHP.ini sessions setting? What are the optimal PHP settings for Hybridauth sessions to work reliably?

For example, trying to solve this, I went back to the bare bones "callback" file shown in Example 7. But it also has the same problem: after returning from authorization, nothing is stored anymore via Hybridauth storage.

This part of the "callback.php" code from example 7 causes a blank page, because nothing is stored once returning from authorization, as shown by a blank in the echo line where the provider should be. Also, nothing shows for `$userProfile`:

```
echo 'after returning, use stored provider: '.$storage->get('provider').'<br>';
    if ($provider = $storage->get('provider')) {
        $hybridauth->authenticate($provider);
        $storage->set('provider', null);

        // Retrieve the provider record
        $adapter = $hybridauth->getAdapter($provider);
        $userProfile = $adapter->getUserProfile();
        echo '<pre>'; print_r($userProfile); echo '</pre>';
   }
```
This is a very frustrating issue. I've checked our server's session storage, everything seems fine there.

### Version and provider

What version of Hybrid Auth does this relates to? 3.8
Is this an issue with a provider? If yes, which one? No, same with any.

### Reproduction

How can we replicate this issue? Use above code in the callback, but as I said, the problem seems intermittent.

**Comment by jamminjames** [comment]
Okay, it seems this was just an issue with two apps that conflicted in the browser, killing each other's sessions. The other was Live Helper Chat. Now I'm using different browsers for each, and it's working fine. 

It seems counterintuitive, since information stored in a session is stored at the web server, as opposed to in the browser, like cookies. So why would it matter that I'm using different browsers for the two apps?

**Comment by stephanedupont** [comment]
This is happening to me also, but only for Apple sign-in in my case. Same thing, the session is (sometimes) cleared. I generally have to sign in two times when signing in with Apple because the first time my session has been cleared.

Thank you for your post as it helped me realize that the problem is only on my Google Chrome session. I don't encounter this on Firefox and Edge. So it's probably something similar where an extension is clearing the session data.

Now the question is which one, how can it be solved, and how many users will encounter this also...

**Comment by stephanedupont** [comment]
... well, I disabled all extensions and the problem is still happening. What could cause the session being cleared if not an extension?

**Comment by mijorus** [comment]
In my case the problem was caused by `session.cookie_samesite` being set to `Strict`. 
Please make sure you understand the implications that it has before changing anything

**Comment by nftticketsro** [comment]
Is there any way to keep the cookies SameSite=Strict?
