### ISSUE TITLE
Apple sign in broken for composer 1.x

### ISSUE THREAD

**Issue by adamjimenez** [hybridauth/hybridauth#1340]
Apple sign in broken for composer 1.x
It gives the error
`Class 'Composer\InstalledVersions' not found `

Due to [this line](https://github.com/hybridauth/hybridauth/commit/92b5e1c0059c72017b5f1a8c86e2a8bde4ff8fa1#diff-6dc7b6ec9e3e7b5e2450b6e5671ba6e4de184af36b8449577e552b9aed690fd3R10).

**Comment by sputnik73** [comment]
Thank you for your report, I confirm this is a bug.

I guess there are two solutions: 

a) skip the version check if 'Composer\InstalledVersions' is not found. So assume JWT is an old version if an old version of composer is used (same behavior than before [the code change](https://github.com/hybridauth/hybridauth/commit/92b5e1c0059c72017b5f1a8c86e2a8bde4ff8fa1#diff-6dc7b6ec9e3e7b5e2450b6e5671ba6e4de184af36b8449577e552b9aed690fd3R10) 
b) do a hack like `composer show '<package>' | sed -n '/versions/s/^[^0-9]\+\([^,]\+\).*$/\1/p'` to get the version with composer 1. I don't think that this is a clean solution and it also might be a performance problem.

Opinions are welcome, option 1) should be easy to solve.
