### ISSUE TITLE
Provider issues in 3.8.2

### ISSUE THREAD

**Issue by janturon** [hybridauth/hybridauth#1351]
I suggest to revert ApacheEx politic update which breaks the [Code of Conduct](https://github.com/hybridauth/hybridauth/blob/1d17157382a60494f112fffb463f84dc4ec4f236/CODE_OF_CONDUCT.md). To censore whole culture and nation and coming with emotional proclamations is rather inappropriate, threatening, offensive and harmful. In the near future hybridauth may end up like China, censoring [everything](https://meta.stackexchange.com/a/287070/181028).
I suggest to read about [Rusyns](https://en.wikipedia.org/wiki/Rusyns): one family lives next to my grandmother: they escaped from Transcarpathia to Czechoslovakia after beeing brutalized by Ukrainian units shouting "Slava Ukraini" in their face. If you must, please at least change the infamous slogan to "Mir Ukraini". Reverting to 3.8.1 not to exclude my Ukrainian/Rusyn/Russian (it is hard to distinguish, the families are mixed) friends having Russia-based OAuth providers.

**Comment by ApacheEx** [comment]
russia is a terrorist state who invaded Ukraine, I think it's pretty clear and no sense to explain it here. Reverting is not possible

**Comment by janturon** [comment]
What is pretty clear to me is that "many more than tens of thousands raped" as your banner claims is obvious nonsense, but whatever. What an irony that I intend to use hybridauth 3.8.1 to support VKontakte in a project called Z-Games ;-) I am happy that the MIT license allows it. Thank you for contributing.

**Comment by ApacheEx** [comment]
I don't care what you use, and what is the project you doing, it's definitely something wrong with you, and I don't beed to read the code of conduct to understand what is the going on here, wish you nothing.
