### ISSUE TITLE
What to do about bots feeling out the callback url

### ISSUE THREAD

**Issue by jamminjames** [hybridauth/hybridauth#1361]
## Bug, feature or question?

Question

### Version and provider

What version of Hybrid Auth does this relates to? 3.8
Is this an issue with a provider? If yes, which one? No

### Reproduction

How can we replicate this issue?

We've been periodically getting what seem to be bots trying to sign directly at the callback url, for example: website.com/social-callback.php?provider=EmPW0  -- trying a series of seemingly random bits of text for the "provider".

Of course, they're not successful and get caught as exceptions, but is there a way to throttle this behavior? So far, they've only tried about 30 times in the space of less than a minute, but if they tried a more persistent attack, it seems like they could slow down the site.

Thanks for any help.

**Comment by champsupertramp** [comment]
I would create a nonce or token for the Social Login link before you redirect them to authenticate with social APIs.

https://medium.com/nerd-for-tech/how-to-create-a-simple-nonce-in-php-a5afe046beee

**Comment by jamminjames** [comment]
Thanks!
