### ISSUE TITLE
phpseclib3 support

### ISSUE THREAD

**Issue by mvenghaus** [hybridauth/hybridauth#1364]
Hello,

will there be support for phpseclib3? i'm trying to use it in a project where another module needs v3. both at the same time does not seem like the best solution ;)

Regards
Marcus

**Comment by ApacheEx** [comment]
Hi,
since it's optional dep which is needed for apple peovider, we can support v3 as well

maybe, some changes are needed to do so

**Comment by mvenghaus** [comment]
@ApacheEx i created a pull request for this

https://github.com/hybridauth/hybridauth/pull/1366

**Comment by ApacheEx** [comment]
This is merged now, and will be released as 3.10 (I guess, at the end of this month). Closing for now
