### ISSUE TITLE
PHP 8.2 - Deprecated Functionality: Creation of dynamic property

### ISSUE THREAD

**Issue by DmitrySamushchenko** [hybridauth/hybridauth#1371]
## Bug

![image](https://user-images.githubusercontent.com/90465167/235311630-f00c2314-54c6-479a-9add-0b2bf80c3e93.png)

### Version and provider

3.9.0

### Reproduction

Use Twitter Auth Provider to reproduce it (more likely this issue with all Auth Providers)

**Comment by alexey-motorny-amasty** [comment]
the same case

**Comment by svarup** [comment]
+1

**Comment by richardczeiger** [comment]
+1. This issue still exists as of 29 Sept 2023. I think this was first reported around December 2022. It would be great if the team could look at correcting this. Cheers!

**Comment by svarup** [comment]
This issue has already been fixed #1383 and merged in the master branch. The issue still exists in versions <= 3.10.0 because the new version tag was not created after the pull request merged in the master.

**Comment by ApacheEx** [comment]
it should be released as 3.11 now, pls have a look.
