### ISSUE TITLE
Facebook provider and email?

### ISSUE THREAD

**Issue by dani3l3** [hybridauth/hybridauth#1372]
## Bug, feature or question?

Not sure if a bug or something changed.
Login with Facebook stopped returning the email in the user_profile?

Actual facebook login has occurred, I get the token in the session, etc.
But programmatically, this is what I get  from  $adapter->getUserProfile()

see the email is missing?
I do have permission with this production site ('app') from facebook to get the email (I went to triple-check on their site). It has been working for well over a year without problems... I just noticed it today, it might have broken days or weeks ago but not months....

object(Hybridauth\User\Profile)#10 (23) { ["identifier"]=> string(17) "10159855083953688" ["webSiteURL"]=> NULL ["profileURL"]=> string(42) "https://www.facebook.com/10159855083953688" ["photoURL"]=> string(78) "https://graph.facebook.com/v8.0/10159855083953688/picture?width=150&height=150" ["displayName"]=> string(24) "Daniele Lupetto Montagna" ["description"]=> NULL ["firstName"]=> string(7) "Daniele" ["lastName"]=> string(8) "Montagna" ["gender"]=> NULL ["language"]=> NULL ["age"]=> NULL ["birthDay"]=> int(0) ["birthMonth"]=> int(0) ["birthYear"]=> int(0) ["email"]=> NULL ["emailVerified"]=> NULL ["phone"]=> NULL ["address"]=> NULL ["country"]=> NULL ["region"]=> NULL ["city"]=> NULL ["zip"]=> NULL ["data"]=> array(0) { } }

This is what remains the $_SESSION

    [HYBRIDAUTH::STORAGE] => Array
        (
            [provider] => 
            [facebook.access_token] => EAAOQ7BcPIekBAATHKVfUZAzQaNvNxrr61Y1Ad2NxXFiZCwan4vS3VaUyBudzSO5w1XNFTaPmStJxiXBuOXImerXT0qaRVAAX0xZC6PhvZA2qr2zlBzf4dgPMc74RjF8upMZABKFmb67lPZCH8zdHGZBAks7aMktoZBRLL2R7t4IUtPV0eUzzgW64mtptcbIeErTvd8JpHOZAh7GtcrRtmsrT4sPDpGWdFs9sshF2eYZBO9egZDZD
            [facebook.token_type] => bearer
            [facebook.expires_in] => 5177445
            [facebook.expires_at] => 1688839252
        )

### Version and provider
I upgraded to latest version but no changes.
Just the Facebook provider is doing this; Amazon and Google provider are still working with the same code.

**Comment by mvenghaus** [comment]
do you have the additional permission in facebook to get the email address?

**Comment by dani3l3** [comment]
Yes, I do, we are verified, I checked... this has been working for over a year and we did go thru a lot of their privacy reviews to be allowed to retrieve this bloody email.... and yet even on the API explorer it's not giving me back the email, so it seems the issue is on their end. I am opening also a suppot ticket to facebook to ask on their end.

As a side note, I do see here https://github.com/hybridauth/hybridauth/blob/master/src/Provider/Facebook.php#LL56C30-L56C62 that you are calling graph v8 ? They are on v16 and are about to deprecate version 10...

Still, on the api explorer with v16 it tells me my 'field is empty of disallowed by access token' so it must be something with their configuration/permission in the 'app'....

**Comment by dani3l3** [comment]
So I think it's not a hybridauth issue as much as a FB api issue, after some debugging last night and this morning... but I am not sure it's related to our account/app. I'll keep investigating and let you know if I figure it out :-)

**Comment by dani3l3** [comment]
I figured it out: for some reason, fb stopped exposing the email field for my and my other colleague who's also an admin of the app. Regular users are using it just fine. Absurd. Sort of wasted 24 hrs but this prompted me to add a feature on my system so we now know/track how many users are logging in with a certain provider or another, some information we were previously blind about, so that's good. You library works perfectly fine. Thanks 🙏
