### ISSUE TITLE
new release

### ISSUE THREAD

**Issue by adamjimenez** [hybridauth/hybridauth#1376]
I need the [phpseclib fix](https://github.com/hybridauth/hybridauth/commit/502ad72dcebeed502d8973366b3a82008dba0795) - any chance of a new release?

**Comment by padaliyajay** [comment]
I also need it. my apple login also stopped working so i have to keep it disabled for now. and waiting for new release

**Comment by ApacheEx** [comment]
it's released now as v3.10.0

thanks for pushing.
