### ISSUE TITLE
HybridAuth stores previous social account login even after logging out of social account

### ISSUE THREAD

**Issue by ABDELMOUMEN-MUSTAFA** [hybridauth/hybridauth#1384]
When I logout the user if he decides to connect again it automatically connect him to the previous account, what about if he decides to login with another account, if I clear the cookies manually it works, is there any method in hybridauth package can do that ?

**Comment by ApacheEx** [comment]
this has nothing to do with hybridauth. When user wants to logout - you should redirect user to logout from the social network, and later redirect back to your site where you logout from hybridauth. This is the only way to handle multiple accounts without issues.

**Comment by ABDELMOUMEN-MUSTAFA** [comment]
Ok, Do you mean $adapter->disconnect() ?

**Comment by RahulVerma989** [comment]
You to logout the user from your website and allow him to be able to choose another account the next time, can use getConnectedAdapters() method to get all the connected adapters of hybridauth and use foreach loop and call disconnect() method on each of the adapters. This way on logout all the connected adapters will get disconnected and user can choose another account on next login.
