### ISSUE TITLE
Linkedin now offers OpenID

### ISSUE THREAD

**Issue by champsupertramp** [hybridauth/hybridauth#1385]
Hi @ApacheEx 

Just letting you know that Linkedin now offers OpenID:
https://learn.microsoft.com/en-us/linkedin/consumer/integrations/self-serve/sign-in-with-linkedin-v2?context=linkedin%2Fconsumer%2Fcontext

**Comment by ApacheEx** [comment]
Thanks for update. Your PR got merged and will be released soon as 3.11

**Comment by richardczeiger** [comment]
Hi all, I just downloaded 3.11 and the LinkedIn scope still uses "r_liteprofile r_emailaddress". As far as I can see LinkedIn deprecated their old "Sign In with LinkedIn" and replaced it with "Sign In with LinkedIn using OpenID Connect". So now we can't use the old one. Can you please update the Linkin Provider script to accommodate the new Linkedin 'product'
![Uploading List-Products-App-detail-Developers-LinkedIn.png…]()

**Comment by richardczeiger** [comment]
![Uploading List-Products-App-detail-Developers-LinkedIn.png…]()
