### ISSUE TITLE
Twitter authorization not working

### ISSUE THREAD

**Issue by Morbids** [hybridauth/hybridauth#1387]
Here is the error when logging in via Twitter

HybridAuth Error: Signed API request to https://api.twitter.com/oauth/request_token has returned an error. HTTP error 401. Raw Provider API response: {"errors":[{"code":32,"message":"Could not authenticate you."}]}.

**Comment by Morbids** [comment]
Close

**Comment by reinos** [comment]
What was your issue @Morbids ?

**Comment by Morbids** [comment]
reconfigured Twitter app
