### ISSUE TITLE
Is hybridauth abandoned?

### ISSUE THREAD

**Issue by jamminjames** [hybridauth/hybridauth#1397]
## Bug, feature or question?

Is hybridauth abandoned? Any updates planned? Is there a better alternative? It's been working great until recent Facebook issues, where it returns a blank popup or an error notice.

**Comment by ApacheEx** [comment]
> Is hybridauth abandoned?

Nope, it still accepts any kind of contribution from the community, but as you can see there is no much activity here.

> Any updates planned?

There are no plans or roadmap for now.

> Is there a better alternative?

Probably, it depends on exactly what you need.

**Comment by jamminjames** [comment]
Thanks, @ApacheEx. Turns out, due to changes at FB, I just needed to create a new login app from scratch. It's working again.
