### ISSUE TITLE
LinkedIn doesn't work with new OpenID requirement

### ISSUE THREAD

**Issue by richardczeiger** [hybridauth/hybridauth#1408]
Hi all, I just downloaded 3.11 and the LinkedIn scope still uses "r_liteprofile r_emailaddress". As far as I can see LinkedIn deprecated their old "Sign In with LinkedIn" and replaced it with "Sign In with LinkedIn using OpenID Connect". So now we can't use the old one at all. Can you please update the Linkin Provider script to accommodate the new Linkedin 'product'.

![350242301-ab1e39fa-e68b-4f07-897a-df4f00039f0e](https://github.com/user-attachments/assets/8d3cd45d-c5bd-4d32-a40d-ad71c41e1b64)

**Comment by shohag121** [comment]
Recently, I faced the same issue and found that we need to use  `LinkedInOpenID` as a provider instead of `LinkedIn`.

**Comment by richardczeiger** [comment]
Thanks @shohag121 but when I do that it comes back with "Unknown Provider"... @ApacheEx do you think you could look at this issue? :)

**Comment by richardczeiger** [comment]
That solved it @shohag121 Thanks   :)

**Comment by richardczeiger** [comment]
That solved it @shohag121 Thanks   :)
