### ISSUE TITLE
coding standards

### ISSUE THREAD

**Issue by eurich** [hybridauth/hybridauth#169]
Sorry for opening such a generic issue but I think it's important to define some **coding standards** for Hypbridauth..

1) line endings (some files use crlf while others use lf).. that definetely needs to be standardized, a .gitattribute file should help (example with forced lf).
`* text eol=lf`
 `*.php text`

2) whitespaces..sometimes it's `function( $var1,$var2,$var3 )`, sometimes `function($var, $var)`.. this is also important for ternary operators  and concatenation of strings / vars `($a.$b vs $a . $b)`

3) doc blocs: I'd personally favour api-gen compatible docs

4) single quotes vs. double quotes. Just check the Google provider, there are various variants.

5) coding syntax in general (K&R vs. BSD KNF vs. Allman)

**Comment by AdwinTrave** [comment]
Closing for duplicity with #34
