### ISSUE TITLE
Add an option to set facebook login window type

### ISSUE THREAD

**Issue by beefs** [hybridauth/hybridauth#17]
Hi, 

Just wondering if you could add an option for facebook to set 'display' => 'popup'.

**Comment by Slayer911** [comment]
Few months after commit with this future, property "display" will be removed from class 
"hybridauth/Hybrid/Providers/Facebook.php"
Commit with removed property "display", and added static "display=pages" in function
`function loginBegin(){`
[https://github.com/hybridauth/hybridauth/commit/87b6e19ffc75992c91a2f1e93ca2628cb176d627](url)
Now this file do not have any "display" url params 
[https://github.com/hybridauth/hybridauth/blob/master/src/Provider/Facebook.php](url)
How now i can add this param to login url ?
