### ISSUE TITLE
Hybridauth speed problem

### ISSUE THREAD

**Issue by DerCommodore** [hybridauth/hybridauth#172]
Hey guys. I am using hybridauth (last stable version) extensively for a big project.
I like it so far, BUT I have massive speed problems when logging in. It takes about 20s for a login procedure (Amazon EC2 hosted) with Facebook.

How can I speed things up?
Any tips / tricks?

**Comment by mbardelmeijer** [comment]
Any news on this? Also have speed problems with the getAdapter function for Facebook. Is HybridAuth also using the V2.0 API?

**Comment by madikarizma** [comment]
@mbardelmeijer I moved to the latest PHP SDK for Facebook, which is now at v4 (link below). This increased the my connection speed with Facebook dramatically, once set up properly. I am still using HybridAuth for Twitter and I have no reason to change that.

I am in the middle of a launch, but I will try to share my code soon, if it would be helpful.

https://github.com/facebook/facebook-php-sdk-v4

**Comment by mbardelmeijer** [comment]
That would be great! If i understand it correctly, you are not using HybridAuth for Facebook API call's anymore, but the Facebook PHP SDK? Of did you implement the V4 in HybridAuth?

**Comment by madikarizma** [comment]
@mbardelmeijer Correct. Basically, my app login code is utilizing each library depending on the user's preferred login provider. When it's Twitter, I execute using the HybridAuth methods and Facebook PHP SDK when it's Facebook.
