### ISSUE TITLE
Can not login with Windows Live

### ISSUE THREAD

**Issue by tanviet** [hybridauth/hybridauth#173]
I am working on a simple PHP site and trying to integrate social login in it. So I used Hybridauth library. To login via Windows Live account, I created a new app at https://account.live.com/developers/applications/create. 

In document page (http://hybridauth.sourceforge.net/userguide/IDProvider_info_Live.html), I saw that Callback URL is http://mywebsite.com/path_to_hybridauth/?hauth.done=Live but I could not enter it into Redirect URL field because Live does not accept query string in its redirect URL. So I entered full domain name such as http://mywebsite.com 

Here is my config.php

<pre>
array(
    "base_url" => "http://" . $_SERVER['HTTP_HOST'] . $this->base . "/hybridauth/", 

    "providers" => array ( 

        // windows live
        "Live" => array ( 
            "enabled" => false,
            "keys"    => array ( "id" => "xxxxxxxxx", "secret" => "xxxxxxxxx" ) 
        ), 
    ),

    "debug_mode" => false,

    "debug_file" => ""
);
</pre>

When I click the login link like this

<pre>
<a href="loginwith/live" class="zocial live">Login with Windows Live</a>
</pre>

I am directed to the link

https://login.live.com/err.srf?lc=1066#error=invalid_request&error_description=The%20provided%20value%20for%20the%20input%20parameter%20'redirect_uri'%20is%20not%20valid.%20The%20expected%20value%20is%20'https://login.live.com/oauth20_desktop.srf'%20or%20a%20URL%20which%20matches%20the%20redirect%20URI%20registered%20for%20this%20client%20application.

with error message "We're unable to complete your request Microsoft account is experiencing technical problems. Please try again later."

I tried to change Redirect URL but the result was still same. Can someone fix this issue?

Thanks a lot in advance!

**Comment by myrage18** [comment]
Im facing the same issue... It suddenly stopped working... used to work with redirect url: https://domain.com/hybridauth

Any solution to this problem ?
https://login.live.com/err.srf?lc=1033#error=invalid_request&error_description=The provided value for the input parameter 'redirect_uri' is not valid. The expected value is 'https://login.live.com/oauth20_desktop.srf' or a URL which matches the redirect URI registered for this client application.

**Comment by PareshRadadiya** [comment]
@AdwinTrave  I'm getting same as @myrage18

**Comment by galadhremmin** [comment]
I am getting the same as @AdwinTrave and @myrage18.

**Comment by mattmemmesheimer** [comment]
I'm having this issue as well.  Microsoft does not allow query strings in the redirect URI so I cannot get it to accept https://mywebsite.com/path_to_hybridauth/?hauth.done=Live

**Comment by aWuttig** [comment]
Same Problem here :-1:
