### ISSUE TITLE
authenticate() method fails after app is deauthorized by user

### ISSUE THREAD

**Issue by carr0lls** [hybridauth/hybridauth#185]
When a user signs up for your app the first time, everything authenticates fine. However, when a user deauthorizes your app from the social network (tested with Facebook and Foursquare), you will receive the following error if the user tries to authenticate again:

"User profile request failed! Facebook returned an error: OAuthException: An active access token must be used to query information about the current user."

UPDATE: From digging into the source, I see that what happens is that the login status is stored inside a local session so there isn't really a way to clear that even if we use the social provider's deauth URI to ping the app. The user would have to manually delete the session. The only way I can think of to fix this issue is if we don't store the login status via local sessions, but into our databases which is out of the scope of hybridauth. I guess this might not be an issue that can be resolved easily.

**Comment by j05u3** [comment]
@carr0lls , @hybridauth   I did the same but then it fell into a redirection loop , after that I realized the problem was a cookie: fbsr_[appID] which had to be deleted in order to work normally, so this worked for me:
```php
    if( $e->getCode() == 6){
        if( trim(strtolower($provider)) == "facebook" && isset($_COOKIE["fbsr_"+$fbAppID]) ){						
						setcookie("fbsr_".$fbAppID,  null, time()-3600, '/');
						//cleaning facebook cookie which caused the exception 6 in hybridauth	
						displayLoadingViewAndAuthenticate();//redirects with javascript to authentication
						die();
					}
				}
```

**Comment by alidl923** [comment]
Still facing the same issue....
