### ISSUE TITLE
Authentication failed! Facebook returned an invalid user id

### ISSUE THREAD

**Issue by mbasfour** [hybridauth/hybridauth#188]
I'm using this library to create facebook signup link for my website it worked fine on my localhost but when i moved it to the server it didn't work and it gave me this error message "Authentication failed! Facebook returned an invalid user id" i tried a lot of solutions from this links: 
- http://stackoverflow.com/questions/14068425/hybridauth-php-facebook-returned-an-invalid-user-id
- http://stackoverflow.com/questions/20777100/hybridauth-facebook-returned-an-invalid-user-id
- http://stackoverflow.com/questions/17515618/laravel4-hybridauth-facebook-authentication-failed-facebook-returned-an-invalid

but nothing seem to fix this problem so can you help me fix it?

**Comment by Dreamvention** [comment]
Hi I have the same error! it does not work with https, no matter what I put in facebook app settings - it only works with http.

has anyone found a solution yet?

**Comment by hardikoc** [comment]
I have tried all the possible options i see above and i found online, updating SDK version from 3.2.1 to 3.2.2, adding config options, setting trustforwarded in config, updating the proxi section on base facebook page etc but after i have setup SSL on my server, only facebook signup doesn't work, the twitter, linked in, instagram etc works just fine. Can you please help?

**Comment by tartakxg** [comment]
Yes, the same problem - https site:
[HybridAuth] Authentication failed! Facebook returned an invalid user id.
fix, please

**Comment by githubitsme** [comment]
Same Problem For me too

**Comment by JPustkuchen** [comment]
I'm also having the same issue. G+ works great. Facebook with https doesn't work... :(

**Comment by g4b1nagy** [comment]
Same problem here...

**Comment by JPustkuchen** [comment]
We've had 3 possible problems causing this. Perhaps that will help you:
1. The website was password protected (htpasswd) due to development / tests. We had to remove that
2. There were language specific redirects perhaps causing the FB call to be redirected
3. We had to enter the whole URL to the HybridAuth Path for facebook (not just the base URL of the website). For the HybridAuth Drupal module we've described it here. For other implementations the URL might be different: https://www.drupal.org/node/2684015

Finally it's working now...

**Comment by g4b1nagy** [comment]
I've managed to fix it on my end as well. The production site had been recently moved to https so I needed to update the `base_url` in the config file to use https as well => http://hybridauth.sourceforge.net/userguide/Configuration.html

**Comment by cfv1000** [comment]
In base_facebook.php do following

```
  public static $CURL_OPTS = array(
    CURLOPT_CONNECTTIMEOUT => 50,
    CURLOPT_RETURNTRANSFER => true,
    CURLOPT_TIMEOUT        => 60,
    CURLOPT_USERAGENT      => 'facebook-php-3.2',
    CURLOPT_SSL_VERIFYPEER => false,
    CURLOPT_SSL_VERIFYHOST => false,
  );

  protected $trustForwarded = true;
  protected $allowSignedRequest = false;

```

Fixed it for me.

Thanks

**Comment by dugwood** [comment]
You should set the parameter in the config file, and not change the base_facebook.php:
`array('enabled' => true, 'keys' => array('id' => YOUR_ID, 'secret' => YOUR_SECRET), 'scope' => 'email', 'trustForwarded' => true)`

**Comment by syedbar** [comment]
@cfv1000  not working for me..

 it seems my hosting plan is having issue and my ip is having some issue.

**Comment by NZX-DeSiGN** [comment]
Same problem, SSL on my server. Can somebody help us ? Please

**Comment by MohannadNaj** [comment]
Maybe this comment help someone else there:

My issue wasn't SSL or curl, wasn't hybridauth, wasn't base_url or redirect_url, wasn't god. it was the `Server IP Whitelist` in facebook app `advanced` settings. I just had to put my public IP there after it was changed :)

**Comment by samantanabin02** [comment]
got exception error Authentication failed! Facebook returned an invalid user id...in hybrid auth social plugin in cakephp 2.8.6 
Google plus works fine...but facebook not working...please help

**Comment by ApacheEx** [comment]
@samantanabin02 thid issue is closed, so nobody will help. Pls create a new one with all needed details
