### ISSUE TITLE
Yahoo problem

### ISSUE THREAD

**Issue by alex7tula** [hybridauth/hybridauth#208]
Hi

I replace "Id" to "key" and use it as
"keys" => array ( "key" => "Consumer Key", "secret" => "Consumer Secret" )
Add to app on Yahoo "Social Directory (read-only)" and verify my domain.

Authorizations starts (I see "login" page and "Authorizing access" page), but on next page (/examples/social_hub/profile.php?provider=Yahoo) I see the error:

User id request failed! Yahoo returned an invalid response.

Trace

#0 Hybrid/Providers/Yahoo.php(37): Hybrid_Providers_Yahoo->getCurrentUserId()
#1 Hybrid/Provider_Adapter.php(191): Hybrid_Providers_Yahoo->getUserProfile()
#2 examples/social_hub/profile.php(25): Hybrid_Provider_Adapter->__call('getUserProfile', Array)
#3 examples/social_hub/profile.php(25): Hybrid_Provider_Adapter->getUserProfile()
#4 {main}

How to run Yahoo auth? Your sample page, generate same error http:///opensource/hybridauth/social_hub/login.php

**Comment by AdwinTrave** [comment]
Closing due to examples removal in 2.4. New examples should come in 2.5
