### ISSUE TITLE
Logout doesn't really logout

### ISSUE THREAD

**Issue by roydekleijn** [hybridauth/hybridauth#220]
Given the following scenario.
1. user logs in with google.
2. user logs out
3. user want to log in again. This time the username/password fields are not show, but the user automatically is logged in

this is how my log out method looks like:
$adapter -> logout();
$hybridauth -> logoutAllProviders();

What is wrong here? or is this expected behaviour ? 

Question is about relogging using the same provider.

**Comment by bahman2216** [comment]
I know issue closed, But it is possible to revoke token when user logout?

**Comment by Taapo** [comment]
@bahman2216 -- I have the same question: **how to revoke/invalidate the access token from hybridauth**? (You can issue a "delete" request against "/me/permissions/" via the Facebook SDK) Or is this outside the scope of HybridAuth?

**Comment by engharb** [comment]
Hello,
I have tried different ways to logout from Twitter but it does not work. I want to logout completely and then reloggin with username and password.

Could someone help me.

regards,
