### ISSUE TITLE
Github: getUserProfile() does not contain email address

### ISSUE THREAD

**Issue by vbezruchkin** [hybridauth/hybridauth#227]
Github: getUserProfile() does not contain email address, though it might be mandatory for some actions. It would be great to have it among the other user details.

**Comment by jollysean** [comment]
Hi,

Has this solved the issue. I still do not get email.

**Comment by vbezruchkin** [comment]
Hey, this is what we have in our Github Provider configuration:
```
	// default permissions  
	// (no scope) => public read-only access (includes public user profile info, public repo info, and gists).
	public $scope = "user:email";
```

Working fine for us. You can test this on http://www.subrion.org/
