### ISSUE TITLE
Undefined property $error for OAuth2 provider (Instagram)

### ISSUE THREAD

**Issue by hellopablo** [hybridauth/hybridauth#253]
When attempting to authenticate against Instagram I'm getting an error which results in a fatal. The response in this particular situation is (ignore the fact it's erroring, I know why):

```
stdClass Object
(
    [code] => 400
    [error_type] => OAuthException
    [error_message] => You must provide a redirect_uri
)
```

which results in the following undefined error:

```
Notice: Undefined property: stdClass::$error in /**...**/vendor/hybridauth/hybridauth/hybridauth/Hybrid/thirdparty/OAuth/OAuth2Client.php on line 83
```

Line 83 of OAuth2Client is looking for an `error` property, not finding it and then falling over with a `headers already sent` fatal error.

Who's a fault? Is Instagram breaking standards? Or should HybridAuth be looking for `error_message`. what's the best way to address this?

I guess, ideally, the provider should be able to define what the error key looks like.

**Comment by alexanderzatko** [comment]
I still see this problem in v. 2.11, albeit with different provider.
