### ISSUE TITLE
Google timeout

### ISSUE THREAD

**Issue by noh4ck** [hybridauth/hybridauth#286]
I get this error when the php session is still running while the google "token"? has timed out.
(I don't know how to explain it better). If I delete the "PHPSESSID" cookie the error disappears and log in works as normal again. 

Hybridauth version: 2.1.1

```
Fatal error: Uncaught exception 'Exception' with message 'User profile request failed! 
Google returned an invalid response.' in /srv/http/eporten/handles/api/hybridauth/Hybrid/Providers/Google.php:83
Stack trace: #0 /srv/http/eporten/handles/api/hybridauth/Hybrid/Provider_Adapter.php(200):
Hybrid_Providers_Google->getUserProfile() #1 /srv/http/eporten/handles/api/account.php(82):
Hybrid_Provider_Adapter->__call('getUserProfile', Array) #2
/srv/http/eporten/handles/api/account.php(82): Hybrid_Provider_Adapter->getUserProfile() #3
/srv/http/eporten/includes/menu.php(11): Account->validUser() #4 /srv/http/eporten/index.php(8):
include('/srv/http/eport...') #5 {main} thrown in
/srv/http/eporten/handles/api/hybridauth/Hybrid/Providers/Google.php on line 83
```

**Comment by mohit-varshney** [comment]
Just enable Google +APi from console.....
then it's working well

**Comment by c6burns** [comment]
@mohit-varshney no that is incorrect, this is not about having G+ API enabled or disabled. The problem wouldn't be intermittent or solvable as described if that is correct.

This problem still exists in the latest version
