### ISSUE TITLE
How to re-request revoked permission?

### ISSUE THREAD

**Issue by vzani** [hybridauth/hybridauth#287]
Hello

I´m testing only Facebook behavior now.
I want the email to be a required permission that the user should accept on my App. When the user revokes the email from authentication, the Facebook dialog never show up again when the user try to login/registrate,

I checked Facebook Api and there´s a rerequest authtype to do that (ask the user the permissions again)

https://developers.facebook.com/docs/facebook-login/login-flow-for-web/v2.1#re-asking-declined-permissions
FB.login(
  function(response) {
    console.log(response);
  },
  {
    scope: 'user_likes',
    auth_type: 'rerequest'
  }
);

How to do that with Hybridauth?

Thanks

**Comment by hunters14473** [comment]
Hi,
same issue here... Tried both force and auth_type as rerequest but it is not wiorking as for sabaohai .
Any news?
Thank you
Bye
Marcello
