### ISSUE TITLE
Hybrid Auth - Moving sessions to database

### ISSUE THREAD

**Issue by rohanabraham** [hybridauth/hybridauth#290]
Hybrid Auth out of the box uses PHP sessions on File System. Our sessions are in the database.

We created our own session handling mechanism and registered it with set_session_save_handler. The issue we have is that the session data only contains the following:

HA::CONFIG|a:2:{s:14:"php_session_id";s:34:"s:26:"u8asahas7asyasq7shqyshrryfh";";s:7:"version";s:12:"s:5:"2.1.2";";}

It is missing other important data causing the login mechanism to crash with this error message:
Endpoint: Config storage not found when trying to init Hyrid_Auth.

**Comment by redorff** [comment]
We store session in database too.
The workaround we found is to force a "session write" directive into hybridauth before end of the php script.
In file *hybridauth/Auth.php*, on the blank line 368, you just need to write just before `die()`:
`session_write_close();`
Everything works fine for us with this! :)

**Comment by guyzeug** [comment]
Well done :) And thanks for the trick! As I couldn't get it to work I finally chose to use [redis] (http://redis.io/)

**Comment by Eclat-Engg** [comment]
@guyzeug Hey hi , Just had a question , have you successfully implemented Hybridauth with Redis (being used for saving sessions). We have implemented Hybrid Auth on our Drupal based site . We are facing an issue , the issue we faced is that hybrid auth is not able to get the session values from Redis . If we implement it without Redis , all the social logins work fine for us . We debugged it , and found that when used with Redis the hybrid auth library for some reason is not able to fetch the session values. It would be great if you could just guide us , how you implemented it with redis.

**Comment by guyzeug** [comment]
@Eclat-Engg Sorry it worked for me straight away (but we're using the yii framework, which does some magic behind the scenes sometimes). Changing where the session was stored was transparent from our code perspective.
Good luck!

**Comment by chamsmarena** [comment]
hello worked for me with custom php script
attached the mysql session handler modified from _(https://github.com/zpweber/MySQLSessionHandler/blob/master/MySQLSessionHandler.php)_
[wsession.txt](https://github.com/hybridauth/hybridauth/files/3044151/wsession.txt)

make hybridauth use mysql session handler
modify 3 files 
hybridauth\Hybrid\Storage.php 
hybridauth\Hybrid\Auth.php
hybridauth\Hybrid\Endpoint.php

add this line to require the mysql handler at the top three files
require_once($_SERVER['DOCUMENT_ROOT'].'/weeklywca/scripts/wsession.php');

and done
