### ISSUE TITLE
Call back url with "." or "_" ?

### ISSUE THREAD

**Issue by wlf10** [hybridauth/hybridauth#329]
Hi,
In this line a call back url is generated where 'hauth.done' is added
https://github.com/hybridauth/hybridauth/blob/master/hybridauth/Hybrid/Provider_Adapter.php#L162

Then 'hauth.done' is replaced with 'hauth_done' and it is asserted as strange behavior that the provider returns 'hauth.done' with a point.
https://github.com/hybridauth/hybridauth/blob/master/hybridauth/Hybrid/Endpoint.php#L27-L38

In the library code 'hauth_done' is used and for call back 'hauth.done' is used. Why is it so? Maybe we should correct a call back link to use 'hauth_done'?

Thanks.

**Comment by miled** [comment]
the strange behavior we were speaking about is that _some_ providers will include `?` twice in the query string which may result on something like this `/index.php?hauth.done={provider}?{args}`

as to whether use . or _ is irrelevant http://tools.ietf.org/html/rfc3986#section-2.3
