### ISSUE TITLE
LinkedIn login error

### ISSUE THREAD

**Issue by vbnvicky** [hybridauth/hybridauth#333]
When trying to login with LinkedIn it shows message.
" User has cancelled the authentication or the provider refused the connection. "

Please suggest how to resolve this.

**Comment by timersys** [comment]
Try adding more scopes to the app you created in linkedin   r_network, r_fullprofile, r_emailaddress, w_messages (if needed)
The remove the app from your authorized account and start authorization again

**Comment by karthikeyan-manivasagam** [comment]
Try by these steps http://monkpal.com/exception-serialization-closure-not-allowed-hybridauth-linkedin-phalcon
