### ISSUE TITLE
Twitter provider - Authentication failed! Twitter returned an error. 401 Unauthorized.

### ISSUE THREAD

**Issue by prostoroman** [hybridauth/hybridauth#335]
Hello, just installed this great library.
All providers work well except twitter.

First I got error message:
Undefined index: oauth_token

Then I fxed OAuth1Client.php add to  line 85:
if(empty($token['oauth_token'])) return false;

Then I always getting message:
Authentication failed. The user has canceled the authentication or the provider refused the connection. And:
Authentication failed! Twitter returned an error. 401 Unauthorized.

Double checked all keys and app config values on twitter but nothing :(.

**Comment by AlbertoMrFz** [comment]
Hi, I have similar problemes, but i can't resolve them. I need your help. This is my config file:

"Twitter" => array(
					"enabled" => true,
					"keys" => array("key" => "KEY", "secret" => "SECRET"),
					"includeEmail" => false
				),
