### ISSUE TITLE
You cannot access this page directly

### ISSUE THREAD

**Issue by Andradez** [hybridauth/hybridauth#336]
Hello, i am trying to access Hybridauth with curl but it gives the error:
"You cannot access this page directly".
I make a Ajax request to a "php" page on my site and that page connects with  hybridauth via curl.
when i access the page directly, it works well but when i try to access it with Ajax, the curl response in my php page shows: "You cannot access this page directly".
I believe it has something to do with : $_SESSION["HA::STORE"] that is set  internally inside hybridauth.
Does  anyone know how to allow "ajax and then curl" access to hybridauth?

**Comment by memare-ahvaz** [comment]
hi
plz help me by fix You cannot access this page directly. errore
my script phpfox
http://www.homdorong.ir/include/library/hybridauth/?hauth.start=Yahoo&hauth.time=1424268283

**Comment by ankitce** [comment]
Try after adding `@session_start();` statement at the top of your files.

**Comment by cirofeitosa** [comment]
Same problem here. 
Per day, 25 users have problem in login via Facebook or Google using Hybridauth.
I've tried many ways to fix (including this previous), but not successful.

**Comment by Mexiswow** [comment]
I had a same problem and this safe my life :)

Go to Storage.php file in your Hybrid extension directory and add following line on top in the __construct() method

session_set_cookie_params(0, '/', '.yourdomain.com');

**Comment by manifsp** [comment]
Hi to All,

We have implemented the hybridauth in our cakephp 3.0 web app. As usual we created FB App and configured with our site. Its working well on local and development environment. But we faced issue on our Production environment. We stuck with the below URL, application doesn't redirect to FB

https://www.mydomin.com/home/socialch?hauth.start=Facebook&hauth.time=1470129476

When the user login with facebook getting error like this..

http://i.imgur.com/g2uuKyv.png

Please guide us to resolved this issue. Actually more than 50-60 usres login with FB in our site. But still now its not working on PROD environment. Thanks in advance..!

**Comment by cirofeitosa** [comment]
Hey @Mexiswow 

Thanks for reply. 

I've tried your idea, but not works. Continues with the fatal error:

> 
Uncaught Hybrid_Exception: You cannot access this page directly. 
in /var/www/html/_libs/hybridauth/Hybrid/Endpoint.php:211
>
Stack trace:
#0 /var/www/html/_libs/hybridauth/Hybrid/Endpoint.php(117): Hybrid_Endpoint->authInit()
#1 /var/www/html/_libs/hybridauth/Hybrid/Endpoint.php(51): Hybrid_Endpoint->processAuthStart()
#2 /var/www/html/_libs/hybridauth/Hybrid/Endpoint.php(72): Hybrid_Endpoint->__construct(Array)
#3 /var/www/html/_auth.php(25): require_once('/var/www/html/...')
#4 {main}
>
Next Hybrid_Exception: Endpoint: Error while trying to init Hybrid_Auth: You cannot access this page directly. in /var/www/html/_libs/hybridauth/Hybrid/Endpoint.php:217
>
Stack trace:
#0 /var/www/html/_libs/hybridauth/Hybrid/Endpoint.php(117): Hybrid_Endpoint->authInit()
#1 /var/www/html/_libs/hybridauth/Hybrid/Endpoint.php(51): Hybrid_End in /var/www/html/_libs/hybridauth/Hybrid/Endpoint.php on line 217


This is very strange bug, because happens sometimes (like 10% per users in a day)

**Comment by Mexiswow** [comment]
Hey @cirofeitosa 
I know this bug and i had a same problem.
show me Storage.php with included fix

**Comment by cirofeitosa** [comment]
@Mexiswow 

Here the Storage.php file:

```
<?php

/**
 * HybridAuth
 * http://hybridauth.sourceforge.net | http://github.com/hybridauth/hybridauth
 * (c) 2009-2015, HybridAuth authors | http://hybridauth.sourceforge.net/licenses.html 
 */
require_once realpath(dirname(__FILE__)) . "/StorageInterface.php";

/**
 * HybridAuth storage manager
 */
class Hybrid_Storage implements Hybrid_Storage_Interface {

	/**
	 * Constructor
	 */
	function __construct() {
		session_set_cookie_params(0, '/', '.mydomain.com');

		if (!session_id()) {
			if (!session_start()) {
				throw new Exception("Hybridauth requires the use of 'session_start()' at the start of your script, which appears to be disabled.", 1);
			}
		}

		$this->config("php_session_id", session_id());
		$this->config("version", Hybrid_Auth::$version);
	}

	/**
	 * Saves a value in the config storage, or returns config if value is null
	 *
	 * @param string $key   Config name
	 * @param string $value Config value
	 * @return array|null
	 */
	public function config($key, $value = null) {
		$key = strtolower($key);

		if ($value) {
			$_SESSION["HA::CONFIG"][$key] = serialize($value);
		} elseif (isset($_SESSION["HA::CONFIG"][$key])) {
			return unserialize($_SESSION["HA::CONFIG"][$key]);
		}
		
		return null;
	}

	/**
	 * Returns value from session storage
	 *
	 * @param string $key Key
	 * @return string|null
	 */
	public function get($key) {
		$key = strtolower($key);

		if (isset($_SESSION["HA::STORE"], $_SESSION["HA::STORE"][$key])) {
			return unserialize($_SESSION["HA::STORE"][$key]);
		}

		return null;
	}

	/**
	 * Saves a key value pair to the session storage
	 *
	 * @param string $key   Key
	 * @param string $value Value
	 * @return void
	 */
	public function set($key, $value) {
		$key = strtolower($key);
		$_SESSION["HA::STORE"][$key] = serialize($value);
	}

	/**
	 * Clear session storage
	 * @return void
	 */
	function clear() {
		$_SESSION["HA::STORE"] = array();
	}

	/**
	 * Delete a specific key from session storage
	 *
	 * @param string $key Key
	 * @return void
	 */
	function delete($key) {
		$key = strtolower($key);

		if (isset($_SESSION["HA::STORE"], $_SESSION["HA::STORE"][$key])) {
			$f = $_SESSION['HA::STORE'];
			unset($f[$key]);
			$_SESSION["HA::STORE"] = $f;
		}
	}

	/**
	 * Delete all keys recursively from session storage
	 *
	 * @param string $key Key
	 * @retun void
	 */
	function deleteMatch($key) {
		$key = strtolower($key);

		if (isset($_SESSION["HA::STORE"]) && count($_SESSION["HA::STORE"])) {
			$f = $_SESSION['HA::STORE'];
			foreach ($f as $k => $v) {
				if (strstr($k, $key)) {
					unset($f[$k]);
				}
			}
			$_SESSION["HA::STORE"] = $f;
		}
	}

	/**
	 * Returns session storage as a serialized string
	 * @return string|null
	 */
	function getSessionData() {
		if (isset($_SESSION["HA::STORE"])) {
			return serialize($_SESSION["HA::STORE"]);
		}
		return null;
	}

	/**
	 * Restores the session from serialized session data
	 * 
	 * @param string $sessiondata Serialized session data
	 * @return void
	 */
	function restoreSessionData($sessiondata = null) {
		$_SESSION["HA::STORE"] = unserialize($sessiondata);
	}

}
```

**Comment by manifsp** [comment]
I have been trying to figure out why the sessions weren't persistent. I have started the session on my controller. Its working for me...

`public function beforeFilter(Event $event) {
        parent::beforeFilter($event);              
        $this->Auth->allow(['index', 'socialLogin', 'socialch', 'contactFacilityAdmin', 'contactRentertoAdmin', 'contactus', 'indexnewsletter', 'newsletter', 'about']);                
           if($this->request->params['action'] == 'socialch'){         
                @session_id();
                @session_start();
                @session_name('CAKEPHP'); 
           }  
    }`
Issue fixed now... :)

**Comment by hepaestus** [comment]
I am getting the same error when trying to integrate into CMS Made Simple. I have tried all the fixes stated here but I am still having what I think is a SESSION issue. It looks like when the Endpoint tries to re-establish the Auth config and it fails to find it in the Session.  Any ideas on how to address this?
Thanks,
P.

**Comment by miguelpragier** [comment]
**Here I made two things at the same time, but I'm not sure which one solved. Check:**
- Changed THIS `if ( isset($_REQUEST['hauth_start']) || isset($_REQUEST['hauth_done'])  ) {` TO THIS `if ( isset($_REQUEST['hauth_start']) || isset($_REQUEST['hauth_done']) || isset($_REQUEST['hauth.start']) || isset($_REQUEST['hauth.done']) ) {`
- Changed THIS `ini_set('session.gc_probability', 1)`; TO THIS `ini_set('session.gc_probability', 0);`

And now it's working.
My beliefs:
- If it's about the garbage collector, it's not working as expected.
- If it's about the $_REQUEST checks, it's a difference between versions I'm using in my servers.

Please, share if some of these fixes worked for your environment.

**Comment by smil2k** [comment]
I think it is the first one:

$ fgrep "hauth.start" -R .                                                            
./includes/hybridauth/Hybrid/Provider_Adapter.php:                      $this->params["login_start"] = $HYBRID_AUTH_URL_BASE . ( strpos($HYBRID_AUTH_URL_BASE, '?') ? 
'&' : '?' ) . "hauth.start={$this->id}&hauth.time={$this->params["hauth_time"]}";                                                                                     
./includes/hybridauth/Hybrid/Endpoint.php:              // If we get a hauth.start  

.start is sent and _ is expected.

**Comment by ApacheEx** [comment]
this error depends on your environment (not on HA), possible reasons:

1) session is not configured.
2) wrong server configuration.
3) wrong apache2/nginx configuration.
4) extra redirection and so on.


I'm closing this issue because do not see what to fix.

**Comment by luigi37** [comment]
Hi, Seeing the same issue and it's likely linked to the server as it happened since a change from my provider... any suggestion on what needs to be checked on the server?

**Comment by agbarbosa** [comment]
@ApacheEx would you please help us who are using Wordpress in a CPanel environment of a shared hosting server? I am not so knowledgeable on the 4 reasons you have listed for this problem. Thanks in advance.

**Comment by agbarbosa** [comment]
FIXED IT! I found in my Config (config.php) file I have forgotten to finalize the "base_url" variable with the "?hauth.done=[provider]" parameter. For Wordpress users, the entire base_url should be something like:  https://yoursite.com/wordpress/wp-content/plugins/wordpress-social-login/hybridauth/?hauth.done=[provider of your choice]

**Comment by subhtak** [comment]
Hi @ApacheEx we are facing the same issue on nginx which is hosted on Kinsta. Can you provide a fix? Which nginx rule is required to fix this issue?

**Comment by nightw0lv** [comment]
> 
> 
> Hi @ApacheEx we are facing the same issue on nginx which is hosted on Kinsta. Can you provide a fix? Which nginx rule is required to fix this issue?

note mostly 1 and 4 steps, unless you need to follow redirects from curl and use cookies those steps is what you need to work on mostly, but the way you aproach to use hybrid auth is not how it was meant to or build to. consider rethinking your aproach.
