### ISSUE TITLE
RFC: Refactoring / 3.0 - PSR-0, Composer, and more...

### ISSUE THREAD

**Issue by EvanDotPro** [hybridauth/hybridauth#34]
I'd like to propose that a new branch be "officially" started, possibly as a beginning to a 3.0 release.

* Upgrade to PSR-0 and (possibly) namespaces -- I can understand the argument against making 5.3 a requirement (Edit: To carify, the extra adapters do not conform to PSR-0 and are astonishingly annoying to set up autoloading for properly in the context of other projects due to the hard-coded require_once statemnts in HybridAuth.)
* Implement some coding standards
* Remove all the static usage in favor of real OOP practices
* Add official composer/packagist support
* Make it overall more friendly for integration with projects and frameworks
* Unit tests

Yes, I could fork and just start working on it, but I'd prefer to get upstream support from the project and users so that it can hopefully be a more collaborative effort if there's sufficient interest.

Thoughts?

**Comment by localheinz** [comment]
Any news on this one? 

Seems long overdue!

**Comment by AdwinTrave** [comment]
v3 dev is currently PSR-4 compliant

**Comment by localheinz** [comment]
@AdwinTrave 

That would be [`3.0.0-Remake`](https://github.com/hybridauth/hybridauth/tree/3.0.0-Remake)?

**Comment by AdwinTrave** [comment]
Yes

**Comment by lorezyra** [comment]
Any plans to implement namespaces?

**Comment by nazar-pc** [comment]
As written before in this thread - already implemented in experimental 3.0-Remake branch

**Comment by lorezyra** [comment]
Cool. :+1:

**Comment by Soullivaneuh** [comment]
Follow PSR-1/2 practices could be also a good start.

See #459 as example.

**Comment by Soullivaneuh** [comment]
@EvanDotPro please see #461.

Feel free to comment it. :+1:

**Comment by wheelsandcogs** [comment]
Is 3.0 currently in a usable state? i.e. is it working with a few missing providers / small bugs or is it still under heavy dev / fairly broken?

I'm trying to make a decision on whether to go with 3.0 or 2.4 on a new project, so a rough idea of stability would really help, cheers.

**Comment by miled** [comment]
@wheelsandcogs 3.0 is still under heavy development and not suited for production. afaik, there's few braves people who already using it, but the decision is yours. 

For anyone interested to know, the exact status of project can be found in https://github.com/hybridauth/hybridauth/blob/3.0.0-Remake/TODO.md
