### ISSUE TITLE
[dropbox] Is anyone developing a Dropbox provider?

### ISSUE THREAD

**Issue by VladyslavKurmaz** [hybridauth/hybridauth#344]

**Comment by chrisgraham** [comment]
Does anyone know hat happened to the Dropbox provider? I can see it as an "additional provider" in the git history, but it seems to have disappeared with a newer version, and I can't see any references to this being purposeful. Perhaps this was a mistake?

**Comment by ApacheEx** [comment]
@chrisgraham, it's just not migrated yet to Hybridauth v3. You are welcome to prepare a PR for that or create a new request issue.

**Comment by chrisgraham** [comment]
Is there some kind of issue tracking what hasn't been migrated yet? If not, can there be?
