### ISSUE TITLE
Class 'Hybrid_Logger' not found / Oophs. Error!

### ISSUE THREAD

**Issue by haimat** [hybridauth/hybridauth#350]
After installing HybridAuth to my server and creating a hello world example page I call it as suggested in the documentation. However, after the browser was redirected to the `index.php` page of HybridAuth (where `Hybrid_Endpoint::process()` is being called), nothing happens.

It turns out the problem is that apparently the file `Logger.php` is not included correctly. This is the error message in the Apache logs:

```
Class 'Hybrid_Logger' not found in /var/www/lib/hybridauth/Hybrid/Endpoint.php on line 202
```

Any ideas how to fix this?

**Comment by Etdashou** [comment]
Man, what was your fix??
I have the exact same error...

**Comment by j05u3** [comment]
I had the exact same error, I discovered the session global variable wasn't saving the required variables and it was because I set the base_url to a different than the one from which I was testing. To be more specific: I was accesing with www.mywebsite.com and the base_url was set to just mywebsite.com.

**Comment by charlesmudy** [comment]
@haimat what is the solution you used? I'm getting the same error using Codeigniter. Unfortunately, @j05u3's suggestion is not a solution for me as I have done that already.

**Comment by onuraktas** [comment]
Same error, buy only for Chrome on osx

**Comment by onetarek** [comment]
I had same problem. 
Resolved by including Logger.php and Exception.php at top of other file in /hybridauth/index.php.
Idea came from @haimat 's comment
//My codes bellow.
require_once( "Hybrid/Logger.php" );
require_once( "Hybrid/Exception.php" );
require_once( "Hybrid/Auth.php" );
require_once( "Hybrid/Endpoint.php" );

**Comment by onetarek** [comment]
I thought my above code worked but I see that is not working , 
**Finally I found the main cause of the issue and solution,** 
The error happened when you call static method of Hybrid_Auth class directly with an object, 
For example you may call this **Hybrid_Auth::getAdapter( $provider );** in a function when the main class **Hybrid_Auth** have not been instantiate any where your script yet. 
Cause: The class **Hybrid_Auth** loads all require other class file in its **__consruct()** , and construct() fire only when you create an object of the class. Now when you are calling **Hybrid_Auth::getAdapter();** , this method calls Logger class that is not included yet in your script. 

**Probably you are trying following codes and getting error **
`		if( ! class_exists( 'Hybrid_Auth', false ) )
		{
require_once "/hybridauth/Hybrid/Auth.php";
		}	
		$adapter = Hybrid_Auth::getAdapter( $provider );`

Here you included this class file if not class exists , but this class is not instantiated. 
**So my solution is bellow:**

`		if( ! class_exists( 'Hybrid_Auth', false ) )
		{		
			require_once "/hybridauth/Hybrid/Auth.php";
			$config = get_my_hybrid_config($provider);
			$hybridauth = new Hybrid_Auth( $config );
		}	
		$adapter = Hybrid_Auth::getAdapter( $provider );`

**Comment by nazar-pc** [comment]
Guys, STOP RIGHT THERE! You're doing pathologically wrong things.
Simply implement [PSR-0 autoloader](https://github.com/hybridauth/hybridauth/blob/master/composer.json#L24), this is the only correct working solution.

**Comment by rafaelxavierborges** [comment]
The comment made by @j05u3 helped me a lot, problem solved, URL was 'wrong': with 'www' and without 'www'. I removed the 'www' and worked pretty well.
