### ISSUE TITLE
Drupal hybridauth Paypal login issue

### ISSUE THREAD

**Issue by mng4** [hybridauth/hybridauth#355]
My website is loggin error while trying to login with Paypal in my Drupal 7 website by using hybridauth.

Exception: Authentication failed! Paypal returned an error: invalid_scope in Hybrid_Auth::initialize() (line 153 of /abc/xyz/public_html/mydomain/sites/all/libraries/hybridauth/Hybrid/Auth.php).

I have created REST app in paypal and using the client id and secret. Could anyone tell me where I'm doing wrong?

I have entered return url as https://www.mysite/hybridauth/endpoint?hauth.done=Paypal for test and live. And unchecked Accept payments because I do not need it.

I'm not facing any issue with other providers except this one.

**Comment by Slurpee** [comment]
@mng4 I've been trying to get this to work in Drupal 7 without any luck. Is this still working for you? How did you know what the callback URL should be? In Paypal, which options are you selecting in "Login with PayPal", all of the options or just some? No matter which combination of settings I select, I still see same error "Relying Party Validation error: scope in the request does not match any of the registered clients. Please check the request.".

**Comment by mng4** [comment]
@Slurpee It's been a while I tested with paypal. Currently my site is facing downtime. Once it's up I will keep you posted.

**Comment by mng4** [comment]
@Slurpee Yes, its still working. At least it takes me to login page of PayPal. Did not sign in though.

**Comment by Slurpee** [comment]
@mng4 I've moved forward a bit, but still having issues. First issue is that I needed to add Paypal.php file into additional providers. Now I can click Paypal to authenticate anonymous or authenticated users in Drupal with a Paypal login screen.  I have a sandbox account at Paypal and the credentials work.  The problem now is being redirected back to Drupal to finish authentication.  Error message below.  Paypal seems to be working as expected, but nothing changes on the Drupal side. 

Example, an anonymous user clicks "login with Paypal", Paypal login screen appears, Paypal credentials work, then redirected back to proper Drupal URL, but user sees error" There was an error processing your request." and is not authenticated.  Drupal log message for this is below:

_USER	Anonymous (not verified)

LOCATION	http://example.com/hybridauth/window/Paypal?destination=node&destination_error=node

REFERRER	

MESSAGE	Exception: User profile request failed! Paypal returned an invalid response. in Hybrid_Providers_Paypal->getUserProfile() (line 106 of /home/pp/htdocs/sites/all/libraries/hybridauth/hybridauth/Hybrid/Providers/Paypal.php)._

**Comment by Slurpee** [comment]
@mng4 - I'm able to get a bit further by changing line 105 in htdocs/sites/all/libraries/hybridauth/hybridauth/Hybrid/Providers/Paypal.php to 

                if ( isset( $response->message ) ){

At this point, the auth tokens are being in stored in Drupal, but the workflow is a bit confused. Example, if you create a new account with Hybridauth/Paypal in Drupal, the account is created, but the user is not logged in.  It seems majority of this code is here, but it is not very well documented.

**Comment by mng4** [comment]
I just tested now, I'm facing the same error. I think we should reopen the bug report for developer to verify.

**Comment by mng4** [comment]
Re-Opening the issue for re-occurrence.

**Comment by ApacheEx** [comment]
will be fixed in #856
