### ISSUE TITLE
Autoloading: Requiring hybridauth/hybridauth does not give us autoloading

### ISSUE THREAD

**Issue by localheinz** [hybridauth/hybridauth#359]
When requiring a project that requires `hybridauth/hybridauth`, we don't get autoloading right out of the box.

```
Fatal error: Class 'Hybrid_Providers_GitHub' not found in /var/www/vendor/socalnick/scn-social-auth/src/ScnSocialAuth/HybridAuth/Provider/GitHub.php on line 7
```

Why is that so?

Can you fix that, please?

**Comment by AdwinTrave** [comment]
Not sure if the earlier commit fixes this, so please let me know.
