### ISSUE TITLE
Provider - EveOnline.com

### ISSUE THREAD

**Issue by soratidus999** [hybridauth/hybridauth#364]
Trying to implement OAuth SSO from eveonline.com (details on their oauth at https://developers.eveonline.com/resource/single-sign-on)

and i just cant wrap my head around it, HybridAuth looks like it can do it, my skills just don't allow me to put the two together

**Comment by ApacheEx** [comment]
if anybody really needs to have this provider - feel free to fill new issue. Currently, I don't see any reasons to add it to HA.
