### ISSUE TITLE
New extension to include HybridAuth in CMS Made Simple

### ISSUE THREAD

**Issue by haimat** [hybridauth/hybridauth#369]
We have created a wrapper for HybridAuth to use it in our web site, which is running CMS Made Simple. That wrapper/plugin is now open source, also here on github:

https://github.com/ImpetusGames/cms-oauth

Please have a look and let me know what you think. It would be nice if you include a link to our plugin from your web site (3rd party extensions). Thanks!

**Comment by AdwinTrave** [comment]
Will be added to the new version of the website. Preview bellow:

![screen shot 2015-01-03 at 19 46 47](https://cloud.githubusercontent.com/assets/1715235/5603349/577116da-9381-11e4-8852-b8fcbefaedc4.png)

**Comment by AdwinTrave** [comment]
Will be added to the new version of the website. Preview bellow:

![screen shot 2015-01-03 at 19 46 47](https://cloud.githubusercontent.com/assets/1715235/5603349/577116da-9381-11e4-8852-b8fcbefaedc4.png)

**Comment by haimat** [comment]
Great, thank you very much!
