### ISSUE TITLE
vkontakte email

### ISSUE THREAD

**Issue by nywuctuk** [hybridauth/hybridauth#373]
this:
Hybrid_Auth::storage()->set( "hauth_session.{$this->providerId}.user_email", $response->email );

change to:
Hybrid_Auth::storage()->set( "hauth_session.{$this->providerId}.user_email", $response->user_email );

**Comment by AdwinTrave** [comment]
Please provide a PR next time.

**Comment by nywuctuk** [comment]
Sure, its my 1st "PR" actually.
I have some issue (with HOAUTH (https://github.com/SleepWalker/hoauth) - hybridauth for Yii framework) When i fix this flaw, I 1 time could see email from Vkontakte. After delete acc from my site other connections didnt give me any email more. And i dont know is it real to get city from Vk? May be there is a bad method that use $scope? Facebook do all good for example.
Do you have some ideas dude?

**Comment by danaki** [comment]
nywuctuk please double check next time, the $response->email was correct
