### ISSUE TITLE
Pinterest provider?

### ISSUE THREAD

**Issue by AlexeyKosov** [hybridauth/hybridauth#378]
I can't find Pinterest provider in the sources.
Why it's missed?

**Comment by AdwinTrave** [comment]
Looks like nobody wrote it. Feel free to do so.

**Comment by marktamis** [comment]
Here is what I wrote - still needs some pagination code on the followers.

/**
 * Hybrid_Providers_Instagram (By Mark Tamis)
 */
class Hybrid_Providers_Pinterest extends Hybrid_Provider_Model_OAuth2
{
    // default permissions
    public $scope = "read_public,read_relationships";

    /**
     * IDp wrappers initializer
     */
    function initialize()
    {
        parent::initialize();

        // Provider api end-points
        // Gotcha: when declaring your Pinterest App redirect uri, include the hauth.done parameter
        // i.e. https://www.example.com/hybrid.php?hauth.done=Pinterest
        $this->api->api_base_url  = "https://api.pinterest.com/v1/";
        $this->api->authorize_url = "https://api.pinterest.com/oauth/";
        $this->api->token_url     = "https://api.pinterest.com/v1/oauth/token";
    }

    /**
     * load the user profile from the IDp api client
     *
     */
    function getUserProfile(){
        $data = $this->api->api("me/?fields=url,username,first_name,last_name,bio,image[medium]" );

        /*if ( $data->meta->code != 200 ){
            throw new Exception( "User profile request failed! {$this->providerId} returned an invalid response.", 6 );
        }*/
        $this->user->profile->identifier  = $data->data->id;
        $this->user->profile->firstName   = $data->data->first_name;
        $this->user->profile->lastName    = $data->data->last_name;
        $this->user->profile->displayName = $data->data->first_name.' '.$data->data->last_name;
        $this->user->profile->description = $data->data->bio;
        $this->user->profile->photoURL    = $data->data->image->medium ->url;

        $this->user->profile->webSiteURL  = $data->data->url;

        $this->user->profile->username    = $data->data->username;

        return $this->user->profile;
    }
    /**
     * https://developers.pinterest.com/docs/api/users/
     * {
    "data": [
    {
    "url": "https:\/\/www.pinterest.com\/ben\/",
    "first_name": "Ben",
    "last_name": "Silbermann",
    "id": "123456"
    },
    {
    "url": "https:\/\/www.pinterest.com\/evan\/",
    "first_name": "Evan",
    "last_name": "Sharp",
    "id": "234567"
    }
    ],
    "page": {
    "cursor": "PyEyNXxmMGVmZDA5mOTAw",
    "next": "https:\/\/api.pinterest.com\/v1\/me\/followers\/?access_token=<YOUR-ACCESS-TOKEN>&cursor=PyEyNXxmMGVmZDA5YmOTAw"
    }
    }
     */
    function getUserContacts() {
        // refresh tokens if needed
        $this->refreshToken();

        // need to add code to
        //
        $response = array();
        $contacts = array();
        $profile = ( ( isset( $this->user->profile->identifier ) )?( $this->user->profile ):( $this->getUserProfile() ) );
        try {
            $response = $this->api->api( "following/users/?fields=url,username,first_name,last_name,bio,image[medium]" );
        } catch (LinkedInException $e) {
            throw new Exception("User contacts request failed! {$this->providerId} returned an error: $e");
        }
        //

        if ( isset( $response ) && $response->meta->code == 200 ) {
            foreach ($response->data as $contact) {
                               //
                $uc = new Hybrid_User_Contact();
                //
                $uc->identifier  = $contact->id;
                $uc->firstName   = $contact->first_name;
                $uc->lastName    = $contact->last_name;
                $uc->displayName = $contact->first_name.' '.$contact->last_name;
                $uc->description = $contact->bio;
                $uc->photoURL    = $contact->image->medium ->url;

                $uc->webSiteURL  = $contact->url;

                $uc->username    = $contact->username;
                //$uc->email          = ;
                //
                $contacts[] = $uc;
            }
        }
        return $contacts;
    }
}

**Comment by nazar-pc** [comment]
Not funny. Make a PR, please
