### ISSUE TITLE
Problem with custom session_name()

### ISSUE THREAD

**Issue by WebAgencyContat** [hybridauth/hybridauth#383]
Hi, to start: awesom work! I find some problems with custom session_name() in php.
The class Storage must be fixed. Currently i have that much  time to investigate but i belive that you are more than me into the project. So,  please, fix it as soon as possible :+1:

**Comment by pranshuagrawal** [comment]
@WebAgencyContat @StorytellerCZ I was using this amazing library but I have faced the same issue and way to make it work?

**Comment by afbora** [comment]
+1 I got the same error on v2.9.x

**Comment by hepaestus** [comment]
I too am having session name/id issues. I am on v2.9.6 and trying to authenticate with Google. 

I think that the storage object cannot find the saved info because the session id/name changes during the call to google. 

Any Ideas?
Thanks,
P.

**Comment by ApacheEx** [comment]
I'm closing this issue since v2 is under Maintenance mode.
