### ISSUE TITLE
GitHub not returning email

### ISSUE THREAD

**Issue by al35mm** [hybridauth/hybridauth#384]
I am using Hybridauth on an app I am developing with PhalconPHP framework. I have Facebook working fine, but GitHub will not return an email. I have tried changing the scope from blank to user, but that gives me a warning `Warning: property_exists() expects parameter 2 to be string, object given in` and still no email is returned. I have seen other similar error reports about GitHub emails, but these were reported as "Fixed". I am using latest GitHub.php from Hybridauth Github repo - the commit comment suggests that an email issue has been fixed. Any ideas?

**Comment by Shade-** [comment]
It works fine for me. Are you sure you have set your email to be public? By default, GitHub will hide your primary email address.

**Comment by JamesNock** [comment]
I've worked out the solution, which is this:

In Providers/Github.php

Lines 61 to 66 should be:
```php
if ($email instanceof stdClass
	&& property_exists($email, 'primary')
	&& true === $email->primary
	&& property_exists($email, 'email')
) {
```

i.e. property_exists arguments need to be the other way around.
