### ISSUE TITLE
Google issues

### ISSUE THREAD

**Issue by al35mm** [hybridauth/hybridauth#386]
I've got problems using the standard google OAuth2 system. At first I get a `400 Error: redirect_uri_mismatch`. Then if I set "redirect_uri" in config.php, after confirming with google I just get standard message from auth which contains my...

```
require_once("hybridauth/Hybrid/Auth.php");
require_once("hybridauth/Hybrid/Endpoint.php");
\Hybrid_Endpoint::process();
```

**Comment by Remo** [comment]
you mean you get to see the PHP code in your browser? Are using PHP short tags?

**Comment by systemedia** [comment]
and I get  "Undefined property: Hybrid_Providers_Google::$access_token" ... I changed $this->access_token to $this->api_>access_token , the errors disappears , but now I am getting : This webpage has a redirect loop " error
