### ISSUE TITLE
Unable to use Facebook provider

### ISSUE THREAD

**Issue by inquam** [hybridauth/hybridauth#391]
I'm able to login using Twitter, Google etc without any issues. But setting up a new Facebook app and trying to login with that I always get 

"Uncaught exception 'Exception' with message 'Authentication failed! Facebook returned an invalid user id.'"

The SDK used by Hybridauth seems to be marked as deprecated and a new Facebook PHP SDK is released (v4.0). I'm not sure but perhaps new apps are forced to use this SDK?

Is there any updated version that use this new SDK instead?

**Comment by kerphi** [comment]
I'm not sure but I think the warning I got when trying to auth with the hybridauth facebook provider is related to this issue. Here is the screenshot showing the warning:
![image](https://cloud.githubusercontent.com/assets/328244/6201062/a67092ee-b495-11e4-9422-8ee746c37bf4.png)

**Comment by Shade-** [comment]
See #280.
