### ISSUE TITLE
Steam provider needs to be updated

### ISSUE THREAD

**Issue by Shade-** [hybridauth/hybridauth#393]
The current method used to obtain the profile of a Steam user parsing an XML file is deprecated (https://partner.steamgames.com/documentation/community_data) and should be updated with an API_KEY-dependent approach described in details here: https://partner.steamgames.com/documentation/webapi

Also, the current method breaks the login process if the user has a custom Steam url, which causes file_get_contents() to return a blank and invalid page. SimpleXMLElement throws an error ("String could not be parsed as XML") because the processed url does not return a valid XML file.

This is urgent, but I have no time to fix this at the moment.

**Comment by Cyril-Beeckman** [comment]
+1 same error

**Comment by OddworldCrash** [comment]
Yes, can confirm the same problem. I'm using hybrid auth based plugins for Durpal and Joomla.
Did Steam now completely shut off openid?

Does someone know, what has changed with their new API?

**Comment by jacob1237** [comment]
Hi guys!

I've created a pull request https://github.com/hybridauth/hybridauth/pull/420 with updated Steam provider.

But I need to say that the Steam provider is already updated in 3.0.0 version of HybridAuth, so you can try to use 3.0.0 branch, or just copy/paste the Steam.php file from my commit.
