### ISSUE TITLE
Make Hybrid_Endpoint methods non-static

### ISSUE THREAD

**Issue by nazar-pc** [hybridauth/hybridauth#396]
I'm currently experimenting with ReactPHP and since this class may store state in its static properties this will definitely cause problems in asynchronous long-playing environment.
If there is no need to call statically anything except `::process()` from outside (it is so at the first glance) we can create object in `::process()` method and pass argument there. This will allow to convert all other methods into non-static calls while keeping previous interface.
If you thing this is OK - I can send pull request for this change.

**Comment by AdwinTrave** [comment]
Definitely send a PR. It is easier to talk about it when we see exactly the changes you are suggesting.

**Comment by nazar-pc** [comment]
PR #408
