### ISSUE TITLE
Please include the latest version of the XING provider

### ISSUE THREAD

**Issue by FabianBeiner** [hybridauth/hybridauth#400]
It's available at https://github.com/FabianBeiner/HybridAuth-XING. Thank you!

**Comment by AdwinTrave** [comment]
Feel free to submit a Pull Request that adds it.

**Comment by VladyslavKurmaz** [comment]
@FabianBeiner If you don't mind, I can copy XING.php to the additional-providers area and prepare pull request.
But in this case, I will steal your contribution )

**Comment by FabianBeiner** [comment]
To be honest, I totally forgot about that. ;) I added it to my todo list and will send a request soon.

**Comment by VladyslavKurmaz** [comment]
Ok. Make sure that XING provider is in additional-providers area before pull request.

**Comment by StorytellerCZ** [comment]
You might want to create it now for v3.

**Comment by FabianBeiner** [comment]
The XING public API shut down. 😞 So there won't be an update coming.
