### ISSUE TITLE
[Twitter] get all follower list 

### ISSUE THREAD

**Issue by myselfgaurav** [hybridauth/hybridauth#402]
how can i get all twitter follower using this api please guide

**Comment by VladyslavKurmaz** [comment]
@myselfgaurav 
Twitter API endpoint you need is
https://dev.twitter.com/rest/reference/get/followers/list

I put some references about "how to use providers api call" here 
'[Twitter] Get statistics #440'
and
'Hope you guys add Youtube and Flickr Provider #424' issues
