### ISSUE TITLE
Hybrid_Provider_Adapter::factory(): Failed opening required 

### ISSUE THREAD

**Issue by naneri** [hybridauth/hybridauth#407]
I get this error: 
```php
Hybrid_Provider_Adapter::factory(): Failed opening required 
'C:\xampp\htdocs\gamer\vendor\hybridauth\hybridauth\hybridauth\Hybrid/Providers/Steam.php' 
```

Because "Steam" resides in additional providers folder. I can solve by manulally moving the file to Providers folder, but that is a bad practice (because modyfying other people packages is a bad idea). How should I solve this?

**Comment by AdwinTrave** [comment]
Actually you are suppose to copy from the additional providers folder to the hybrid auth providers folders. Check the `install.html` in the additional providers folder for more info.
