### ISSUE TITLE
Fatal Error: Declaration of Hybrid_Storage::config() must be compatible with that of Hybrid_Storage_Interface::config() 

### ISSUE THREAD

**Issue by AdwinTrave** [hybridauth/hybridauth#413]
Going of https://www.drupal.org/node/2332631

```
Fatal error: Declaration of Hybrid_Storage::config() must be compatible with that of Hybrid_Storage_Interface::config() in /Hybrid/Storage.php on line 13`

**Comment by miled** [comment]
I think this happen with php <5.2.

https://github.com/hybridauth/hybridauth/blob/master/hybridauth/Hybrid/StorageInterface.php#L13

$value needs to be eq null: `$value = null`
