### ISSUE TITLE
Hybrid_Auth::redirect not working

### ISSUE THREAD

**Issue by NestorZal** [hybridauth/hybridauth#421]
Hi, I using hybridauth in my site and was working perfectly, but I change my site to another server and when I tried to use the login with social media, the access to hybridauth library send to me 500 internal server error, log file in the end says:
 Hybrid_Provider_Adapter::login( Google ), redirect the user to login_start URL
 Enter Hybrid_Auth::redirect 

and that's it, nothing more, and I know my code was working perfectly because it worked in the previous server

I know is not my .htacces file because I'm using clean urls for my pages and is working perfectly

I hope you can help me

**Comment by AdwinTrave** [comment]
Have you changed your settings on the social media? Google for example is very strict on authorized domains.

**Comment by NestorZal** [comment]
No, I not change anything, and I'm using the same domain. The only thing I changed is the server IP.

**Comment by AdwinTrave** [comment]
That is strange indeed. Do you have the issue with Google only or with all providers?

**Comment by NestorZal** [comment]
I'm using facebook, google, linkedin and twitter, for all happens the same. I'm using wordpress and I created my own plugin for login into my site using hybridauth.

**Comment by NestorZal** [comment]
I resolved the problem, thanks anyway for everything. Is a server problem, files permission.

**Comment by hellboy81** [comment]
How can you resolved this problem?
