### ISSUE TITLE
Hybridauth dependancy

### ISSUE THREAD

**Issue by naneri** [hybridauth/hybridauth#423]
I had a problem with Steam Login deprecated method with Hybrid Auth 2.3, but it was solved in 2.4. Unfortunately I don't get the update. 
I use Atticmedia/Anvard  library which has dependancy - "hybridauth/hybridauth": "2.*@dev", but it only updates to 2.3
When will 2.*@dev be updated to 2.4?

**Comment by AdwinTrave** [comment]
There are still few things that I would like to resolve before 2.4, but in short it will be when the number of pull requests reaches zero.
