### ISSUE TITLE
Hope you guys add Youtube and Flickr Provider

### ISSUE THREAD

**Issue by trungnnh** [hybridauth/hybridauth#424]
I love Hybrid, it's simple but powerfull

Now I got a situation that require connect to Youtube and Flickr

Hope you guys add Youtube and Flickr Provider soon

Regards !

**Comment by VladyslavKurmaz** [comment]
@trungnnh You can already use Youtube API features with current Google OAuth authantication.
1. Enable Youtybe API for you app using Google Developers Console
https://developers.google.com/youtube/v3/getting-started
2. Specify additional Youtube scope inside hybridauth config
```
    // youtube scope: https://www.googleapis.com/auth/youtube
    $config =
        array(
            "base_url" => $base.'libs/'.$hybridauthVersion.'/hybridauth/', 
            "providers" => array ( 
                "Google" => array ( 
                    "scope" => "https://www.googleapis.com/auth/plus.login https://www.googleapis.com/auth/plus.profile.emails.read https://www.google.com/m8/feeds/ https://www.googleapis.com/auth/drive https://www.googleapis.com/auth/youtube"
                )
            )
        );
```
3. Call Youtube API
```
$adapter = $hybridauth->authenticate( "Google" );
$subs = $adapter->api()->get( "https://www.googleapis.com/youtube/v3/channels", array( "part" => "contentDetails", "mine" => "true" ) );
echo json_encode( $subs );
```

More sample are here
https://developers.google.com/youtube/v3/code_samples/php

**Comment by bahman2216** [comment]
I successfully connected to **Google** account and some other social networks via Hybridauth, For **Youtube**, I tried to login and authorize with **Google** API.
It response me **Invalid Credentials** with error code 401.

My part code:

    $adapter = $hybridauth->authenticate( "Google", $params  );

It is work for Google, But not work for Youtube. I made two Key ID and Secret. One for Google+ and one for Youtube. But still have same error.

I read youtube data API and try it online. work normally. https://developers.google.com/youtube/v3/docs/search/list#try-it
My question is: can I connect to youtube through google authentication API? if true? Then with google+ everything is ok and with youtube response me Invalid Credentials with error code 401.

**Comment by VladyslavKurmaz** [comment]
@bahman2216 Have you updated scope for Google provider with Youtube auth
// youtube scope: https://www.googleapis.com/auth/youtube
?
See my comment above about.

**Comment by bahman2216** [comment]
Yes, I did exactly as you said. But I thinks it is related to Client ID and secret ID.
I made separated file with name Youtube.php and created new Client and secret ID.It is worked for youtube login but same error with google!!! I confused

**Comment by VladyslavKurmaz** [comment]
@bahman2216
Why do you need separate ids for google/youtube? Is this from highlevel requirements?
Google uses single oauth2 entry point for all services.
...
I just checked code from my comment above and it still works fine.
...
Only one thing I can suggest without code snapshot: check one more time scope variable.
Here is what I'm using
```
"scope" => "https://www.googleapis.com/auth/plus.login https://www.googleapis.com/auth/plus.profile.emails.read https://www.google.com/m8/feeds/ https://www.googleapis.com/auth/drive https://www.googleapis.com/auth/youtube"
```
