### ISSUE TITLE
Twitter Provider Error

### ISSUE THREAD

**Issue by brili** [hybridauth/hybridauth#428]
Just updated hybridauth and got this error Error: Cannot redeclare class OAuthSignatureMethod_HMAC_SHA1

**Comment by AdwinTrave** [comment]
Did not encounter, can you give us more info? What exactly are you trying to do with the provider.

**Comment by josiahgoff** [comment]
I have the same issue. I check my whole project and I'm not redeclaring this class anywhere. Only thing that changed is I updated to hybridauth 2.4. I'm not doing anything special with it, just connecting to Twitter.

**Comment by AdwinTrave** [comment]
Some links:
https://wordpress.org/support/topic/plugin-simple-twitter-connect-cannot-redeclare-class-oauthsignaturemethod_hmac_sha1
https://www.drupal.org/node/1661494

I will see how much recent third party Twitter libraries I can pull in. In the meantime please make sure that you have upgraded properly.

**Comment by AdwinTrave** [comment]
@brili and @josiahgoff please check now after the fix merge and let us know if that fixed the error.

**Comment by chadwick37** [comment]
This didn't fix it for me. No problems when I roll back to 2.3.0 but 2.4.0 gives this error:

`PHP Fatal error:  Cannot redeclare class OAuthConsumer in /var/www/vendor/hybridauth/hybridauth/hybridauth/Hybrid/thirdparty/OAuth/OAuth.php on line 15`

**Comment by SocalNick** [comment]
@AdwinTrave - #430 fixes this. Please cut 2.4.1 including this fix.

**Comment by josiahgoff** [comment]
Yes, the patch fixed it for me. Ready for 2.4.1. Thanks, guys!

**Comment by AdwinTrave** [comment]
@SocalNick, @josiahgoff 2.4.1 is out
@chadwick37 Do you have another authentication system on your website that could be beating heads with HybridAuth?

**Comment by josiahgoff** [comment]
2.4.1 fixes it for me. Thanks!
