### ISSUE TITLE
Search string into all post from Twitter and Facebook

### ISSUE THREAD

**Issue by XinYiMan** [hybridauth/hybridauth#429]
Hello guys, I have only just discovered the existence of this magnificent project: HybridAuth

I was wondering if someone makes me an example to understand how to get from Facebook and Twitter from the list of messages that contain a particular word.

I would like to create a kind of Twitter Search, but that works both for Twitter and for facebook.

Someone can help me?

thanks a lot

**Comment by VladyslavKurmaz** [comment]
@XinYiMan Please look at my answers for 
'[Twitter] Get statistics #440'
and
'Hope you guys add Youtube and Flickr Provider #424' issues

The workflow is the same for any provider:
once you are successfully authenticated with one or more providers you can make any additional api calls. Just check Twitter and/or Facebook api and find endpoint you need.
API calls with hybridauth is really easy.

Hope this help
