### ISSUE TITLE
Feature request: use custom session

### ISSUE THREAD

**Issue by nazar-pc** [hybridauth/hybridauth#433]
I'm developer of CleverStyle CMS, which uses own [custom session management](https://github.com/nazar-pc/CleverStyle-CMS/blob/master/core/classes/Session.php) interface which is not based on PHP's built-in because of number of reasons.

Whould be nice if you wrap everything that deals with sessions into simple class and allow to provide custom version that implements the same interface (it is sad to see hard dependency on PHP sessions right now).

This will allow many CMS/CMF and frameworks nicer and deeper integration with HybridAuth.

Of course, this is for 3.x branch, 2.x is not actively developed except pull requests and serious bug fixes as I understand.

**Comment by AdwinTrave** [comment]
@miled

**Comment by miled** [comment]
> Whould be nice if you wrap everything that deals with sessions into simple class and allow to provide 

yep, v3 session backend is already implemented that way.
