### ISSUE TITLE
[LinkedIn] getusercontacts error

### ISSUE THREAD

**Issue by dcnl1980** [hybridauth/hybridauth#438]
ErrorException (E_NOTICE)
HELP
Undefined variable: ch
Open: /var/www/clients/client1/web4/web/laravel/vendor/hybridauth/hybridauth/hybridauth/Hybrid/thirdparty/LinkedIn/LinkedIn.php

      // set the last url, headers
      $this->last_request_url = $url;
      $this->last_request_headers = $header;
 
      // gather the response
      $return_data['linkedin']        = curl_exec($handle);
      if( $return_data['linkedin'] === FALSE ) {
          Hybrid_Logger::error( "LinkedIn::fetch(). curl_exec error: ", curl_error($ch) );
      }
      $return_data['info']            = curl_getinfo($handle);

**Comment by VladyslavKurmaz** [comment]
Looks like a typo in 
http://code.google.com/p/simple-linkedinphp/
```
      $return_data['linkedin']        = curl_exec($handle);
      if( $return_data['linkedin'] === FALSE ) {
          Hybrid_Logger::error( "LinkedIn::fetch(). curl_exec error: ", curl_error($ch) );
      }
```
**$ch** should be **$handle**
Latest simple-linkedinphp version (3.2.0) was published in Nov 2011.

Should we fix our instance of library?
I'm afraid we will not receive new version of simple-linkedinphp soon.

**Comment by dcnl1980** [comment]
Just change this in the code, but no we are unable to fetch the users. The last time it was working, since the update not.

**Comment by dcnl1980** [comment]
Just change this in the code, but no we are unable to fetch the users. The last time it was working, since the update not.

**Comment by VladyslavKurmaz** [comment]
Additional error check was added at Feb 15, 2014
pull request #98 from mindon/master …
53c1ba645adad670b9ed6d41e5534692cb503c5c
```
if( $return_data['linkedin'] === FALSE ) {
          Hybrid_Logger::error( "LinkedIn::fetch(). curl_exec error: ", curl_error($ch) );
      }
```
It's clear now, I will fix it.

**Comment by dcnl1980** [comment]
Super and thanks for your fix. I will wait for the pull request to get accepted. Found also some problems with Google+, but i will make some other thread.
