### ISSUE TITLE
[Twitter] Get statistics

### ISSUE THREAD

**Issue by Kevonia** [hybridauth/hybridauth#440]
It There a way to get The number of Likes and rewteets from hybridauth

**Comment by VladyslavKurmaz** [comment]
@Kevonia after successful authentication with Hybridauth, you can make additional Twitter api call.
```
$adapter = $hybridAuth->getAdapter( "Twitter" );  
$adapter->api->api( "statuses/retweets/".$tweetId );
```
Please check link below, in case you still need number of retweets
https://dev.twitter.com/rest/reference/get/statuses/retweets/%3Aid

**Comment by Kevonia** [comment]
Call to a member function api() on a non-object i get this error. 
faber est quisque fortunae suae  (every man is architect of his own fortune) 

(while there is life, there is hope)
Kevonia A. Tomlinson,Pending Bachelor of Science in Computing
University of Technology, Jamaica,
Tel:4898237, 3171074

**Comment by VladyslavKurmaz** [comment]
Sorry, my bad
```
$adapter = $hybridAuth->getAdapter( "Twitter" );  
$adapter->api()->api( "statuses/retweets/".$tweetId );
```

**Comment by Kevonia** [comment]
Hi hybridauth/hybridaut,

I'd like to add you to my professional network on LinkedIn.

- kevonia

Confirm that you know kevonia: https://www.linkedin.com/e/v2?e=0-iibxxaka-zp&t=ssuw&tracking=eml-guest-invite-cta&ek=invite_guest&sharedKey=uLoRkh_U&invitationId=6083666506242146305








You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=0-iibxxaka-zp&t=lun&midToken=AQFmrFVhGEd36Q&ek=invite_guest&loid=AQHheYLZqlguJgAAAVG2GjH7uuR-NNs7MnkCGUrEj8YyGGH-InzO875RtcgJN2DMyVL6LeCHL4PqCd1R786FXtqDVsyr-K7H-IVpDyzP8PGQBtX5u1BdPwDFHWlbk8TWNwaUENATgCqU0t1oRMZDEmcvqqHgb-i92CixNv6BvmWg_iu6_mWuauoXnBRYqppVUSx8&eid=0-iibxxaka-zp


This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=0-iibxxaka-zp&a=customerServiceUrl&ek=invite_guest

&copy; 2015 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by Kevonia** [comment]
kevonia Tomlinson would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/e/v2?e=-65hhtf-ij090ii8-d8&a=preRegInvite&ek=first_guest_reminder_01&li=14&m=hero&ts=accept_text&sharedKey=uLoRkh_U&invitationID=6083666506242146305

View kevonia Tomlinson&#39;s profile: https://www.linkedin.com/e/v2?e=-65hhtf-ij090ii8-d8&a=preRegInvite&ek=first_guest_reminder_01&li=3&m=hero&ts=profile_text&sharedKey=uLoRkh_U&invitationID=6083666506242146305





You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=-65hhtf-ij090ii8-d8&t=lun&midToken=AQFmrFVhGEd36Q&ek=first_guest_reminder_01&li=16&m=unsub&ts=HTML&eid=-65hhtf-ij090ii8-d8&loid=AQHgyzeteeOIowAAAVIOgtozFrq3GOIv4a5AAaulBtrdsHCmERluGuJQ3LeY_E9OfmE2UNN1821V5NcXtHUl_NITUdvzyDdWveHkhO9PUxHYM5870q1nKFxnOkKOM1hCGszimSgxaTNi6fM3q_tS3A-YziDTF66MN9ZfVajZEsd54-8UPpRbIIEEuVZdtfcEAgwq

This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=-65hhtf-ij090ii8-d8&a=customerServiceUrl&ek=first_guest_reminder_01

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.
