### ISSUE TITLE
More documentation

### ISSUE THREAD

**Issue by fulldecent** [hybridauth/hybridauth#443]
Here is the readme and the page that is successfully loaded after installing:

I was hoping for more documentation.

![screen shot 2015-04-11 at 10 36 39 am](https://cloud.githubusercontent.com/assets/382183/7101768/b3d39fcc-e036-11e4-8314-fe3bc80577c3.png)
![screen shot 2015-04-11 at 10 36 01 am](https://cloud.githubusercontent.com/assets/382183/7101769/b630f5b2-e036-11e4-9a2f-8a603d505faa.png)

**Comment by AdwinTrave** [comment]
http://hybridauth.sourceforge.net/
