### ISSUE TITLE
Split Adapter::authenticate method to make it optional

### ISSUE THREAD

**Issue by Soullivaneuh** [hybridauth/hybridauth#456]
I'm trying to create a [SLLHHybridAuthBundle](https://github.com/Soullivaneuh/SLLHHybridAuthBundle) to integrate your library.

After looking through your source code, I saw that your system works with the main [AdapterInterface::authenticate](https://github.com/hybridauth/hybridauth/blob/3.0.0-Remake/src/Adapter/AdapterInterface.php#L34) method that call a `header` method form [HttpClient\Util](https://github.com/hybridauth/hybridauth/blob/3.0.0-Remake/src/HttpClient/Util.php#L19-L24) in order to redirect to the third party authentication website.

This is a quite big problem for me because your library directly manage HTTP requests and responses.

Symfony Security compoment has is own system for dealing with requests and responses.

You can see with this tutorial: http://symfony.com/doc/current/cookbook/security/custom_authentication_provider.html

Or in action on this bundle: https://github.com/FriendsOfSymfony/FOSFacebookBundle

So my question is: Did you plan any enhancements in order to split authenticate method to make it optional?

I'm thinking of something like this:
- `AdapterInterface::getAuthorizeUrl` => Get the third party URL to make it redirect yourself
- `AdapterInterface::setAccessToken` => Manually set the access token

With this solution, I could make redirects to OAuth manually with keeping [providers features](https://github.com/hybridauth/hybridauth/blob/3.0.0-Remake/src/Adapter/AbstractAdapter.php#L129-L156) like 'getUserProfile' method.

Do you see my point of view? Don't hesitate to ask me if you want more precision.

Do you think this is feasible for 3.0 release?

If it's not possible at all, I suggest you two things:
- Remove my bundle from your [plugins list](http://hybridauth.sourceforge.net/plugins.html) because I won't continue it's not compatible.
- Suggest Symfony user to not use this library because of HTTP manipulation overrides. Could be very nice to suggest [HWIOAuthBundle](https://github.com/hwi/HWIOAuthBundle) instead, for example.

Best regards.

**Comment by nazar-pc** [comment]
I think it is possible in 3.0 release, I actually need that too for  as well as eliminating `die()` (there is only one currently in 3.0 AFAIK, look #433 and #451 for some discussion).
Take a look at 3.0-Remake branch for current state, also @miled said he'll prepare some more docs about this branch and I'm planning to participate as well.
Also feel free to make pull request, I think it is valuable feature to have.

**Comment by Soullivaneuh** [comment]
@nazar-pc Thanks for your answer, I'll take a look to those issues.

I'm rightly talking about 3.0-Remake branch! ;-)

The problem it's not only the `die` function but the fact of making http response and redirect inside the library with not another dev choice. As I said, the security compoment of Symfony has his proper rules about it and cannot deal properly with your actual system.

I will take a look for a PR but haven't lot of time for. Not sure to be able to make a proposition.
