### ISSUE TITLE
One network - how to show only one network (e.g. Facebook)

### ISSUE THREAD

**Issue by godm82** [hybridauth/hybridauth#467]
Please help, how to show only one network (e.g. Facebook)
instead of all (foreach):

now I have such an output (in opencart):

<?php if ($this->config->get('hybrid_auth_status')) { ?>
  <?php foreach ($this->config->get('hybrid_auth') as $config) { ?>
      <a href="<?php echo $this->url->link('hybrid/auth', 'provider=' . $config['provider']); ?>"><img src="<?php echo HTTPS_IMAGE . 'themezee_social_icons/' . strtolower($config['provider']); ?>.png" alt="<?php echo $config['provider']; ?>" title="<?php echo $config['provider']; ?>"/></a>
  <?php } ?>
<?php } ?>

sorry for code...

**Comment by nazar-pc** [comment]
HybridAuth doesn't show any network, it is up to you what to show.
You should write such question somewhere on OpenCart's forums.

**Comment by godm82** [comment]
can not find such a firum.... :(

**Comment by AdwinTrave** [comment]
Try the OpenCart forums: http://forum.opencart.com/
Or ask the plugin creator (if you are using the open cart hypbridauth plugin).
