### ISSUE TITLE
Post to Twitter timeline using access token and secret key

### ISSUE THREAD

**Issue by moazam1** [hybridauth/hybridauth#469]
I am looking for a way to post on my twitter timeline using my access token and secret key. I have checked docs and did Google search but unfortunately I couldn't any helpful hint.

Is there any hack available to do this job?

**Comment by ApacheEx** [comment]
@moazam1,
not sure if it still actual 🙃
but in short, just try this:
```
$hybridauth = new Hybrid_Auth($config);
$adapter = $hybridauth->authenticate("Twitter");
$status = $adapter->setUserStatus("Yay, let's tweet!");
```

p.s. should work since v2.8.0
