### ISSUE TITLE
[Provider] WeChat

### ISSUE THREAD

**Issue by teripak** [hybridauth/hybridauth#471]
Hi,

Our sevice will be mainly providing in China and WeChat is wide used for social communication.

Can I use hybridauth in our Drupal site to give a permit to login from Wechat user?

Thank you

**Comment by AdwinTrave** [comment]
There currently isn't a provider for WeChat, but anybody is welcomed to create it.

**Comment by StorytellerCZ** [comment]
#409

**Comment by marsjaninzmarsa** [comment]
#842.
