### ISSUE TITLE
how to alter the $config in a custom module in drupal 7

### ISSUE THREAD

**Issue by SukanyaD** [hybridauth/hybridauth#475]
Hi,
I need to alter the google provider's config array to set "approval_prompt" and "hd" value to be set permanently. Please help. Thanks in advance

**Comment by AdwinTrave** [comment]
Are you using the Drupal HybridAuth plugin?

**Comment by SukanyaD** [comment]
Hi, thanks! 
Yes, hybridauth module on drupal 7. So, without tweaking the the module code, i was able to alter the google  config array by using hybridauth alter hook function and only the hd parameter(domain specific login) works. Additionally, i also want to prevent the autologin instead show up the login screen to the user after every logout which i am not able to do.

**Comment by AdwinTrave** [comment]
You might want to ask on the Drupal plugin page (https://www.drupal.org/project/issues/hybridauth?categories=All) as your question seem to portray to specific plugin application and not the core HybridAuth.

**Comment by ApacheEx** [comment]
@SukanyaD,

it should be very easy, just try:
```
/**
 * Implements hook_hybridauth_provider_config_alter().
 */
function my_module_hybridauth_provider_config_alter(&$config, $provider_id) {
  switch ($provider_id) {
    case 'Google':
      $config['approval_prompt'] = 'force';
      break;
  }
}
```
