### ISSUE TITLE
[Facebook] session variables

### ISSUE THREAD

**Issue by andrisi** [hybridauth/hybridauth#481]
In addition to values under $_SESSION['HA::STORE'] the Facebook provider adds values like "fb_53783913...._access_token" directly to the session.

**Comment by PatrickBK** [comment]
and I'd like to unset these since they serve no purpose after login is done. To unset them via unset() I have to know how to get the names to unset:-) please help.

**Comment by chrisgraham** [comment]
I don't think this exists anymore. I only see 'HYBRIDAUTH::STORAGE' being created. And anyone who wants to 'tidy' that can just loop over and unset anything that doesn't end in ".user".
Can this issue be closed?

**Comment by ApacheEx** [comment]
I'm closing this issue since v2 is under Maintenance mode.
