### ISSUE TITLE
Zend Server using php-5.6-curl-zend-server

### ISSUE THREAD

**Issue by webru** [hybridauth/hybridauth#482]
Zend Server using php-5.6-curl-zend-server and during installation hybridauth through сomposer an error :
- hybridauth/hybridauth ... requires ext-curl * -> the requested PHP extension curl is missing from your system.

what can you do?

**Comment by nazar-pc** [comment]
Error message is extremely clear - just install curl extension

**Comment by webru** [comment]
In zend server is already CURL, php-5.6-curl-zend-server

**Comment by nazar-pc** [comment]
Is it installed and enabled? These two things are quite different.

**Comment by webru** [comment]
Yep, installed and enabled :) On another server without the Zend Server, where established php5.6-curl, enabled. The problem is that hybridauth does not see extension php-5.6-curl-zend-server, and see php-5.6-curl

**Comment by vrkansagara** [comment]
@webru the same issue but no better luck with issue.
