### ISSUE TITLE
[Live + PayPal] provider redirect URI

### ISSUE THREAD

**Issue by andrisi** [hybridauth/hybridauth#484]
The Live authentication setup (https://account.live.com/developers/applications/index / API Settings - where you get your app keys & secret) does not allow query strings in the exact redirect URL anymore, so the one you auto generate, example.com/?hauth.done=Live does not work. A custom_redirect directive under the provider's config might help.

**Comment by yodjii** [comment]
Same issue for months. Thanks

**Comment by kusmierz** [comment]
Same issue for paypal.

**Comment by SirLouen** [comment]
When you talk about Live, you mean OneDrive?

**Comment by andrisi** [comment]
The Live (Microsoft, Windows, etc.) login provider

**Comment by SirLouen** [comment]
Do you have an URL where you are viewing this key/secret?

**Comment by andrisi** [comment]
yes, added to ticket description

**Comment by PareshRadadiya** [comment]
I'm getting the same

**Comment by frangeris** [comment]
Same issue here using `v2.5.0` for Live... 

Keep getting this: 
`error_description=The+provided+value+for+the+input+parameter+'redirect_uri'+is+not+valid.`

**Comment by jmgomezpoveda** [comment]
Same issue here. There seem to be a couple of workarounds at http://hybridauth.sourceforge.net/userguide/IDProvider_info_Live.html

**Comment by neo22s** [comment]
This issue still happening
https://github.com/open-classifieds/openclassifieds2/issues/1993#issuecomment-234524826

**Comment by neo22s** [comment]
any update on this?

**Comment by ApacheEx** [comment]
should work in the latest version **v2.9.6-dev**. Pls upgrade and check an actual [documentation](https://hybridauth.github.io/hybridauth/userguide/IDProvider_info_Live.html)
