### ISSUE TITLE
Extra providers needs to be copied in the folder providers

### ISSUE THREAD

**Issue by nahuelsgk** [hybridauth/hybridauth#497]
To use the providers from the folder adittional providers, I had to copy the file into the providers Folder.
If it's not done, the provider it's not found giving a compilation error.

For exemple I had to copied vendor/hybridauth/hybridauth/additional-providers/hybridauth-tumblr/Providers/Tumblr.php into the folder vendor/hybridauth/hybridauth/hybridauth/Hybrid/Providers/
Into the vendor. 
It's seems not really good idea. And seems a deploy operation. Am I right? It's planned to be solved  in the future or Am I wrong doing it in that way?

**Comment by VladyslavKurmaz** [comment]
@nahuelsgk you don't have to copy any source codes to use additional providers. You need just properly configure provider inside config.
Please, check part of my configuration script

               "Github" => array (
                    "enabled" => true,
                    "keys"    => array(), 
                    "wrapper" => array(
                        "class" => "Hybrid_Providers_GitHub",
                        "path" => $_SERVER['DOCUMENT_ROOT'].'/libs/hybridauth/additional-providers/hybridauth-github/Providers/GitHub.php'
                    )
                ),

**Comment by nahuelsgk** [comment]
Oh! Thank you! I could find this on the docs!. I will close the issue!
