### ISSUE TITLE
Bug fixed?!

### ISSUE THREAD

**Issue by hennott** [hybridauth/hybridauth#498]
Hello,
I´ve tried HybridAuth with my Drupal 7 Environment and it doesn´t work. Now I changed a few lines of code and now it´s working in the correct way. Because I´m not familar with Git I´ll post my changes here:

Logger.php

This causes the error
..
(new DateTime)->format(DATE_ATOM),
..

and I changed it to
$Date = new DateTime();
$Date = $Date->format(DATE_ATOM);
..
$Date,
..

Can you please take this in the productive versionen?!

**Comment by nazar-pc** [comment]
This should not be a problem, what kind of error do you get?

**Comment by hennott** [comment]
The error was:
Parse error: syntax error, unexpected T_OBJECT_OPERATOR, expecting ')' in /path/libraries/hybridauth/hybridauth/Hybrid/Logger.php on line 44

After my change everything worked fine. This is my productiv environment which is not running the latest PHP version at the moment (maybe it´s 5.3 or 5.4)

**Comment by AdwinTrave** [comment]
@hennott Can you please submit a PR with your fix so that we can look at the code more closely? Thanks!

**Comment by hennott** [comment]
Sorry..I´m not so familiar with the worlds best code repository..you can search for the string and replace it with my string.
