### ISSUE TITLE
Implement the new OpenID Standard, OpenID Connect

### ISSUE THREAD

**Issue by Lawri-van-Buel** [hybridauth/hybridauth#502]
Feature request:
 Since OpenID Connect is a IDP on top of oAuth 2 it should be possible to implement this in hybridauth. with minimal developers effort required.

**Comment by ethier** [comment]
As far as I can tell, it's just adding openid scope.

**Comment by ApacheEx** [comment]
seems like @ethier is right. Please fill new issue if you have any problems with OpenID Connect.
