### ISSUE TITLE
Handle multiple session for each provider

### ISSUE THREAD

**Issue by bahman2216** [hybridauth/hybridauth#506]
Hi,
I challenged long time for manage multi account for each provider. 
If I have two google account and add both of them, Hybrid just know the last one and lost previous.
When we login or sync each account, token access replaced. token access name for Google provider is: 
hauth_session.google.token.access_token 
change to 
hauth_session.google.my_identity.token.access_token
Im a simple solution. It is possible to add provider identifier after provider name in session name.

**Comment by bahman2216** [comment]
No idea?
Im going to change Hybridauth session variable name from hauth_session.POVIDER_NAME.token.access_token to hauth_session.POVIDER_NAME.PROVIDER_IDENTITY.token.access_token.
Guys, if you have better idea please share it.
It seems it is hard to updae my hybridauth after these changes.

**Comment by nazar-pc** [comment]
Hybrid Auth 2.4.x is in maintenance mode, 3.0 is under development and already allows to use custom session handler.
