### ISSUE TITLE
[Vimeo] Invalid signature in Vimeo OAuth

### ISSUE THREAD

**Issue by Sammi89** [hybridauth/hybridauth#508]
Hi guys.
I'm using the [Hybridauth Social Login](https://www.drupal.org/project/hybridauth) Drupal module. I added Vimeo as a additional provider in **Hybridauth library 2.4.1** following the tutorial at this [link](http://hybridauth.sourceforge.net/userguide/Extend_New_Provider.html). 
When I try to authenticate user Vimeo return the following error:
`401 Unauthorized - Invalid signature - The oauth signature passed was not valid.`
I checked the _generateSignature function inside thirdparty folder but can't find the problem.
Some idea? Is planned by chance the update to _Vimeo OAuth 2_ in the future?
Thanks

**Comment by sraboni** [comment]
Hello,

I am having the same problem.  Are you able to find a solution for this error?
I am using v2.5.0 for PHP.

Thanks.

**Comment by adanjz1** [comment]
Same here!

**Comment by ApacheEx** [comment]
Hi guys, fixed in v2.9.5. Please try.
