### ISSUE TITLE
[Facebook] Function getUserProfile() still working ???

### ISSUE THREAD

**Issue by invader7** [hybridauth/hybridauth#509]
Hello im trying to use your library with scnsocialauth module for zf2 !

After some debug i found out that when the code goes to this function and executes the $data = $this->api->api('/me'); line

the $data variable becomes an array of 2 , id and name !

so every other line below as $this->user->profile->email         = (array_key_exists('email',$data))?$data['email']:""; will be ""

Did i missed something ? Thanks

**Comment by invader7** [comment]
https://github.com/hybridauth/hybridauth/commit/e8015af23cc9b5aaa3755508b4d8117df8ceda5a

**Comment by AdwinTrave** [comment]
Check now, I think #525 should have fixed this.

**Comment by AdwinTrave** [comment]
Looks like the module version of HybridAuth is outdated. According to their Github they are still on version 2.2.
