### ISSUE TITLE
http://hybridauth.sf.net/

### ISSUE THREAD

**Issue by yang-wei** [hybridauth/hybridauth#511]
Currently the website is not working.

http://hybridauth.sf.net/

**Comment by yang-wei** [comment]
Why not just use gh-pages

**Comment by nazar-pc** [comment]
Documentation on gh-pages will be (it should be already) for 3.0 release, current stable version is 2.4.x

**Comment by yang-wei** [comment]
:+1: 

so it's here http://hybridauth.github.io/hybridauth/

Thanks

**Comment by taiguaraguiradodearaujo** [comment]
link error
https://hybridauth.github.io/hybridauth/wsl/index.html
