### ISSUE TITLE
[LinkedIn] Solution For Number Of Connections

### ISSUE THREAD

**Issue by christ0ph3r** [hybridauth/hybridauth#512]
LinkedIn recently made updates that changed some stuff including getting contacts.   Currently there is no out of the box way to get the number of contacts on LinkedIn in the hybridauth libraray. 

You can get the number of contacts by using num-connections and by editing Linkedin.php, line:95 and adding num-connections.

`$response = $this->api->profile('~:(id,num-connections,first-name,last-name,public-profile-url,picture-url,email-address,date-of-birth,phone-numbers,summary)');`

Then put this on line Linkedin.php 119

`$this->user->profile->numconnections = (string) $data->{'num-connections'};`

However this does not use the getUserContacts() method.  So it seems the to support number of contacts on LinkedIn the interface would have to change and that will affect all providers.

Also thank you @VladyslavKurmaz for the help on this.

**Comment by AdwinTrave** [comment]
I think this is something you want to bring up with @miled for 3.0
