### ISSUE TITLE
Multiple Providers by User [CakePHP]

### ISSUE THREAD

**Issue by mrnetworks** [hybridauth/hybridauth#514]
Hi,

first: great work :)
I'm looking for a way to allow multiple Providers by one User, so if the user is logged in he could connect with other providers to, i.e. for posting on facebook and google+ wall.

Is there a solution integrated? :)

**Comment by nazar-pc** [comment]
It is already possible, just log in through few providers one by one.

**Comment by mrnetworks** [comment]
thank you for your answer.

my idea is an 1:n relation between user table and a table for providers.

https://github.com/ADmad/CakePHP-HybridAuth#database
with this database structure it isn't possible, isn't it?

**Comment by nazar-pc** [comment]
With that structure no.
Write your own, for instance, mine is here: https://github.com/nazar-pc/CleverStyle-CMS/blob/master/components/modules/HybridAuth/meta/install_db/integration/MySQLi.sql#L1
Works with users from here: https://github.com/nazar-pc/CleverStyle-CMS/blob/master/install/DB/MySQLi.sql#L93

**Comment by mrnetworks** [comment]
so i can write an 1:n structure and hybridauth can handle this?

- USER -
id, int
email, varchar
password, varchar

- PROVIDERS - 
id, int
user_id, int
provider, varchar
provider_uid, varchar

**Comment by nazar-pc** [comment]
Yes

**Comment by mrnetworks** [comment]
i tried so, but it doesn't work:

Error: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'Users.provider' in 'where clause'

Users Table Model:
namespace App\Model\Table;

use Cake\ORM\Table;

class UsersTable extends Table
{

    public function initialize(array $config)
    {
        $this->hasMany('UserSocial');
    }

}


Database:

CREATE TABLE IF NOT EXISTS `users` (
`id` int(10) unsigned NOT NULL,
  `email` varchar(150) COLLATE utf8_unicode_ci NOT NULL,
  `password` varchar(150) COLLATE utf8_unicode_ci NOT NULL,
  `created` datetime NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE IF NOT EXISTS `user_socials` (
`id` int(10) unsigned NOT NULL,
  `user_id` int(11) NOT NULL,
  `provider` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `provider_uid` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `created` datetime NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

ALTER TABLE `users`
 ADD PRIMARY KEY (`id`);

ALTER TABLE `user_socials`
 ADD PRIMARY KEY (`id`), ADD UNIQUE KEY `user_id` (`user_id`,`provider`);

What am i doing wrong? :)

I read your code but you didn't changed hybridauth core code, right? Why does it work on your code? :)

**Comment by nazar-pc** [comment]
I do not use CakePHP.
That was simple DB structure, how to connect it to HybridAuth depends on your framework, but that is not a HybridAuth issue.
Probably, you want to fill issue in https://github.com/ADmad/CakePHP-HybridAuth, but this issue should be closed since is not relevant to library itself.

**Comment by mrnetworks** [comment]
ah, sry. i didn't know about that link. i'll close this and reopen it at cakephp hybridauth :)
