### ISSUE TITLE
Support for Mozilla Persona

### ISSUE THREAD

**Issue by DouglasdeMoura** [hybridauth/hybridauth#515]
Is there plans for adding support for [Mozilla Persona](https://developer.mozilla.org/en-US/Persona)?

**Comment by AdwinTrave** [comment]
I might try at one of the hackathons in my area, but if anything that is going to be for 3.0.

It really depends if somebody takes the time to do that.

**Comment by StorytellerCZ** [comment]
Since Mozilla Persona is being shut down (https://wiki.mozilla.org/Identity/Persona_Shutdown_Guidelines_for_Reliers), this is no longer relevant.
