### ISSUE TITLE
Google+ vs Google OpenID Connect

### ISSUE THREAD

**Issue by Gargaj** [hybridauth/hybridauth#517]
The current Google auth provider (http://hybridauth.sourceforge.net/userguide/IDProvider_info_Google.html) is actually Google+, whereas Google still offers a non-G+ authentication method called OpenID Connect (which is a misleading name since it's still OAuth): https://developers.google.com/identity/protocols/OpenIDConnect

Shouldn't the current provider be renamed from Google to GooglePlus and an actual Google provider created for OpenID Connect?

**Comment by AdwinTrave** [comment]
Something to think for 3.0 @miled

**Comment by ivanbaldo** [comment]
Also, in the Google Developer Console, one must enable the Google+ API for it to work, that should be mentioned in http://hybridauth.sourceforge.net/userguide/IDProvider_info_Google.html .
