### ISSUE TITLE
[Yahoo] Can't set Callback Domain

### ISSUE THREAD

**Issue by TiMESPLiNTER** [hybridauth/hybridauth#520]
According to http://hybridauth.sourceforge.net/userguide/IDProvider_info_Yahoo.html I have to set a callback URL like:

```
http://mywebsite.com/path_to_hybridauth/?hauth.done=Yahoo
```

The problem is, I'm not allowed to set this callback URL in my [Yahoo App settings](https://developer.yahoo.com/apps/create/):

> The following strings are not allowed: yahoo, yahoo! and y!

**Comment by timersys** [comment]
Yes I got lot of clients with the same problem. It seems that files names need to be changed for Yahoo

**Comment by timersys** [comment]
@TiMESPLiNTER I just tried using just my domain in there. Instead of the full callback url I entered only the domain and it worked. Could you confirm on your end?

**Comment by NabiKAZ** [comment]
What's news about this bug?!

**Comment by ApacheEx** [comment]
it's fixed in v2.9.3. Please also check the latest [documentation](https://hybridauth.github.io/hybridauth/userguide/IDProvider_info_Yahoo.html).

if something will not work, create a new issue or reopen existing one.
