### ISSUE TITLE
refresh_token always  empty !

### ISSUE THREAD

**Issue by AkkaKhalid** [hybridauth/hybridauth#522]
I was using the Hybridauth 2.3.0 library for my last project with the CodeIgniter framework and I was encountering a problem. My issue is that the refresh token is always empty.

Hybrid\Provider_Model_OAuth2.php:

```
      function refreshToken()
      {
      // have an access token?
      if( $this->api->access_token ){
       // have to refresh?
      //==> $this->api->refresh_token always return false (empty)

      if( $this->api->refresh_token && $this->api->access_token_expires_at ){
    // expired?
    if( $this->api->access_token_expires_at <= time() ){ 
        $response = $this->api->refreshToken( array("refresh_token" => $this->api->refresh_token ) );

        if( ! isset( $response->access_token ) || ! $response->access_token ){
            // set the user as disconnected at this point and throw an exception
            $this->setUserUnconnected();

            throw new Exception( "The Authorization Service has return an invalid response while requesting a new access token. " . (string) $response->error ); 
        }

        // set new access_token
        $this->api->access_token = $response->access_token;

        if( isset( $response->refresh_token ) ) 
            $this->api->refresh_token = $response->refresh_token; 

            if( isset( $response->expires_in ) ){
                $this->api->access_token_expires_in = $response->expires_in;

                // even given by some idp, we should calculate this
                $this->api->access_token_expires_at = time() + $response->expires_in; 
            }
        }
    }

    // re store tokens
    $this->token( "access_token" , $this->api->access_token  );
    $this->token( "refresh_token", $this->api->refresh_token );
    $this->token( "expires_in"   , $this->api->access_token_expires_in );
    $this->token( "expires_at"   , $this->api->access_token_expires_at );
}
```

}

that means when the access token expires, an exception is triggered at this time like this:

Hybrid\Providers\Google.php:

```
   throw new Exception( "User profile request failed! {$this->providerId} returned an invalid response.", 6 );
```

so the user must log out and log in again. What should I do to solve this issue?

**Comment by AdwinTrave** [comment]
First, if you can, try upgrading to the newest version.

**Comment by AkkaKhalid** [comment]
Hi,
Although I've updated the library, the problem remains.
Thanks

Le jeudi 27 août 2015, Jan Dvorak <notifications@github.com> a écrit :
> First, if you can, try upgrading to the newest version.
>
> —
> Reply to this email directly or view it on GitHub.<
https://ci3.googleusercontent.com/proxy/CS-ztGtCDWL2rjkUn9dZJcVZcRqXBp2GXdIt4HhV4PaMTUOgygtXxV0fBE5ERYjcVc-cMOPEHqwFBFk4Cj3fsiCbmCy-5GUR9doFS4YDxvUKxVlI8CdHLVHg6XKeK9V_i6zd_l42OcYk-vRQx872h1AYo9cXuw=s0-d-e1-ft#https://github.com/notifications/beacon/ANGW2uXl2DZav5avwiSwPapG3qM6QGVSks5orkTqgaJpZM4Fo7mR.gif
>

-- 
Khalid Akka (Développeur/Intégrateur web)

**Comment by AdwinTrave** [comment]
Thanks that good to know.

**Comment by ApacheEx** [comment]
[here](https://github.com/ApacheEx/CodeIgniter-HybridAuth) is CodeIgniter implementation of Hybridauth, you can check there how it's implemented properly.
