### ISSUE TITLE
where to find the examples and demos ?

### ISSUE THREAD

**Issue by ezekel** [hybridauth/hybridauth#530]
HI, where I can find the demos and example so that I have reference on how to use this hybridauth in my website.

Thank you in advance.

**Comment by nazar-pc** [comment]
There is documentation on the main page of repository...

**Comment by ezekel** [comment]
@nazar-pc , 

yes I tried this `http://hybridauth.sourceforge.net/userguide/IDProvider_info_Facebook.html`
but it says it's outdated.
and this is the response after authenticated in facebook login, can I ask why all are empty ?

```
object(Hybrid_User_Profile)#10 (24) { ["identifier"]=> string(16) "1481084508878224" ["webSiteURL"]=> string(0) "" ["profileURL"]=> string(0) "" ["photoURL"]=> string(72) "https://graph.facebook.com/1481084508878224/picture?width=150&height=150" ["displayName"]=> string(17) "charles chinx" ["description"]=> string(0) "" ["firstName"]=> string(0) "" ["lastName"]=> string(0) "" ["gender"]=> string(0) "" ["language"]=> string(0) "" ["age"]=> NULL ["birthDay"]=> NULL ["birthMonth"]=> NULL ["birthYear"]=> NULL ["email"]=> string(0) "" ["emailVerified"]=> string(0) "" ["phone"]=> NULL ["address"]=> NULL ["country"]=> NULL ["region"]=> string(0) "" ["city"]=> NULL ["zip"]=> NULL ["username"]=> string(0) "" ["coverInfoURL"]=> string(269) "https://graph.facebook.com/1481084508878224?fields=cover&access_token=CAAVE8ueaRqUBAHwJGxD2d05ZCbZCoYUiDB5sqj1MutWonxS8E3nwGZCLiKzTkjgRosjqoZBUFXZCiG8ZACOILZCwIqmQ3c1ri9QIz0BL8ArdVhiKs6k0ofbEhfKXC4WTqRGtiPEz6H13bBYtaV0WgOguKj6oRT13DWErwsZCY7QyQjMOd0eK1ZCiyTjQLfjT5VlUZD" } 


```

Thank you in advance.

**Comment by nazar-pc** [comment]
According to your snippet it is far from empty.
SourceForge page is still usefull indeed, however, have you seen this?: https://hybridauth.github.io/hybridauth/

**Comment by ezekel** [comment]
@nazar-pc ,

Is this correct ? this is what I'm using, ..yes I see that link, and I used that but why is this null and the other is empty ? what am I doing wrong ?

 ["age"]=> NULL ["birthDay"]=> NULL ["birthMonth"]=> NULL ["birthYear"]=> NULL ["email"]=> string(0) ""
["address"]=> NULL ["country"]=> NULL ["region"]=> string(0) "" ["city"]=> NULL ["zip"]=> NULL ["username"]=> string(0) "" 



```
  	
   $config = array(
    "base_url" => "http://newuser.mysite.com/hybridauth/hybridauth/",
    "providers" => array (
        "Facebook" => array (
            "enabled" => true,
             "keys"    => array ( "id" => "--myid---", "secret" => "--mysecret---" ),
             "scope"   => "email, user_about_me, user_birthday, user_hometown", // optional
			 "display" => "popup", // optional
			 "trustForwarded" => false
           
        )));

       require_once( "hybridauth/hybridauth/Hybrid/Auth.php" );
	   
	   
		try{
			
			$hybridauth = new Hybrid_Auth( $config );

			$adapter = $hybridauth->authenticate( "Facebook" );

			$user_profile = $adapter->getUserProfile();

			die(var_dump($user_profile));
			
		}catch(Exception $e){
 
          echo $e->getMessage();
         
		}


```

Thank you in advance.

**Comment by nazar-pc** [comment]
What you get depends on scope you're requesting and what Facebook user allowed you to get.
So if user will deny access to his birth day - you'll get NULL there.

**Comment by ezekel** [comment]
@nazar-pc ,

so how can I make my users to login to my website just like other website did.  that if you login your facebook account you can loging in...so if the facebook user will restrict his email and profiles, how can he log in to my site because the response of email will be null. and I want to use his email to insert it to my table.

**Comment by nazar-pc** [comment]
You have to request emai separately with exmplanations why do you need that information or (as bad sites do) just redirect back to facebook requesting required information until user agree to give that information to you.

**Comment by ezekel** [comment]
I just followed this tutorial `http://hybridauth.sourceforge.net/userguide/Integrating_HybridAuth_Social_Login.html`

**Comment by ezekel** [comment]
@nazar-pc , 

This helps me https://github.com/hybridauth/hybridauth/issues/524

Now I get now the email of user,it's because there should be changes in facebook provider.

**Comment by AdwinTrave** [comment]
Sorry, but unless somebody makes them, there are no examples for the 2.4 version and they are currently not planned. We'll have to wait for 3.0.
