### ISSUE TITLE
Tag older releases

### ISSUE THREAD

**Issue by fulldecent** [hybridauth/hybridauth#536]
It appears this project does not use semantic versioning.

I am working on https://github.com/alixandru/q2a-open-login which uses hybridauth 2.1.2. I would like to modernize this but don't know much about what is going on. The easiest way for me would be to pull the real 2.1.2 from this project into there, then increment the version until it breaks and then fix it.

Please support my very stupid workflow by tagging the historical releases in this project between 2.0 and 2.2.

**Comment by AdwinTrave** [comment]
Added

**Comment by fulldecent** [comment]
Very nice, thank you
