### ISSUE TITLE
Improve Twitter generic 403 error

### ISSUE THREAD

**Issue by smagnaschi** [hybridauth/hybridauth#539]
The Twitter api related to setUserStatus throw a generic exception reporting exclusively the default error message based on the http code received.
Twitter though gives the api client an additional and more specific error code in the response body, for example:

```
[response:protected] => stdClass Object
    (
        [errors] => Array
            (
                [0] => stdClass Object
                    (
                        [code] => 186
                        [message] => Status is over 140 characters.
                    )

            )

    )
```

Would it be possible to integrate this code + message in the exception message thrown? Should I write a PR for this or do you think this is not important? Or am I missing something and there is already a way to catch this message?

**Comment by ApacheEx** [comment]
I'm closing this issue since v2 is under Maintenance mode.
