### ISSUE TITLE
I can not bring timeline LinkedIn

### ISSUE THREAD

**Issue by ezev123** [hybridauth/hybridauth#540]
I am new to this chat. I wanted to ask if you know how to connect to Linkedin hybridauth and get a timeline. I use the following code and variable $ user_timeline not work.

<?php
session_start();
// include hybridauth lib
$config = 'apis_src/hybridauth-2.5.0/hybridauth/config.php';
require_once('apis_src/hybridauth-2.5.0/hybridauth/Hybrid/Auth.php');

try {
    $hybridauth = new Hybrid_Auth($config);
    $linkedin = $hybridauth->authenticate( "linkedin" );

```
$userConnected = $linkedin->isUserConnected();
$user_profile = $linkedin->getUserProfile();
$user_contacts = $linkedin->getUserContacts();
$user_activity = $linkedin->getUserActivity("timeline");
```

} catch (Exception $e) {
    die("<b>got an error!</b> " . $e->getMessage());
}
// logged in ?
if (!$userConnected || !isset($user_activity)) {
    $fullUrl = "https://www.linkedin.com/uas/oauth2/authorization?response_type=code&client_id=77zmh91vqkc0pg&redirect_uri=http://guilgul.com/english/prueba_linkedin.php&state=987654321";
    ?>
    <p>
    <a href ="<?php echo($fullUrl) ?>" >Linkedin</a></h2>
 </p>
 <?php
}
else{
print_r($user_activity);  
}
?>

**Comment by VladyslavKurmaz** [comment]
A few months ago, Linkedin has changed policy for external apps.
So, from now, you can access to a very small part of user's information.
https://developer.linkedin.com/docs/fields/basic-profile

----
Try to test Linkedin API via this service to identify set of information you can get
https://apigee.com/console/linkedin

----
The maximum what you can receive is last user activity: current-share
https://api.linkedin.com/v1/people/~:(id,num-connections,picture-url,email-address,current-share)?format=json

**Comment by ApacheEx** [comment]
Unfortunately, `getUserContacts` and `getUserActivity` no longer work because LinkedIn has restricted their open API access. Check the latest [documentation](https://hybridauth.github.io/hybridauth/userguide/IDProvider_info_LinkedIn.html) for more info.
