### ISSUE TITLE
Obtain FB infos using an exist Access Token?

### ISSUE THREAD

**Issue by fedyfausto** [hybridauth/hybridauth#541]
Hello guys i have a question: If i just have an Access Token from user, how can i use that with Hybridauth and obtain the user's info? thx a lot

**Comment by nazar-pc** [comment]
If you have access_token - you do not need Hybridauth to get info, just make simple HTTP request to Facebook as written in documentation.
If you're using Hybridauth - there is useful `->api()` method for making such request, just look into documentation.
