### ISSUE TITLE
 HybridAuth Plugins Not Downloading For Cakephp3

### ISSUE THREAD

**Issue by soravgarg123** [hybridauth/hybridauth#544]
I need urgently  HybridAuth Plugins For Cakephp3 but it`s not downloading please help me it`s urgently..

**Comment by AdwinTrave** [comment]
Go here: https://github.com/ADmad/CakePHP-HybridAuth/tree/3.0

**Comment by soravgarg123** [comment]
Hello Jan,

Thank you for reply i will try this method..

On Thu, Sep 17, 2015 at 2:02 AM, Jan Dvorak <notifications@github.com>
wrote:

> Go here: https://github.com/ADmad/CakePHP-HybridAuth/tree/3.0
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hybridauth/hybridauth/issues/544#issuecomment-140881257>
> .
>



-- 
*Thanks & Regards*
*Sorav Garg*
*Software Developer*

*+919074939905*
*Indore (M.P.)*
