### ISSUE TITLE
PHP Fatal error: Class 'Hybrid_Exception' not found in /home/.../hybridauth/Hybrid/Endpoint.php on line 205

### ISSUE THREAD

**Issue by mbpineyro** [hybridauth/hybridauth#545]
Hi people,
i install hybridAuth and it was working fine for Facebook/Google+ login for a long time, but now i have this error:

PHP Fatal error: Class 'Hybrid_Exception' not found in /home/.../hybridauth/Hybrid/Endpoint.php on line 205

I upload my entire directory to a friend's hosting and it works perfect. My hosting is not solving this problem. What can i do to fix this? I read something about autoload but it don't know how it works. 
Thanks!

**Comment by nazar-pc** [comment]
There is already the same issue reported, use search first before reporting new one: https://github.com/hybridauth/hybridauth/issues/529
Also there is proper solution there.

**Comment by mbpineyro** [comment]
Hi @nazar-pc, i read that, but why if i upload to another hosting its working? Autoload is a server configuration? Thanks

**Comment by nazar-pc** [comment]
It is not connected with hosting, you just don't have autoloader!
If everything works fine - that is nice, but if something happens Hybridauth needs to throw an exception. Since you don't have autoloader you can't see what an exception was because exception class itself wasn't found.

**Comment by mbpineyro** [comment]
@nazar-pc  I test my site in two hostings.

In the primary it's not working (works for a long time, but now it's not working)
In the second, i uploaded all my files and works.

That's why i asked if there is a server configuration. I'm looking for more info about autoloader, i don't understand how it works. Thank you a lot.

**Comment by nazar-pc** [comment]
Autoloader is simple thing. Every time you're trying to use some class that PHP doesn't know about yet autoloader is called. So autoloader's job is to include class by it's name (if autoloader knows about class). If you install Hybridauth with Composer that will be done for you automaticaly.

**Comment by mbpineyro** [comment]
Excellent, i will try installing with composer.
Its funny that it was working fine for a long time and now it stopped working.
Thanks for your support  @nazar-pc

**Comment by nazar-pc** [comment]
It means it was working without errors, which is even more awesome) But that would happen sooner or later anyway.

**Comment by rahuljs** [comment]
Somebody pls guide me step by step how to solve this error
