### ISSUE TITLE
[provider] Azure Active Directory

### ISSUE THREAD

**Issue by frodeste** [hybridauth/hybridauth#548]
Can we create a provider for Azure OpenID Connect or OAUTH?

I can contribute

**Comment by AdwinTrave** [comment]
If you can make it that would be great!

**Comment by dearsina** [comment]
Any news on this? Azure uses Oauth2, and I (foolishly) thought it was easy enough to extend a provider class to cover it. I'm using 3.0, but have gotten nowhere. Any pointers?

**Comment by frodeste** [comment]
I have not time to spend on this now

**Comment by dearsina** [comment]
After I wrote the comment, I had one more go at it and managed to set it up, was actually pretty straightforward. Your example template in the 3.0 documentation is very useful. Thanks!

**Comment by chrisgraham** [comment]
This sounds like it is referring to the MicrosoftGraph provider, which does exist. The app you end up with via Microsoft's labyrinth of wizards, tutorials, etc, is a "Azure Active Directory" one.

**Comment by ApacheEx** [comment]
We have PR for it, let's wait for fixes: https://github.com/hybridauth/hybridauth/pull/1197

**Comment by odain-cbd** [comment]
is this issue still up to date? it seems to me it could be close no?
