### ISSUE TITLE
HA 3.0.0 Expecting a non-null oauth_token to continue the authorization flow.

### ISSUE THREAD

**Issue by standus** [hybridauth/hybridauth#552]
When I close Twitter popup window and reopen it again I got error message:
Expecting a non-null oauth_token to continue the authorization flow.
When I open it aggain then it is OK, but after reopen it is the same error.
Soo closing popup windows and reopening it second time is this error.
Same problem with Tumblr provider.

**Comment by stephanedupont** [comment]
This issue is still happening in 3.3.0.

Why has it been closed?

**Comment by ApacheEx** [comment]
@stephanedupont, it was closed since no activite for 5 years. So, if you still receive such errors - create a new issue with details. We will take a look, thx.

**Comment by stephanedupont** [comment]
Will do, thanks. But it's exactly the same issue as this one.
