### ISSUE TITLE
Yahoo documentation

### ISSUE THREAD

**Issue by standus** [hybridauth/hybridauth#554]
In documentation is information for Yahoo Callback.
http://mywebsite.com/path_to_hybridauth/?hauth.done=Yahoo

But at Yahoo App Panel is possible add only domain, without any URI or params.

**Comment by ApacheEx** [comment]
already done in v2.9.3. For more info check the latest [documentation](https://hybridauth.github.io/hybridauth/userguide/IDProvider_info_Yahoo.html).
