### ISSUE TITLE
In TwitchTV Adapter wrong code

### ISSUE THREAD

**Issue by standus** [hybridauth/hybridauth#555]
Next problem with another adapter.
wrong code:
if (! $data->exists('id')) {
            throw new UnexpectedValueException('Provider API returned an unexpected response.');
        }
$userProfile->identifier  = $data->get('id');

must be:
if (! $data->exists('_id')) {
            throw new UnexpectedValueException('Provider API returned an unexpected response.');
        }
$userProfile->identifier  = $data->get('_id');

**Comment by AdwinTrave** [comment]
Please create a Pull Request with the fix. I don't see the code you are referring to in TwitchTV provider.
