### ISSUE TITLE
You must provide a client_id

### ISSUE THREAD

**Issue by standus** [hybridauth/hybridauth#556]
On some providers I receive error message: You must provide a client_id.
When I debug I can see that client_id is already in request.
This is my request:

    [request] => Array
        (
            [uri] => https://login.live.com/oauth20_token.srf
            [method] => POST
            [parameters] => Array
                (
                    [code] => M99fdb16f-bdd1-bed4-8e74-5db1fac7573d
                    [client_id] => myid
                    [client_secret] => mysecret
                    [grant_type] => authorization_code
                    [redirect_uri] => http://www.mydomain.com/login
                )

            [headers] => Array
                (
                    [Accept] => */*
                    [Cache-Control] => max-age=0
                    [Connection] => keep-alive
                    [Expect] => 
                    [Pragma] => 
                    [Content-Type] => application/x-www-form-urlencoded
                )

        )
And response:

    [response] => Array
        (
            [code] => 400
            [headers] => Array
                (
                    [cache_control] => no-store
                    [pragma] => no-cache
                    [content_length] => 113
                    [content_type] => application/json
                    [server] => Microsoft-IIS/8.5
                    [x_wlid_error] => 0x80049D58
                    [x_content_type_options] => nosniff
                    [date] => Wed, 30 Sep 2015 10:39:30 GMT
                    [connection] => close
                )

            [body] => {"error":"invalid_client","error_description":"The provided request must include a 'client_id' input parameter."}
        )

Same problem with Instagram for example. Used HA 3.0.0 remake. After this error are other working adapters with random different errors.

**Comment by adamnguyenit** [comment]
Hello standus, I got the same problem. Can you help me to resolve it? Many thanks.

**Comment by standus** [comment]
Hi,this is my code which works:
namespace Hybridauth\Provider;

use Hybridauth\Adapter\OAuth2;
use Hybridauth\Exception\UnexpectedValueException;
use Hybridauth\Data;
use Hybridauth\User;


/**
 * &grant_type=authorization_code
 */
class WindowsLive extends OAuth2
{
    /**
    * {@inheritdoc}
    */
    public $scope = 'wl.basic wl.emails wl.contacts_emails wl.signin wl.birthday wl.postal_addresses';//wl.emails wl.share
    //Note  Do not include the wl.offline_access scope if you're using the implicit grant flow (response_type=token)
    /**
    * {@inheritdoc}
    */
    protected $apiBaseUrl = 'https://apis.live.net/v5.0/';

    /**
    * {@inheritdoc}
    */
    protected $authorizeUrl = 'https://login.live.com/oauth20_authorize.srf';//https://login.live.com/oauth20_authorize.srf

    /**
    * {@inheritdoc}
    */
    protected $accessTokenUrl = 'https://login.live.com/oauth20_token.srf';//https://login.live.com/oauth20_token.srf


    protected function initialize()
    {
        parent::initialize();
        $this->apiRequestParameters = [
            'Authorization' => 'Bearer ' . $this->token('access_token')
        ];
    }

    /**
    * {@inheritdoc}
    */
    public function getUserProfile()
    {
        $response = $this->apiRequest('me');

        $data = new Data\Collection($response);

        if (! $data->exists('id')) {
            throw new UnexpectedValueException('Provider API returned an unexpected response.');
        }

        $userProfile = new User\Profile();

        $userProfile->identifier    = $data->get('id');
        $userProfile->displayName   = $data->get('name');
        $userProfile->firstName     = $data->get('first_name');
        $userProfile->lastName      = $data->get('last_name');
        $userProfile->gender        = $data->get('gender');
        $userProfile->profileURL    = $data->get('link');
        $userProfile->email         = $data->filter('emails')->get('preferred');
        $userProfile->emailVerified = $data->filter('emails')->get('account');
        $userProfile->birthDay      = $data->get('birth_day');
        $userProfile->birthMonth    = $data->get('birth_month');
        $userProfile->birthYear     = $data->get('birth_year');

        return $userProfile;
    }
}

**Comment by adamnguyenit** [comment]
Thank you a lot.
