### ISSUE TITLE
Youtube - subscribe to a channel

### ISSUE THREAD

**Issue by sraboni** [hybridauth/hybridauth#561]
Hello,
Can anyone please suggest me how to subscribe a user to a channel using Hybridauth PHP api?

Any help will be appreciated.

Thanks,
Sraboni

**Comment by sraboni** [comment]
Hello,
Can anyone please help?
I have added scopes : 
1. https://www.googleapis.com/auth/youtube
2. https://www.googleapis.com/auth/youtube.force-ssl

When I am posting data to OAUTH2 API, it is returning invalid credentials error.
I am sending param array as : 
$params = array(
"kind"	=>	"youtube#subscription",
"part" => "snippet",
 "snippet.resourceId.kind" => "youtube#subscription",
"snippet.resourceId.channelId" => "CHANNEL ID",
	);
and calling the url :https://www.googleapis.com/youtube/v3/subscriptions?part=snippet with post method.

Can you please tell me what I am doing wrong?

*** Please note that I am using HybridAuth PHP edition.

**Comment by sraboni** [comment]
Hello

Anyone please help!!

**Comment by ApacheEx** [comment]
you can use `apiRequest` from v3, all endpoints can be found here: https://developers.google.com/youtube/v3/docs/subscriptions/insert
