### ISSUE TITLE
[Google] problem with some case scope.

### ISSUE THREAD

**Issue by tsecheng** [hybridauth/hybridauth#566]
when scope setting like this "scope"=> "https://www.googleapis.com/auth/plus.profile.emails.read https://www.googleapis.com/auth/userinfo.profile"

google response language locale to language, so i add below code to solve this problem.
if (empty($this->user->profile->language)){
$this->user->profile->language = (property_exists($response, 'language')) ? $response->language : ((property_exists($verified, 'language')) ? $verified->language : "");
}

if you setting like this "scope"=> "https://www.googleapis.com/auth/userinfo.profile"
google response locale, so current code is not problem, but you can't get user email from google.

**Comment by ApacheEx** [comment]
to get an email you have to provide scope: `https://www.googleapis.com/auth/userinfo.email`
