### ISSUE TITLE
[Facebook] not working with https

### ISSUE THREAD

**Issue by Jasper-Grasmaijer** [hybridauth/hybridauth#569]
Hi, first of all thanks for all the work put into this!

For me the facebook login was not working for my Drupal website hosted on Openshift using the [HybridAuth module](https://www.drupal.org/project/hybridauth) with version 2.5.1 of this library.

I found the cause and a solution [here](https://www.drupal.org/node/2413493#comment-10489168):
the method getHttpProtocol() in base_facebook.php (of the HybridAuth library, not the module) was returning 'http', not 'https'.

After changing http to htpps in base_facebook.php I was able to login to my website with facebook.

**Comment by AdwinTrave** [comment]
Note to self: https://www.sammyk.me/upgrading-the-facebook-php-sdk-from-v3-x-to-v5

**Comment by tchalvak** [comment]
Is this still a continuing issue?  Was hoping to run hybridAuth on an ssl site and not sure whether this is going to cause problems for that.

**Comment by xe3tec** [comment]
This is still an issue with 2.14. But you only have to add the s to http to get https and then it worked. Did cost me half a day of finding this though.

**Comment by tchalvak** [comment]
Fair enough, thanks.

**Comment by nazar-pc** [comment]
This is not a problem in HybridAuth, this is rather misconfiguration.
You can force HybridAuth to honour `X-Forwarded-*` headers by specifying option `trustForwarded` for Facebook provider alongside with others, like [here](https://github.com/nazar-pc/CleverStyle-CMS/blob/master/components/modules/HybridAuth/providers.json#L63).

**Comment by tartakxg** [comment]
This doesn't fix problem in MODX CMF 
/core/components/hybridauth/model/hybridauth/lib/resourcesconfig.php.tp
`
			"Facebook" => array ( 
				"enabled" => #FACEBOOK_ADAPTER_STATUS#,
				"keys"    => array ( "id" => "#FACEBOOK_APPLICATION_APP_ID#", "secret" => "#FACEBOOK_APPLICATION_SECRET#" ),
				"trustForwarded" : 1
			),`

**Comment by mln-mln-mln** [comment]
@nazar-pc Thank you, your solution worked perfectly.
