### ISSUE TITLE
Hybridauth not finished...

### ISSUE THREAD

**Issue by EJFJCorp** [hybridauth/hybridauth#579]
What is this partially done project???

Files are all messed, in many folders, when we include one file, we get errors saying things are missing (from othr files, all default providers are in one folder, but none work... The configuration is complex, but when it is done, files are missing... It is just to loose time... Please see standardizations of MediSecure International PSC! You have up to January to finalize this, and uniformize services... Since March 15th, 1996, logins with passwords are forbidden (by EJFJ Universal Justice) as with violence we can get any password, and a password allow any one pretend being someone else! MediSecure International identifies objects facing a screen, objects movements, objects owners (the one who take an object to him buys it at the sentimental value, or if not defined by the owner, and the commercial residual value!). Bill !nternational Technologies PSC allows 20 years of price updates so that all commercial partners can be sure to be totally satisfied with what they did... Any human being is responsible of his acts, and only his acts! Each thing is immediately paid at the most affordable (evolutive price, and all pay the same price for the same service, with 20 years of adaptations (when required!).Anything is exchangeable, nothing can be robbed! 

Human beings need securities, freedom, and opportunities... Google will have to reform systems till January 15th, 2016, to solve disparities and problems, which do not allow respect of fundamentals human beings rights (EJFJ Principles - introduced with the 8th Reform of the Universal Declaration of the Human Rights). Mafias do not want securities, but only the most convenient and affordable thing is legal, accoding to EJFJ Unicity Principle! Simplify things, collaborate with others, and automatize things so that all human beings can only benefit from the most convenient and affordable things... There are lot of wastings (52% up to 89% : http://state.ejfj.org).

Try to definitely solve problems before the EJFJ Penal affairs, there are lot of victims of risks, unconvenient things and lacks... Only the evolutive best is legal...

**Comment by EJFJCorp** [comment]
We need help to authenticate users on http://medstaff.ejfj.org (MedStaff International PSC, your Employement Public Services Company!). We need to instore collaboration, rather than concurrency (stupid wastings) and opponency (creating fights, violence and missunderstandings)...

**Comment by EJFJCorp** [comment]
Identification of users is not the responsability of any single human beings (webmasters), it is not a choice, it is a fundamental right all human beings need to benefit from (MFS:id2004 is taking advantage of unofficial and factice identification systems, MediSecure International PSC made the worlwide reference norm, since March 16th, 1996! We need t do better than this, not let anyone waste any second to do anything worse... SDC++ and SMC++ make this available in second, with aliases and parameters, much smaller than all the different forms witch exist for now, even you cannot propose a secure system for loging in! Assume your responsability, do better to reduce your responsabilities...

**Comment by StorytellerCZ** [comment]
I don't understand even half of what you are rambling about.
HybridAuth is not for medical software it never did make any such claim. Honestly from what little that I know about medical software social login should be one thing to avoid.
HybridAuth is not full user authentication package, it is something you integrate with your existing system.

**Comment by EJFJCorp** [comment]
I do not speak of medical purpose, MediSecure International Technologies
PSC is for everything, even secret personal daten (medical, fiscal,
professional, financial included). There is a reference, everything
unperfect is illegal, and a wasting of time... Your system is like opauth,
but opauth works not well, but better than your hybridauth which is fully
unuseable, lot of bugs, files missing, no reference, lot of documentations,
but nothing functional... Things need to be simple, uniformize it with
opauth!

Emmanuel Jean-François Jotterand
Membre fondateur d'*EJFJ Corporation* <http://goo.gl/LYhqI>
Initiateur du projet *Medical Pack*
Ingénieur ergonomiste en fin de formation
Inventeur multi-domaines
...
*Société de services publics, à conditions particulières
<http://conditions.ejfj-corporation.org/>,*
*État libre, indépendant, à territoire variable, défendeur des nouvelles
normes de protection des individus* (sécurité personnelle
<http://www.ejfj-corporation.org/FR/n-Produits-SecuritePersonnelle.htm>,
sécurité
physique
<http://www.ejfj-corporation.org/FR/n-Produits-SecuritePhysique.htm>, sécurité
mentale <http://www.ejfj-corporation.org/FR/n-Produits-SecuriteMentale.htm>
, sécurité financière
<http://www.ejfj-corporation.org/FR/n-Produits-SecuriteFinanciere.htm>,
sécurité
informative
<http://www.ejfj-corporation.org/FR/n-Produits-SecuriteInformative.htm>,
sécurité législative, sécurité mobile
<http://www.ejfj-corporation.org/FR/n-Produits-SecuriteMobile.htm> et
finalement la sécurité professionnelle
<http://www.ejfj-corporation.org/FR/n-Produits-SecuriteProfessionnelle.htm>
).
Voir les conditions d'*EJFJ Corporation*
<http://conditions.ejfj-corporation.org>, toute intervention est soumise à
condition, que ce soit un mandat exigé par vous pour profiter de notre
aide, ou que ce soit un mandat spontané rendu impératif pour cause de
risques encourus par l'espèce humaine (dès un individu!).

See *EJFJ Corporation*'s Terms <http://terms.ejfj-corporation.org>, any
intervention is conditional, be it a warrant required by you for
benefitting from our assistance, or be it a spontaneous warrant made
imperative by reason of risks incurred by other humans (from one person!).

2015-11-08 22:24 GMT+01:00 Jan Dvorak <notifications@github.com>:
