### ISSUE TITLE
Getting issue during Login in <iframe>

### ISSUE THREAD

**Issue by kumardippu** [hybridauth/hybridauth#584]
Hi , I have successfully integrated the Hybrid Social Auth api.
Problem is that when some one want to create "iframe" of my website to their own website then it creates problem during login.
Is there any solution ?

**Comment by programmersujeet** [comment]
same problem with my integration, Help

**Comment by StorytellerCZ** [comment]
I think this could be cross-origin security issue.

**Comment by ApacheEx** [comment]
seems it's not related to HA. Feel free to fill new issue with all details if you still have this error.
