### ISSUE TITLE
facebook getUserActivity("timeline") error and Twitter api gives error

### ISSUE THREAD

**Issue by miraclesolutions** [hybridauth/hybridauth#585]
Hello there, 
When I use facebook getUserActivity using timeline it gives error like 
"Ooophs, we got an error: User activity stream request failed! Facebook returned an error: OAuthException: (#200) Requires extended permission: read_stream Error code: 0 "

and when I use "me" it returns empty array.

Another issue is when I try to login with twitter as provider it gives error like below

"Undefined index: oauth_token in F:\wamp\www\social\classes\hybridauth\Hybrid\thirdparty\OAuth\OAuth1Client.php on line 85";

" Undefined index: oauth_token_secret in F:\wamp\www\social\classes\hybridauth\Hybrid\thirdparty\OAuth\OAuth1Client.php on line 85"

"Warning: Cannot modify header information - headers already sent by (output started at F:\wamp\www\social\classes\hybridauth\Hybrid\thirdparty\OAuth\OAuth1Client.php:85) in F:\wamp\www\social\classes\hybridauth\Hybrid\Auth.php on line 363"

Anyone help me solve these issue?

**Comment by CNSKnight** [comment]
+1 getting the undefined index auth'ing w/twitter
- HybridAuth v2.7.0
I've got a var_dump at line 54 in Hybrid_Providers_Twitter if interested

**Comment by StorytellerCZ** [comment]
Please check the newest version if the issue still persists.

**Comment by ApacheEx** [comment]
yeah, pls upgrade HA library to the latest stable v2.
