### ISSUE TITLE
twitter and email adress

### ISSUE THREAD

**Issue by PatrickBK** [hybridauth/hybridauth#587]
Hi,

I understand it's possible to get a Twitter users email adress so I requested permission and altered the permissions of my Social login Twitter app to include a users email address.

However, when I sign in with a Twitter account the email address is still not listed.

Am I missing something? I use HA 2.5.

Is there a configuration alteration I have to do in Hybrid Auth?

Sincerely,

Patrick

**Comment by PatrickBK** [comment]
Some searching in the Hybrid Auth code got me this.....

add:
"includeEmail" => true 

in the hybridauth config file, to the Twitter options:-)

So, solved. I might add that the documentation seems to be missing this info or at least, I couldn't find it:-)

**Comment by portalzine** [comment]
You need to request elevated permissions / whitelisting first, before you can get emails from Twitter.
1. https://support.twitter.com/forms/platform
2. Select "I need access to special permissions"
3. Application Name and ID

More info ... https://dev.twitter.com/rest/reference/get/account/verify_credentials

Alex

**Comment by PatrickBK** [comment]
Did that allready:-) and I answered my own question, check it out:-) I coudln't find how to config Hybridauth to actually benefit from the elevated permissions.

Thx for the effort.

Patrick

**Comment by ErAnkurSharma** [comment]
Patrick's solution worked for me as well.
Apply these steps after getting email access permission from twitter dev support.
/public_html/application/third_party/hybridauth/Hybrid/Providers/Twitter.php
Search for method "getUserProfile()" and change "$this->config['includeEmail'] : false" to "$this->config['includeEmail'] : true"

BR
-Ankur

**Comment by nazar-pc** [comment]
@ErAnkurSharma, you should almost NEVER edit source code. Patrick's solution was to add that option to configuration, not source code.

**Comment by ErAnkurSharma** [comment]
@nazar-pc , I completely agree with your point.Thank you for making a notice :) :)
I have edited my comment accordingly.

BR
-Ankur
