### ISSUE TITLE
Digital Ocean Endpoint

### ISSUE THREAD

**Issue by christ0ph3r** [hybridauth/hybridauth#595]
I brought this up on the following commit but felt it would be better in issues section.

https://github.com/hybridauth/hybridauth/commit/3e77cf08eb0413f1b1ab3da46cdf0cc27ff0acdf

Is there good reason v1 is being targeted on the endpoints on line 19-22?

v1 will give errors https://developers.digitalocean.com/documentation/v1/

v2 is the new DO api.

Also I think it may be best delete location as Digital Ocean does not offer that for account endpoint on v2 and as far as I can see it wasn't offered on v1.

```
$this->user->profile->region      = @ $data->account->location;
```

@minorOffense

And thank you for your work and adding DO!

**Comment by christ0ph3r** [comment]
I am incorrect regarding the v1 issue.  The oauth uses v1 while the REST api uses v2.  This confused me.  Sorry about that. :smile: 

However I still think issue with location :earth_asia:  should be discussed.

**Comment by minorOffense** [comment]
Yeah their API and Auth are separate. On two different versions.

The location stuff I'll have a look.

**Comment by christ0ph3r** [comment]
I have taken another look and only location stuff is about droplets.  And I don't think that would work well as its not user related.

**Comment by minorOffense** [comment]
Yup you're right. I'll roll a patch later today for it. Just remove that line all together.
