### ISSUE TITLE
Stack Exchange and Folder Structure

### ISSUE THREAD

**Issue by christ0ph3r** [hybridauth/hybridauth#599]
Stack Exchange recently got intregrated.  Nice work @Shade- .  One thing I noticed is this file is just sitting on its own without being in a folder like all the other additional providers. I do not see any good reason why this is the only provider that should not have a seperate folder.  Is there reason behind this?

https://github.com/hybridauth/hybridauth/commit/36a044d9a89ed4ec7c8ee32c349cfe6d9c102859

**Comment by christ0ph3r** [comment]
And we are missing .php extension :)

**Comment by Shade-** [comment]
Sorry, my fault. It should be added to the relative folder and the .php extension should be added too. Feel free to propose the changes yourself, I'm too busy at the moment.

**Comment by christ0ph3r** [comment]
Will do.  Thanks.  :+1:
