### ISSUE TITLE
Can't Get User Info While Login With Facebook IN Codeigniter Hybridauth

### ISSUE THREAD

**Issue by lavish-tyagi** [hybridauth/hybridauth#601]
I am using Hybridauth  in Codeigniter And Not  able to get data from facebook when i print user $user_profile i get this response

Please Help Me Out I Already Spent Too Many Times Over this

Hybrid_User_Profile Object(
[identifier] => myid 
[webSiteURL] =>
[profileURL] =>
[photoURL] => 
https://graph.facebook.com/myi... 
[displayName] => Myname 
[description] =>
[firstName] => 
[lastName] => 
[gender] =>
[language] => 
[age] => 
[birthDay] => 
[birthMonth] => 
[birthYear] =>
[email] =>
[emailVerified] => 
[phone] =>
[address] => 
[country] => 
[region] => 
[city] =>
[zip] =>
)

**Comment by StorytellerCZ** [comment]
It would be better if you contacted the creator of the HybridAuth plugin in CodeIgniter.

**Comment by StorytellerCZ** [comment]
Check the newest version. This has been probably fixed.
