### ISSUE TITLE
Get Facebook Likes

### ISSUE THREAD

**Issue by leomalaveraG** [hybridauth/hybridauth#602]
Hey I try to get the user likes but I can not.
I'm using user_likes in scope and in the fields using "likes".

Thank you for your help.

**Comment by VladyslavKurmaz** [comment]
@leomalaveraG 
where do you expect to see "likes"? in profile?
or you use custom api call $this->api->api('/me/likes');?

**Comment by leomalaveraG** [comment]
Hey Thanks 
I have solved the problem.
I left the code for those who need something similar.
https://gist.github.com/leomalaveraG/852815848adcb98ce00f

**Comment by leomalaveraG** [comment]
@VladyslavKurmaz thanks now I close issue.
