### ISSUE TITLE
Error From Facebook API

### ISSUE THREAD

**Issue by Kevonia** [hybridauth/hybridauth#603]
Warning
Invalid Scopes: read_stream. This message is only shown to developers. Users of your app will ignore these permissions if present. Please read the documentation for valid permissions at: https://developers.facebook.com/docs/facebook-login/permissions

**Comment by leomalaveraG** [comment]
read_stream is Deprecated Permission
https://developers.facebook.com/docs/facebook-login/permissions#reference-read_stream
Remove read_stream for $public scope in 
Dir:yourapp/Hybrid/providers/facebook.php
or config file.
