### ISSUE TITLE
Twitter auth error

### ISSUE THREAD

**Issue by AlbertoMrFz** [hybridauth/hybridauth#615]
Hi, I have this problemes, but i can't resolve them. I need your help. This is my config file:

"Twitter" => array(
"enabled" => true,
"keys" => array("key" => "KEY", "secret" => "SECRET"),
"includeEmail" => false
),

AND this is the error:
Authentication failed. The user has canceled the authentication or the provider refused the connection.

Original error message: Authentication failed! Twitter returned an error. 401 Unauthorized.

**Comment by VladyslavKurmaz** [comment]
@AlbertoMrFz 
Are you using latest stable version of library?
Did twitter auth work before?
What is the value for "Callback URL" at the twitter app configuration page?

**Comment by AlbertoMrFz** [comment]
Hi @VladyslavKurmaz 
I change the "Callback URL" and it works!
Thank you
