### ISSUE TITLE
Scope for Window Live: wl.basic or wl.signin

### ISSUE THREAD

**Issue by iot4kids** [hybridauth/hybridauth#619]
Looks like Scope value is not transmitted correctly (or not at all) while authorization via Window Live. No matter what public $scope I declare in Live.php, it seems to request everything while authentication.

I'd like to limit Scope to either wl.signin if feasible or at most wl.basic. 

Can someone advice how to make it work?

Ref: https://msdn.microsoft.com/en-us/library/hh243646.aspx

**Comment by mrtuvn** [comment]
same issues and nobody care

**Comment by ApacheEx** [comment]
should work in the latest version v2.9.6-dev. Pls upgrade.
