### ISSUE TITLE
Hybridauth Not pulling email id after facebook authentication

### ISSUE THREAD

**Issue by anver** [hybridauth/hybridauth#621]
The facebook email is not present in getUserProfile() function call
$adapter = $hybridauth->getAdapter( $provider );
$hybridauth_user_profile = $adapter->getUserProfile();

Its shows only ( identifier, photourl and displayname ) The fb api is v2.5

**Comment by nazar-pc** [comment]
You have to specify it in scope: https://developers.facebook.com/docs/facebook-login/permissions
Default scope doesn't include email, but you can request it if necessary.

**Comment by anver** [comment]
I have already done so, so it's not the scope issue.

            $config["providers"]['Facebook']["enabled"] = TRUE;
            $config["providers"]['Facebook']["keys"]["id"] = trim( $webby_settings['fb_app_id'] );
            $config["providers"]['Facebook']["keys"]["secret"] = trim( $webby_settings['fb_app_secret'] );
            $config["providers"]['Facebook']["scope"] = "email, user_about_me, user_birthday, user_hometown, user_website";
            $config["providers"]['Facebook']["display"] = "popup";

**Comment by nazar-pc** [comment]
As user you always have right to reject permissions, for instance, you can allow all permissions except email.
As developer you have to be ready for this. You can either explain that to user and redirect back to Facebook requesting remaining permissions or ask for email in some alternative way.
I've [modified default scope](https://github.com/nazar-pc/CleverStyle-CMS/blob/master/components/modules/HybridAuth/providers.json#L68) for my use case and it works as expected.

The only difference that I'm not using `$config["providers"]['Facebook']["display"] = "popup";`, not sure whether it affects anything fundamentally.

**Comment by ApacheEx** [comment]
since v2.8.0 default scope in HA is: 
```
'email', 'user_about_me', 'user_birthday', 'user_hometown', 'user_location', 'user_website', 'publish_actions', 'read_custom_friendlists'
```

you can also check more info in the latest [documentation](https://hybridauth.github.io/hybridauth/userguide/IDProvider_info_Facebook.html).
p. s. if something will not work, create a new issue or reopen existing one.
