### ISSUE TITLE
HybridAuth install without Composer?

### ISSUE THREAD

**Issue by Mandaricks** [hybridauth/hybridauth#622]
I know it's shameful these days, but my host provider does not have Composer installed, and once asked show no intent on install it. Still, I really need HybridAuth installed for a project of mine. I already spent money, when I had it, on this host for some years in advance. And now I can't just purchase another service.
Is there some step-by-step guide on how to install HybridAuth without the use of Composer? Purely and simply using, let's say, some ftp service and making by hand the rest? I am using (sorry) Windows 10 on my computer, if this information helps.

**Comment by nazar-pc** [comment]
Here is all you need to know: https://github.com/hybridauth/hybridauth/blob/master/composer.json#L24
Just stop asking the same questions over and over. Autoloaders are well  documented and Composer is not essential to get it working.

**Comment by Mandaricks** [comment]
I never asked that before.

**Comment by nazar-pc** [comment]
Just try to search what other people asked even in this repository alone or on StackOverflow. There are a lot of useful answers there. Anyway, just look at line I've pointed to in last message - it will work fine.

**Comment by wheelsandcogs** [comment]
Composer is just a tool to fetch dependencies, not a deployment tool. If you already have your project running locally, then just include the vendors dir in your deploy and you will not need to run composer on your production host.

**Comment by ApacheEx** [comment]
> I know it's shameful these days, but my host provider does not have Composer installed

if you have php installed (I'm sure you have), then you can easily install composer,
just run commands from [here](https://getcomposer.org/download/). Then when the composer is downloaded, just try `php composer.phar install` in your HA dir. Hope it's clear
