### ISSUE TITLE
Why hybridauth not working for facebook new app v2.4

### ISSUE THREAD

**Issue by Kirancloudnix** [hybridauth/hybridauth#623]
Why hybridauth not working for facebook new app v2.4

**Comment by nazar-pc** [comment]
Information provided is not enough to answer you

**Comment by Kirancloudnix** [comment]
I integrated Hybridauth 2.5 years back, and now I facing issue with facebook v2.4 app. It is working with v2.2. Is there an update for v2.4 app?

**Comment by nazar-pc** [comment]
Would be nice to read which exactly "issue" are you facing.
Besides that current version of Hybridauth is 2.6.0, so new issues about version 2.5 is kind of irrelevant. Check if it works for you with 2.6, please.

**Comment by Kirancloudnix** [comment]
If I upgrade the hybridauth to current master version, will it work for facebook new apps?
