### ISSUE TITLE
error code 6: "User profile request failed. Most likely the user is not connected to the provider and he should to authenticate again".

### ISSUE THREAD

**Issue by RiyadKhalifeh** [hybridauth/hybridauth#626]
I try to register users to my website by twitter using hybridauth,I make
an twitter application and set my key and secret in hybridauth config.
When
user click Register With Twitter, the page navigate to twitter website
and ask the user to accept my application, if he accept, twitter returns
him to my callback url here this error apears!!
what is the problem and how can I solve it.
thank you.

$service = $this->hybridauthlib->authenticate($provider);
This is my var_dump($service);

object(Hybrid_Provider_Adapter)#23 (5) { ["id"]=> string(7) "Twitter" ["config"]=> array(2) { ["enabled"]=> bool(true) ["keys"]=> array(2) { ["key"]=> string(25) "myKey" ["secret"]=> string(50) "mySecret" } } ["params"]=> array(1) { ["hauth_return_to"]=> string(59) "http://149.202.96.105/rappelz/index.php/hauth/login/Twitter" } ["wrapper"]=> string(24) "Hybrid_Providers_Twitter" ["adapter"]=> object(Hybrid_Providers_Twitter)#24 (8) { ["request_tokens_raw"]=> NULL ["access_tokens_raw"]=> NULL ["providerId"]=> string(7) "Twitter" ["config"]=> array(2) { ["enabled"]=> bool(true) ["keys"]=> array(2) { ["key"]=> string(25) "my_key" ["secret"]=> string(50) "mySecret" } } ["params"]=> array(1) { ["hauth_return_to"]=> string(59) "http://149.202.96.105/rappelz/index.php/hauth/login/Twitter" } ["endpoint"]=> NULL ["user"]=> object(Hybrid_User)#25 (3) { ["providerId"]=> string(7) "Twitter" ["timestamp"]=> int(1456821905) ["profile"]=> object(Hybrid_User_Profile)#26 (22) { ["identifier"]=> NULL ["webSiteURL"]=> NULL ["profileURL"]=> NULL ["photoURL"]=> NULL ["displayName"]=> NULL ["description"]=> NULL ["firstName"]=> NULL ["lastName"]=> NULL ["gender"]=> NULL ["language"]=> NULL ["age"]=> NULL ["birthDay"]=> NULL ["birthMonth"]=> NULL ["birthYear"]=> NULL ["email"]=> NULL ["emailVerified"]=> NULL ["phone"]=> NULL ["address"]=> NULL ["country"]=> NULL ["region"]=> NULL ["city"]=> NULL ["zip"]=> NULL } } ["api"]=> object(OAuth1Client)#27 (20) { ["api_base_url"]=> string(26) "https://api.twitter.com/1/" ["authorize_url"]=> string(42) "https://api.twitter.com/oauth/authenticate" ["authenticate_url"]=> string(0) "" ["request_token_url"]=> string(43) "https://api.twitter.com/oauth/request_token" ["access_token_url"]=> string(42) "https://api.twitter.com/oauth/access_token" ["request_token_method"]=> string(3) "GET" ["access_token_method"]=> string(3) "GET" ["redirect_uri"]=> string(0) "" ["decode_json"]=> bool(true) ["curl_time_out"]=> int(30) ["curl_connect_time_out"]=> int(30) ["curl_ssl_verifypeer"]=> bool(false) ["curl_auth_header"]=> bool(false) ["curl_useragent"]=> string(77) "OAuth/1 Simple PHP Client v0.1; HybridAuth http://hybridauth.sourceforge.net/" ["curl_proxy"]=> NULL ["http_code"]=> string(0) "" ["http_info"]=> string(0) "" ["sha1_method"]=> object(OAuthSignatureMethod_HMAC_SHA1)#28 (0) { } ["consumer"]=> object(OAuthConsumer)#29 (3) { ["key"]=> string(25) "MyKey" ["secret"]=> string(50) "mYsecret" ["callback_url"]=> NULL } ["token"]=> object(OAuthConsumer)#30 (3) { ["key"]=> string(50) "myKey" ["secret"]=> string(45) "mySecret" ["callback_url"]=> NULL } } } } 

if ($service->isUserConnected())
{
The error occurs here:
$user_profile = $service->getUserProfile();
}

**Comment by RRajnishR** [comment]
I am facing the same problem but in Google authentication. I have enabled both google+ api and contacts api, still stuck at same place.

any pointers to resolve this one?

**Comment by ApacheEx** [comment]
It has to be fixed in v3. There is no plan to fix it in v2 but you are welcome to submit a PR.
