### ISSUE TITLE
Disconnect provider

### ISSUE THREAD

**Issue by kamov** [hybridauth/hybridauth#635]
Is possible to disconnect provider ?
I don't mean logout, but I mean remove the permission that user give?
Or is required that user remove this from facebook, google, etc?

Thanks

**Comment by StorytellerCZ** [comment]
What you are talking about isn't a provider, but a feature. I don't recall there being a specific API call that all providers would share to remove permissions, so the easiest way is to go to Facebook, Google, etc. and remove permissions from there.

**Comment by kamov** [comment]
> What you are talking about isn't a provider, but a feature.

Yes I don't mean a provider, what I mean was "Disconnect a provider"

**Comment by kamov** [comment]
but if you closed this, then how you can find it?

**Comment by dearsina** [comment]
Can this issue / new feature request be re-opened?
