### ISSUE TITLE
Set google scope, user cover

### ISSUE THREAD

**Issue by kamov** [hybridauth/hybridauth#640]
How to setup google "scope" configuration?
with default setting I don't get cover from google.
my setup now is:
"scope"   => "https://www.googleapis.com/auth/userinfo.profile https://www.googleapis.com/auth/userinfo.email", 
thanks!

**Comment by ApacheEx** [comment]
Hi,

no sure if I got your point, but if you do like this:
```
$hybridauth = new Hybrid_Auth($config);
$adapter = $hybridauth->authenticate("Google");
$user_profile = $adapter->getUserProfile();
```
there will be url to user photo: `$user_profile->photoURL`

**Comment by Askaridze** [comment]
https://hybridauth.github.io/hybridauth/userguide/IDProvider_info_Google.html
There is answer

**Comment by ApacheEx** [comment]
I have updated docs, pls check once more.
https://hybridauth.github.io/hybridauth/userguide/IDProvider_info_Google.html
