### ISSUE TITLE
Facebook API Version 2.6 Required

### ISSUE THREAD

**Issue by aymanrb** [hybridauth/hybridauth#644]
I am building an app that requires Facebook pages "fan_count" field to be selected with a bunch of other fields. The API calls works fine but when I run it using HybridAuth I get the following error.

`
    (#12) fan_count field requires version v2.6 or higher
`

Any solution ?

**Comment by christ0ph3r** [comment]
From the changelog https://developers.facebook.com/docs/apps/changelog:

**Changes from v2.5 to v2.6**

Pages

- The likes field on the Page node has been renamed to fan_count


You have 2 options it sounds like.

1.  Target the likes field instead of fan_count

2.  Upgrade to 2.6 or higher

**Comment by StorytellerCZ** [comment]
We should upgrade the provider.Though I'm not sure if I will have the time to do it.

**Comment by StorytellerCZ** [comment]
Updating in v2.8
