### ISSUE TITLE
Add Pinterest login API

### ISSUE THREAD

**Issue by nodeffect** [hybridauth/hybridauth#646]
Are you able to add Pinterest login API to hybridauth ? I can't seem to find it here. Thanks

**Comment by christ0ph3r** [comment]
This was discussed in https://github.com/hybridauth/hybridauth/issues/378 .

There is currently no option for Pinterest.    It would be nice to have.  If you wanted to submit a PR for Pinterest that would be awesome.

**Comment by eduardo-marcolino** [comment]
https://github.com/hybridauth/hybridauth/pull/649

**Comment by eduardo-marcolino** [comment]
#649
