### ISSUE TITLE
Error 400: redirect_uri_mismatch

### ISSUE THREAD

**Issue by Davide88Sr** [hybridauth/hybridauth#648]
Hello i have a problem with google login. My error is "redirect_uri_mismatch". In the API Google i have setting uri_url http://www.mydomain.it/hybridauth/?hauth.done=Google but not function. Help me. thanks.

**Comment by hellboy81** [comment]
I have the same problem

**Comment by ddsky** [comment]
Same here.

**Comment by RRajnishR** [comment]
I am stuck at this problem from last 4 days. Was anyone able to solve it?

**Comment by ApacheEx** [comment]
@RRajnishR,
pls provide more details and verify the following:
1) which version of HA have you used?
2) do you use any additional frameworks?
3) which value of `base_url` in your `config.php`
4) please make sure that you have created Google App properly (https://console.developers.google.com/apis/credentials/oauthclient):
![image](https://user-images.githubusercontent.com/1918108/27030027-5d98ff72-4f73-11e7-98b0-f77a5e9030e4.png)

**Comment by RRajnishR** [comment]
@ApacheEx Hey,
Thanks for your reply, I solved the above problem last night by adding "redirect_uri" => "http://localhost/liveecole_new/hauth/?hauth.done=Google" to the config's array and adding the same link to Authorized Redirect uri.
But once I login and allow the permissions, it returns back to the page from where it started. It is supposed to show me the retrieved profile data.
I am using HA 2.4.0

**Comment by RRajnishR** [comment]
@ApacheEx Hey, I have solved the redirect mismatch problem, but I don't understand how "hauth.done=google" is working and if I use another custom redirect_URI, how should I retrieve the user profile information after allowing the permissions and redirection to the redirect_uri.

**Comment by ApacheEx** [comment]
Hi @RajnishR,
Pls use `http://mywebsite.com/path_to_hybridauth/?hauth_done=Google` as redirection URL for Google App.

😄 Just an example how it should be in your code:

0. let's imagine your **path_to_hybridauth** is `hybridauth/endpoint`, so it means in your Google App, you should have `http://mywebsite.com/hybridauth/endpoint?hauth.done=Google` as **Authorized redirect URIs**
1. once more let's imagine you have a `Google` button (on USER LOGIN page) which leads to `hybridauth/window/Google`.
2. on that page your framework should execute:
```
$hybridauth = new Hybrid_Auth($config);
$adapter = $hybridauth->authenticate("Google"); 
// IF YOU NOT AUTHORIZED, then your will be redirected to URL which is used in Google App as Authorized redirect URIs (see #4).
// AFTER APPROVE PERMISSIONS, you will be back to this place and can finally get user profile.
$profile = $adapter->getUserProfile();
// HERE you can use profile data, you can save it in your DB or put in $_SESSION (up to you and your framework).
// THEN you can redirect the user to whatever page you want.
```
4. after allowing permissions, the Google will redirect to `http://mywebsite.com/hybridauth/endpoint?hauth.done=Google` automatically, and on that page your framework should execute:
```
require_once $PATH_TO_HA_LIBRARY . '/index.php';
```

that's it. Let me know results.

**Comment by RRajnishR** [comment]
@ApacheEx Hi, Thanks again for your reply.
I have changed my endpoint function a little
`function hybridauth_endpoint( $action, $provider ) {
 
		include APPPATH."vendor/hybridauth/hybridauth/hybridauth/Hybrid/Auth.php";
		include APPPATH."vendor/hybridauth/hybridauth/hybridauth/Hybrid/Endpoint.php";

		echo $key = 'hauth_' . $action; // either `hauth_start` or `hauth_done`

		$_REQUEST[ $key ] = $provider; // provider will be something like `facebook` or `google`

		Hybrid_Endpoint::process();

	}`
and to access it I use "http://localhost/project/google_auth/hybridauth_endpoint/done/google" as my redirect uri. Now as soon as app asks for permission and I allow it, it throws this exception:


**exception 'Exception' with message 'User profile request failed! Google returned an error: The Authorization Service has return: invalid_request' in C:\wamp64\www\project\application\vendor\hybridauth\hybridauth\hybridauth\Hybrid\Auth.php:169 Stack trace: #0 C:\wamp64\www\project\application\vendor\hybridauth\hybridauth\hybridauth\Hybrid\Auth.php(55): Hybrid_Auth::initialize(Array) #1 C:\wamp64\www\project\application\controllers\Google_auth.php(38): Hybrid_Auth->__construct(Array) #2 [internal function]: Google_auth->signin_with_hybridauth('google') #3 C:\wamp64\www\project\system\core\CodeIgniter.php(514): call_user_func_array(Array, Array) #4 C:\wamp64\www\project\index.php(315): require_once('C:\\wamp64\\www\\l...') #5 {main}**

Can you tell me if I am doing something wrong?

**Comment by ApacheEx** [comment]
I see in URL `google`, but it should be `Google`.
Then, make sure you use right scopes:
just put it in your config:
```
"scope" => "https://www.googleapis.com/auth/plus.login https://www.googleapis.com/auth/plus.me https://www.googleapis.com/auth/plus.profile.emails.read"
```

show me a bit more code how you get a user profile.

**Comment by RRajnishR** [comment]
`public function signin_with_hybridauth( $provider ) {
		$config = array(
	      "base_url" => base_url('vendor/hybridauth/hybridauth/hybridauth/'),
	      'callback' => 'http://localhost/liveecole_new/google_auth',
	      "providers" => array (
	        "Google" => array (
	          "enabled" => true,
	          "keys"    => array ( "id" => "54564503190-cdqjo8a8pt756jk8jba50min30fcnhbn.apps.googleusercontent.com", "secret" => "0ihSl-El4d8EdOn1QX0Wef_P" ),
	          "redirect_uri" => "http://localhost/liveecole_new/google_auth/hybridauth_endpoint/done/Google",
	          "scope" => "https://www.googleapis.com/auth/plus.login https://www.googleapis.com/auth/plus.me https://www.googleapis.com/auth/plus.profile.emails.read",
	    )));
		include APPPATH."vendor/hybridauth/hybridauth/hybridauth/Hybrid/Auth.php";
		$base_url = 'http://localhost/liveecole_new/google_auth/hybridauth_endpoint';

		try{
			$hybridauth = new Hybrid_Auth( $config );

		// we'll need to tell HybridAuth to use custom endpoint URLs
		$adapter    = $hybridauth->authenticate( $provider, array(
			'login_start' => $base_url . '/start/' . strtolower( $provider ),
			'login_done'  => $base_url . '/done/'  . strtolower( $provider ),
		) );
	 
	    $user_profile = $adapter->getUserProfile();
	    $tokens = $adapter->getAccessToken();
		} catch(Exception $e){
			echo "<br/>".$e;
		}
`
I have used above function to start the authentication process. Please have a look.
P.S: I tried to run it by changing 'google' to 'Google', still the same problem.

**Comment by ApacheEx** [comment]
in your $config - base URL is wrong. You changed a lot in paths, that's also very bad. That's why it doesn't work for you.

This is completely a wrong idea:
```
// we'll need to tell HybridAuth to use custom endpoint URLs
$adapter    = $hybridauth->authenticate( $provider, array(
  'login_start' => $base_url . '/start/' . strtolower( $provider ),
  'login_done'  => $base_url . '/done/'  . strtolower( $provider ),
) );
```

**why not use STANDARD behaviors instead of overriding everything?**

Pls check once more documentation: https://hybridauth.github.io/hybridauth/userguide.html

**Comment by RRajnishR** [comment]
Thanks alot. I was trying to override all the methods to suit my project's structure, anyways I deleted the code and started from scratch. Everything is working fine now.
Many Thanks again.
