### ISSUE TITLE
Yahoo Login Issue.

### ISSUE THREAD

**Issue by nodeffect** [hybridauth/hybridauth#651]
Using the latest version, I'm still getting this error for Yahoo login: "Could not process your request for the document because it would cause an HTTP proxy cycle." It seems that this problem happens a year ago but it still exists today. May I know if you guys solved this problem ? Thanks.

**Comment by christ0ph3r** [comment]
May be a yahoo issue @nodeffect .

https://github.com/timbreitkreutz/omniauth-yahoo/issues/11

**Comment by vinothrajm** [comment]
Hi,
Login with yahoo doesn't work. I'm getting the following error.

exception 'Exception' with message 'User id request failed! Yahoo returned an invalid response: stdClass::__set_state(array( 'error' => stdClass::__set_state(array( '@lang' => 'en-US', '@uri' => 'http://yahoo.com', 'description' => 'Access forbidden for the user as cookie validation failed', 'detail' => 'Access forbidden for the user as cookie validation failed', )), ))' in socialauth/Hybrid/Providers/Yahoo.php:270

Can you please help to resolve the issue.

**Comment by StorytellerCZ** [comment]
Closing in favor of #787.
