### ISSUE TITLE
?hauth.start=Facebook&hauth.time=

### ISSUE THREAD

**Issue by detaildotcom** [hybridauth/hybridauth#654]
Hi,
   When I tried authenticate using both Facebook and Google (from Godaddy Server), URL is re-directed to 
?hauth.start=Facebook&hauth.time=xxxx for Facebook and ?hauth.start=Google&hauth.time=xxx for Google.

But I am able to successfully authenticate for both Facebook and Google from localhost.

Is it an issue with Facebook / Google Setups or bug?
Log file details for Server..

INFO -- 5.66.204.18 -- 2016-06-13T18:37:42+00:00 -- Enter Hybrid_Auth::initialize()
INFO -- 5.66.204.18 -- 2016-06-13T18:37:42+00:00 -- Hybrid_Auth::initialize(). PHP version: 5.4.43
INFO -- 5.66.204.18 -- 2016-06-13T18:37:42+00:00 -- Hybrid_Auth::initialize(). Hybrid_Auth version: 2.6.0
INFO -- 5.66.204.18 -- 2016-06-13T18:37:42+00:00 -- Hybrid_Auth::initialize(). Hybrid_Auth called from: http://website.com/index.php?facebook&sid=b5f978bf615732122fa6581574a56d3b
DEBUG -- 5.66.204.18 -- 2016-06-13T18:37:42+00:00 -- Hybrid_Auth initialize. dump used config:  -- a:8:{s:8:"base_url";s:47:"http://website.com/hybridauth/index.php";s:9:"providers";a:9:{s:6:"OpenID";a:1:{s:7:"enabled";b:1;}s:5:"Yahoo";a:2:{s:7:"enabled";b:1;s:4:"keys";a:2:{s:3:"key";s:0:"";s:6:"secret";s:0:"";}}s:3:"AOL";a:1:{s:7:"enabled";b:1;}s:6:"Google";a:2:{s:7:"enabled";b:1;s:4:"keys";a:2:{s:2:"id";s:72:" xxxxxx";s:6:"secret";s:24:"xxxxx";}}s:8:"Facebook";a:3:{s:7:"enabled";b:1;s:4:"keys";a:2:{s:2:"id";s:16:"xxxx";s:6:"secret";s:32:"xxxx";}s:14:"trustForwarded";b:0;}s:7:"Twitter";a:3:{s:7:"enabled";b:1;s:4:"keys";a:2:{s:3:"key";s:0:"";s:6:"secret";s:0:"";}s:12:"includeEmail";b:0;}s:4:"Live";a:2:{s:7:"enabled";b:1;s:4:"keys";a:2:{s:2:"id";s:0:"";s:6:"secret";s:0:"";}}s:8:"LinkedIn";a:2:{s:7:"enabled";b:1;s:4:"keys";a:2:{s:3:"key";s:0:"";s:6:"secret";s:0:"";}}s:10:"Foursquare";a:2:{s:7:"enabled";b:1;s:4:"keys";a:2:{s:2:"id";s:0:"";s:6:"secret";s:0:"";}}}s:10:"debug_mode";b:1;s:10:"debug_file";s:19:"hybridauth/test.log";s:9:"path_base";s:64:"/home/websiteserver2000/public_html/websitecom/hybridauth/Hybrid/";s:14:"path_libraries";s:75:"/home/websiteserver2000/public_html/websitecom/hybridauth/Hybrid/thirdparty/";s:14:"path_resources";s:74:"/home/websiteserver2000/public_html/websitecom/hybridauth/Hybrid/resources/";s:14:"path_providers";s:74:"/home/websiteserver2000/public_html/websitecom/hybridauth/Hybrid/Providers/";}
DEBUG -- 5.66.204.18 -- 2016-06-13T18:37:42+00:00 -- Hybrid_Auth initialize. dump current session:  -- a:3:{s:38:"hauth_session.facebook.hauth_return_to";s:90:"s:82:"http://website.com/index.php?facebook&sid=b5f978bf615732122fa6581574a56d3b";";s:37:"hauth_session.facebook.hauth_endpoint";s:75:"s:67:"http://website.com/hybridauth/index.php?hauth.done=Facebook";";s:41:"hauth_session.facebook.id_provider_params";s:419:"a:5:{s:15:"hauth_return_to";s:82:"http://website.com/index.php?facebook&sid=b5f978bf615732122fa6581574a56d3b";s:11:"hauth_token";s:32:"xxxxxxx";s:10:"hauth_time";i:1465843003;s:11:"login_start";s:90:"http://website.com/hybridauth/index.php?hauth.start=Facebook&hauth.time=1465843003";s:10:"login_done";s:67:"http://website.com/hybridauth/index.php?hauth.done=Facebook";}";}
INFO -- 5.66.204.18 -- 2016-06-13T18:37:42+00:00 -- Hybrid_Auth initialize: check if any error is stored on the endpoint...
INFO -- 5.66.204.18 -- 2016-06-13T18:37:42+00:00 -- Hybrid_Auth initialize: no error found. initialization succeed.
INFO -- 5.66.204.18 -- 2016-06-13T18:37:42+00:00 -- Enter Hybrid_Auth::authenticate( Facebook )
INFO -- 5.66.204.18 -- 2016-06-13T18:37:42+00:00 -- Hybrid_Auth::authenticate( Facebook ), User not connected to the provider. Try to authenticate..
DEBUG -- 5.66.204.18 -- 2016-06-13T18:37:42+00:00 -- Enter Hybrid_Auth::setup( Facebook ) -- 
DEBUG -- 5.66.204.18 -- 2016-06-13T18:37:42+00:00 -- Hybrid_Auth::setup( Facebook ), no params given. Trying to get the stored for this provider. -- Array
(
    [hauth_return_to] => http://website.com/index.php?facebook&sid=b5f978bf615732122fa6581574a56d3b
    [hauth_token] => xxxxxxx
    [hauth_time] => 1465843003
    [login_start] => http://website.com/hybridauth/index.php?hauth.start=Facebook&hauth.time=1465843003
    [login_done] => http://website.com/hybridauth/index.php?hauth.done=Facebook
)

INFO -- 5.66.204.18 -- 2016-06-13T18:37:42+00:00 -- Enter Hybrid_Provider_Adapter::factory( Facebook )
DEBUG -- 5.66.204.18 -- 2016-06-13T18:37:42+00:00 -- Hybrid_Provider_Model::__construct( Facebook ) initialized. dump current adapter instance:  -- O:25:"Hybrid_Providers_Facebook":8:{s:5:"scope";s:121:"email, user_about_me, user_birthday, user_hometown, user_location, user_website, publish_actions, read_custom_friendlists";s:3:"api";O:8:"Facebook":11:{s:18:" * sharedSessionID";N;s:11:" * response";N;s:8:" * appId";s:16:"xxxxxxx";s:12:" * appSecret";s:32:"xxxxxxx";s:7:" * user";i:0;s:16:" * signedRequest";N;s:8:" * state";N;s:14:" * accessToken";s:49:"xxxxxxx|xxxxxxx";s:20:" * fileUploadSupport";b:0;s:17:" * trustForwarded";b:0;s:21:" * allowSignedRequest";b:1;}s:10:"providerId";s:8:"Facebook";s:6:"config";a:3:{s:7:"enabled";b:1;s:4:"keys";a:2:{s:2:"id";s:16:"xxxxxxx";s:6:"secret";s:32:"xxxxxxx";}s:14:"trustForwarded";b:0;}s:6:"params";a:5:{s:15:"hauth_return_to";s:82:"http://website.com/index.php?facebook&sid=b5f978bf615732122fa6581574a56d3b";s:11:"hauth_token";s:32:"xxxxxxx";s:10:"hauth_time";i:1465843003;s:11:"login_start";s:90:"http://website.com/hybridauth/index.php?hauth.start=Facebook&hauth.time=1465843003";s:10:"login_done";s:67:"http://website.com/hybridauth/index.php?hauth.done=Facebook";}s:8:"endpoint";s:67:"http://website.com/hybridauth/index.php?hauth.done=Facebook";s:4:"user";O:11:"Hybrid_User":3:{s:10:"providerId";s:8:"Facebook";s:9:"timestamp";i:1465843062;s:7:"profile";O:19:"Hybrid_User_Profile":22:{s:10:"identifier";N;s:10:"webSiteURL";N;s:10:"profileURL";N;s:8:"photoURL";N;s:11:"displayName";N;s:11:"description";N;s:9:"firstName";N;s:8:"lastName";N;s:6:"gender";N;s:8:"language";N;s:3:"age";N;s:8:"birthDay";N;s:10:"birthMonth";N;s:9:"birthYear";N;s:5:"email";N;s:13:"emailVerified";N;s:5:"phone";N;s:7:"address";N;s:7:"country";N;s:6:"region";N;s:4:"city";N;s:3:"zip";N;}}s:10:"compressed";b:0;}
INFO -- 5.66.204.18 -- 2016-06-13T18:37:42+00:00 -- Enter Hybrid_Provider_Adapter::login( Facebook ) 
INFO -- 5.66.204.18 -- 2016-06-13T18:37:42+00:00 -- Enter [Facebook]::logout()
DEBUG -- 5.66.204.18 -- 2016-06-13T18:37:42+00:00 -- Hybrid_Provider_Adapter::login( Facebook ), redirect the user to login_start URL. -- 
INFO -- 5.66.204.18 -- 2016-06-13T18:37:42+00:00 -- Enter Hybrid_Auth::redirect( http://website.com/hybridauth/index.php?hauth.start=Facebook&hauth.time=1465843062, PHP )
INFO -- 5.66.204.18 -- 2016-06-13T18:37:42+00:00 -- Hello
INFO -- 5.66.204.18 -- 2016-06-13T18:37:42+00:00 -- Really Done
INFO -- 5.66.204.18 -- 2016-06-13T18:37:48+00:00 -- Enter Hybrid_Auth::initialize()
INFO -- 5.66.204.18 -- 2016-06-13T18:37:48+00:00 -- Hybrid_Auth::initialize(). PHP version: 5.4.43
INFO -- 5.66.204.18 -- 2016-06-13T18:37:48+00:00 -- Hybrid_Auth::initialize(). Hybrid_Auth version: 2.6.0
INFO -- 5.66.204.18 -- 2016-06-13T18:37:48+00:00 -- Hybrid_Auth::initialize(). Hybrid_Auth called from: http://website.com/index.php?facebook&sid=b5f978bf615732122fa6581574a56d3b
DEBUG -- 5.66.204.18 -- 2016-06-13T18:37:48+00:00 -- Hybrid_Auth initialize. dump used config:  -- a:8:{s:8:"base_url";s:47:"http://website.com/hybridauth/index.php";s:9:"providers";a:9:{s:6:"OpenID";a:1:{s:7:"enabled";b:1;}s:5:"Yahoo";a:2:{s:7:"enabled";b:1;s:4:"keys";a:2:{s:3:"key";s:0:"";s:6:"secret";s:0:"";}}s:3:"AOL";a:1:{s:7:"enabled";b:1;}s:6:"Google";a:2:{s:7:"enabled";b:1;s:4:"keys";a:2:{s:2:"id";s:72:" xxxxx";s:6:"secret";s:24:"xxxxxxx";}}s:8:"Facebook";a:3:{s:7:"enabled";b:1;s:4:"keys";a:2:{s:2:"id";s:16:"xxxxxxx";s:6:"secret";s:32:"xxxxxxx";}s:14:"trustForwarded";b:0;}s:7:"Twitter";a:3:{s:7:"enabled";b:1;s:4:"keys";a:2:{s:3:"key";s:0:"";s:6:"secret";s:0:"";}s:12:"includeEmail";b:0;}s:4:"Live";a:2:{s:7:"enabled";b:1;s:4:"keys";a:2:{s:2:"id";s:0:"";s:6:"secret";s:0:"";}}s:8:"LinkedIn";a:2:{s:7:"enabled";b:1;s:4:"keys";a:2:{s:3:"key";s:0:"";s:6:"secret";s:0:"";}}s:10:"Foursquare";a:2:{s:7:"enabled";b:1;s:4:"keys";a:2:{s:2:"id";s:0:"";s:6:"secret";s:0:"";}}}s:10:"debug_mode";b:1;s:10:"debug_file";s:19:"hybridauth/test.log";s:9:"path_base";s:64:"/home/websiteserver2000/public_html/websitecom/hybridauth/Hybrid/";s:14:"path_libraries";s:75:"/home/websiteserver2000/public_html/websitecom/hybridauth/Hybrid/thirdparty/";s:14:"path_resources";s:74:"/home/websiteserver2000/public_html/websitecom/hybridauth/Hybrid/resources/";s:14:"path_providers";s:74:"/home/websiteserver2000/public_html/websitecom/hybridauth/Hybrid/Providers/";}
DEBUG -- 5.66.204.18 -- 2016-06-13T18:37:48+00:00 -- Hybrid_Auth initialize. dump current session:  -- a:3:{s:38:"hauth_session.facebook.hauth_return_to";s:90:"s:82:"http://website.com/index.php?facebook&sid=b5f978bf615732122fa6581574a56d3b";";s:37:"hauth_session.facebook.hauth_endpoint";s:75:"s:67:"http://website.com/hybridauth/index.php?hauth.done=Facebook";";s:41:"hauth_session.facebook.id_provider_params";s:419:"a:5:{s:15:"hauth_return_to";s:82:"http://website.com/index.php?facebook&sid=b5f978bf615732122fa6581574a56d3b";s:11:"hauth_token";s:32:"xxxxxxx";s:10:"hauth_time";i:1465843062;s:11:"login_start";s:90:"http://website.com/hybridauth/index.php?hauth.start=Facebook&hauth.time=1465843062";s:10:"login_done";s:67:"http://website.com/hybridauth/index.php?hauth.done=Facebook";}";}
INFO -- 5.66.204.18 -- 2016-06-13T18:37:48+00:00 -- Hybrid_Auth initialize: check if any error is stored on the endpoint...
INFO -- 5.66.204.18 -- 2016-06-13T18:37:48+00:00 -- Hybrid_Auth initialize: no error found. initialization succeed.
INFO -- 5.66.204.18 -- 2016-06-13T18:37:48+00:00 -- Enter Hybrid_Auth::authenticate( Facebook )
INFO -- 5.66.204.18 -- 2016-06-13T18:37:48+00:00 -- Hybrid_Auth::authenticate( Facebook ), User not connected to the provider. Try to authenticate..
DEBUG -- 5.66.204.18 -- 2016-06-13T18:37:48+00:00 -- Enter Hybrid_Auth::setup( Facebook ) -- 
DEBUG -- 5.66.204.18 -- 2016-06-13T18:37:48+00:00 -- Hybrid_Auth::setup( Facebook ), no params given. Trying to get the stored for this provider. -- Array
(
    [hauth_return_to] => http://website.com/index.php?facebook&sid=b5f978bf615732122fa6581574a56d3b
    [hauth_token] => xxxxxxx
    [hauth_time] => 1465843062
    [login_start] => http://website.com/hybridauth/index.php?hauth.start=Facebook&hauth.time=1465843062
    [login_done] => http://website.com/hybridauth/index.php?hauth.done=Facebook
)

INFO -- 5.66.204.18 -- 2016-06-13T18:37:48+00:00 -- Enter Hybrid_Provider_Adapter::factory( Facebook )
DEBUG -- 5.66.204.18 -- 2016-06-13T18:37:48+00:00 -- Hybrid_Provider_Model::__construct( Facebook ) initialized. dump current adapter instance:  -- O:25:"Hybrid_Providers_Facebook":8:{s:5:"scope";s:121:"email, user_about_me, user_birthday, user_hometown, user_location, user_website, publish_actions, read_custom_friendlists";s:3:"api";O:8:"Facebook":11:{s:18:" * sharedSessionID";N;s:11:" * response";N;s:8:" * appId";s:16:"xxxxxxx";s:12:" * appSecret";s:32:"xxxxxxx";s:7:" * user";i:0;s:16:" * signedRequest";N;s:8:" * state";N;s:14:" * accessToken";s:49:"xxxxxxx|xxxxxxx";s:20:" * fileUploadSupport";b:0;s:17:" * trustForwarded";b:0;s:21:" * allowSignedRequest";b:1;}s:10:"providerId";s:8:"Facebook";s:6:"config";a:3:{s:7:"enabled";b:1;s:4:"keys";a:2:{s:2:"id";s:16:"xxxxxxx";s:6:"secret";s:32:"xxxxxxx";}s:14:"trustForwarded";b:0;}s:6:"params";a:5:{s:15:"hauth_return_to";s:82:"http://website.com/index.php?facebook&sid=b5f978bf615732122fa6581574a56d3b";s:11:"hauth_token";s:32:"xxxxxxx";s:10:"hauth_time";i:1465843062;s:11:"login_start";s:90:"http://website.com/hybridauth/index.php?hauth.start=Facebook&hauth.time=1465843062";s:10:"login_done";s:67:"http://website.com/hybridauth/index.php?hauth.done=Facebook";}s:8:"endpoint";s:67:"http://website.com/hybridauth/index.php?hauth.done=Facebook";s:4:"user";O:11:"Hybrid_User":3:{s:10:"providerId";s:8:"Facebook";s:9:"timestamp";i:1465843068;s:7:"profile";O:19:"Hybrid_User_Profile":22:{s:10:"identifier";N;s:10:"webSiteURL";N;s:10:"profileURL";N;s:8:"photoURL";N;s:11:"displayName";N;s:11:"description";N;s:9:"firstName";N;s:8:"lastName";N;s:6:"gender";N;s:8:"language";N;s:3:"age";N;s:8:"birthDay";N;s:10:"birthMonth";N;s:9:"birthYear";N;s:5:"email";N;s:13:"emailVerified";N;s:5:"phone";N;s:7:"address";N;s:7:"country";N;s:6:"region";N;s:4:"city";N;s:3:"zip";N;}}s:10:"compressed";b:0;}
INFO -- 5.66.204.18 -- 2016-06-13T18:37:48+00:00 -- Enter Hybrid_Provider_Adapter::login( Facebook ) 
INFO -- 5.66.204.18 -- 2016-06-13T18:37:48+00:00 -- Enter [Facebook]::logout()
DEBUG -- 5.66.204.18 -- 2016-06-13T18:37:48+00:00 -- Hybrid_Provider_Adapter::login( Facebook ), redirect the user to login_start URL. -- 
INFO -- 5.66.204.18 -- 2016-06-13T18:37:48+00:00 -- Enter Hybrid_Auth::redirect( http://website.com/hybridauth/index.php?hauth.start=Facebook&hauth.time=1465843068, PHP )

**Comment by papakay** [comment]
Please i'm having similar issue on Digital ocean with php7.0.

It works fine on localhost. Please how can i resolve this issue?

Thank you.

**Comment by hellboy81** [comment]
How can you resolved this problem?

**Comment by himanshu208** [comment]
Hi
I have same problem did any one got  any solution to resolve this??

**Comment by Neticx** [comment]
what the solution? i didnt found the solution but the issues has been closed

**Comment by ApacheEx** [comment]
Yes it was closed, because works well and in your case you have wrong configuration or so. You didn't provide any details (version, code, logs, etc). I'd recommend to check documentation once more.

**Comment by CT-NetService** [comment]
What's the solution for this issue? Latest version 2 and running on PHP 5.6 and Nginx.
Exact same issue as the OP.

**Comment by CT-NetService** [comment]
My log:
DEBUG -- 82.72.13.xxx -- 2018-05-27T21:43:28+00:00 -- Hybrid_Auth initialize. dump current session:  --
INFO -- 82.72.13.xxx -- 2018-05-27T21:43:28+00:00 -- Hybrid_Auth initialize: check if any error is stored on the endpoint...
INFO -- 82.72.13.xxx -- 2018-05-27T21:43:28+00:00 -- Hybrid_Auth initialize: no error found. initialization succeed.
INFO -- 82.72.13.xxx -- 2018-05-27T21:43:28+00:00 -- Enter Hybrid_Auth::authenticate( facebook )
INFO -- 82.72.13.xxx -- 2018-05-27T21:43:28+00:00 -- Hybrid_Auth::authenticate( facebook ), User not connected to the provider. Try to authenticate..
DEBUG -- 82.72.13.xxx -- 2018-05-27T21:43:28+00:00 -- Enter Hybrid_Auth::setup( facebook ) --
DEBUG -- 82.72.13.xxx -- 2018-05-27T21:43:28+00:00 -- Hybrid_Auth::setup( facebook ), no params given. Trying to get the stored for this provider. --
INFO -- 82.72.13.xxx -- 2018-05-27T21:43:28+00:00 -- Hybrid_Auth::setup( facebook ), no stored params found for this provider. Initialize a new one for new session
DEBUG -- 82.72.13.xxx -- 2018-05-27T21:43:28+00:00 -- Hybrid_Auth::setup( facebook ). HybridAuth Callback URL set to:  -- https://subdomain.domain.com/user/index.php?provider=facebook
INFO -- 82.72.13.xxx -- 2018-05-27T21:43:28+00:00 -- Enter Hybrid_Provider_Adapter::factory( facebook )
DEBUG -- 82.72.13.xxx -- 2018-05-27T21:43:28+00:00 -- Hybrid_Provider_Model::__construct( Facebook ) initialized. dump current adapter instance:  -- O:25:"Hybrid_Providers_Facebook":9:{s:5:"scope";a:3:{i:0;s:5:"email";i:1;s:13:"user_birthday";i:2;s:13:"user_hometown";}s:3:"api";O:17:"Facebook\Facebook":9:{s:6:"*app";C:20:"Facebook\FacebookApp":48:{183307875623441|49db17e6cf28cc9e43a97d5d233ebbae}s:9:"*client";O:23:"Facebook\FacebookClient":2:{s:17:"*enableBetaMode";b:0;s:20:"*httpClientHandler";O:43:"Facebook\HttpClients\FacebookCurlHttpClient":4:{s:19:"*curlErrorMessage";s:0:"";s:16:"*curlErrorCode";i:0;s:14:"*rawResponse";N;s:15:"*facebookCurl";O:33:"Facebook\HttpClients\FacebookCurl":1:{s:7:"*curl";N;}}}s:15:"*oAuth2Client";N;s:22:"*urlDetectionHandler";O:40:"Facebook\Url\FacebookUrlDetectionHandler":0:{}s:30:"*pseudoRandomStringGenerator";O:61:"Facebook\PseudoRandomString\McryptPseudoRandomStringGenerator":0:{}s:21:"*defaultAccessToken";N;s:22:"*defaultGraphVersion";s:4:"v2.8";s:24:"*persistentDataHandler";O:59:"Facebook\PersistentData\FacebookMemoryPersistentDataHandler":1:{s:14:"*sessionData";a:0:{}}s:15:"*lastResponse";N;}s:11:"useSafeUrls";b:1;s:10:"providerId";s:8:"Facebook";s:6:"config";a:4:{s:7:"enabled";b:1;s:4:"keys";a:2:{s:2:"id";s:15:"183307875623441";s:6:"secret";s:32:"49db17e6cf28cc9e43a97d5d233ebbae";}s:5:"scope";s:35:"email, user_birthday, user_hometown";s:14:"trustForwarded";b:0;}s:6:"params";a:1:{s:15:"hauth_return_to";s:60:"https://subdomain.domain.com/user/index.php?provider=facebook";}s:8:"endpoint";N;s:4:"user";O:11:"Hybrid_User":3:{s:10:"providerId";s:8:"Facebook";s:9:"timestamp";i:1527457408;s:7:"profile";O:19:"Hybrid_User_Profile":24:{s:10:"identifier";N;s:10:"webSiteURL";N;s:10:"profileURL";N;s:8:"photoURL";N;s:11:"displayName";N;s:11:"description";N;s:9:"firstName";N;s:8:"lastName";N;s:6:"gender";N;s:8:"language";N;s:3:"age";N;s:8:"birthDay";N;s:10:"birthMonth";N;s:9:"birthYear";N;s:5:"email";N;s:13:"emailVerified";N;s:5:"phone";N;s:7:"address";N;s:7:"country";N;s:6:"region";N;s:4:"city";N;s:3:"zip";N;s:9:"job_title";N;s:17:"organization_name";N;}}s:10:"compressed";b:0;}

INFO -- 82.72.13.xxx -- 2018-05-27T21:43:28+00:00 -- Enter Hybrid_Provider_Adapter::login( Facebook )
INFO -- 82.72.13.xxx -- 2018-05-27T21:43:28+00:00 -- Enter [Facebook]::logout()
DEBUG -- 82.72.13.xxx -- 2018-05-27T21:43:28+00:00 -- Hybrid_Provider_Adapter::login( Facebook ), redirect the user to login_start URL. --
INFO -- 82.72.13.xxx -- 2018-05-27T21:43:28+00:00 -- Enter Hybrid_Auth::redirect( https://subdomain.domain.com/assets/functions/hybridauth/?hauth.start=Facebook&hauth.time=1527457408, PHP )

**Comment by ApacheEx** [comment]
Guys, nobody will help you on closed issue.
