### ISSUE TITLE
Branch 3.0.0-Remake not updated for almost a year

### ISSUE THREAD

**Issue by JeSuisAlrick** [hybridauth/hybridauth#660]
Hi,

There doesn't seem to be a roadmap for version 3.0.0-Remake and the branch has not being updated in awhile. Is it okay to use that branch or stick to the main one (currently at version 2.7.0)?

**Comment by nicolaiskogheim** [comment]
I'm sticking with 2.7. Just got it working with Google auth.

I tried 3.0.0, but because of #200, caused by https://github.com/hybridauth/hybridauth/blob/3.0.0/src/Hybridauth/Endpoint.php#L120, that was a no-go.

**Comment by JeSuisAlrick** [comment]
Well, 3.0.0-Remake "was" a work-in-progress that seems to have stopped, but I did get it to work with my application. I've been making changes and fixing bugs in this fork https://github.com/KingstonCloudOrg/hybridauth.

The library is good--it just needs some TLC.

**Comment by nicolaiskogheim** [comment]
Yes, it's too bad that good projects die out. Glad to hear you got it working.

We just discovered laravel/socialite, and since we are using laravel, and socialite looks very easy to work with, we switched to that.

**Comment by StorytellerCZ** [comment]
If you guys are fixing things, please submit PR back so that we can incorporate those for everyone. Thanks!

**Comment by JeSuisAlrick** [comment]
Will do.
