### ISSUE TITLE
Support for oauth bearer token

### ISSUE THREAD

**Issue by inquam** [hybridauth/hybridauth#662]
A lot of oauth providers add a bearer token when signed in. The current oauth client don't seem to support this. I have seen several client classes online that has support for this and some "providers" on Hybrid Auth where this has been added for the specific provider by extending the existing oauth clinet class and injecting the bearer token in different ways. Would it not make sense to add support for this to the main oauth client class itself?

**Comment by inquam** [comment]
How is 3.0 coming along? Seems like development has stalled a bit? Why not enable this for the 2.x version? Many providers use custom oauth clients to make this work at the moment or other hacks.

**Comment by StorytellerCZ** [comment]
Feel free to submit a PR with this.

**Comment by miled** [comment]
It's done in v3.
