### ISSUE TITLE
Error hauth.start and hauth.time (Don't use it)

### ISSUE THREAD

**Issue by airtonjr** [hybridauth/hybridauth#664]
No code. No problem. Right?

**Comment by avallac** [comment]
Check. What is the problem?

**Comment by airtonjr** [comment]
@avallac The proble is when I click to login with facebook or google it send me to the index page with the address that I put above. It should check if I was logged and if not open google or facebook to procced with the login proccess and this is not happening.

**Comment by avallac** [comment]
Your code is horrible. Check $_SESSION before create instance of Hybrid_Auth.

**Comment by airtonjr** [comment]
@avallac It is the code that I found as an example for the Hybrid. If it is crappy, sorry, I can change it in the Hybrid website.
