### ISSUE TITLE
Facebook Graph API 2.1 update

### ISSUE THREAD

**Issue by giorgio79** [hybridauth/hybridauth#665]
Received a warning on FB

XYZ has been making recent API calls to Graph API v2.0, which will reach the end of the 2-year deprecation window on Monday, August 8, 2016. Please migrate all calls to v2.1 or higher in order to avoid potential broken experiences.

**Comment by StorytellerCZ** [comment]
Looking at the issue, the reason why we haven't upgraded already is due to the fact that we are using the Facebook SDK v3.2.3. The newest is already two major releases ahead. They also started from scratch in v4. So on our side that requires a complete rework.

**Comment by egyptianbman** [comment]
According to [Facebook's website](https://developers.facebook.com/docs/apps/changelog), version 2.1 will no longer be available after October 30, 2016. Are there plans to migrate off of version 2.1 by then?

**Comment by StorytellerCZ** [comment]
If anyone want to take this on, that would be great. Sadly I don't have the resources to do so in the near future.

**Comment by annuh** [comment]
I will try to update the Facebook provider this week. I'll keep you posted.

**Comment by sleepndevelop** [comment]
Hi annuh, thank you for your update. 
But i can't get it to work.
I have 
- downloaded the hybridauth-master zip from your annuh/hybridauth repo
- copied the contents of hybridauth-master into the proper place within my project
- cd to that directory 
- run 'composer install' with success, it correctly downloaded the fb php graph sdk 5.4.1 etc.

But when i try doing a facebook login on the site, it says
Fatal error: Class 'Facebook\Facebook' not found in C:\xampp183\htdocs\savebybooking\protected\modules\user\vendors\hybridauth\Hybrid\Providers\Facebook.php on line 56

Am i supposed to manyally modify the Providers\Facebook.php source? I thought everything should work as-is

**Comment by annuh** [comment]
@sleepndevelop Thanks for testing my fork.

Do manually load the class files in your php files? If you use [Composer autoloading](https://getcomposer.org/doc/01-basic-usage.md#autoloading) all the required class files should be included automatically.

If you include the following line at the top of your php script, the Facebook class should be loaded automatically, since it is included in the autload.php file that Composer created.

`require __DIR__ . '/vendor/autoload.php'`
You may need to change the path to the correct location of the autoload.php file.

**Comment by pbscreativeben** [comment]
Hello, 

I get this PHP warning on the new code inside Provider_Adapter:

Warning: property_exists() expects parameter 2 to be string, object given in /mnt/host/boatshed/socialsignin/hybridauth/Hybrid/Provider_Adapter.php on line 168

Not sure yet if this is relevant but currently its failing for me after Facebook returns the user back to my site with the message:

Facebook Graph returned an error: Error validating verification code. Please make sure your redirect_uri is identical to the one you used in the OAuth dialog request

**Comment by annuh** [comment]
@pbscreativeben It looks like you have outdated code. You can clone the latest version from https://github.com/annuh/hybridauth.

This should fix both your problems. If the problem still occurs, could you give the redirect_uri that you entered in the Facebook app? It should look like `http://mywebsite.com/path_to_hybridauth/?hauth_done=Facebook`

**Comment by pbscreativeben** [comment]
@annuh - it worked!! Thank you so much for responding and for writing the code in the first place! :-)

**Comment by hellboy81** [comment]
I have set at `developers.facebook.com` in `Products` ->  `Facebook Login` -> `Client OAuth Settings` -> `Valid OAuth redirect URIs` as follows:

````
http://dev.mysite.com/.../vendor/hybridauth/hybridauth/hybridauth/index.php?hauth_done=Facebook
````

Should I also provide `redirect_uri` as Facebook provider config  parameter?

**Comment by annuh** [comment]
@hellboy81 No, that is not needed. You only need the hauth_done parameter.
