### ISSUE TITLE
Facebook Graph API upgrade

### ISSUE THREAD

**Issue by tatocaster** [hybridauth/hybridauth#666]
Hello guys!
I have a question. Does HybridAuth v2.6 solves Facebook API upgrade problem? I got an email from Facebook
`{App} has been making recent API calls to Graph API v2.0, which will reach the end of the 2-year deprecation window on Monday, August 8, 2016. Please migrate all calls to v2.1 or higher in order to avoid potential broken experiences.`

 I use Hybridauth v.2.4 right now.
thanks in advance.

**Comment by StorytellerCZ** [comment]
Duplicate of #665
