### ISSUE TITLE
Facebook SDK v3.2.3 should be documented here as #DEPRICATED

### ISSUE THREAD

**Issue by CNSKnight** [hybridauth/hybridauth#674]

**Comment by Shade-** [comment]
HybridAuth's Facebook SDK is not deprecated, read #280.

TL;DR: Facebook pushes out new SDK versions too fast to maintain them, and they cut out old PHP version programatically. While this is ideally a great way to stimulate devs to update their code to use the latest technology available, many servers still do not support newer PHP versions and neither does HybridAuth at the current state. HybridAuth is using a modified v3.2.3 Facebook SDK which **works** fine as it uses the new API endpoints while maintaining old PHP versions compatibility.

**Comment by StorytellerCZ** [comment]
Facebook provider updated for v2.8
