### ISSUE TITLE
OAuth2Client should correctly handle token error response

### ISSUE THREAD

**Issue by lukos** [hybridauth/hybridauth#676]
The code to handle an error response is incorrect. After checking for whether there is no response or no access token, it then raises an exception and accesses $response->error without checking this property even exists. If there is no response or it is not correctly formed, this causes a crash which is logged in the PHP error log.

It should either check for $response->error before throwing or simply only throw the error message.

**Comment by ragulka** [comment]
It would be even better if providers could parse the error response and return the error message, since the error property may be differently named across providers.

**Comment by vmtv** [comment]
diff --git a/sites/all/libraries/hybridauth/hybridauth/Hybrid/thirdparty/OAuth/OAuth2Client.php b/sites/all/libraries/hybridauth/hybridauth/Hybrid/thirdparty/OAuth/OAuth2Client.php
index c9bc769..b76f58c 100644
--- a/sites/all/libraries/hybridauth/hybridauth/Hybrid/thirdparty/OAuth/OAuth2Client.php
+++ b/sites/all/libraries/hybridauth/hybridauth/Hybrid/thirdparty/OAuth/OAuth2Client.php
@@ -233,14 +233,14 @@
 
     if( $type == "POST" ){
       curl_setopt($ch, CURLOPT_POST, 1);
-      if($params) curl_setopt( $ch, CURLOPT_POSTFIELDS, $params );
+      if($params) curl_setopt( $ch, CURLOPT_POSTFIELDS, http_build_query($params, '', '&') );
     }
     if( $type == "DELETE" ){
         curl_setopt($ch, CURLOPT_CUSTOMREQUEST, "DELETE");
     }
     if( $type == "PATCH" ){
       curl_setopt($ch, CURLOPT_POST, 1);
-      if($params) curl_setopt( $ch, CURLOPT_POSTFIELDS, $params );
+      if($params) curl_setopt( $ch, CURLOPT_POSTFIELDS, http_build_query($params, '', '&') );
       curl_setopt($ch, CURLOPT_CUSTOMREQUEST, "PATCH");
     }
     $response = curl_exec($ch);

**Comment by StorytellerCZ** [comment]
@vmtv Please submit a proper pull request.

**Comment by ApacheEx** [comment]
this is already fixed in v3. Currently, there is no plan to fix it in v2 but you are welcome to submit a PR.
