### ISSUE TITLE
New extension to include HybridAuth in CMS Made Simple V2 X

### ISSUE THREAD

**Issue by master3395** [hybridauth/hybridauth#677]
Hello.
I've noticed that the cmsms module doesn't work on version later than 1x. It isn't supported on V2.X
I'm running the latest version 2.1.5

**Comment by StorytellerCZ** [comment]
Create an issue on the plugin repo: https://github.com/ImpetusGames/cms-oauth
If the author is willing they might fix that. In the meantime, I will specify in the plugins page that it is for v1.
