### ISSUE TITLE
Enable additional provider is complicated additional step

### ISSUE THREAD

**Issue by aight8** [hybridauth/hybridauth#678]
To enable additional provider you have to copy those in the Provider folder. This copying in the composers vendor folder is not nice. Is there not a better solution?

**Comment by ragulka** [comment]
It should also be possible by following the instructions here: http://hybridauth.sourceforge.net/userguide/tuts/specific-provider-wrapper.html. However, this does not work for all providers, as described in #371

**Comment by StorytellerCZ** [comment]
This library predates composer, so this was not taken into account in the original design.
