### ISSUE TITLE
PayPal live (non-sandbox) mode not usable?

### ISSUE THREAD

**Issue by ragulka** [hybridauth/hybridauth#681]
PayPal provider class has a property `sandbox`, which is set to `true`. (https://github.com/hybridauth/hybridauth/blob/master/additional-providers/hybridauth-paypal/Providers/Paypal.php#L25)

However, I don't see how this can be changed without actually changing it in the source code. It would need to be set to `false` programmatically before authentication, so that if we use a live (non-sandbox) app, we're redirected to the correct PayPal URL.

How can we do it?

**Comment by rnagulapalle** [comment]
We have same issue and even if I change that value to true and it still going to sandbox URLs. Any thing else we are missing? Would appreciate your help!

**Comment by ApacheEx** [comment]
it's fixed in #857, so now you can ON / OFF sandbox mode in your config 🌞
