### ISSUE TITLE
Use http_build_query() to set cURL options

### ISSUE THREAD

**Issue by ragulka** [hybridauth/hybridauth#683]
It seems that cURL options are set as an array in OAuth API clients (OAuth1Client, OAuth2Client). This causes cURL to override any custom `Content-Type` headers being set by `$this->api->curl_header` in a Provider. 

Some providers, however, require the `Content-Type` header to be explicitly set to some value. For example, [Amazon](https://github.com/hybridauth/hybridauth/pull/682/files#diff-3b531c4f8ce780a341644f07799641a6R51). Since cURL overrides the content type, the API request fails. The only way to workaround this issue is to provide a custom `Oauth2Client`, for example HumanatarianId, Drupal, Amazon.

A simple fix would be to simply use `http_build_query()` [here](https://github.com/hybridauth/hybridauth/blob/master/hybridauth/Hybrid/thirdparty/OAuth/OAuth2Client.php#L236), and those providers could simply use the built-in OAuth2Client. This, of course, in case some other providers don't need the values to be JSON encoded or something?

**Comment by StorytellerCZ** [comment]
Fixed in #707.
