### ISSUE TITLE
Plurk provider not using https

### ISSUE THREAD

**Issue by kinmenRP** [hybridauth/hybridauth#693]
Hello. I've found out that the library still makes use of http intead of https for the Plurk connector. I think it would be better to switch to https to improve the security, since Plurk has implemented https since some time. I've already changed the code in the file Plurk.php to test it, and it works on my website. I therefore attach the modified version of Plurk.php, if you wanto to check it and eventually commit the changes.
Regards,
Kinmen

[Plurk.php.txt](https://github.com/hybridauth/hybridauth/files/546253/Plurk.php.txt)

**Comment by StorytellerCZ** [comment]
Hi @kinmenRP !
Thanks for the notice. I would strongly encourage you to go ahead and create a pull request with these changes so that you get credit for the fix.

**Comment by kinmenRP** [comment]
sorry for the delay, I was away. Created the request

**Comment by StorytellerCZ** [comment]
Fixed in #705
