### ISSUE TITLE
Fatal error: Class 'Facebook\Facebook' not found

### ISSUE THREAD

**Issue by nodeffect** [hybridauth/hybridauth#698]
I get this error below if login using Facebook:
Fatal error: Class 'Facebook\Facebook' not found in C:\wamp64\www\hybridauth\Hybrid\Providers\Facebook.php on line 56 

I also notice that the Facebook folder is missing under "hybridauth/hybridauth/Hybrid/thirdparty/" ? Not sure if that's the problem. It used to be there on older version.

Using the latest version 2.8.0. I did not encounter this problem on older version.

**UPDATE: Check below for solution.**
**UPDATE: Check below for new solution for Hybridauth v2.8.2/3.**

**Comment by TheJoin95** [comment]
I get the same error with the latest version of HybridAuth (2.8):
`FastCGI sent in stderr: "PHP message: PHP Fatal error:  Class 'Facebook\Facebook' not found in /var/www/connect/lib/vendor/hybridauth/hybridauth/hybridauth/Hybrid/Providers/Facebook.php on line 56" while reading response header from upstream`

I installed HybridAuth via composer, so I also get the new facebok sdk.
Is the new facebook sdk (5.4.1) stable? Or is it included correctly? 
Because the error seems to be a namespace's error.

I fixed with a downgrade a 2.7 version of hybridauth, with the older sdk.

**Comment by Alxdhere** [comment]
I had such error. I use Yii 1.x and PHP 5.5.9.

Firstly I download https://github.com/facebook/php-graph-sdk and extract it in /opt/Facebook. Declare alias in Yii in config/main.php:
`Yii::setPathOfAlias('Facebook','/opt/Facebook');`

Then, download https://github.com/paragonie/random_compat and extract it in /opt/random_compat. Add in index.php:
`require_once "/opt/random_compat/lib/random.php";`

Then, in controller write:
```
if(!function_exists('hash_equals')) {
    function hash_equals($str1, $str2) {
        if(strlen($str1) != strlen($str2)) {
            return false;
        } else {
            $res = $str1 ^ $str2;
            $ret = 0;
            for($i = strlen($res) - 1; $i >= 0; $i--) $ret |= ord($res[$i]);
            return !$ret;
        }
    }
}
```

Facebook auth work fine!

**Comment by nodeffect** [comment]
Hi guys, I've actually solved the problem. This version is not as straight forward as the previous versions.
You do need to get the Facebook API from https://github.com/facebook/php-graph-sdk first.

Then extract to the "third party" folder. You only need the folder that contains all the Facebook API files and folders. Examples for files: autoload.php, facebook.php, etc....  and it's folders including "Authentication", "Exceptions", etc.... 

This is basically my structure. "hybridauth\Hybrid\thirdparty\Facebook"

Then, on your project, you'll need to include both the Hybridauth and the Facebook API. Example below:
```
require_once('hybridauth/Hybrid/Auth.php');
require_once('hybridauth/Hybrid/thirdparty/Facebook/autoload.php');
```

**Comment by TheJoin95** [comment]
@nodeffect Did you install HybridAuth by composer or manually?

Your solution works but, imho it's better if we fixed the last release of the library.
Because if someone else run a [composer update], then facebook login will crash every time because of a "Fatal error"

**Comment by nodeffect** [comment]
@TheJoin95 I install HybridAuth manually. It's a temporary solution, hopefully they would include it in the next version.

**Comment by ramu2514** [comment]
autoload.php is now removed from facebook sdk and is not available in latest revision.
https://github.com/facebook/php-graph-sdk/commits/master

Using sdk version 5.4.0 helped me.
https://codeload.github.com/facebook/php-graph-sdk/zip/5.4.0

**Comment by acrolink** [comment]
Please solve this issue.

**Comment by nodeffect** [comment]
@ramu2514 By now, please use only v5.4.0..

If you go here: https://github.com/facebook/php-graph-sdk you will see the message below:
NOTICE: This branch is under active development. For the stable release please use the 5.4 branch.

So, in this case, you should use this version 5.4.0. I believe that the latest version is still under development. So no point using it.

**Comment by hellboy81** [comment]
Fix this ...ing bug! why should I downgrade to 2.8 ?

**Comment by Omniru** [comment]
They are planning on fixing this right?

**Comment by NinoSkopac** [comment]
Still broken with composer

**Comment by NinoSkopac** [comment]
# Solution if using Composer

Go to `vendor/hybridauth/hybridauth/hybridauth/index.php` and add this:

`require __DIR__ . '/../../../autoload.php';`

**Comment by hellboy81** [comment]
Can your fix be applied to version `2.8.2` ?

**Comment by NinoSkopac** [comment]
If that is latest, yes.

**Comment by hellboy81** [comment]
Which `hybridauth` version should I use at **current** moment  to allow Facebook auth?

Is there real-world samples with authorize callback URL?

**Comment by hellboy81** [comment]
which Facebook API version should I use with the latest current stable `hybridauth` release?

Only `2.8`? 

Which latest `hybridauth` version should use together with Facebook API version 2.8?

Is Facebook API version 2.2 deprecated?

Should I **not** use it together with current  ~~stable~~ dev version of `hybridauth`?

**Comment by gumdal** [comment]
I have followed this post but do not understand what has to be done in order to fix this error. Is the development version available with this fix yet? This seems to be a priority issue with many people relying on Facebook login.

**Comment by nodeffect** [comment]
Please see the new solution for the latest Hybridauth update here:
https://github.com/hybridauth/hybridauth/issues/714

**Comment by nodeffect** [comment]
# New Solution for Hybridauth v2.8.2/3

# Story
I've seen many people having this Facebook login problem on previous version because they did not include the Facebook API in it. And I did provide a solution for it on the previous ticket here https://github.com/hybridauth/hybridauth/issues/698.

However, on the latest version of Hybridauth v2.8.2/3, many people still getting this error even though they included the Facebook API. And I think this is mainly because they missed out some stuffs and you might need to modify some files to make it work. Below is the solution and it's working for me so I hope it works for you guys too.

# Solution
Extract the downloaded zip file. Your main folder should be "hybridauth-master"

Step 1: On \hybridauth-master folder. Run "composer install" and then you'll see a new folder called "vendor". (This is basically the Facebook API)

Step 2: Place this line "`require_once('../vendor/autoload.php');`" on  "\hybridauth-master\ hybridauth\index.php" and also "live.php". See example below:
```
require_once( "Hybrid/Auth.php" );
require_once( "Hybrid/Endpoint.php" );
require_once('../vendor/autoload.php'); #add this new line
```

Step 3: On your config file or your login page file, include this two lines like below:
```
#HybridAuth - social login plug-in
require_once('./inc/lib/hybridauth/hybridauth/Hybrid/Auth.php'); #Hybridauth API
require_once('./inc/lib/hybridauth/vendor/autoload.php'); #Facebook API
```

**Comment by kapilgp** [comment]
**Fix without composer**

Actually we need to load the thirdparty library of facebook. So fix is following

**Add below line in hybridauth\Hybrid\Providers\Facebook.php**

require_once Hybrid_Auth::$config["path_libraries"] . "Facebook/autoload.php";

**Comment by StorytellerCZ** [comment]
Anyone is welcome to make a PR with the fix. I will eventually get to it, but the question is when. Thanks!

**Comment by IRuslan** [comment]
@StorytellerCZ Hi, I've create a simple PR with fix. Works for me.

**Comment by ApacheEx** [comment]
Hi guys,

I've added a little PR #760 with fix which works well in both cases: 
1) if you use composer (so Facebook SDK placed in vendor/)
2) if you don't use composer (so Facebook SDK placed in thirdparty/)

**Comment by crueol** [comment]
@nodeffect thanks. I've followed your instruction and it works. I'm not use composer.

**Comment by 9meAhmed** [comment]
I am having this error when trying to login with LinkedIn Error User has cancelled the authentication or the provider refused the connection.
LinkedIn

**Comment by ApacheEx** [comment]
@9meAhmed, why not to create a new issue with all needed details and steps?

**Comment by 9meAhmed** [comment]
i am new here and i just solved the facebook issue by this discussion
