### ISSUE TITLE
Facebook App using graph api v2.8 returns error while login

### ISSUE THREAD

**Issue by ktrev** [hybridauth/hybridauth#699]
I need to enable hybridauth login in a drupal site using the hybridauth drupal module. It is subdmain like mi.domain.com
I am getting the following error when trying to use the facebook login feature.
Exception: Facebook Graph returned an error: Can't Load URL: The domain of this URL isn't included in the app's domains. To be able to load this URL, add all domains and subdomains of your app to the App Domains field in your app settings. in Hybrid_Auth::initialize() (line 169 of /var/www/libraries/hybridauth/Hybrid/Auth.php).

My facebook app settings is

![image](https://cloud.githubusercontent.com/assets/9925644/20066656/55017582-a538-11e6-9879-874fe4eec2c8.png)

**Comment by yosiaken** [comment]
You can try to downgrade to v2.7.0. 
https://github.com/hybridauth/hybridauth/releases/tag/v2.7.0
It works for me!

**Comment by hellboy81** [comment]
should I still use `2.7.0`?

**Comment by uitlaber** [comment]
how to fix ?
`
Facebook Graph returned an error: Can't Load URL: The domain of this URL isn't included in the app's domains. To be able to load this URL, add all domains and subdomains of your app to the App Domains field in your app settings.
`

**Comment by cobenash** [comment]
Hey @uitlaber , Do your facebook website are HTTPS website?

**Comment by uitlaber** [comment]
@cobenash yes

**Comment by cobenash** [comment]
@uitlaber I have the same situation. I dont know how to fix that. :(

**Comment by cobenash** [comment]
@uitlaber I found an issue talking about https issue.
#569 was talking about the same issue. But Its didnt work.
So Do you find the answer ?

**Comment by driade** [comment]
@cobenash @uitlaber I had today to add the https URL to the list of valid URLs to redirect, in section session login with Facebook. Previously I just had the http ones (don't event know why it worked, but it did).

So, now, I have both http://site.com/social/auth and https://site.com/social/auth, been the https the good and the missing one.

**Comment by cobenash** [comment]
@driade Many Thanks.

**Comment by EC-jmassanet** [comment]
Hello, i have the same problem, the version 2.9 fix this issues 
#727 + #734 - [Facebook] Fix problem which occurs during calling the Facebook Graph API to 
getAccessToken() for a specific redirectUrl

And my problems is solved, thanks
