### ISSUE TITLE
Google getUserContacts

### ISSUE THREAD

**Issue by stewartmegaw** [hybridauth/hybridauth#700]
Hi,

I think it's due to the depreciation guidelines as of Sep 2016 stated here https://developers.google.com/+/web/people/
...I am not getting any contacts returned when using Google+ to connect my application (Facebook works fine). 

Am I correct? If so are there any plans to incorporate the new People API functionality to get user contacts?

Many thx

**Comment by marsjaninzmarsa** [comment]
Fixed in #855?

**Comment by marsjaninzmarsa** [comment]
Ugh, this is 2.x branch issue, ignore above.

**Comment by ApacheEx** [comment]
closed in favor of #961
