### ISSUE TITLE
Authentication with Google is failing on iOS

### ISSUE THREAD

**Issue by araiczyk** [hybridauth/hybridauth#701]
Hi,

I've integrated this great API for social login authentication in a WiFi captive portal. It works great in all devices but iOS as seen in the attached image.
![img_7807](https://cloud.githubusercontent.com/assets/87342/20253688/7940ab1a-aa0c-11e6-9296-ec39099ce2b4.PNG)

I've been googling and what I found that "In the coming months, we will no longer allow OAuth requests to Google in embedded browsers known as “web-views”, such as the WebView UI element on Android and UIWebView/WKWebView on iOS, and equivalents on Windows and OS X."
([](https://developers.googleblog.com/2016/08/modernizing-oauth-interactions-in-native-apps.html))

I thought the captive window in iOS (& OSX) was a Safari instance, but for my surprise it's not. It's an app: System/Library/CoreServices/Captive Network Assistant.app. And that's probably why G+ auth is not working in iOS.

Any ideas?

Thanks in advance.

**Comment by nodeffect** [comment]
Have you whitelist google in your router ?

**Comment by araiczyk** [comment]
@nodeffect yep, it's whitelisted. This works fine for every device but iOS.

**Comment by StorytellerCZ** [comment]
Check now after #707.

**Comment by araiczyk** [comment]
Great, it works!! Thank you so much!
