### ISSUE TITLE
Twitter oauth issue

### ISSUE THREAD

**Issue by Nimesh-Soni** [hybridauth/hybridauth#706]
Exception Object
(
    [message:protected] => Authentication failed! Twitter returned an error. 401 Unauthorized.
    [string:Exception:private] => 
    [code:protected] => 5
    [file:protected] => /var/www/vhosts/***/httpdocs/hybridauth/hybridauth/Hybrid/Auth.php
    [line:protected] => 169
    [trace:Exception:private] => Array
        (
            [0] => Array
                (
                    [file] => /var/www/vhosts/***/httpdocs/hybridauth/hybridauth/Hybrid/Auth.php
                    [line] => 55
                    [function] => initialize
                    [class] => Hybrid_Auth
                    [type] => ::
                    [args] => Array
                        (
                            [0] => /var/www/vhosts/***/httpdocs/hybridauth/hybridauth/config.php
                        )

                )

            [1] => Array
                (
                    [file] => /var/www/vhosts/mskmktg.net/httpdocs/hybridauth/index.php
                    [line] => 31
                    [function] => __construct
                    [class] => Hybrid_Auth
                    [type] => ->
                    [args] => Array
                        (
                            [0] => /var/www/vhosts/***/httpdocs/hybridauth/hybridauth/config.php
                        )

                )

        )

    [previous:Exception:private] => 
)

**Comment by StorytellerCZ** [comment]
Could this be related to #707?
