### ISSUE TITLE
OAuth2Client POST request invalid parameters

### ISSUE THREAD

**Issue by vmtv** [hybridauth/hybridauth#708]
diff --git a/sites/all/libraries/hybridauth/hybridauth/Hybrid/thirdparty/OAuth/OAuth2Client.php b/sites/all/libraries/hybridauth/hybridauth/Hybrid/thirdparty/OAuth/OAuth2Client.php
index c9bc769..b76f58c 100644
--- a/sites/all/libraries/hybridauth/hybridauth/Hybrid/thirdparty/OAuth/OAuth2Client.php
+++ b/sites/all/libraries/hybridauth/hybridauth/Hybrid/thirdparty/OAuth/OAuth2Client.php
@@ -233,14 +233,14 @@
 
     if( $type == "POST" ){
       curl_setopt($ch, CURLOPT_POST, 1);
-      if($params) curl_setopt( $ch, CURLOPT_POSTFIELDS, $params );
+      if($params) curl_setopt( $ch, CURLOPT_POSTFIELDS, http_build_query($params, '', '&') );
     }
     if( $type == "DELETE" ){
         curl_setopt($ch, CURLOPT_CUSTOMREQUEST, "DELETE");
     }
     if( $type == "PATCH" ){
       curl_setopt($ch, CURLOPT_POST, 1);
-      if($params) curl_setopt( $ch, CURLOPT_POSTFIELDS, $params );
+      if($params) curl_setopt( $ch, CURLOPT_POSTFIELDS, http_build_query($params, '', '&') );
       curl_setopt($ch, CURLOPT_CUSTOMREQUEST, "PATCH");
     }
     $response = curl_exec($ch);

**Comment by StorytellerCZ** [comment]
#707 ?
