### ISSUE TITLE
Joomla

### ISSUE THREAD

**Issue by CallumBrankin** [hybridauth/hybridauth#709]
Is there any extension for Joomla? If not is there any alternatives?

**Comment by CallumBrankin** [comment]
If you click on this [link](http://hybridauth.sourceforge.net/plugins.html) it'll take you to the plugin page showing two Joomla extensions which both have broken links but this [link](http://hybridauth.github.io/hybridauth/plugins.html) takes you to the correct plugin page (I presume) which shows one Joomla extension with the link working. Is this a problem?

**Comment by StorytellerCZ** [comment]
Just haven't uploaded a new version of the docs to sourceforge, will fix.
