### ISSUE TITLE
[Solution] "Fatal error: Class 'Facebook\Facebook' not found Provider" on latest v2.8.2/3

### ISSUE THREAD

**Issue by nodeffect** [hybridauth/hybridauth#714]
# Story
I've seen many people having this Facebook login problem on previous version because they did not include the Facebook API in it. And I did provide a solution for it on the previous ticket here https://github.com/hybridauth/hybridauth/issues/698.

However, on the latest version of Hybridauth v2.8.2/3, many people still getting this error even though they included the Facebook API. And I think this is mainly because they missed out some stuffs and you might need to modify some files to make it work. Below is the solution and it's working for me so I hope it works for you guys too.

# Solution
Extract the downloaded zip file. Your main folder should be "hybridauth-master"

Step 1: On \hybridauth-master folder. Run "composer install" and then you'll see a new folder called "vendor". (This is basically the Facebook API)

Step 2: Place this line "`require_once('../vendor/autoload.php');`" on  "\hybridauth-master\ hybridauth\index.php" and also "live.php". See example below:
```
require_once( "Hybrid/Auth.php" );
require_once( "Hybrid/Endpoint.php" );
require_once('../vendor/autoload.php'); #add this new line
```

Step 3: On your config file or your login page file, include this two lines like below:
```
#HybridAuth - social login plug-in
require_once('./inc/lib/hybridauth/hybridauth/Hybrid/Auth.php'); #Hybridauth API
require_once('./inc/lib/hybridauth/vendor/autoload.php'); #Facebook API
```

**Comment by mehulchauhan** [comment]
Solution above didn't work for me, sorry will try again to debug more and provide some more insight.

**Comment by jmgomezpoveda** [comment]
Thanks for taking the time documenting a solution. Note that the solution to https://github.com/hybridauth/hybridauth/issues/698 should be in that issue, not in a separate one.

**Comment by nodeffect** [comment]
@jmgomezpoveda Thanks, I've updated my previous issue ticket.

Mod, please close this ticket. Thanks.

**Comment by tsmulugeta** [comment]
I don't understand #3. I am running a Drupal website so where exactly would this go?
