### ISSUE TITLE
Fatal Error : Class 'Facebook\Facebook' not found

### ISSUE THREAD

**Issue by arvindvashisat** [hybridauth/hybridauth#717]
I am using latest version of hybridauth. google+ login is working fine but when i tried to login from facebook then I got error "Class Facebook\Facebook not found ". Can you please tell us when we get the latest update regarding this issue.

Thanks.

**Comment by nodeffect** [comment]
please read my solution https://github.com/hybridauth/hybridauth/issues/714

**Comment by jmgomezpoveda** [comment]
This is a duplicate of https://github.com/hybridauth/hybridauth/issues/698
