### ISSUE TITLE
Google login problem

### ISSUE THREAD

**Issue by imreballa** [hybridauth/hybridauth#719]
Hi,

after Google login we got error message "User profile request failed! Google returned an error: exception 'Exception' with message 'The Authorization Service has return: invalid_request'"

We are using 2.4.1 and don't want to upgrade if it is not necessary.

Thank you
Imre

**Comment by ApacheEx** [comment]
Hi, pls have a look on this PR which is already merged to latest stable version (2.8.2).
https://github.com/hybridauth/hybridauth/pull/707

I think this should fix your problem.

**Comment by imreballa** [comment]
Thank you, will try to refresh.

**Comment by CaelanBorowiec** [comment]
I've just updated to 2.8.2 but am still having the issue from #707.

**Comment by imreballa** [comment]
It is working for us.
It is in test environment at the moment, but it should work on prod as well (still fixinf Facebook issue).

**Comment by CaelanBorowiec** [comment]
@imreballa thanks, it appears our prod server was being very slow in mirroring the updated files.  It's working just fine now.
