### ISSUE TITLE
[Facebook + Google] emailVerified able to be empty string because of Unicode

### ISSUE THREAD

**Issue by izzycreamcheese** [hybridauth/hybridauth#720]
First off, I admit this is not hybridauth's fault, but it's something it could check for and save people some issues.

As of 2012 it's possible for email addresses to have Unicode U+007F. If not handled properly in PHP (which we don't, unfortunately) some Unicode can cause a string to become empty. We had a user inadvertently link his account to an empty email and then anyone else who attempted to log in with an offending email, was able to log in with his account. 

I fixed this by checking for an empty emailVerified, but it seems to me like it would be a good idea for everyone who uses hybridauth, if it did that for you so this can't take anyone unaware.

As a note, this happened with a Facebook account, also Google supports Unicode in emails.

**Comment by StorytellerCZ** [comment]
@izzycreamcheese Might not be a bad idea to write a notice into the documentation if you are for it.
Or maybe we might need to figure if we can possibly get this sorted somewhere in HA.

**Comment by ApacheEx** [comment]
I'm closing this issue since v2 is under Maintenance mode.
