### ISSUE TITLE
If you are starting new project you shouldn't use HybridAuth

### ISSUE THREAD

**Issue by hellboy81** [hybridauth/hybridauth#722]
>If you are starting new project you shouldn't use HybridAuth.

what should I use in new project to make auth available for multiple providers (Facebook/Google/Twitter...)

**Comment by filisko** [comment]
where did you quote that from?

**Comment by hellboy81** [comment]
Jan Dvorak @StorytellerCZ

**Comment by hellboy81** [comment]
[OAuth 2 Client](http://oauth2-client.thephpleague.com/) from ~~[LXG](https://en.wikipedia.org/wiki/The_League_of_Extraordinary_Gentlemen)~~ The League of Extraordinary Packages should be used instead

**Comment by hellboy81** [comment]
any feedback?

**Comment by jmgomezpoveda** [comment]
The quote is from http://stackoverflow.com/questions/19149729/any-good-alternatives-to-replace-hybridauth-php#comment70383475_19149729
