### ISSUE TITLE
PxHybridAuth TYPO3 Extension

### ISSUE THREAD

**Issue by aWuttig** [hybridauth/hybridauth#725]
Could you please add our TYPO3 extension px_hybrid_auth to your project homepage:

https://typo3.org/extensions/repository/view/px_hybrid_auth
https://github.com/portrino/px_hybrid_auth
https://packagist.org/packages/portrino/px_hybrid_auth

You can get TYPO3 logos here: http://styleguide.typo3.org/patternlab/public/index.html

**Comment by StorytellerCZ** [comment]
Yes, but for speedy addition creating a pull request to `gh-pages` branch is recommended.

**Comment by aWuttig** [comment]
Done in https://github.com/hybridauth/hybridauth/commit/435030e4679149eda5a7931cfd047ee538cab9dc
