### ISSUE TITLE
Error on Facebook Login for Codeigniter

### ISSUE THREAD

**Issue by sphinx-ganesh** [hybridauth/hybridauth#726]
I'm trying to implement facebook login in my website using Hybridauth library in codeigniter.

I created an application on facebook and added required info (App Key & Secret Key) in hybridauth config file.

My issue is when i try to login with facebook and allow application on my facebook login, while redirecting on my website i get error as "User has cancelled the authentication or the provider refused the connection."

This is my call back url on facebook - http://xx.xxxx.xxxx.xxxx/MY_WEB_FOLDER/index.php/hauth/endpoint?hauth.done=Facebook

Can somebody please help me to resolve my issue and help me to facebook login working ?

**Comment by StorytellerCZ** [comment]
@sphinx-ganesh There are some fixes for FB coming up in v2.8.3, so keep an eye out for that.

**Comment by StorytellerCZ** [comment]
@sphinx-ganesh Try it now, a lot of fixes for Facebook came in the recent versions.

**Comment by ApacheEx** [comment]
Yeah, pls upgrade HA library to the latest stable v2. Pls also check an actual [documentation](https://hybridauth.github.io/hybridauth/userguide/IDProvider_info_Facebook.html).
if still occurs pls re-open.

**Comment by xaiborweb** [comment]
@StorytellerCZ 
But how could you integrate the new hybridauth versions into CodeIgniter if the only integration found in the network is
Https://github.com/andacata/HybridIgniter

And for a normal person like me who is not a programmer it is very difficult to do it by chance you have a version that works and you can share it?

**Comment by ApacheEx** [comment]
@xaiborweb,
lots of requests were about CodeIgniter + HA.
I will try to take care about that this week.
which version of CodeIgniter should it support? only 3.x or 2.x as well?

**Comment by xaiborweb** [comment]
@ApacheEx
Thank you very much friend if you can update HybridAuth CodeIgniter 3.x to work properly you would be the first to make this contribution on the internet and I would be eternally grateful

**Comment by ApacheEx** [comment]
@xaiborweb,

https://github.com/ApacheEx/CodeIgniter-HybridAuth 🎉 
pls have a look, it's only first version. 
Will be improved a bit later with more examples.

**Comment by isantolin** [comment]
@ApacheEx can you modify to HybridAuth 3?

**Comment by ApacheEx** [comment]
@isantolin,
Yeah, I will.

**Comment by xaiborweb** [comment]
@ApacheEx 
Thanks friend but the third_party folder did not add it to try if it works with facebook login

**Comment by ApacheEx** [comment]
You need to run `composer install` in the `third_party/hybridauth` library, then fb will work. Or just install HA as composer dependency in thr root of CI:
```
composer install hybridauth/hybridauth
```

**Comment by ApacheEx** [comment]
@xaiborweb,
I've added more readme 🎉 ,
pls check it out https://github.com/ApacheEx/CodeIgniter-HybridAuth
