### ISSUE TITLE
Connecting to OpenID Connect provdier

### ISSUE THREAD

**Issue by sdanko** [hybridauth/hybridauth#743]
Is it possible to connect to my own OpenID Connect provdier that I implemented in IdentityServer 3 framework?

**Comment by CallumBrankin** [comment]
Have a look at [my implementation of OpenID Connect ](https://github.com/PixelPinPlugins/PixelPin-HybridAuth) which uses PixelPin. It's not full OpenID Connect but it works.

**Comment by marsjaninzmarsa** [comment]
404…

**Comment by winstonhong** [comment]
[Pixelpin OpenID Connect 7](https://github.com/PixelPinPlugins/Drupal-7-PixelPin-OpenID-Connect)

PixelPin OpenID Connect 7 Uses the OpenID Connect identity layer on top of OAuth 2.0 protocol to authenticate users using PixelPin.

Requirements
Drupal 7 (7.*)
ctools (7.x-1.12)
entity (7.x-1.8)

**Comment by ApacheEx** [comment]
closed in favor of #960
