### ISSUE TITLE
[Provider] idQ

### ISSUE THREAD

**Issue by winstonhong** [hybridauth/hybridauth#747]
(1) idQ Developer Documentation
https://docs.idquanta.com

(2) Register a new application at idQ Server.
https://account.idquanta.com

HybridAuth idQ Provider
https://www.drupal.org/project/hybridauth_idqoauth2

**Comment by winstonhong** [comment]
#737

**Comment by isantolin** [comment]
@StorytellerCZ Can be closed by #737

**Comment by winstonhong** [comment]
Passwords are so 2016. See what’s next!

Hello Folks.

idQ Trust as a Service (TaaS) solution is next. [Try it out](https://inbaytech.com/#signup).

I work at inBay Technologies, a startup that developed the idQ TaaS platform to get rid of passwords.
And I invite you to use it to see what a passwordless Internet of the future would look like. Did I mention it’s more secure too?

Download the free idQ Connect app from your phone’s app store, and try our [Dropcrate demo](https://dropcrate.idquanta.com/), as described on [our web page](https://inbaytech.com/).
