### ISSUE TITLE
Google login return empty first and last name

### ISSUE THREAD

**Issue by mpkumar87** [hybridauth/hybridauth#748]
Hi Team,

I am getting empty user profile data except email id while login through google. For some email ids, it is working fine. Below is the response,

[user] =&gt; Hybrid_User Object
                (
                    [providerId] =&gt; Google
                    [timestamp] =&gt; 1489756027
                    [profile] =&gt; Hybrid_User_Profile Object
                        (
                            [identifier] =&gt; 108363722522739827456
                            [webSiteURL] =&gt; 
                            [profileURL] =&gt; 
                            [photoURL] =&gt; https://lh3.googleusercontent.com/-XdUIqdMkCWA/AAAAAAAAAAI/AAAAAAAAAAA/4252rscbv5M/photo.jpg?sz=200
                            [displayName] =
                            [description] =
                            [firstName] =
                            [lastName] =
                            [gender] =
                            [language] =
                            [age] =
                            [birthDay] = 0
                            [birthMonth] = 0
                            [birthYear] = 0
                            [email] = mpkumar.87@gmail.com
                            [emailVerified] = mpkumar.87@gmail.com
                            [phone] =&gt; 
                            [address] =&gt; 
                            [country] =&gt; 
                            [region] =&gt; 
                            [city] =&gt; 
                            [zip] =&gt; 
                        )

                )

Please guide me to solve this issue. I have also checked the same with lastest hybrid library (2.8.2).

Thanks,

Premkumar M

**Comment by bev-ru** [comment]
I had the same problem. I set Google scope to 'profile email https://www.googleapis.com/auth/plus.profile.emails.read' and now it works fine.
Probably default scopes are outdated in HybridAuth.
This happens when login with already accepted permissions. On first login and accept permissions it return correct profile.

**Comment by StorytellerCZ** [comment]
@bev-ru Can you please submit a PR with your fix? Thanks!

**Comment by ApacheEx** [comment]
Should be fixed in HA 2.9.6
