### ISSUE TITLE
Cannot use object of type Facebook\FacebookResponse as array

### ISSUE THREAD

**Issue by tatocaster** [hybridauth/hybridauth#750]
`Fatal error: Cannot use object of type Facebook\FacebookResponse as array in ***/Facebook.php on line 260`
here it is 
```php
function getUserActivity(){
    ....
    if (!$response || !count($response['data'])) {
        return [];
    }

```
written this. this causes error, 

the fix is to write getGraphObject from response.
 just add a line before
```php
$response = $response->getGraphObject();
```

**Comment by ApacheEx** [comment]
@tatocaster Hi,
I've created a little PR to fix this issue.
