### ISSUE TITLE
Facebook auth that worked for years now fails

### ISSUE THREAD

**Issue by LuckStock** [hybridauth/hybridauth#754]
Hello,

It was working smoothly for years, but right now it fails with the message:
"Authentication failed! Facebook returned an invalid user id."

Have tried to update to latest HybridAuth, change facebook app settings, but nothing helps.
It fails on the stage:
`$hybridauth = new Hybrid_Auth( $authConfig );`

**Comment by aWuttig** [comment]
I had the same problem. And the soution for me was here: https://github.com/hybridauth/hybridauth/issues/727

**Comment by LuckStock** [comment]
I had to add autoload for Facebook-sdk so now my index.php looks like:
```
require_once ROOT_PATH . '../vendor/hybridauth/hybridauth/hybridauth/Hybrid/Auth.php';
require_once ROOT_PATH . '../vendor/facebook/graph-sdk/src/Facebook/autoload.php';
require_once ROOT_PATH . '../vendor/hybridauth/hybridauth/hybridauth/Hybrid/Endpoint.php';

Hybrid_Endpoint::process();

```

**Comment by aWuttig** [comment]
autloading will be done via composer autoloader normally

**Comment by TihomirS** [comment]
@aWuttig i use last hybridauth release with described fix but still can't login with FB ..

Any ideas?

**Comment by Tr4cer0ute** [comment]
have the same problem here since two days

**Comment by aWuttig** [comment]
Do you add the  Valid OAuth Redirect URI in Facebook?

I make a complete doc for shopware here https://store.shopware.com/en/port171127432370/social-login-via-hybridauth.html

You only have to do the facebook stuff which should be equal on all frameworks

**Comment by Tr4cer0ute** [comment]
@aWuttig Yes I did

**Comment by aWuttig** [comment]
Do you really use v2.9.1 of hybridauth?

**Comment by Tr4cer0ute** [comment]
@aWuttig no the old one. Should I update?

**Comment by TihomirS** [comment]
yes, and try with 2.9.0 too

**Comment by aWuttig** [comment]
Yes please update, because my fix from https://github.com/portrino/hybridauth/commit/810edcff909195220bff5a72c5eff0f8c2112aac is only available in the new version 2.9.x

**Comment by TihomirS** [comment]
ok, once again with clear upload 2.9.1

now i get:
Fatal error: Uncaught Error: Class 'Facebook\Facebook' not found in /_inc/hybridauth/Hybrid/Providers/Facebook.php:56

**Comment by Tr4cer0ute** [comment]
I did update the repo but still getting in the same issue

Hybrid_Auth->__construct('../hybridauth/c...') #2 {main} thrown in MY_PATH/hybridauth/Hybrid/Auth.php on line 152

**Comment by somsgod** [comment]
you need to include autoload.php 
//Something like this in Provider/Facebook.php
require_once(__DIR__ . '\Facebook\autoload.php');

but issue on mine side is after going through all process and logging in on fb when it return it says

 Can't Load URL: The domain of this URL isn't included in the app's domains. To be able to load this URL, add all domains and subdomains of your app to the App Domains field in your app settings.

but i didnt changed anything on developer console till yesterday when it was working.

**Comment by aWuttig** [comment]
Maybe Facebook changed the Graph API or the security level.

**Comment by TihomirS** [comment]
I think this is FB change .. i have logged users last night via FB login.
i try include FB Graph API SDK but still not luck..

**Comment by ApacheEx** [comment]
Hi guys,
have the same issue. Perhaps that's because v2.2 of API was available until March 25, 2017. And if you check changelog https://developers.facebook.com/docs/apps/changelog from v2.2 to v2.3:

you will see the following:

> [Oauth Access Token] Format - The response format of https://www.facebook.com/v2.3/oauth/access_token returned when you exchange a code for an access_token now return valid JSON instead of being URL encoded. The new format of this response is {"access_token": {TOKEN}, "token_type":{TYPE}, "expires_in":{TIME}}. We made this update to be compliant with section 5.1 of RFC 6749.

perhaps that's the reason - I'm currently trying to fix that. Will let you know results.

**Comment by TihomirS** [comment]
i have it working on my 2 sites :)

**solution**:
---------------
use new 2.9.1 version
get the Facebook API from https://github.com/facebook/php-graph-sdk
Then extract to the "third party" folder. You only need the folder that contains all the Facebook API files and folders. Examples for files: autoload.php, facebook.php, etc.... and it's folders including "Authentication", "Exceptions", etc....

Then, on your project, you'll need to include both the Hybridauth and the Facebook API. Example below:
`require_once('hybridauth/Hybrid/Auth.php');
require_once('hybridauth/Hybrid/thirdparty/Facebook/autoload.php');`

On, index.php and live.php under Hybridauth folder, I also added a new line 
Example:
`require_once( "Hybrid/Auth.php" );
require_once( "Hybrid/Endpoint.php" );
require_once( "Hybrid/thirdparty/Facebook/autoload.php" );`

Don't forget to use only public permissions on config.php:
`"Facebook" => array(
					"enabled" => true,
					"keys" => array("id" => "111", "secret" => "222"),
					"trustForwarded" => false,
					"scope" => array("public_profile", "email")
				),`

Best,
T.

**Comment by thesios** [comment]
Are we going to get this changes integrated / checked in ?

**Comment by thesios** [comment]
I do see the FB api was removed on 2.91

**Comment by ApacheEx** [comment]
ok, I upgraded hybridauth to the latest version (v2.9.1) 

and then changed in FB app:
From: http://yourdomain.com/hybridauth/?hauth.done=Facebook
To: http://yourdomain.com/hybridauth/?hauth_done=Facebook

that's it. Sharing / Login / Sign up works well for me.

p.s. if you use older version, you have to upgrade to latest one and run "composer install"

**Comment by driade** [comment]
Can confirm too it's due to a change in the Facebook API. Upgraded composer yesterday to 2.8.* and got it working with no further change in my code but the issue described in #745

**Comment by tanmayk** [comment]
Made it working by referencing all above comments and below are my steps:

1. Upgraded hybridauth library (v2.9.1) and put php-graph-sdk (https://github.com/facebook/php-graph-sdk) under hybridauth so autoload.php can be found at *hybridauth/Hybrid/thirdparty/Facebook/autoload.php*.
2. Instead of adding *require_once* lines in *index.php*, added below in hybridauth/Hybrid/Providers/Facebook.php at Line 45.
```
require_once Hybrid_Auth::$config["path_libraries"] . "Facebook/autoload.php";
```
3. After this, changed app configuration for redirect URL to use **hauth_done** instead of hauth.done.

It is working fine now. Thanks guys for sorting this out :)

**Comment by somsgod** [comment]
ya its working fine now guys use hybridauth library (v2.9.1) and facebook sdk and change app configuration.

**Comment by thesios** [comment]
you need to make the change in your global php.ini file

**Comment by jouey** [comment]
Interesting... so run this command there:

date_default_timezone_set('UTC');

Why ever would I have started having this problem anyway, suddenly a year ago, never having had such problems before?

**Comment by isantolin** [comment]
Upgrading to 2.9.2-dev still occurs?

**Comment by hijarian** [comment]
@jouey 
> Why ever would I have started having this problem anyway, suddenly a year ago, never having had such problems before?

Because PHP 5.4+ requires you to setup your default timezone explicitly, either in php.ini or by the `date_default_timezone_set`. Most possibly you upgraded your PHP installation. This setting has been required for ages already.

**Comment by coscho** [comment]
> An uncaught Exception was encountered
> Type: Error
> Message: Class 'Hybrid_Auth' not found
> Filename: /var/www/html/coscho.ro/application/third_party/hybridauth/Hybrid/Storage.php
> Line Number: 26

I still get this error after all this steps.

> endpoint?hauth.start=Facebook&hauth.time=1491864305

**Comment by ApacheEx** [comment]
@coscho 

It seems that your autoloader not working properly or you don't have one at all.

**Comment by superight** [comment]
Having same issue it stop working in all my scripts was working fine just few days ago now its working i tried everything above but nothing worked for me any one can help please.

**Comment by ApacheEx** [comment]
@superight, pls provide the following info:
1) version of hybridauth library
2) version of your fb app (it's called API Version)
3) do you use composer installation ?

**Comment by superight** [comment]
@ApacheEx here are my settings:
1-I am not sure about version number but its at least one year old.
2-If your SDK that is also old version.
3-I used it in procedural php everything was working fine just a week i thing i m receiving complains about facebook login not working the same thing was working before.

Your Immediate reply is highly appreciated.

**Comment by ApacheEx** [comment]
@superight, 
1-2 I think here we have a problem. 

I highly recommended you to do the following steps:
1. Go to https://developers.facebook.com/apps/YOUR_APP_ID/dashboard and make sure that you use API version at least v2.3, if no please recreate your app or use Upgrade API tool.
2. Upgrade your hybridauth library to the latest stable version (v2.9.1 or even 2.9.2-dev)
3. If you use Facebook Login, go to https://developers.facebook.com/apps/YOUR_APP_ID/fb-login and make sure that you use hauth_done in Valid OAuth redirect URIs (before it was hauth.done)

**Comment by superight** [comment]
@ApacheEx Ok every thing is fine now i just need to upgrade hybridauth library i also download that but it showing me following error now  

> Class 'Facebook\Facebook' not found in /home/......................../lib/hybridauth/Hybrid/Providers/Facebook.php on line 56

I open hybridauth/Hybrid/Providers/Facebook.php and saw 

> use Facebook\Exceptions\FacebookSDKException;
> use Facebook\Facebook as FacebookSDK;

at the top of page but these files are not any where in hybridauth library
I am a bit confused what to do now

P.S All other providers working just fine after updating the hybridauth library.

**Comment by ApacheEx** [comment]
@superight, 

Yeah, fb-sdk was moved separately as composer package.
That's only one thing which is not fixed in the latest version. 
I've added a little PR which fix it.  Please try #760. 

And of course please not to forget run "composer install" in the root of hybridauth library

**Comment by superight** [comment]
@ApacheEx  ok done now its working but in getting this `http://example.com/scripts/login#_=_`

can you please tell me why?

**Comment by superight** [comment]
@ApacheEx forgive me that was not because of hybridauth library i m getting proper response Hybrid_User_Profile Object ( [identifier] => 1398135583576063 [webSiteURL] => [profileURL] => https://www.facebook.com/app_scoped_user_id/1398135583576063/ [photoURL] => https://graph.facebook.com/1398135583576063/picture?width=150&height=150 [displayName] => Altaf Hussain [description] => [firstName] => Altaf [lastName] => Hussain [gender] => male [language] => en_US [age] => [birthDay] => 20 [birthMonth] => 6 [birthYear] => 1994 [email] => superight.com@gmail.com [emailVerified] => superight.com@gmail.com [phone] => [address] => [country] => [region] => Gujrat [city] => [zip] => [job_title] => [organization_name] => ) see this :) thanks a lot for your time and help 👍 👍

**Comment by RazaLabs** [comment]
I had the issue with 2.3.0 Hybridauth lib, Here was my fix  [Comment by zeroduh at Drupal](https://www.drupal.org/node/2684015#comment-12020885)
also I  changed getHttpProtocol to return always 'https' as I am on cludflare SSL proxy.
Here is my base_facebook.php 
https://pastebin.com/dyZ4PtuM

**Comment by ApacheEx** [comment]
@RazaLab,

you know it's hack in fb library. IMHO it's weird to change the original code of external library (because will be hard to support / upgrade). 
That's why I purpose to use just the latest version of the library which should work (even if you use SSL proxy or any other stuff).

**Comment by RazaLabs** [comment]
@ApacheEx Thanks for your proposal, It is not just Hybridauth Library,  if we upgrade to latest HybridAuth library than we also need to upgrade our framework, due to lack of time we are unable to do so... But in near future we will port to the latest version, until than this hack/fix is fine with us.

**Comment by Kirancloudnix** [comment]
@tanmayk Awsome answer with clear instructions, thanks a lot

**Comment by vinothrajm** [comment]
Hi,
I have upgraded to latest hybridauth library files.

I get the following error while login with Facebook.

**Access token metadata contains unexpected app ID.0**

Note: It is working fine in my localhost. But not working in Live server.

Please help me.

**Comment by ApacheEx** [comment]
@vinothrajm,

Hi, can you provide more info:
1. which version of hybridauth library you have installed (2.x or 3.x) ?
2. do you use composer installation?
3. Which version of Facebook API have you? (check here https://developers.facebook.com/apps/YOUR_APP_ID/dashboard/)
4. Make sure you have correct Facebook id and secret in config.php

**Comment by vinothrajm** [comment]
@ApacheEx

Hi,

1. I have installed 2.x library files
2. I don't use composer. I have downloaded SDK files
3. API 2.8
4. Yes. I have checked it . Facebook id and secret key  are correct.

**Comment by ApacheEx** [comment]
@vinothrajm,

thanks for info, I see possible cases:
1. in your site configuration App ID is not the same as App ID on Facebook  
2. make sure you have installed https://github.com/facebook/php-graph-sdk (5.4)
3. somehow your HA config is not passed properly (maybe there is some custom code which brakes HA config).

have you used some CMS(F) or frameworks?

**Comment by vinothrajm** [comment]
@ApacheEx 

Thank you.

I have installed sdk 5.4 downlaoded from https://github.com/facebook/php-graph-sdk

I use CakePHP frame work

**Comment by vinothrajm** [comment]
I tried in another website also. But i have the same error.

**exception 'Exception' with message 'Access token metadata contains unexpected app ID.'**

**Comment by vinothrajm** [comment]
@ApacheEx 

 **public function validateAppId($appId)
    {	
		
		if ($this->getAppId() !== $appId) {
            throw new FacebookSDKException('Access token metadata contains unexpected app ID.', 401);
        }
    }**

I get **$appId** as **Integer** and **$this->getAppId()** as **String**.
So, that i throws an error.

**Comment by ApacheEx** [comment]
@vinothrajm,

Yeah, that's the reason. So in your config please use app ID in quotes

**Comment by vinothrajm** [comment]
@ApacheEx 

Thank you.

**Comment by follower90** [comment]
Also getting exception.
`Catchable error detected: 0 - DateTime::__construct(): It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone.`

I use composer, Hybrid Auth 2.9.6, and there facebook graph 5.6.1 (api version 2.10)

**Comment by ApacheEx** [comment]
@follower90, 
I think you see the problem, it's even not related to hybridauth library. To fix it on your server change `date.timezone` in your `php.ini` or use somewhere `date_default_timezone_set`

**Comment by follower90** [comment]
@ApacheEx Yeah, it works now, `date_default_timezone_set` was not helping, but found i needed to restart php-fpm to reload php.ini settings. Problem is solved. Thank you!
