### ISSUE TITLE
Any chances for PSR-4 ?

### ISSUE THREAD

**Issue by nntoan** [hybridauth/hybridauth#757]
Hello there,
I love namespace and Magento 2. But in the real life, Magento 2 sticks with namespaces things and I have to added them manually to Hybrid library at this moment.

Should I create my owned fork for this? Or we will do this on 3.x ?

Regards,
Toan

**Comment by isantolin** [comment]
@nntoan you can create a PR and submit the changes

**Comment by miled** [comment]
>Should I create my owned fork for this? Or we will do this on 3.x ?
Namespaces and autoloading are already done in v3.
