### ISSUE TITLE
 Call to undefined method Facebook\\Facebook::api()

### ISSUE THREAD

**Issue by christ0ph3r** [hybridauth/hybridauth#762]
Facebook recently updated their API so I had to update HybridAuth to the latest version.  I also added the Facebook SDK library under the thirdparty folder and required it.  I got the login working fine and most of the app working fine.  However some custom API call's no longer work.  I am a bit confused and wondering if anyone could help point me in the right direction.  This is a slimmed down version of what the code looks like.  This use to work but now I get " Call to undefined method Facebook\\Facebook::api()" in the error log.  What is the new method I am suppose to be using? Is there any examples I can view?

```php
// GET FACEBOOK FRIENDS COUNT
$hybridauth = new Hybrid_Auth( $config );
$adapter = $hybridauth->authenticate( "facebook" );
$taggable = $adapter->api()->api("/me/taggable_friends", "GET");
echo count( $taggable['data'] );
```

```php
// POST STATUS ON FACEBOOK
$hybridauth = new Hybrid_Auth( $config );
$service = $hybridauth->getAdapter("Facebook");
$service->api()->api("me/feed", "post", array(
  "message" => $message,
  "picture" => $campaign['picture'],
  "link"    => $campaign['link'],
  "name"    => $campaign['name'],
  "caption" => $campaign['caption'],
));
```

**Comment by miled** [comment]
I believe you'll have to use new methods get and post instead, ex: 
```
$taggable = $adapter->api()->get("/me/taggable_friends");
```
Because in the case of Facebook, `$adapter->api()` now returns an instance of `Facebook\Facebook`, and api requests must be done accordingly to their new SDK interface https://developers.facebook.com/docs/php/gettingstarted#making-requests

**Comment by christ0ph3r** [comment]
Hey @miled thanks so much for pointing me to the docs.  The code kept failing so I used the exceptions to catch the error.  An access token was required.  This is how I got it to work.

```php
$taggable = $adapter->api()->get( "/me/taggable_friends", $token );
$taggable_array = $taggable->getDecodedBody();
$total_fb_friends = count( $taggable_array['data'] );
```
