### ISSUE TITLE
So what's happening with HybridAuth 3?

### ISSUE THREAD

**Issue by CallumBrankin** [hybridauth/hybridauth#763]
At the moment it says on the readme.md that hybridauth is deprecated. Will the release of Hybridauth 3 change this? I see that Wordpress Social Login is migrating over to HybridAuth 3.

So will HybridAuth 3 change the deprecation status?

**Comment by hellboy81** [comment]
you should rewrite all the things using https://github.com/thephpleague/oauth2-client

**Comment by miled** [comment]
Yes, it does. I'll move that notice.
