### ISSUE TITLE
Error: redirect_uri_mismatch

### ISSUE THREAD

**Issue by TechFanDan** [hybridauth/hybridauth#764]
I keep getting the error redirect_uri_mismatch when attempting to use Google for authentication.

The URL indicated in the error is configured and enabled in the Google API. I've waited 30 minutes after having added this URL in the API before trying again. Also tried in an Incognito window. Same results.

Are there something that come to mind that one could be missing in such a scenario?

**Comment by hellboy81** [comment]
I have the same problem

**Comment by ddsky** [comment]
got the same problem, tells me 

> The redirect URI in the request, https://yoursite.com/hybridauth/?hauth.done=Google, does not match the ones authorized for the OAuth client. Visit...

I added both hauth.done=Google and hauth_done=Google as callbacks.

**Comment by ddsky** [comment]
@hellboy81 seems like you solved the problem, I don't understand how though. My redirect URL has only the hauth.done=Google parameter and the message from Google claims I didn't configure that. Do you have a hint for me?

**Comment by TechFanDan** [comment]
I just tried, after adding the full URL to the API, and it goes through but with a different error.

The URL I put in: https://mydomain.com/myapp/hybrid-auth/endpoint?hauth.done=Google

**Comment by hellboy81** [comment]
@ddsky It was issue with additional parameters for handling redirect in `done` "callback".
Google requires all *should* be encoded *only* in standard `state` param (which is used to prevent CSRF attacks) .

I am not using HA, I am using `oauth2-client`. Therefore I am not sure this is the same issue.

**Comment by ApacheEx** [comment]
> Google requires all should be encoded only in standard `state` param

@hellboy81, can you tell me a proof where this info can be found? I have google login in the production site (HA version is v2.9.5), and so far it works well.

**Comment by StorytellerCZ** [comment]
Closing in favor of #648.
