### ISSUE TITLE
PixelPin is interested in implementing OpenID Connect into HybridAuth 3

### ISSUE THREAD

**Issue by CallumBrankin** [hybridauth/hybridauth#765]
[PixelPin’s](https://www.pixelpin.co.uk) unique security advantage comes from the use of [picture login](https://login.pixelpin.io), eliminating passwords and their inherent weaknesses.

We use [OpenID Connect](http://openid.net/specs/openid-connect-core-1_0.html#Introduction) on top of OAuth 2 as our protocol. So we need a PHP base library to build our PHP plugins off from. Since HybridAuth 3 has most of the work already done, PixelPin will like to contribute to the project by implementing OpenID Connect along with PixelPin being HybridAuth 3's first OpenID Connect core provider. 

Are we free to do this?

**Comment by miled** [comment]
Yes, contributions are welcome. Ideally, OpenID Connect implementation wouldn't require any external dependency as HybridAuth is meant to be a self contained library.

**Comment by CallumBrankin** [comment]
Understood, PixelPin will start planning how to implement OpenID Connect.
