### ISSUE TITLE
Google Auth not working anymore

### ISSUE THREAD

**Issue by ddsky** [hybridauth/hybridauth#772]
I just updated to v 2.9.1 to fix the broken Facebook login (which works now) and now Google is not working anymore. I get "Try clearing your cookies. ERR_TOO_MANY_REDIRECTS".

In my Google API console I have both variants of redirect urls:
https://mysite.com/hybridauth/?hauth.done=Google
https://mysite.com/hybridauth/?hauth_done=Google

Any idea what causes this issue?

**Comment by mkhazov** [comment]
It didn't work for me neither until I cleared my website's cookies. But I had another error message in google response Invalid Credentials)

**Comment by ApacheEx** [comment]
Hi, 
it seems the issue not in hybridauth library (I have just checked and it works well so far). Perhaps, redirect path is wrong.

@ddsky,
do you use some CMS(F) or additional frameworks?

**Comment by ddsky** [comment]
No CMS, all self-coded. It used to work until I updated so I figured it must be an issue with hybridauth. Also I downgraded again and it is working with the old code.

**Comment by ApacheEx** [comment]
@ddsky, 
to which version exactly you have downgraded?

**Comment by ddsky** [comment]
@ApacheEx version 2.1.2

**Comment by ApacheEx** [comment]
@ddsky,
do you have `redirect_uri` in your HA config?

**Comment by ddsky** [comment]
@ApacheEx No, but where would that go, I didn't find any sample where the redirec_uri would be mentioned in the HA config?
