### ISSUE TITLE
OpenID example_04 fatal error

### ISSUE THREAD

**Issue by HowardF** [hybridauth/hybridauth#780]
Getting the following error when trying to implement example_04.php

Fatal error: Class Hybridauth\Provider\OpenID contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (Hybridauth\Adapter\AdapterInterface::apiRequest) in...

Am I missing a step?

Sorry I should have mentioned Version 3 - https://github.com/hybridauth/hybridauth/tree/master/examples

**Comment by StorytellerCZ** [comment]
Where are you getting the examples from?

**Comment by ApacheEx** [comment]
I guess [here](https://github.com/hybridauth/hybridauth/blob/master/examples/example_04.php) (v3.x)

**Comment by miled** [comment]
`apiRequest` was missing from abstract adapter class, but should be fixed now.

**Comment by HowardF** [comment]
Confirm accessing user profile now.Thank you. Tokens array is empty. Assume that is expected?

**Comment by miled** [comment]
Yes, that's expected. Tokens are for oauth based adapters.
