### ISSUE TITLE
Uncaught exception 'Exception' with message 'Could not authorize user. Bad request'

### ISSUE THREAD

**Issue by adityapurwa** [hybridauth/hybridauth#781]
I got this message after clicking on done when it showing a blocked URL notice:

`Uncaught exception 'Exception' with message 'Could not authorize user. Bad request'`

`URL Blocked: This redirect failed because the redirect URI is not whitelisted in the app’s Client OAuth Settings. Make sure Client and Web OAuth Login are on and add all your app domains as Valid OAuth Redirect URIs.`

The address when the popup is shown is as below:
`https://www.facebook.com/v2.8/dialog/oauth?auth_type=rerequest&client_id=530133577179948&state=4f22095121e7885d9cdad095f925fce1&response_type=code&sdk=php-sdk-5.4.4&redirect_uri=http%3A%2F%2Fdev3.wirednest.net%2Fcrossoverconceptstore%2Findex.php%2Fhauth%2Fendpoint%3Fhauth_done%3DFacebook&scope=email%2Cuser_about_me%2Cuser_birthday%2Cuser_hometown%2Cuser_location%2Cuser_website%2Cpublish_actions%2Cread_custom_friendlists`

I try setting the facebook callback uri as per the url above: `http://dev3.wirednest.net/crossoverconceptstore/index.php/hauth/endpoint?hauth_done=Facebook` but it still mentioning about URL blocked issue.

**Comment by ApacheEx** [comment]
Hi,

1. open https://developers.facebook.com/apps/YOUR_APP_ID/fb-login/
2. in Valid OAuth redirect URIs put `http://dev3.wirednest.net/crossoverconceptstore/hauth/endpoint?hauth_done=Facebook` (without index.php)

btw, do you any CMS(F) or frameworks? if it still fails, let us know.

**Comment by adityapurwa** [comment]
1. I use a modified CodeIgniter by previous developer.
2. I used the v.2.9.2
3. I manually download the release
4. I use PHP SDK 5.4..4

Sorry, I just noticed that I loaded the wrong configuration so it kept failing over because the it doesn't point to the correct FB application. It is working now.

Thank you for your helps!
