### ISSUE TITLE
Failed to open Stream problem

### ISSUE THREAD

**Issue by engharb** [hybridauth/hybridauth#782]
Hi,
I have integrated the hybridauth 2.9 via composer into my system, here I call the bybridauth class
$hybridauth = new \Hybrid_Auth($config);
$adapter = $hybridauth->getAdapter( 'Facebook' );

but I get the following error:
" failed to open stream: No such file or directory in /myProjectURI/vendor/hybridauth/hybridauth/hybridauth/Hybrid/Providers/Facebook.php:61 ..." (why is it like hybridauth/hybridauth/hybridauth it should be hybridauth/hybridauth/)

I added require_once(MAINDIR.'vendor/autoload.php'); to index.php and live.php,
but it does not help.

Could anyone help me.

Regards,

**Comment by ApacheEx** [comment]
Hi,

> why is it like hybridauth/hybridauth/hybridauth it should be hybridauth/hybridauth/
it's ok if you use `composer install hybridauth/hybridauth`

> I added require_once(MAINDIR.'vendor/autoload.php'); to index.php and live.php,
> but it does not help.
it's already fixed in v2.9.3-dev, you can check this PR #776.

**Comment by engharb** [comment]
How about the login to Facebook login page.
this is my controller impl.:
$hybridauth = new \Hybrid_Auth($config);

            $adapter = $hybridauth->getAdapter( 'Facebook' );

            $tokens = $adapter->getAccessToken();
      
            $userProfile = $adapter->getUserProfile();
But I get exception : User not connected to the provider.

My front end is: <a href="http://myWebsite/auth/facebook" data-type="fbook"></a>

Is there something should be added to the front end to popup the FB login form.?

**Comment by ApacheEx** [comment]
First of all, please read [documentation]
 (https://hybridauth.github.io/hybridauth/userguide/IDProvider_info_Facebook.html)

it should be like this:
```
 $hybridauth = new Hybrid_Auth( $config );
 $adapter = $hybridauth->authenticate( "Facebook" );
 $user_profile = $adapter->getUserProfile();
```

p.s. http://a.memegen.com/jy0j99.gif
