### ISSUE TITLE
Bug in class Hybrid_Provider_Model

### ISSUE THREAD

**Issue by engharb** [hybridauth/hybridauth#783]
I think the "loginFinish()" and "loginBegin()" functions must be defined as public instead of protected. Because these two functions are called in "Hybrid_Endpoint" class which does not inherits the "Hybrid_Provider_Model" class.

**Comment by engharb** [comment]
this issue related to v2.x-dev

**Comment by ApacheEx** [comment]
Hi,
Basically, each provider adapter has to define at least 3 methods which are **public**:
 *   Hybrid_Providers_{provider_name}::initialize()
 *   Hybrid_Providers_{provider_name}::loginBegin()
 *   Hybrid_Providers_{provider_name}::loginFinish()
so, there is no exception. But, IDE (e.g PhpStorm) thinks that `$hauth->adapter` is Hybrid_Provider_Model which has protected access (`loginFinish()` and `loginBegin()`).

I think you are right and they can be public. Here is PR #784

**Comment by ApacheEx** [comment]
@engharb, it's merged to `v2` branch, can you check?
