### ISSUE TITLE
Login with yahoo doesn't work

### ISSUE THREAD

**Issue by vinothrajm** [hybridauth/hybridauth#787]
We are getting the following error while login with Yahoo.

exception 'Exception' with message 'User id request failed! Yahoo returned an invalid response: stdClass::__set_state(array( 'error' => stdClass::__set_state(array( '@lang' => 'en-US', '@uri' => 'http://yahoo.com', 'description' => 'Access forbidden for the user as cookie validation failed', 'detail' => 'Access forbidden for the user as cookie validation failed', )), ))' in
socialauth/Hybrid/Providers/Yahoo.php:270

I have upgraded to the latest version of hybrid auth.

Note: Login with yahoo works fine in my localhost, but every time i need to approve the app to all access.

In live server, it doesn't work well.

Can you please help me to fix it out. Thanks in advance.

**Comment by ApacheEx** [comment]
can you check if it works for you with changes from this PR #788

**Comment by ApacheEx** [comment]
some issues were fixed and documentation was updated. Check once more #788.

**Comment by vinothrajm** [comment]
@ApacheEx 


I have updated the changes in #788 
Now it is working fine. 

But users need to authorize the app every time they login with Yahoo.
![Uploading everytime_login.png…]()
