### ISSUE TITLE
Login with Twitter : Unable to get User emailid

### ISSUE THREAD

**Issue by ravi24june1** [hybridauth/hybridauth#793]
I am unable to login with Twitter provider. 
After debugging the code, i found that emailid field contains null value.
When i have checked the app permission with twitter officials , it is found ok.

Finally i get the code where need to be changed .

File: Twitter.php - function getUserProfile()

$includeEmail = isset($this->config['includeEmail']) ? (bool) $this->config['includeEmail'] : false;

IncludeEmail default value should be true as below:
$includeEmail = isset($this->config['includeEmail']) ? (bool) $this->config['includeEmail'] : true;

There is no Email/user profile settings in HybridAuth configuration like facebook.

Hope this would  help to contributors and other users.

thanks
Ravi

## Bug, feature or question?

Is this a bug, a feature request or a question?
may be a bug

Give us a short description.

### Version and provider

What version of Hybrid Auth does this relates to?
v 2.9.2

Is this an issue with a provider? If yes, which one?
Twitter

### Reproduction

How can we replicate this issue?
Login with Twitter account

**Comment by ApacheEx** [comment]
Hi, it's not a bug. You can just change `includeEmail` to `true` in your config.php

as you can see in [`hybridauth/config.php`](https://github.com/hybridauth/hybridauth/blob/v2/hybridauth/config.php) (there is already param `includeEmail` which is false by default, so please change)

**Comment by ravi24june1** [comment]
Thanks
