### ISSUE TITLE
Invalid appsecret_proof provided in the API argument

### ISSUE THREAD

**Issue by engharb** [hybridauth/hybridauth#794]
Hi,

When I am trying to login to Facebook, I get the following error: User profile request failed! Facebook returned an error: Invalid appsecret_proof provided in the API argument.

can someone help me?

regards,

**Comment by ApacheEx** [comment]
Hi,
first of all, why you don't use this template? it's much easier to answer and help you when more info provided.


so, please update your description according to the template: https://github.com/hybridauth/hybridauth/blob/master/ISSUE_TEMPLATE.md


Thanks!
