### ISSUE TITLE
Can I use one Facebook app for multi websites

### ISSUE THREAD

**Issue by engharb** [hybridauth/hybridauth#795]
## question?

I have two Facebook apps for one test domain (http://testdomain.de), each app has its website url as (http://testdomain.de/auth/fb, http://testdomaibn.de/loginAuth/fb). I get error time to time from facebook may be because I am using two different apps in my application (the following error: User profile request failed! Facebook returned an error: Invalid appsecret_proof provided in the API argument.).
My question: is it possible to create one app for one domain but with different website url?

### Version and provider

v2.x-dev

Is this an issue with a provider? If yes, which one? 
fb, twitter

**Comment by ApacheEx** [comment]
thank you for more info,

you have one domain, so it should be one app. I'd say yes, it's possible. Just go to https://developers.facebook.com/apps/YOUR_APP/fb-login/ and provide two urls in that section `Valid OAuth redirect URIs`, hope it will help.

But the questions is why do you use two urls to do the same action (login by facebook)?

**Comment by engharb** [comment]
I have converted to use one FB app, but I still have getting the following error: User profile request failed! Facebook returned an error: Invalid appsecret_proof provided in the API argument.

Do someone have info?

**Comment by ApacheEx** [comment]
please check once more (HA config) if App Secret and App ID are correct and belong to your FB App

**Comment by ApacheEx** [comment]
if it still fails, please make sure that `Require App Secret` is disabled. You can go here and check

`https://developers.facebook.com/apps/YOUR_APP_ID/settings/advanced/`

**Comment by ApacheEx** [comment]
seems fixed and no other questions appear, I'm close this issue
