### ISSUE TITLE
Provider/Facebook.php triggers a Failed Warning file not found

### ISSUE THREAD

**Issue by mlubbers** [hybridauth/hybridauth#796]
## Bug, feature or question?
The file Provider/Facebook.php

require_once Hybrid_Auth::$config["path_libraries"] . "Facebook/autoload.php";
The Hybrid_Auth::$config["path_libraries"] reference to the thirdparty directory.
In this directory the directory Facebook doesn't exist.

and cause the page to breakdown.

### Version and provider

What version of Hybrid Auth does this relates to?
2.9.2
Is this an issue with a provider? If yes, which one?
Facebook
### Reproduction

How can we replicate this issue?
Uses de Facebook provider to login

**Comment by ApacheEx** [comment]
it's already fixed in v2.9.3-dev. There are many duplicates of this problem.

**Comment by visabhishek** [comment]
Hi ApacheEx, where can i find "v2.9.3-dev" please share the link.

**Comment by ApacheEx** [comment]
there is branch [v2](https://github.com/hybridauth/hybridauth/tree/v2). Please check it out.

**Comment by visabhishek** [comment]
Thanks ApacheEx, Its working fine.
