### ISSUE TITLE
Vendor Strava is set as strava instead of Strava.php and returns an error 500

### ISSUE THREAD

**Issue by XStreamke** [hybridauth/hybridauth#798]
## Bug
strava.php under the vendor directory should be called Strava.php
### Version and provider
HybridAuth v2.0.4
What version of Hybrid Auth does this relates to?
HybridAuth v2.0.4
Is this an issue with a provider? If yes, which one?

### Reproduction

How can we replicate this issue?
Just add the id and secret and you'll notice that it won't work. Rename strava.php into Strava.php and it will work.

**Comment by ApacheEx** [comment]
I agree with you, it looks like a bug. As workaround for your version, you can simply add `wrapper` in your config.php (more info [here](https://hybridauth.github.io/hybridauth/userguide/tuts/specific-provider-wrapper.html))
```
"Strava" => array(
    "enabled" => true,
    "wrapper" => array("path" => "Providers/strava.php", "class" => "Hybrid_Providers_Strava")
    ....
)
```

will you add PR with the fix or should I?

**Comment by XStreamke** [comment]
Hi, at the moment I just fixed it by changing the vendor name.
About the second thing: you can do it. I'm not the frequent GitHub user (and not familiarised with the common abbreviations).
