### ISSUE TITLE
Sometimes you don't need a JSON with id and secret but with key and secret (eg. LinkedIn)

### ISSUE THREAD

**Issue by XStreamke** [hybridauth/hybridauth#799]
## feature

When deploying an OAUTH for LinkedIn it didn't work...So I started analyzing the code and noticed that the magic happens under the vendor php's. There you'll see it wants key instead of id.
Maybe this can be mentioned under the homepage or something?

### Version and provider
HybridAuth v2.0.4
Is this an issue with a provider? If yes, which one?

### Reproduction

just add the key value as id/secret JSON format

**Comment by ApacheEx** [comment]
Hi,
basically, in v2 of HA library, LinkedIn based on OAuth1 protocol (Provider_Model_OAuth1) which requires `key` and `secret`. In this PR (#749) it's going to use OAuth2 protocol (Provider_Model_OAuth2) which requires `id` and `secret`. So, nothing to do here and hope it's clear for you.

**Comment by XStreamke** [comment]
OK, that's clear...But a bit strange then, because I only filled in a OAuthv2 call back URL. So I would suspect that the vendor isn't accepting a OAuthv1 version...And I didn't see a link on the app to enforce v2...

**Comment by ApacheEx** [comment]
now, I totally agree with @XStreamke. We don't need to have both options for consumer ids (`id`, `key`). 

**Some reasons:**
1. It's a bit confusing a user which one should be used.
2. It's always a breaking change when you migrate provider from Oauth1 to Oauth2.
3. and so on and so on.

**My proposition:**
1. Use always `ID` and `Secret`.
2. Add a backward capability for `key` but show a warning.
3. Remove the backward capability (let's say in 2.9.9).

@StorytellerCZ, @XStreamke what do you think, any other ideas? if agree I will start working on it.

**Comment by XStreamke** [comment]
Fine for me. I'm using a modx version (which apparently doesn't get updated often). But soon I'll perform the upgrade of the hybridauth manually.

**Comment by StorytellerCZ** [comment]
@ApacheEx Given that v3 is here, I don't see a reason why to introduce breaking changes into v2, but I'm fine with propositions 1 & 2.

**Comment by ApacheEx** [comment]
yeah, it's always a question for me, should we improve v2 or force users to use v3. 
I like v3, but need to finish upgrade guide and changelog, then other modules and users can use it or upgrade.

so, probably we need to close this issue (just in favor of v3).
