### ISSUE TITLE
hybridauth v2.9.3 and Codeigniter Configuration help!

### ISSUE THREAD

**Issue by omurkaangokyar** [hybridauth/hybridauth#800]
question?
I want to use hybridauth v2.9.3 with codeigniter.  When i follow standart configuration steps from https://hybridauth.github.io/hybridauth/userguide/Configuration.html address it doesnt work. 

(When i import autoload.php in Hybridauth.php is not find class Hybridauth)

I tried couple ways but always have class Hybridauth errors.( $hybridauth = new Hybridauth( $config );.)

I need hepl for config and autoload settings for Codeigniter Version 3.1.4. Thanx.

**Comment by ApacheEx** [comment]
How did you install HA library?

**Comment by omurkaangokyar** [comment]
First i download latest version from https://github.com/hybridauth/hybridauth/releases page.
In codeigniter application folder:
1- i create config file in config folder.
2- import Hybridauth folder in third_party folder.
3-  import autoload.php in Hybridauth.php
4- In Config file first declare ( require_once APPPATH.'/third_party/hybridauth/hybridauth.php'; ) then providers arrays. 
5- When i try to access user profile with import config file and declare $hybridauth = new Hybridauth( $config ); it shows error. No find class Hybridauth!

**Comment by ApacheEx** [comment]
Thanks for more info. Have you seen this https://github.com/andacata/HybridIgniter ? Perhaps it will help

**Comment by omurkaangokyar** [comment]
I know it but it is old version Hybridauth . And so different folder structures.
In https://hybridauth.github.io/hybridauth/userguide/Configuration.html  page shows old versions and old class name is Hybrid_Auth. But in hybridauth v2.9.3 have Hybridauth class.

Can u renew configuration details for hybridauth v2.9.3 please?

**Comment by ApacheEx** [comment]
> In https://hybridauth.github.io/hybridauth/userguide/Configuration.html page shows old versions and old class name is Hybrid_Auth
nope, it shows 2-x.x which looks quite actual, and I can say nothing changed in configuration between v2.1.2 and v2.9.3. Please be aware, in `master` branch there is v3 of HA library. So, you should check `v2` branch.

**Comment by omurkaangokyar** [comment]
I check it from https://github.com/hybridauth/hybridauth/releases page. 

-----------------------------
hybridauth-2.9.3 / src / Structure
-> Adapter
-> Data
-> Exception
-> HttpClient
-> Logger
-> Provider
-> Storage
-> Thirdparty
-> User
autoload.php
Hybridauth.php
index.html
-----------------------------
hybridauth-2.9.2 / Structure
-> Hybrid
config.php
index.php
live.php
-----------------------------
They are big differences from v2.9.2 to v2.9.3
For this reason i need help for latest version.
I have -> A PHP Error was encountered
Severity: Error
Message: Class 'Hybridauth' not found
Can you help me pls.Tnx.

**Comment by ApacheEx** [comment]
wow, this is 3.x version of HA library. Sorry, release was created not properly I guess. Please download from here: https://github.com/hybridauth/hybridauth/archive/v2.zip

@StorytellerCZ, can you recreate release from branch v2. Because https://github.com/hybridauth/hybridauth/tree/v2.9.3 has 3.x version 😮

**Comment by omurkaangokyar** [comment]
Thanks for quick answer. I will search my answer in 3.x version documents.

**Comment by StorytellerCZ** [comment]
@ApacheEx On it!
