### ISSUE TITLE
Version 2.9.3 on composer is actually v3 dev-master

### ISSUE THREAD

**Issue by Sroose** [hybridauth/hybridauth#802]
**Bug**

Composer actually installs the v3 code while my composer.json has:

    {
      "require": {
        "hybridauth/hybridauth": "~2.0"
      }
    } 

When you look at the composer site, packages, you will see 2.9.3 has the same source reference as the dev-master branch.

**Comment by ApacheEx** [comment]
yeah, I already mentioned here: https://github.com/hybridauth/hybridauth/issues/800#issuecomment-298318978

**Comment by StorytellerCZ** [comment]
Fixed and to make sure I have also released v2.9.4. Thanks!
