### ISSUE TITLE
Vimeo uses OAUTHv2 but HybridAuth is still using the Hybrid_Provider_Model and the deprecated phpVimeo

### ISSUE THREAD

**Issue by XStreamke** [hybridauth/hybridauth#804]
## Bug, feature or question?
Well...It isn't working now. I'm getting the returned an invalid Request Token error. So I assume that it needs improvement. But I also checked (and I'm changing the library locally so that it uses the new Vimeo php file.
Is this a bug, a feature request or a question?

Give us a short description.
The vimeo.php file in Providers directory is still using the deprecated phpVimeo class. Since Vimeo used OAuthv2 this doesn't need to be used any longer. I also believe the wrapper needs to be rewritten using the extends Hybrid_Provider_Model_OAuth2
### Version and provider

What version of Hybrid Auth does this relates to?
v2.9.1 (via Modx)
Is this an issue with a provider? If yes, which one?

### Reproduction

How can we replicate this issue?
Just try to create a new OAuth

**Comment by ApacheEx** [comment]
Hi,
yeah you are right, here is PR #807 🌞
