### ISSUE TITLE
How can i limit hybridauth login by ip address?

### ISSUE THREAD

**Issue by omurkaangokyar** [hybridauth/hybridauth#809]
Question
-------------
If user login with google provider, he cant login with twitter provider at the same ip address!
How can i do it?
Tnx

**Comment by ApacheEx** [comment]
> If user login with google provider, he cant login with twitter provider at the same ip address!

I think it's not related to this library and should be done by you. Anyways, do you use any CMS / frameworks?

**Comment by omurkaangokyar** [comment]
Codeigniter. 
I just wonder is it possible with hybridauth functions.
I quess it is possible with Hybridauth session insert in db with ip address and check it .
