### ISSUE TITLE
[Core] Consider making it easier to use custom OAuth (api) client classes

### ISSUE THREAD

**Issue by ragulka** [hybridauth/hybridauth#811]
### Background

Some shared hosts do not have cURL enabled, which is why sometimes a different transport must be used (for example, PHP streams) for making remote requests. For example, WordPress provides an abstract HTTP class, which uses either cURL or PHP streams for remote requests.

### Our use-case

We are subclassing `OAuth2Client` in WooCommerce Social Login to take advantage of this, and only need to override the `request()` method, but since that method is private, we also need to override any other methods calling it or referencing it at some point: `authenticate`, `tokenInfo`, `refreshToken`, `parseRequestResult` and `api`. This means we end up duplicating a lot of methods we wouldn't have to if the `request()` method was public (or at least protected).

Also, we need to subclass each provider so that we can overrde the `initialize()` method to provide our own oauth2 implementation for the api. However, we must override the whole `initialize()` method which is far from ideal, as it's prone to break should we need to upgrade HybridAuth.

### Proposals

* Make `request()` methods protected in all oauth client classes
* Introduce a way to provide a custom oauth class for an provider, for example via a protected `api_class` property (see below).

```php
class Hybrid_Provider_Model_OAuth2 extends Hybrid_Provider_Model {

  protected $api_class = 'OAuth2Client';

  protected function initialize() {
    //...
    $this->api = new $this->api_class($this->config["keys"]["id"], $this->config["keys"]["secret"], $this->endpoint, $this->compressed);
    //...
  }

  protected function request() {
    // default request() implementation, keep as-is
  }
}

class WP_OAuth2 extends OAuth2Client {
  protected function request() {
    // ... custom request implementation
  }
}

class Custom_Provider extends Hybrid_Provider_Model_OAuth2 {
  protected $api_class = 'WP_OAuth2';
}
```

**Comment by StorytellerCZ** [comment]
Are you talking about v2 or v3?

Wither way feel free to submit PR.

**Comment by sagudev** [comment]
I think it need to be like [PHPauth](https://github.com/PHPAuth/PHPAuth)

**Comment by ApacheEx** [comment]
v3 supports custom http client and you can do what you want. For v2 we won't do anything here.
