### ISSUE TITLE
Vimeo | Authentication failed! vimeo returned an invalid Request Token

### ISSUE THREAD

**Issue by omurkaangokyar** [hybridauth/hybridauth#812]
When try to login with vimeo it is invalid request token error.
In config array like this. 
--------------------
"vimeo" => array (
	"enabled" => true,
		"keys"    => array ("key" => "{Client Identifier}", "secret" => "{Client Secrets}", "access_token" =>"{Your new Access token}"),
        "token_type"=> "Bearer",
        "scope"   => ['public', 'private']
),
It doesnt work https://hybridauth.github.io/hybridauth/userguide/IDProvider_info_Vimeo.html tutorial. Provider Vimeo.php demand key, not id.

Is there any actual tutorials for providers login setup?
pls help.Tnx.

**Comment by ApacheEx** [comment]
Your config is wrong. Vimeo works only from v2.9.5 of HA library, please upgrade. There is worked example here https://hybridauth.github.io/hybridauth/userguide/IDProvider_info_Vimeo.html

**Comment by omurkaangokyar** [comment]
Thanks. i did it. its working.
