### ISSUE TITLE
Does hybridauth support testing with - Behat Mink UI test with Selenium

### ISSUE THREAD

**Issue by engharb** [hybridauth/hybridauth#819]
## question?

question?

Is there a hybridauth - Behat Mink UI test with Selenium? I need to write a Behat test for my social login 
process, where I can insert my test social account credential and get a response.... 

What version of Hybrid Auth does this relates to?
v2.x-dev

**Comment by ApacheEx** [comment]
it's UI tests, of course, you can write them, I don't see any problems or related question to HA.

> process, where I can insert my test social account credential and get a response....

in UI tests you can use DOM, so just put your credentials in specific HTML elements (e.g FB has `input#email`, `input#pass`). 
Then, you should submit a form where you wrote credentials (e.g FB has `form#login_form`). 
Finally, you should check a page after redirect if it's success or no. 

So, once more In UI tests, you should work **only** with UI stuff and HTTP responses.

**Comment by engharb** [comment]
thank you
