### ISSUE TITLE
Using $this when not in object context

### ISSUE THREAD

**Issue by mc388** [hybridauth/hybridauth#826]
## Bug

In my logout action I call `Hybridauth::disconnectAllAdapters()` and get the following error:

```
Type: Error
Message: Using $this when not in object context
File: /var/www/html/vendor/hybridauth/hybridauth/src/Hybridauth.php
Line: 198
```

### Version and provider

~3.0

### Reproduction

Just call `Hybridauth::disconnectAllAdapters()`

**Comment by miled** [comment]
None of Hybridauth class methods is meant to be called statically. The static keyword wasn't removed, but that will get rectified shortly.
