### ISSUE TITLE
how to get the age, birthdate, country ... in i.e Twitter and Facebook

### ISSUE THREAD

**Issue by engharb** [hybridauth/hybridauth#827]
question?

Could someone give me all possible array parameters of the hybridauth config file i.e Facebook =>
 array ('id', 'secret', 'age', '_fb_username_', 'fname', 'lname', '.....'); 
twitter, google too.

What version of Hybrid Auth does this relates to?
2.x-dev

Best regards,

**Comment by ApacheEx** [comment]
Hi, just check documentation, there is `getUserProfile()` which should return you all needed information.

Facebook: https://hybridauth.github.io/hybridauth/userguide/IDProvider_info_Facebook.html
