### ISSUE TITLE
Facebook Login - Authentication failed! Facebook returned an invalid user id.

### ISSUE THREAD

**Issue by yogeshjalodara** [hybridauth/hybridauth#829]
Hi
i'm trying to login with facebook with hybridauth in Codeigniter script but it gives an error in log like, Exception:Authentication failed! Facebook returned an invalid user id. -- Exception Object
where other social media login works fine. 
please help me.

Thanks
Yogesh

**Comment by ApacheEx** [comment]
please reformat your issue with https://github.com/hybridauth/hybridauth/blob/master/ISSUE_TEMPLATE.md

**Comment by engharb** [comment]
check your apps configuration/setting.
be sure website: your main site url,
and the redirect url.
also be sure that the fb app status is enabled.

**Comment by yogeshjalodara** [comment]
Hi, Thanks for your valuable suggestion. It was an issue of base_facebook.php

this article helped me.
[http://stackoverflow.com/questions/42994019/facebook-graph-api-not-work-from-2-2-to-2-3/43016312#43016312](url)

**Comment by ApacheEx** [comment]
@yogeshjalodara, please upgrade HA to v2.9.5 there are many improvements and bug fixes

**Comment by iatpatelishan** [comment]
Solution: https://stackoverflow.com/questions/42994019/facebook-graph-api-not-work-from-2-2-to-2-3

**Comment by ApacheEx** [comment]
@iatpatelishan, nope - it's a hack.
