### ISSUE TITLE
Is it possible to add multiple domains in one Twitter app?

### ISSUE THREAD

**Issue by engharb** [hybridauth/hybridauth#831]
## question

I have multiple domain for my application i.e xyz.de, xyz.com and I want to use one Twitter apps to handle all of request from these different domains. Is thatpossible by tw apps config. or programmatically.?

## version of Hybrid Auth
2.x-dev

**Comment by ApacheEx** [comment]
I guess yes. I know that in UI `https://apps.twitter.com/app/APP_ID/settings` you can provide only one path but I think it doesn't matter which path there. It will work in any way. So, just try to use the same credentials for different domains.
