### ISSUE TITLE
[Facebook] display setting not working

### ISSUE THREAD

**Issue by SuriyaPrakashWebDev** [hybridauth/hybridauth#832]
Hi,
  In my website, I have integrated HybidAuth for Facebook Login authentication. I have installed HybridAuth using composer and integrated all required codes as per the document. The login authentication is working and I'm getting the response too. But now it is redirecting to facebook login page in full screen, to overcome this they have a display setting which includes these different settings "page, popup, iframe, touch or wap".
  
  In this "page" is the default, when I change it to "popup" or "iframe" it is not working.
  
  My Reference Document: https://hybridauth.github.io/hybridauth/userguide/IDProvider_info_Facebook.html

  My Code sample:
  
	$configArray = array(
	   "base_url" => "<< my base url >>",
		   "providers" => array (
		   "Facebook" => array (
			   "enabled" => true, 
			   "keys" => array ( "id" => "<< my app ID >>", "secret" => "<< my app secret key >>" ),
			   "scope" => ['email', 'user_birthday', 'user_hometown'],  
			   "display" => "popup"
		   )
	   )
	);
	
	I have installed the latest version and also included required files in my program, I need someone's help to find a solution to this issue, so I can have the login screen in a pop-up or in iframe.
	
Thanks,
Suriya Prakash.M

**Comment by ApacheEx** [comment]
Hi,
this option doesn't make sense for the current implementation in HA because it will be always a page

here is a proof, from FB docs:
> If you are using the URL redirect dialog implementation, then this will be a full page display, shown within Facebook.com. This display type is called page.

this option will work only when you use Facebook SDK for JavaScript ¯\_(ツ)_/¯
so, nothing to do here.

**Comment by ApacheEx** [comment]
I have removed **display** option from docs.

**Comment by SuriyaPrakashWebDev** [comment]
okay thanks
