### ISSUE TITLE
[LinkedIn] Error! User has cancelled the authentication or the provider refused the connection.

### ISSUE THREAD

**Issue by 9meAhmed** [hybridauth/hybridauth#834]
Bug, feature or question?
Question i an havin this Error! User has cancelled the authentication or the provider refused the connection. (HybriedAuth)
Give us a short description.
i am having error when i am trying with provider linked in i have entered the key and the secret
Version and provider

i am using v 2.8 and the provider Facebook,Twitter,Google, Linkedin?

Is this an issue with a provider? If yes, which one?
i am having a issue with Linkedin
Reproduction

How can we replicate this issue?

**Comment by ApacheEx** [comment]
it sounds like "just do it!" for me, but what exactly to do? There are no details at all, or any steps how to reproduce it. ¯\_(ツ)_/¯

pls use this template and re-write your issue: https://github.com/hybridauth/hybridauth/blob/master/ISSUE_TEMPLATE.md

**Comment by ApacheEx** [comment]
thanks for more details, now it's better to understand.

can you try to upgrade your library to v2.9.5? there is new LinkedIn implementation which works via OAuth 2, and many many fixes in HA.

**Comment by ApacheEx** [comment]
please also make sure, that for LinkedIn in case of HA v2.9.5 you should use in your config: 
```
"keys" => array("id" => "", "secret" => "")
```
instead of 
```
"keys" => array("key" => "", "secret" => "")
```

**Comment by 9meAhmed** [comment]
i have updated it to v2.9.5 now there is error or redirect url mismatch i am using codigniter what will we the url 
controler: hauth, function: linkto

**Comment by ApacheEx** [comment]
![image](https://cloud.githubusercontent.com/assets/1918108/26487089/a75e9e8e-4206-11e7-953b-2d40f5cc2fc6.png)
can you tell me what you use here?

**Comment by 9meAhmed** [comment]
https://my.hello44.com/hauth/callback

**Comment by ApacheEx** [comment]
that's the main problem - it should be:

`https://my.hello44.com/hauth/callback?hauth.done=LinkedIn`

please read documentation once more, and make sure that redirect URL is correct for other providers.

**Comment by 9meAhmed** [comment]
i have added Authorized Redirect URLs:
https://my.hello44.com/hauth/callback?hauth.done=LinkedIn

but still the same error

![image](https://cloud.githubusercontent.com/assets/17180707/26488288/541c60b0-421c-11e7-8813-5a4a7ea82dc8.png)

**Comment by ApacheEx** [comment]
I'm confusing but`/hauth/endpoint` leads to 404, so you use wrong link, pls try this:
`https://my.hello44.com/hauth/endpoint?hauth.done=LinkedIn`

**Comment by 9meAhmed** [comment]
i did that before but now i am having this error
User profile request failed. Most likely the user is not connected to the provider and he should to authenticate again.

**Comment by ApacheEx** [comment]
can you show me some code how you get user profile after authorization?

**Comment by 9meAhmed** [comment]
public function linkto($provider)
	{

		$valid_providers = array();
		array_push($valid_providers,'facebook');
		array_push($valid_providers,'google');
		array_push($valid_providers,'googleplus');
		array_push($valid_providers,'linkedin');
		array_push($valid_providers,'twitter');
		array_push($valid_providers,'yahoo');
		array_push($valid_providers,'instagram');
		//array_push($valid_providers,'openid');
			
		if(in_array(strtolower($provider),$valid_providers))
		{
		}
		else
		{
			redirect('index.php/profile/');
			exit;
		}

		$this->load->model('site_core');
		$this->site_core->login_check();
		
		$this->credentials_arr = svar_get_credentials();
		$this->api_config_path = $this->config->item('api_config_path');
		$this->config->load($this->api_config_path.'common', FALSE, TRUE);
		$this->config->load($this->api_config_path.'hauth', FALSE, TRUE);
		$this->api_url = $this->config->item('BASE_URL');
		$this->input->post(NULL, TRUE); // returns all POST items with XSS filter 
		//log_message('debug', "controllers.HAuth.login($provider) called");
		if(_get_SESSION_VAL('sess_user_currency')==false)
		{
			redirect('index.php/profile/');
			exit;
		}	


		try
		{
			log_message('debug', 'controllers.HAuth.login: loading HybridAuthLib');
			$this->load->library('HybridAuthLib');

			if ($this->hybridauthlib->providerEnabled($provider))
			{

				log_message('debug', "controllers.HAuth.login: service $provider enabled, trying to authenticate.");
				$autharr = array();
				$autharr['hauth_return_to'] = base_url('index.php/hauth/linkto/'.$provider);
				$autharr['hauth_token']     = (session_id());
                $autharr['hauth_time']      = time();
				$autharr['login_start']     = base_url('index.php/hauth/endpoint?hauth.start='.$provider.'&hauth.time='.$autharr['hauth_time']);
				$autharr['login_done']      = base_url('index.php/hauth/endpoint?hauth.done='.$provider);
			
			    /*[hauth_time] => 13940880890

				[login_start] => https://my.hello44.com/index.php/hauth/endpoint?hauth.start=Facebook&hauth.time=1394088089
				[login_done] => https://my.hello44.com/index.php/hauth/endpoint?hauth.done=Facebook*/

				if(strtolower($provider) === strtolower('openid'))
					// Authenticate with Yahoo! then grab the user profile
					$service = $this->hybridauthlib->authenticate( "OpenID", array( "openid_identifier" => "https://me.yahoo.com/khaledatphp"));
				else
					$service = $this->hybridauthlib->authenticate($provider,$autharr);
			
			
				if ($service->isUserConnected())
				{
					log_message('debug', 'controller.HAuth.login: user authenticated.');
					
					//$user_c = $service->getUserCardDAVContacts();
					
					$user_profile = $service->getUserProfile();

					/*print_r($user_profile);
					exit();*/

					log_message('info', 'controllers.HAuth.login: user profile:'.PHP_EOL.print_r($user_profile, TRUE));
					
					$user_profile->provider = $this->uri->segment(3);
					/*foreach($user_profile as $k=>$v)
					{
						echo $k;
						echo '>>';
						echo $v;
						echo '<br>';
					}
					exit;*/
					
					$arr = array();
					$arr['show_ousers'] = (int)1;		
					
					$arr['oauth_provider'] 	= strtolower($user_profile->provider);	
					$arr['oauth_uid']		= $user_profile->identifier;
					$arr['oauth_username']	= $user_profile->displayName;
					if(!empty($user_profile->emailVerified))
						$arr['oauth_email']		= $user_profile->emailVerified;					
					else
					if(!empty($user_profile->email))
						$arr['oauth_email']		= $user_profile->email;					
					else
						$arr['oauth_email']		= 'no';					
						
						
					$arr['type'] = (string)'set';	
					$arr = array_merge($arr,$this->credentials_arr);
					
					$url = $this->api_url.$this->config->item('OAUTH_LINK_ACCOUNTS_API_URL');
					$d   = __send_curl_request($url,$arr);
                    $d	 = json_decode($d,true);
					
					if(isset($d['errors']) && $d['errors'] === (string)'no' && isset($d['response']) && is_array($d['response']))
					{
						if(isset($d['response']['update']) && (string)$d['response']['update'] === (string)'done')
						{
							redirect('index.php/account/profile');
							exit;							
						}
						redirect('index.php/account/profile');
						exit;							
					}
					else
					{
						redirect('index.php/account/profile');
						exit;							
					}
					
					
					/*foreach($user_profile as $k=>$v)
					{
						echo $k;
						echo '>>';
						echo $v;
						echo '<br>';
					}*/
					/*output of above foreach object*/
				//identifier>>1304054416
				//webSiteURL>>
				//profileURL>>https://www.facebook.com/khal3d.husa3n
				//photoURL>>https://graph.facebook.com/1304054416/picture?width=150&height=150
				//displayName>>Khalid Hussain
				//description>>
				//firstName>>Khalid
				//lastName>>Hussain
				//gender>>male
				//language>>
				//age>>
				//birthDay>>4
				//birthMonth>>2
				//birthYear>>1985
				//email>>khussain320@gmail.com
				//emailVerified>>khussain320@gmail.com
				//phone>>
				//address>>
				//country>>
				//region>>Multan
				//city>>
				//zip>>
				//provider>>Facebook
					/**/

					//$prep_key = uniqid();
				}
				else // Cannot authenticate user
				{
					
					//echo json_encode(array('error'=>'yes','msg'=>'cannot authenticate user'));
					//exit;
					#show_error('Cannot authenticate user');
                    $data['message'] = 'Can not authenticate user';
                    _show_errors($data);
				}
			}
			else // This service is not enabled.
			{
				log_message('error', 'controllers.HAuth.login: This provider is not enabled ('.$provider.')');
				#show_404($_SERVER['REQUEST_URI']);
                $data['message'] = 'This provider is not enabled ('.$provider.')';
                _show_errors($data);
			}
		}
		catch(Exception $e)
		{

			$error = 'Unexpected error';
			switch($e->getCode())
			{
				case 0 : $error = 'Unspecified error.'; break;
				case 1 : $error = 'Hybriauth configuration error.'; break;
				case 2 : $error = 'Provider not properly configured.'; break;
				case 3 : $error = 'Unknown or disabled provider.'; break;
				case 4 : $error = 'Missing provider application credentials.'; break;
				case 5 : log_message('debug', 'controllers.HAuth.login: Authentification failed. The user has canceled the authentication or the provider refused the connection.');
				         //redirect();
				         if (isset($service))
				         {
				         	//log_message('debug', 'controllers.HAuth.login: logging out from service.');
				         	$service->logout();
				         }
				         #show_error('User has cancelled the authentication or the provider refused the connection.');
				         $error = 'User has cancelled the authentication or the provider refused the connection.';
				         break;
				case 6 : $error = 'User profile request failed. Most likely the user is not connected to the provider and he should to authenticate again.';
				         break;
				case 7 : $error = 'User not connected to the provider.';
				         break;
			}

			if (isset($service))
			{
				$service->logout();
			}

			//log_message('error', 'controllers.HAuth.login: '.$error);
			#show_error('error authenticating user'. 'controllers.HAuth.login: '.$error);
            
            $data['message'] = $error;
            _show_errors($data);
		}
	}

	public function endpoint()
	{
		//log_message('debug', 'controllers.HAuth.endpoint called.');
		#log_message('info', 'controllers.HAuth.endpoint: $_REQUEST: '.print_r($_REQUEST, TRUE));
       /*print_r($_REQUEST);
       exit();*/
        
        $hauth_done = ($this->input->get('hauth_done'));

        $prob = $this->input->get('oauth_problem');

        if($hauth_done == 'LinkedIn' and $prob == 'user_refused')
        {
            $data['message'] = 'The request get refused';
            _show_errors($data);
        }
        else
		if ($_SERVER['REQUEST_METHOD'] === 'GET')
		{
			//log_message('debug', 'controllers.HAuth.endpoint: the request method is GET, copying REQUEST array into GET array.');
			$_GET = $_REQUEST;
            require_once APPPATH.'/third_party/hybridauth/index.php';
		}
		//log_message('debug', 'controllers.HAuth.endpoint: loading the original HybridAuth endpoint script.');
	}

**Comment by 9meAhmed** [comment]
public function login($provider, $user_type='provider')
    {

        log_message('debug', "controllers.HAuth.login($provider) called");

        try
        {
            log_message('debug', 'controllers.HAuth.login: loading HybridAuthLib');
            $this->load->library('HybridAuthLib');


            // echo "hre";
            // exit;

            if ($this->hybridauthlib->providerEnabled($provider))
            {
                log_message('debug', "controllers.HAuth.login: service $provider enabled, trying to authenticate.");



                $service = $this->hybridauthlib->authenticate($provider);

                if ($service->isUserConnected())
                {
                    log_message('debug', 'controller.HAuth.login: user authenticated.');


                    $user_profile = $service->getUserProfile();

                    log_message('info', 'controllers.HAuth.login: user profile:'.PHP_EOL.print_r($user_profile, TRUE));

                    if(count($user_profile) <= 0)
                    {
                        $this->session->set_flashdata('alert_data', array('type' => 'danger', 'description' => 	'Unable to get data'));
                        redirect('login/');
                    }


                    $data_array = array(

                        'first_name'     => $user_profile->firstName,
                        'last_name'      => $user_profile->lastName,
                        'display_name'   => $user_profile->displayName,
                        'email'          => $user_profile->email,
                        'email_verified' => $user_profile->emailVerified,
                        'address'        => $user_profile->address,
                        'country'        => $user_profile->country,
                        'identifier'     => $user_profile->identifier,
                        'auth_provider'  => $provider
                    );
                }
                else // Cannot authenticate user
                {
                    show_error('Cannot authenticate user');
                }
            }
            else // This service is not enabled.
            {

                log_message('error', 'controllers.HAuth.login: This provider is not enabled ('.$provider.')');
                show_404($_SERVER['REQUEST_URI']);
            }
        }
        catch(Exception $e)
        {
            $error = 'Unexpected error';
            switch($e->getCode())
            {
                case 0 : $error = 'Unspecified error.'; break;
                case 1 : $error = 'Hybriauth configuration error.'; break;
                case 2 : $error = 'Provider not properly configured.'; break;
                case 3 : $error = 'Unknown or disabled provider.'; break;
                case 4 : $error = 'Missing provider application credentials.'; break;
                case 5 : log_message('debug', 'controllers.HAuth.login: Authentification failed. The user has canceled the authentication or the provider refused the connection.');
                         //redirect();
                         if (isset($service))
                         {
                             log_message('debug', 'controllers.HAuth.login: logging out from service.');
                             $service->logout();
                         }
                         show_error('User has cancelled the authentication or the provider refused the connection.');
                         break;
                case 6 : $error = 'User profile request failed. Most likely the user is not connected to the provider and he should to authenticate again.';
                         break;
                case 7 : $error = 'User not connected to the provider.';
                         break;
            }

            if (isset($service))
            {
                $service->logout();
            }

            log_message('error', 'controllers.HAuth.login: '.$error);
            show_error('Error authenticating user.');
        }
    }

**Comment by 9meAhmed** [comment]
now having this statement
Error!
User profile request failed. Most likely the user is not connected to the provider and he should to authenticate again

**Comment by ApacheEx** [comment]
as I understand you use this?
https://github.com/andacata/HybridIgniter

perhaps the issue is related to that lib. But, can you debug that  `catch(Exception $e)`, just log `$e->getMessage()`

**Comment by ApacheEx** [comment]
any updates?

**Comment by ApacheEx** [comment]
@9meAhmed, have you solved this issue? is it still actual?

**Comment by 9meAhmed** [comment]
resolved

**Comment by mondalarup** [comment]
@9meAhmed how did u fix this? I am also fetching same problem

**Comment by anuraggu** [comment]
I think issue in passport-oauth2 module and user_cancelled_login error is not handle. you can delete this module and paste this https://github.com/anuraggu/passport-oauth2.git link package.json file after that install the module
