### ISSUE TITLE
[LinkedIn] User profile request failed! LinkedIn returned an invalid response

### ISSUE THREAD

**Issue by 9meAhmed** [hybridauth/hybridauth#835]
Is this a bug, a feature request or a question?

i am having this exception 

User profile request failed! LinkedIn returned an invalid response: stdClass::__set_state(array(
))

i am using v2.9.5 and the provider is Linkedin
Is this an issue with a provider? If yes, which one?

How can we replicate this issue?

**Comment by ApacheEx** [comment]
How can we replicate this issue? which config you use (scope and so on)?

**Comment by 9meAhmed** [comment]
This is the config i am using

<?php if ( ! defined('BASEPATH')) exit('No direct script access allowed');
/*!
* HybridAuth
* http://hybridauth.sourceforge.net | https://github.com/hybridauth/hybridauth
*  (c) 2009-2011 HybridAuth authors | hybridauth.sourceforge.net/licenses.html
*/

// ----------------------------------------------------------------------------------------
//	HybridAuth Config file: http://hybridauth.sourceforge.net/userguide/Configuration.html
// ----------------------------------------------------------------------------------------

$config =
	array(
		// set on "base_url" the relative url that point to HybridAuth Endpoint
		'base_url' => '/hauth/endpoint',
		//'base_url' => 'https://my.hello44.com/',

		'providers' => array (
			// openid providers
			'OpenID' => array (
				'enabled' => TRUE
			),

			'Yahoo' => array (
				'enabled' => TRUE,

				'keys'    => array ( "key" => "", 
				"secret" => "" ),
			),

			'AOL'  => array (
				'enabled' => TRUE
			),

			'Google' => array (
				'enabled' => TRUE,

				'keys'    => array ( "id" => "", "secret" => "" ),
				//'keys'    => array ( "id" => "768182982400.apps.googleusercontent.com", "secret" => "z4utZCTfdc_YGn_3sWhqQpt_" ),
				'scope'   => ''
			),

			'Facebook' => array (
				'enabled' => TRUE,
				
				'keys'    => array ( "id" => "", "secret" => "" ),

				'scope'   => '',

				'display' => ''

			),
			'Twitter' => array (
				'enabled' => TRUE,
				'keys'    => array ( "key" => "", "secret" => "" )
			),

			// windows live
			'Live' => array (
				'enabled' => TRUE,
				'keys'    => array ( "id" => "", "secret" => "" )
			),

			'MySpace' => array (
				'enabled' => TRUE,
				'keys'    => array ( "key" => "", "secret" => "" )
			),
            #https://www.linkedin.com/developer/apps
			'LinkedIn' => array (
				'enabled' => TRUE,

				'keys'    => array ( "key" => "", "secret" => "" )
			),

			'Foursquare' => array (
				'enabled' => TRUE,
				'keys'    => array ( "id" => "", "secret" => "" )
			),
		),

		// if you want to enable logging, set 'debug_mode' to TRUE then provide a writable file by the web server on "debug_file"
		'debug_mode' => false,
		'debug_file' => null,
		
        #'debug_mode' => TRUE,
		#'debug_file' => APPPATH.'logs/auth.php',
		
		#'debug_mode' => (ENVIRONMENT == 'development'),
		#'debug_file' => APPPATH.'/logs/hybridauth.log',
		//'debug_file' => '',
	);

**Comment by ApacheEx** [comment]
As I see, all providers are enabled but there are no information about consumer id/key or secret, make sure that for LinkedIn you use `id and secret`, for more info check [documentation](https://hybridauth.github.io/hybridauth/userguide/IDProvider_info_LinkedIn.html)

**Comment by 9meAhmed** [comment]
i do have id/key for the consumer but i didnt posted

**Comment by ApacheEx** [comment]
ok, your config looks like this, right?

```
$config = array(
  "base_url" => "http://mywebsite.com/path/to/hybridauth",
  "providers" => array(
    "LinkedIn"  => array(
      "enabled" => true,
      "keys"    => array("id" => "YOUR_CLIENT_ID", "secret" => "YOUR_CLIENT_SECRET"),
      "scope"   => array("r_basicprofile", "r_emailaddress"),
    ),
  ),
);
```

and here `https://www.linkedin.com/developer/apps/YOUR_APP_ID/auth` you have checked?
![image](https://cloud.githubusercontent.com/assets/1918108/26539895/6384c320-4457-11e7-9a22-91fb0c6733e2.png)

**Comment by 9meAhmed** [comment]
thanks its working now 👍
