### ISSUE TITLE
Envato - Error - authenticating user?

### ISSUE THREAD

**Issue by sanug** [hybridauth/hybridauth#837]
Im using Hybridauth 2.9.5 version. I set redirect url and etc. 
Why is that error. Please help?

**Comment by StorytellerCZ** [comment]
What error? Please provide more information and the error message.

**Comment by omurkaangokyar** [comment]
I have envato api key and secret key. And i setup redirect uri is correctly (same setting more than 10 providers). After signin process, it show Error : Error authenticating user.

**Comment by ApacheEx** [comment]
@omurkaangokyar,
which redirect uri have you exactly setup?

**Comment by omurkaangokyar** [comment]
With Codeigniter. 
http://localhost/social/endpoint?hauth.done=Envato

**Comment by ApacheEx** [comment]
pls add to your config:
```
"scope" => "default user:username user:email"
```

**Comment by omurkaangokyar** [comment]
Same Error.
An Error Was Encountered
Error authenticating user.

**Comment by ApacheEx** [comment]
it seems you use something like this: [HybridIgniter](https://github.com/andacata/HybridIgniter)

can you enable logs in your config and give me more details from here `/logs/hybridauth.log`?

**Comment by omurkaangokyar** [comment]
I didnt use hybridigniter. And dont save log files. I used hybridauth 295 and i have succesfull 16 providers. In config i guess envato need extra values.I try to add redirect uri like google but it doesnt work. Everything looks good. but after signin completed and approve the envato app permission it turns empty values and show this error. I couldnt find solution :( Thanks for helps
