### ISSUE TITLE
Configurable photoURL dimensions

### ISSUE THREAD

**Issue by GusAntoniassi** [hybridauth/hybridauth#844]
Currently from what I see in the providers configuration files the photoURL dimensions are set in code and there is no way to configure it. Facebook for instance:
```
// hybridauth/Hybrid/Providers/Facebook.php - line 249
$this->user->profile->photoURL = !empty($this->user->profile->identifier) ? "https://graph.facebook.com/" . $this->user->profile->identifier . "/picture?width=150&height=150" : ''; // width and height set to 150
```

I know not every provider has a way to set photoURL dimensions, but could this be turned into a configuration for the ones that provide it?

### Version
v2.9.5

Thanks in advance.

**Comment by ApacheEx** [comment]
Makes sense.
I will add an option `photo_size`, so it will be like `width={$photo_size}&height={$photo_size}`. Hope, it's good for you.

**Comment by ApacheEx** [comment]
@GusAntoniassi, 
ok, it should work. The changes in v2 branch (_v2.9.6-dev_). To use, just add this to your config:
```
"photo_size" => 200,
```
