### ISSUE TITLE
twitter get email

### ISSUE THREAD

**Issue by xaiborweb** [hybridauth/hybridauth#847]
I have application permission to request the email on twitter
As you can see in this picture: https://i.gyazo.com/9a3beebd0acb3f4cf6caee4aa89e5fb5.png

In the configuration of hybridauth I have:
"Twitter" => array (
				"enabled" => true,
				"keys"    => array ( "key" => "", "secret" => "" ),
				"includeEmail" => true,
			),
But do not bring twitter email, any solution please?

**Comment by ApacheEx** [comment]
You need to have something like this:
![image](https://user-images.githubusercontent.com/1918108/27996796-ca899422-64f2-11e7-860e-bbb417b46528.png)

To do this, pls provide the following settings here (https://apps.twitter.com/app/YOUR_APP_ID/settings):
![image](https://user-images.githubusercontent.com/1918108/27996800-e4f16c2c-64f2-11e7-8dad-28f8dd03423a.png)

Make sure you have enabled `Request email addresses from users` here (https://apps.twitter.com/app/YOUR_APP_ID/permissions):
![image](https://user-images.githubusercontent.com/1918108/27996809-01b7455c-64f3-11e7-8dcf-4f8d8e6cb30d.png)

**Comment by xaiborweb** [comment]
Thanks I found the error only had to regenerate the key token for the changes to be applied, thanks.
