### ISSUE TITLE
[Windows live] Problem redirect url - Question

### ISSUE THREAD

**Issue by kurtvergeyle** [hybridauth/hybridauth#849]
Hi,

I'm using library version v2.9.6 (together with Drupal) and try to implement Windows Live login.

In the Windows Live application I put as RedirectUrl https://mydomain/hybridauth/endpointlive.php (url that works to get the login-form of Windows Live). After logging in, I will be redirected to https://mydomain/hybridauth/endpointlive.php?code=Me1f265d2-ae72-e27... and for this url the website gives a 404-error (and we are not logged in to the site).

Probably I missed something in configuration. Could someone help me to let this work?

FYI:
Drupal version I'm using is 7.41, together with drupal module HybridAuth Social Login v. 7.x-2.15.

Thanks!
Kurt

**Comment by ApacheEx** [comment]
Hi, 
it seems Drupal module is not well adapted to login with Windows Live, but you can try this workaround:

1. Let's create a hook_menu (e.g. in `my_module`):
```php
/**
 * Implements hook_menu().
 */
function my_module_menu() {
  $items['hybridauth/live'] = array(
    'page callback' => 'my_module_hybridauth_live_endpoint',
    'access arguments' => array('use hybridauth'),
    'type' => MENU_CALLBACK,
  );
  return $items;
}
```
2. Then create this page callback:
```php
/**
 * Handle Windows Live auth.
 */
function my_module_hybridauth_live_endpoint() {
  $_REQUEST['hauth_done'] = 'Live';
  hybridauth_endpoint();
}
```
3. Set redirection URI as `https://mydomain/hybridauth/live`
4. Proooofit

p.s. I will take care to have this in contrib module.

**Comment by ApacheEx** [comment]
and it seems you also need to implement:

```php
/**
 * Implements hook_hybridauth_provider_config_alter().
 */
function my_module_hybridauth_provider_config_alter(&$config, $provider_id) {
  switch ($provider_id) {
    case 'Live':
      $config['hauth_return_to'] = url('hybridauth/live', array(
        'absolute' => TRUE, 
        'language' => _hybridauth_language_default(),
      ));
      break;
  }
}
```

**Comment by kurtvergeyle** [comment]
Hi,

Seems to work! You made my day!

Just 1 fix added in the library, because the redirect_url was still https://mydomain/hybridauth/endpointlive.php

File: libraries/hybridauth/hybridauth/Hybrid/Provider_Adapter.php 
`if ($this->id=="Live") {`
`$domain = str_replace('endpoint', '', $HYBRID_AUTH_URL_BASE);`
`$this->params["login_done"] = $domain.'live';`
`}`
This will generate the correct redirect_uri to Windows Live (https://mydomain/hybridauth/live)

Regards!

**Comment by mng4** [comment]
Hi, I'm facing the same issue with Windows live. I'm not familiar with drupal code system. Would you mind telling me which files do I need to edit?
Thanks.
