### ISSUE TITLE
How to set Twitter scope?

### ISSUE THREAD

**Issue by gonzela2006** [hybridauth/hybridauth#850]
## Question

How can I set/change the twitter scope to only get user email and profile public data

### Version and provider

Hybrid Auth version 2.9.6

Provider: Twitter

Thanks

**Comment by ApacheEx** [comment]
Hi,
1. I think you just need to change your permissions in twitter app (https://apps.twitter.com/app/APP_ID/permissions) like this
![image](https://user-images.githubusercontent.com/1918108/28403403-30f00bb4-6d2d-11e7-87f7-fc9ed84c50ea.png)

2. And make sure that you have filled _Privacy Policy URL_ and _Terms of Service URL_ and _Allow this application to be used to Sign in with Twitter_ (https://apps.twitter.com/app/APP_ID/settings) like this:
![image](https://user-images.githubusercontent.com/1918108/28403505-9e6397ce-6d2d-11e7-8de3-4c6b3ba348f4.png)

**Comment by gonzela2006** [comment]
@ApacheEx Thank you very much It is working well now :)
