### ISSUE TITLE
Facebook- Authentication failed. The user has canceled the authentication or the provider refused the connection.

### ISSUE THREAD

**Issue by nipungarg6138** [hybridauth/hybridauth#852]
Few months ago it was working fine. Today i got to know that  some users are not able to login by facebook.

There are no changes was done. 

HybridAuth version is 2.7.

Redirect URI - http://www.verjobs.com/auth/?hauth.done=Facebook and http://www.verjobs.com/auth/?hauth_done=Facebook

I tried both.

When above error/message appear on the screen. Url is showing this 
http://www.verjobs.com/login-with.php?provider=Facebook#_=_

Let me know if you need any code or something.

Please advise what to do.

**Comment by ApacheEx** [comment]
Hi,
I've tried to login on your site, and what I got from facebook login screen (url):

1) `sdk=php-sdk-3.2.3`
    - it seems you have very old version of [php-graph-sdk](https://github.com/facebook/php-graph-sdk). You have to upgrade it to at least 5.5.0.
    - do you use composer ? if so, you can run `composer install` in hybridauth library and php-graph-sdk will be updated automatically.

2) `redirect_uri=http://www.verjobs.com/auth/?hauth.done=Facebook`:
    - please use `http://www.verjobs.com/auth/?hauth_done=Facebook`
    - make sure it exists in `https://developers.facebook.com/apps/1612692002357929/fb-login/` as `Valid OAuth redirect URIs`

p.s. do you use any frameworks?

**Comment by nipungarg6138** [comment]
No. I am not using composer as i am on shared host. Any idea how can i use composer in shared hosting. I am not using any framework. 

Do i need to upgrade hybridauth as well.

I am not sure what you are trying to say in section 2.

redirect_uri=http://www.verjobs.com/auth/?hauth.done=Facebook:

please use http://www.verjobs.com/auth/?hauth_done=Facebook
make sure it exists in https://developers.facebook.com/apps/1612692002357929/fb-login/ as Valid OAuth redirect URIs


Please explain a bit.

**Comment by ApacheEx** [comment]
> i will change it to http://www.verjobs.com/auth/?hauth_done=Facebook

That's what I meant. For Facebook `hauth_done` is more correct than `hauth.done`

btw, there is workaround how to use facebook login without composer:

1. You need to download https://github.com/facebook/php-graph-sdk and put `src/Faceboook` directory under `/Hybrid/thirdparty/` directory.
2. Make sure that `/Hybrid/thirdparty/Facebook/autoload.php` exists.

So, Hybridauth will include this file and start using the classes that library provides.

**Comment by nipungarg6138** [comment]
Thanks for your prompt response. I will try tonight and share the status with you.

**Comment by nipungarg6138** [comment]
I copied the facebook sdk inside thirdpary directory. There is a existing file base_facebook.php

In this file i can see 

[abstract class BaseFacebook
{
  /**
   * Version.
   */
  const VERSION = '3.2.3';

  /**
   * Signed Request Algorithm.
   */
  const SIGNED_REQUEST_ALGORITHM = 'HMAC-SHA256';

  /**
   * Default options for curl.
   *
   * @var array
   */
  public static $CURL_OPTS = array(
    CURLOPT_CONNECTTIMEOUT => 10,
    CURLOPT_RETURNTRANSFER => true,
    CURLOPT_TIMEOUT        => 60,
    CURLOPT_USERAGENT      => 'facebook-php-3.2',
  );](url)

Do i need to make any changes in this because when i check the facebook url it is still showing sdk version 3.2.3 and i am not sure how can i change hauth.done to hauth_done.

I made the changes in facebook uri section but it seems like it is not updating in the request.

https://www.facebook.com/dialog/oauth?client_id=1612692002357929&redirect_uri=http%3A%2F%2Fwww.verjobs.com%2Fauth%2F%3Fhauth.done%3DFacebook&state=cee5ae1bcc73e014dd6c376377ed4&sdk=php-sdk-3.2.3&scope=email%2C+user_about_me%2C+user_birthday%2C+user_hometown%2C+user_location%2C+user_website%2C+publish_actions%2C+read_custom_friendlists&display=page

**Comment by ApacheEx** [comment]
oh, sorry. The latest stable version of hybridauth is 2.9.6, pls upgrade and issue will be disappeared. There are a lot of fixes for facebook.

**Comment by nipungarg6138** [comment]
Yes, I did that and issue has been fixed. I will check Linkedin and Google later today. Not sure after upgrade they are working or not.

**Comment by nipungarg6138** [comment]
Facebook is working fine. Now i am getting error for Linkedin. You can close this issue. I will check and fix Linkedin. If needed i will open new issue.
