### ISSUE TITLE
Google Authentication throws an Endless Redirection error!

### ISSUE THREAD

**Issue by cssjockey** [hybridauth/hybridauth#853]
## Question

Google Authentication throws and Endless Redirection! error. I've tried both

lib/hybridauth/?hauth_done=Google
lib/hybridauth/?hauth.done=Google

Nothing in the log file and I am stuck.

Facebook and Twitter work fine with the same code but Google Login isn't.

CONFIGURATION:
```
[base_url] => https://LIBRARY-PATH/hybridauth/
[providers] => Array
    (
        [Google] => Array
            (
                [enabled] => 1
                [keys] => Array
                    (
                        [id] => ID
                        [key] => ID
                        [secret] => SECRET
                    )

                [scope] => https://www.googleapis.com/auth/plus.login https://www.googleapis.com/auth/plus.me https://www.googleapis.com/auth/plus.profile.emails.read
                [display] => popup
            )

    )

[wrapper] => Array
    (
        [class] => Hybrid_Providers_Google
        [path] => /LIBRARY-PATH/hybridauth/Hybrid/Providers/Google.php
    )

[trustForwarded] => 1
[redirect_uri] => https://LIBRARY-PATH/hybridauth/?hauth_done=Google
[debug_mode] => 1
[debug_file] => /PATH/wp-content/cjaddons-hybridauth-debug.txt
```

### Version and provider

Hybridauth v2.9.6

Google

### Reproduction

https://cssjockey.com/?process-social-login=google

**Comment by StephenAtty** [comment]
Isn't the config for google:
Google" => array(
            "enabled" => true,
            "keys" => array("id" => "my key in here", "secret" => "my secret in here"),
                      "scope"   => "https://www.googleapis.com/auth/plus.login ". // optional
                       "https://www.googleapis.com/auth/plus.me ". // optional
                       "https://www.googleapis.com/auth/plus.profile.emails.read", // optional
          "access_type"     => "offline",   // optional
          "approval_prompt" => "force", 
          "state" => "",	    // optional
        ),

**Comment by cssjockey** [comment]
Any update on the fix for this issue?

**Comment by cssjockey** [comment]
Hi, This issue still exists in v2.10.0. Please provide a solution to this.

**Comment by ApacheEx** [comment]
from your config:
you use at the same time ID and KEY - it's completely wrong.

Please check documentation once more. https://hybridauth.github.io/hybridauth/userguide/IDProvider_info_Google.html

it should be `hauth.done=Google`
and `trustForwarded` should disabled.

**Comment by ApacheEx** [comment]
I couldn't reproduce this issue with HA 2.10.

**Comment by cssjockey** [comment]
Hi @ApacheEx, 
I tried the settings you suggested but its still the same.
I've enabled Google on my site so you can see the error. 
https://cssjockey.com/?process-social-login=google

**Comment by ApacheEx** [comment]
@cssjockey,

Please make sure that `Authorized redirect URIs` will equal `https://cssjockey.com/wp-content/plugins/addon-social-login/lib/hybridauth/?hauth.done=Google` in your Google App. 
Is that true?

**Comment by cssjockey** [comment]
@ApacheEx Its the same in Google settings. https://prnt.sc/hiy740

**Comment by ApacheEx** [comment]
hmm, then let's once more check configuration.
which exactly config you use for Google ? (pls change app id / secret).

**Comment by cssjockey** [comment]
Tried with new app id and secret and still same error. If you don't mind can we chat on Skype.
