### ISSUE TITLE
Logout doesn't really logout. Issue closed #220

### ISSUE THREAD

**Issue by rubenrafaelmercado** [hybridauth/hybridauth#854]
Version: 2.9.6
Provider: I only have tested Facebook.
Bug: There is not a complete Facebook log out. This can be a security problem for a user when he shares a computer.

My test steps:
1- I log in correctly using Facebook in my site.
2- I log out using `$adapter->logout()` .
3- Now I can log in using Facebook again, but without email nor password within my site
4- Now I can open my Facebook page without email nor password (outside my site)

The problems:
A- There is not a complete Facebook log out within my site nor Facebook site. This can be a security problem for a user when he shares a computer.
B- No possible to change to another user.

Notes: I have verified a Facebook logout using client access token
```
$accessTokenArray = $adapter->getAccessToken();
$fb_logout_Url = 'https://www.facebook.com/logout.php?next=http://my-site.com/my-callback-page.php&access_token=' . $accessTokenArray ["access_token"] ;
```

View more of this:
https://stackoverflow.com/questions/15722456/facebook-getlogouturl-returns-a-url-with-access-token-0-when-clicked-redirects

**Comment by ApacheEx** [comment]
see more info here #875. This feature won't be developed in v2. If it's really needed feature please create an appreciate issue for v3.

**Comment by RahulVerma989** [comment]
You to logout the user from your website and allow him to be able to choose another account the next time, can use getConnectedAdapters() method to get all the connected adapters of hybridauth and use foreach loop and call disconnect() method on each of the adapters. This way on logout all the connected adapters will get disconnected and user can choose another account on next login.
