### ISSUE TITLE
Windows Live, wrong configuration provided for redirect_uri

### ISSUE THREAD

**Issue by Lospepes** [hybridauth/hybridauth#858]
Hello,

When HybridAuth redirect to Windows Live

https://login.live.com/oauth20_authorize.srf?client_id=000000004C18A655&redirect_uri=https%3A%2F%2Fdev.domain.tld%2Fhybrid-authlive.php&response_type=code&scope=wl.signin+wl.basic+wl.birthday+wl.emails+wl.postal_addresses

I was redirect to this address : 

https://login.live.com/err.srf?lc=1036#error=invalid_request&error_description=The+provided+value+for+the+input+parameter+'redirect_uri'+is+not+valid.+The+expected+value+is+'https://login.live.com/oauth20_desktop.srf'+or+a+URL+which+matches+the+redirect+URI+registered+for+this+client+application.

My redirect URL registered in my windows app (https://apps.dev.microsoft.com/#/appList) 👍 

https://dev.domain.tld/hybrid-auth

Hybrid_Auth::setup( Live ), no params given. Trying to get the stored for this provider. -- Array
(
    [hauth_return_to] => https://dev.chateau.com/hybrid-auth?provider=Live&path=login
    [hauth_token] => xxxxxxxxxxxxxxxxxxxxxxxxxx
    [hauth_time] => xxxxxxxxxx
    [login_start] => https://dev.domain.tld/hybrid-auth?hauth.start=Live&hauth.time=xxxxxxxxxx
    [login_done] => https://dev.domain.tld/hybrid-authlive.php
)

The 'Hybrid_Auth login_done' doen't exist in my app.

I don't understand why and what I did wrong ! I need your help please.

I am at your disposal for any additional information.

Thank you

**Comment by ApacheEx** [comment]
Hi, 
Have you seen [documentation](https://hybridauth.github.io/hybridauth/userguide/IDProvider_info_Live.html)  ? Please check once more. Your redirection URL should lead to `live.php` which placed in `hybridauth/hybridauth/live.php` or to your custom endpoint where you have something like this:
```php
$_REQUEST['hauth_done'] = 'Live';
require_once("Hybrid/Auth.php");
require_once("Hybrid/Endpoint.php");
Hybrid_Endpoint::process();
```

can you provide more code how do you do login?

**Comment by Lospepes** [comment]
Hi,

Thank you for your help. I haven't understand that I needed a return URL with live.php at the end.
I use Hybrid because I don't want to do many exceptions. So I will forget this provider.

Thank you,
