### ISSUE TITLE
OpenID using me.yahoo.com fails

### ISSUE THREAD

**Issue by StephenAtty** [hybridauth/hybridauth#860]
Is this a bug, a feature request or a question?  Bug

Give us a short description.

Trying to use OpenID with https://me.yahoo.com fails with

Sorry! There is an error with the request we received from the website you are trying to use. Please try again in a few minutes. If this error persists please contact the site administrator. 

### Version and provider

What version of Hybrid Auth does this relates to?  Version 2.9

Is this an issue with a provider? If yes, which one? OpenID

### Reproduction

How can we replicate this issue?

set $adapter = $hybridauth->authenticate( "OpenID", array( "openid_identifier" => "https://me.yahoo.com/"));
$user_profile = $adapter->getUserProfile();

**Comment by ApacheEx** [comment]
Hi,
Yahoo **openid_identifier** should be `https://open.login.yahooapis.com/openid20/www.yahoo.com/xrds`.

let us know if it works for you.

**Comment by StephenAtty** [comment]
Sorry to say it gives the same error:

Sorry! There is an error with the request we received from the website you are trying to use. Please try again in a few minutes. If this error persists please contact the site administrator.

**Comment by ApacheEx** [comment]
still actual?

**Comment by StephenAtty** [comment]
Unless something has changed - I took it out of the list of auth agents people could use. I'll have to build a test configuration.

Were you able to re-produce it?

**Comment by ApacheEx** [comment]
I'm closing this issue since v2 is under Maintenance mode.
