### ISSUE TITLE
3.0-dev can be cloned but 3.0.0-beta.1 can only be pulled on Packagist 

### ISSUE THREAD

**Issue by JREAM** [hybridauth/hybridauth#863]
## Bug, feature or question?

Appears to be a bug.

Give us a short description.

`3.0.0-beta.1` is the latest I can pull from composer. If I git pull, I get `3.0-dev` only by `git clone` (the current master branch).
- Which one is the actual development version? `3.0-dev` seems more correct (More details below)

What version of Hybrid Auth does this relates to?

`3.0.0-beta.1` mainly, and 3.0-dev not listing in Composer/Packagist or installing.

Is this an issue with a provider? If yes, which one? 

Yes, the Packagist `3.0.0-beta.1`. it seems this is more of an alpha version and `3.0-dev` is further along? 

- In `3.0.0-beta.1`:
- In the main `Hybridauth` class:
    - `public static function isConnectedWith($name)`
    - `public static function getConnectedProviders()`
    - `public static function getConnectedAdapters()`
    - `public static function disconnectAllAdapters()`
- Some of which reference:
    - `protected $config;`
    - `protected $storage;`

### Reproduction

Try a few methods above after pulling:
```
composer require hybridauth/hybridauth:3.0.0-beta.1
```

**Comment by StorytellerCZ** [comment]
`3.0.0-beta.1` is the latest beta release that was made. The `3.0-dev` is a branch for version 3.0 development and hence it contains the most recent changes since the release of `3.0.0-beta.1`.
I think another beta might be in order. @miled

**Comment by JREAM** [comment]
Thanks that clears it up!
