### ISSUE TITLE
Base_URL

### ISSUE THREAD

**Issue by 5oClutch** [hybridauth/hybridauth#865]
## Bug, feature or question?

I am not able to change the base_url in the config file, even if i do change it, it takes me to the same url which i did not provide.

## Version and provider
2.9.6

**Comment by ApacheEx** [comment]
Hi,

> it takes me to the same url which i did not provide.
1) and which URL it takes? can you provide an example.

2) do you use any frameworks / CMS ?

**Comment by ArshadAQ** [comment]
I'm getting the same error! I'm behind this for more than 3 days! Its really frustrating! I'm always getting redirected to http://localhost:8081/?hauth.start=Facebook&hauth.time=1512578610, whatever url I put in the base_url in my config file!

**Comment by ApacheEx** [comment]
seems you have implemented HA integration in wrong way. 
Check once more documentation or even better try to use HA v3.
