### ISSUE TITLE
Your application id is required in order to connect to Twitter

### ISSUE THREAD

**Issue by benderlidze** [hybridauth/hybridauth#866]
Question
Here is my code, on version 3.
Auth is fine, I get the tokens and profile.
But I get this error "Your application id is required in order to connect to Twitter" (I think on this line $adapter->setAccessToken($tokens);), but as I understand there is no ID when using Twitter. 
Any thoughts?
Thanks.
```
$config = [
    'callback' => "***/login.php",
    'providers' => [
        'Twitter' => [ 
            'enabled' => true,
            'keys'    => [ 'key' => '***', 'secret' => '***' ],
            "includeEmail" => true,
        ]
    ],
];
try {
	
    $hybridauth = new Hybridauth\Hybridauth( $config );
    $adapter = $hybridauth->authenticate( 'Twitter' );
    $tokens = $adapter->getAccessToken();
    
    $userProfile = $adapter->getUserProfile();
    $adapter->disconnect();
	
	print_r( $tokens );
    print_r( $userProfile );
		
	$adapter = new Hybridauth\Provider\Twitter($config);
	$adapter->setAccessToken($tokens);
	$userProfile = $adapter->getUserProfile();
	
}
catch (\Exception $e) {
    echo $e->getMessage();
}
```

**Comment by ApacheEx** [comment]
Have you read documentation 😀? Here is also an example how it can be:
https://hybridauth.github.io/introduction.html

In short you have to provide keys in your $config, especially for Twitter you need to create an app and use his credentials (key and secret)

**Comment by benderlidze** [comment]
Did you read the question? As I said the auth is OK, I have the 'key' => '***' and 'secret' => '***' and everything is fine untill this 
$adapter->setAccessToken($tokens);

**Comment by ApacheEx** [comment]
> Auth is fine, I get the tokens and profile.

hmm, I didn't see this...

I see the problem in your example, you try to auth via Twitter first time like this:
```php
$hybridauth = new Hybridauth\Hybridauth( $config );
$adapter = $hybridauth->authenticate( 'Twitter' );
$tokens = $adapter->getAccessToken();
```
it's fine, but then you use a bit different way to auth like this:
```php
$adapter = new Hybridauth\Provider\Twitter($config);
$adapter->setAccessToken($tokens);
```

you see? 
`Hybridauth\Hybridauth` - it expects a configuration array containing the list of providers you want to use.
`Hybridauth\Provider\Twitter` - it expects a configuration array containing a provider credentials.

for second case config should be like this:
```php
$config = [
    'callback' => "***/login.php",
    'keys'    => [ 'key' => '***', 'secret' => '***' ],
    'includeEmail' => true,
];
```
or you can do something like this:
```php
$hybridauth = new Hybridauth\Hybridauth( $config );
$adapter = $hybridauth->authenticate( 'Twitter' );
$tokens = $adapter->getAccessToken();
    
$userProfile = $adapter->getUserProfile();
$adapter->disconnect();
	
print_r( $tokens );
print_r( $userProfile );
		
$adapter = $hybridauth->getAdapter('Twitter');
$adapter->setAccessToken($tokens);
$adapter->authenticate();
$userProfile = $adapter->getUserProfile();
```

**Comment by benderlidze** [comment]
Thanks
But now I got this:
**Signed API request has returned an error. HTTP error 403. Raw Provider API response: {"errors":[{"message":"Your credentials do not allow access to this resource","code":220}]}**

Is there any 100% example of usign setAccessToken?
I want to login/auth the user with $tokens received from session, db, cooke, etc.
Thank you!

**Comment by ApacheEx** [comment]
still actual? it seems you need to be redirected to twitter (it's requirement of twitter)

but I can't understand for what you need this? Hybridauth has own storage for tokens. And it can be overridden. You can create own Storage (like existing one [Session](https://github.com/hybridauth/hybridauth/blob/master/src/Storage/Session.php))  and use it like this:
```php
class DbStorage implements StorageInterface {
  // .... YOUR OWN IMPLEMENTATION HERE.
}
$dbStorage = new DbStorage();
$hybridauth = new Hybridauth\Hybridauth( $config, null, $dbStorage );
$adapter = $hybridauth->authenticate( 'Twitter' );
$userProfile = $adapter->getUserProfile();
```
that's it, all your tokens will be saved in db.

**Comment by benderlidze** [comment]
Thanks, and one more question about the auth logic

1. I have a page with 3 buttons = auth with Facebook, google, twitter. User press the button and go to the page with login.php?provider=Facebook
2. I set the prvider name to session $_SESSION['provider'] = $provider and use the $hybridauth = new Hybridauth\Hybridauth( $config );
3. And here is a moment with CALLBACK that is not clear for me. I get the redirect from Facebook to my script that is set in the callback `'callback' => "https://***/loginRead.php",` and get the provider name from session and auth the user again?

SO the question is about the redirect and is there a way to detect the provider name or auth the user without setting the provider manualy,  only by [HYBRIDAUTH::STORAGE]? 
Here is my script, it works as I want but I think it is not good at all: 

```
session_name("authSession");
session_start();
include 'hybridauth/src/autoload.php';
$config = [
    'callback' => "https://***/loginRead.php",
    'providers' => [
        'Twitter' => [],"includeEmail" => true],
        'Google'   => [], 
        'Facebook' => []   
    ],
];

$authName = "Facebook";
if(isset($_REQUEST['provider'])){

    $provider = strtolower($_REQUEST['provider']);
    switch ($provider) {
        case 'google':
            $authName = "Google";
            break;
        case 'facebook':
            $authName = "Facebook";
            break;
        case 'twitter':
            $authName = "Twitter";
            break;
    }
    $_SESSION['provider'] = $authName;

    $hybridauth = new Hybridauth\Hybridauth( $config ); 
    $adapter = $hybridauth->getAdapter($authName);
    $user = $adapter->authenticate();
    $userProfile = $adapter->getUserProfile();

}
    // this part is for this callback https://***/loginRead.php from config
    if(isset($_SESSION['HYBRIDAUTH::STORAGE']) && count($_SESSION['HYBRIDAUTH::STORAGE'])>=1){

        $provider = $_SESSION['provider'];
        $hybridauth = new Hybridauth\Hybridauth( $config ); 
        $adapter = $hybridauth->getAdapter($provider);
        $user = $adapter->authenticate();
        $userProfile = $adapter->getUserProfile();
    }

    if(isset($_GET['loginExit'])){
        $adapter->disconnect();
        $hybridauth->disconnectAllAdapters();
        session_destroy();
        header("Location:test.php");
        exit();
    }

    echo '<img src="'.$userProfile->photoURL.'"><br>';
    echo $userProfile->identifier.'<br>';
    echo '<a href="?loginExit">Exit</a>';
```

**Comment by ApacheEx** [comment]
does it still actual?

**Comment by ApacheEx** [comment]
Check this example: https://github.com/hybridauth/hybridauth/tree/master/examples/example_06

it should cover all your question.
