### ISSUE TITLE
Missing class

### ISSUE THREAD

**Issue by centurianii** [hybridauth/hybridauth#867]
## Question

In `Providers/Facebook.php `at line 71 there is: `$this->api = new FacebookSDK([`, where is class `FacebookSDK`? I don't use Composer.
From the `composer.json` I see `"facebook/graph-sdk": "^5.4"` so should I search for this lib?
Also do I need `"squizlabs/php_codesniffer": "2.*"` or can I just leave it out?

### Version and provider

[v.2.9.6](https://github.com/hybridauth/hybridauth/tree/v2)

**Comment by centurianii** [comment]
I got Facebook from [github](https://github.com/facebook/php-graph-sdk) and there is no `FacebookSDK` class.

**Comment by StorytellerCZ** [comment]
Run composer to get the dependencies and that will fix the issue.

**Comment by centurianii** [comment]
At line 4 of the same file (`Providers/Facebook.php`) there is a `use Facebook\Facebook as FacebookSDK;`!
So, no it wasn't a class loading problem! Somebody renamed Facebook class!!
