### ISSUE TITLE
I am always redirected to http://localhost/hybridauth-git/hybridauth/?hauth.start=Twitter&hauth.time=1508567411

### ISSUE THREAD

**Issue by benderlidze** [hybridauth/hybridauth#868]
Here is my php file (HA ver. 2.9)
```
<?
error_reporting(E_ALL|E_STRICT);
ini_set('display_errors', true);

require_once( "library/Hybrid/Auth.php" );
$config = array(
    "base_url" => "https://mydomain.com/auth_hybridauth/login.php",
    "providers" => array(
        "Twitter" => array(
            "enabled" => true,
            "keys" => array("key" => "***", "secret" => "***"),
            "includeEmail" => true,
        ),
    ),
);
$hybridauth = new Hybrid_Auth( $config );
  	$twitter = $hybridauth->authenticate( "Twitter" );
  	$twitter_user_profile = $twitter->getUserProfile();
   	echo "Ohai there! U are connected with: <b>{$twitter->id}</b><br />";
  	echo "As: <b>{$twitter_user_profile->displayName}</b><br />";
  	echo "And your provider user identifier is: <b>{$twitter_user_profile->identifier}</b><br />";
   	print_r( $twitter_user_profile );
   	$twitter->logout();

?>
```

Whatever I set in the "base_url" it is always redirects to the http://localhost/hybridauth-git/hybridauth/?hauth.start=Twitter&hauth.time=1508567411
Why? 
**And where I can download the 3. Tiny Social Hub or 4. Sign-in/Sign-up Users examples?**
Thanks

**Comment by ApacheEx** [comment]
so, your base_url is `http://localhost/hybridauth-git/hybridauth/`?

it should lead to page where this code executes (there is index.php [here](https://github.com/hybridauth/hybridauth/blob/v2/hybridauth/index.php)):
```
require_once( "Hybrid/Auth.php" );
require_once( "Hybrid/Endpoint.php" );

Hybrid_Endpoint::process();
```

**Comment by ApacheEx** [comment]
the latest version of HA (v3) is placed in `master` branch. Please check it out [README](https://github.com/hybridauth/hybridauth). There is all information which requested by you.
