### ISSUE TITLE
Version 3.0 Release Date

### ISSUE THREAD

**Issue by dedanirungu** [hybridauth/hybridauth#870]
Hi Development Team,

I have done research and notice hybridauth has been in development since 2014 if the following article is true. https://hasin.me/2014/02/10/integrate-social-sign-on-in-your-php-apps-using-hybridauth/

1.  What could be the cause of this long delay and which effect does it have to the code given the fact php has move from 5.6 to 7.2.
2. Should new project use version 2.9 or 3.0. Given the fact 3.0 is implemented much better than than 2.9
3. Is there any hope it will be released any sooner 

I am new to hybridauth and I have been developing custom codes for each social media site which is not effective at the moment. I would like to make an informed decision before making the switch.

Dedan Irungu

**Comment by StorytellerCZ** [comment]
You should start with 3.0. I'm not actively developing HybridAuth as I have moved on to Meteor.js. @miled is the creator and main developer so new major version depends on him.

**Comment by danslo** [comment]
Would be nice to at least have some timeline indication with regards to when hybrid auth devs plan to tag a stable 3.0.0 release.

**Comment by johndodev** [comment]
I have a bad feeling about this. RIP incoming.

**Comment by johndodev** [comment]
I also started a project with 3.0 but production is coming soon, maybe I should refactor with 2.x ? 

If nobody develop 3.0 anymore maybe you could start a campaign to look for a maintainer on twitter or somewhere else ?

**Comment by ApacheEx** [comment]
@johndodev 
I have feeling that 3.0 is already quite stable. If there will be bug reports or feature requests, it's not a problem to do something there. Don't forget that we are in Open Source and PRs are welcome.

**Comment by danslo** [comment]
@ApacheEx I'm not necessarily questioning the stability. It's just that master branch has gotten minimal updates for the last 6-7 months, while 2.0 just had a new release drafted yesterday. There's no stable tag for 3.0 either, so we can't use it without lowering minimum-stability.

**Comment by ApacheEx** [comment]
Some thoughts about release plan:

1) until the end of the year - fixes.
2) beginning of the next year, during January - stable release 3.0.0 and deprecation warning about 2.x

**Comment by danslo** [comment]
Thanks for the update!

**Comment by dedanirungu** [comment]
Thank you all for you contribution to this project.

As  requested earlier we  agreed to release stable version 3.0 on January 2018. We have missed this deadline. I would like to know which areas need improvement before we release version 3.0.

Below is the message displayed on project description.
_Hybridauth 3 is currently in beta stage and it might NOT be suitable for production use.
           The 3.0 will be released in January 2018._

I am willing to help where I can we realize this goal.

**Comment by ApacheEx** [comment]
Hi @dedanirungu, 
yeah it was a plan to release in January. 
Unfortunately, so far we can't contact @miled. There are some resources like documentation site https://hybridauth.github.io where I do not have access. It's not a good idea to release with proper (latest) documentation.

**Comment by gopi-ar** [comment]
@ApacheEx any updates on this? We'd like to use 3.0 but don't want to lower stability in composer..

**Comment by ApacheEx** [comment]
Hi @gopi-ar, 
As soon as I contact with @miled, we will make a release 🙏. 
Hopefully, this month. Still a little bit to wait.

**Comment by gopi-ar** [comment]
That's great 👍 
For others wanting to include 3x in composer while avoiding having to change stability levels, use this:

`        "hybridauth/hybridauth" : "~3.0@dev"        
`
