### ISSUE TITLE
Working without Session

### ISSUE THREAD

**Issue by mc388** [hybridauth/hybridauth#872]
## Question

I'm planning a stateless application, so I don't have a session. Is it possible to store these date into the JWT data? Can anyone give me a code example how it could work? Or is there an other way to store the data without a session?

**Comment by ApacheEx** [comment]
which version of hybridauth are you using (v2 or v3) ?

**Comment by mc388** [comment]
v2 but i can also update to v3

**Comment by ApacheEx** [comment]
yeah, I'd recommend to upgrade to v3 which is more flexible.
In short: it's possible, here is a few things good to know:

1) Default storage is [Session](https://github.com/hybridauth/hybridauth/blob/master/src/Storage/Session.php) which implements [StorageInterface](https://github.com/hybridauth/hybridauth/blob/master/src/Storage/StorageInterface.php). Pls check the code to know how it's done.
2) You can implement a DataBase storage (based on Session storage).
3) then on your app use smth like this:

here is your DbStorage.
```php
class DbStorage implements StorageInterface {
  // here is your implementation of (inserting, deleting, merging) data in database.
}
```

here is your init:
```php
$dbStorage = new DbStorage();
$hybridauth = new Hybridauth\Hybridauth($config, null, $dbStorage);
```

**Comment by mc388** [comment]
Thanks for your answer. I will have a look into it in the new days.

**Comment by ApacheEx** [comment]
please reopen if something is not clear.

**Comment by champsupertramp** [comment]
Hi @ApacheEx 

I tried createing a new class to handle the storage and I'm currently experiencing an issue.

Here's the class that i'm using for the custom storage for WordPress:

```
use \Hybridauth\Exception\RuntimeException;

class Social_Login_Cookie implements \Hybridauth\Storage\StorageInterface {
  /**
     * Namespace
     *
     * @var string
     */
    protected $storeNamespace = 'UM_SSO::STORAGE';

    /**
     * Key prefix
     *
     * @var string
     */
    protected $keyPrefix = '';

    /**
    * Initiate a new session
    *
    * @throws RuntimeException
    */
    public function __construct()
    {
        if (session_id()) {
            return;
        }

        if (headers_sent()) {
            // phpcs:ignore
            throw new RuntimeException('HTTP headers already sent to browser and Hybridauth won\'t be able to start/resume PHP session. To resolve this, session_start() must be called before outputing any data.');
        }

        if (! session_start()) {
            throw new RuntimeException('PHP session failed to start.');
        }
    }

    /**
    * {@inheritdoc}
    */
    public function get($key)
    {
        $key = $this->keyPrefix . strtolower($key);
        return isset( $_COOKIE[ $this->storeNamespace."_".$key ] ) ? $_COOKIE[ $this->storeNamespace."_".$key ] : null;
    
    }

    /**
    * {@inheritdoc}
    */
    public function set($key, $value)
    {
        $key = $this->keyPrefix . strtolower($key);

        setcookie( $this->storeNamespace."_".$key, $value, time() + 3600, COOKIEPATH, COOKIE_DOMAIN );

    }

    /**
    * {@inheritdoc}
    */
    public function clear()
    {
      //  setcookie( 'my-cookie-name', '', time() - 3600, COOKIEPATH, COOKIE_DOMAIN );
    }

    /**
    * {@inheritdoc}
    */
    public function delete($key)
    {
        $key = $this->keyPrefix . strtolower($key);

    
    }

    /**
    * {@inheritdoc}
    */
    public function deleteMatch($key)
    {
        $key = $this->keyPrefix . strtolower($key);

    }
}
```

It works with the authorization but when it redirects back to the callback URL, it triggers the following response errors:
`Signed API request has returned an error.`

```
Signed API request has returned an error. HTTP error 400. Raw Provider API response: {"error":{"message":"An active access token must be used to query information about the current user.","type":"OAuthException","code":2500,
```

Here's the console logs:
<img width="402" alt="Screen Shot 2020-06-21 at 11 41 59 PM" src="https://user-images.githubusercontent.com/12200688/85228905-ffad8c80-b418-11ea-9dfd-964baba28f51.png">

It retrives the states of all providers that i'm using but the `access_tokens`, `expire_at` and `refresh_token` are all empty.

Let me know if you need more details. 

Any help would be greatly appreciated.

**Comment by MirazMac** [comment]
> Hi @ApacheEx
> 
> I tried createing a new class to handle the storage and I'm currently experiencing an issue.
> 
> Here's the class that i'm using for the custom storage for WordPress:
> 
> ```
> use \Hybridauth\Exception\RuntimeException;
> 
> class Social_Login_Cookie implements \Hybridauth\Storage\StorageInterface {
>   /**
>      * Namespace
>      *
>      * @var string
>      */
>     protected $storeNamespace = 'UM_SSO::STORAGE';
> 
>     /**
>      * Key prefix
>      *
>      * @var string
>      */
>     protected $keyPrefix = '';
> 
>     /**
>     * Initiate a new session
>     *
>     * @throws RuntimeException
>     */
>     public function __construct()
>     {
>         if (session_id()) {
>             return;
>         }
> 
>         if (headers_sent()) {
>             // phpcs:ignore
>             throw new RuntimeException('HTTP headers already sent to browser and Hybridauth won\'t be able to start/resume PHP session. To resolve this, session_start() must be called before outputing any data.');
>         }
> 
>         if (! session_start()) {
>             throw new RuntimeException('PHP session failed to start.');
>         }
>     }
> 
>     /**
>     * {@inheritdoc}
>     */
>     public function get($key)
>     {
>         $key = $this->keyPrefix . strtolower($key);
>         return isset( $_COOKIE[ $this->storeNamespace."_".$key ] ) ? $_COOKIE[ $this->storeNamespace."_".$key ] : null;
>     
>     }
> 
>     /**
>     * {@inheritdoc}
>     */
>     public function set($key, $value)
>     {
>         $key = $this->keyPrefix . strtolower($key);
> 
>         setcookie( $this->storeNamespace."_".$key, $value, time() + 3600, COOKIEPATH, COOKIE_DOMAIN );
> 
>     }
> 
>     /**
>     * {@inheritdoc}
>     */
>     public function clear()
>     {
>       //  setcookie( 'my-cookie-name', '', time() - 3600, COOKIEPATH, COOKIE_DOMAIN );
>     }
> 
>     /**
>     * {@inheritdoc}
>     */
>     public function delete($key)
>     {
>         $key = $this->keyPrefix . strtolower($key);
> 
>     
>     }
> 
>     /**
>     * {@inheritdoc}
>     */
>     public function deleteMatch($key)
>     {
>         $key = $this->keyPrefix . strtolower($key);
> 
>     }
> }
> ```
> 
> It works with the authorization but when it redirects back to the callback URL, it triggers the following response errors: `Signed API request has returned an error.`
> 
> ```
> Signed API request has returned an error. HTTP error 400. Raw Provider API response: {"error":{"message":"An active access token must be used to query information about the current user.","type":"OAuthException","code":2500,
> ```
> 
> Here's the console logs: <img alt="Screen Shot 2020-06-21 at 11 41 59 PM" width="402" src="https://user-images.githubusercontent.com/12200688/85228905-ffad8c80-b418-11ea-9dfd-964baba28f51.png">
> 
> It retrives the states of all providers that i'm using but the `access_tokens`, `expire_at` and `refresh_token` are all empty.
> 
> Let me know if you need more details.
> 
> Any help would be greatly appreciated.

I'm facing the same issue, I'm using laravel's session helpers to write/retrieve but it keeps redirecting back and forth.

**Comment by MirazMac** [comment]
Nevermind I solved the issue. In case anyone else stumbles upon this in the future, the problem was the data wasn't being written to session, because laravel writes data after sending the response and HybridAuth uses an utility function to redirect. To solve this you simply need to overwrite the redirect function. For Laravel it would be:

```php
        \Hybridauth\HttpClient\Util::setRedirectHandler(function ($url) {
            return redirect($url)->send();
        });
```
