### ISSUE TITLE
Daily Limit for Unauthenticated Use Exceeded. Continued use requires signup. Google OAuth2

### ISSUE THREAD

**Issue by hepaestus** [hybridauth/hybridauth#874]
## Bug, feature or question?
This is either a new feature or and undocumented feature. 
Is there a way to add your google service account to hybridauth v3.0.0b1 so that you don't get the "Daily Limit for Unauthenticated Use Exceeded. Continued use requires signup." error

### Version and provider

What version of Hybrid Auth does this relates to?
v3.0.0b1

Is this an issue with a provider? If yes, which one?
Google

### Reproduction

How can we replicate this issue?
Try making a bunch of requests, eventually, when google get tired of you, the error will happen.

**Comment by hepaestus** [comment]
Looks Like Line 95 of Google.php Overwrites the passed params.
    
protected function getAuthorizeUrl($parameters = [])
    {
        $parameters = ['access_type' => 'offline'];

        return parent::getAuthorizeUrl($parameters);
    }

**Comment by Riad-Jarjour** [comment]
I don't get why you are getting this error, doesn't hybridauth v3 already require providing an id and secret? Does changing line 95 fix this?

**Comment by ApacheEx** [comment]
> Looks Like Line 95 of Google.php Overwrites the passed params.
it seems you are wrong.

Once more checked the code, everything seems fine. That's how you can override authorize params:

```
$config = [
    'callback' => Hybridauth\HttpClient\Util::getCurrentUrl(),
    'keys'     => [ 'id' => '', 'secret' => '' ],
    // google's custom auth url params
    'authorize_url_parameters' => [
        'approval_prompt' => 'force', // to pass only when you need to acquire a new refresh token.
        'access_type'     => ..,      // is set to 'offline' by default
        'hd'              => ..,
        'state'           => ..,
]
```
