### ISSUE TITLE
Logout not logging out from social networks

### ISSUE THREAD

**Issue by Jiban81** [hybridauth/hybridauth#875]
Question: $hybridauth -> logoutAllProviders(); not logging out user from social network sites. It will cause issue in shared computers, internet cafe etc. Is there any fix or work around available?
Hybridauth Version 9.6
Provider: Facebook, Google

**Comment by ApacheEx** [comment]
yeah, it's not. And won't be in v2. If it's really needed, then can be added to v3. 

Each social network has own API for logout. For example Facebook:
```php
public function getLogoutUrl() {
    $params = [
         'next' => 'https://path_to_your_page_after_logout',
         'access_token' => $this->token('access_token'),
    ];
    return 'https://www.facebook.com/logout.php?' . http_build_query($params, null, '&');
}
```

then in your html:
```html
<a href="<?php print $facebook->getLogoutUrl(); ?>">Log Out</a>
```
