### ISSUE TITLE
[Bug] Calling setAccessToken with OAuth1 not working 

### ISSUE THREAD

**Issue by johndodev** [hybridauth/hybridauth#878]
## Bug, feature or question?

There is a bug when I want to use multiple profile for the same network (like two twitter accounts) in a single session. Better is an exemple : 

```php
$adapter = $hybridauth->authenticate('Twitter'); // working fine
$adapter->getUserProfile(); // working fine

// somewhere else, maybe in another page

$adapter = $hybridauth->getAdapter('Twitter');
$adapter->setAccessToken($anotherTokenFromDatabase);
$adapter->getUserProfile(); // request is made with the access token of the authentication, not the database
```

### Why ?
OAuth1.php create its "consumerToken" object in "initialize" with stored token in the session. Since initialize() is not called after "setAccessToken()", consumerToken are not updated. 
See OAuth1.php line 185.

I could make a PR but I dont know how you want to fix that (and if there is still someone who maintain hybridauth).

### Version and provider

v3 (dev-master). The bug should be there for every OAuth1 Adapter, for me with twitter.

### Reproduction

See example

**Comment by johndodev** [comment]
It is fixed with this function in OAuth1.php. It's not very sexy (duplication of some initialize code) but it's working : 

```php
    public function setAccessToken($tokens = [])
    {
        parent::setAccessToken($tokens);

        if ($this->getStoredData('request_token')) {
            $this->consumerToken = new OAuthConsumer(
                $this->getStoredData('request_token'),
                $this->getStoredData('request_token_secret')
            );
        }

        if ($this->getStoredData('access_token')) {
            $this->consumerToken = new OAuthConsumer(
                $this->getStoredData('access_token'),
                $this->getStoredData('access_token_secret')
            );
        }
    }
```

**Comment by ApacheEx** [comment]
Yeah, looks like a bug. 
I'd like to refresh this information in `apiRequest` instead of `setAccessToken` like OAuth2 does.

```php
public function apiRequest($url, $method = 'GET', $parameters = [], $headers = [])
{
    if (strrpos($url, 'http://') !== 0 && strrpos($url, 'https://') !== 0) {
        $url = $this->apiBaseUrl . $url;
    }
    if ($this->getStoredData('request_token')) {
        $this->consumerToken = new OAuthConsumer(
            $this->getStoredData('request_token'),
            $this->getStoredData('request_token_secret')
        );
    }
    if ($this->getStoredData('access_token')) {
        $this->consumerToken = new OAuthConsumer(
            $this->getStoredData('access_token'),
            $this->getStoredData('access_token_secret')
        );
    }
    ....
}
```

what do you think?

**Comment by johndodev** [comment]
I didn't study hybridauth enough but it seems cool. Maybe not fully optimized but ok for now.

You can also remove all other "new OAuthConsumer" in validateAccessTokenExchange(), validateAuthTokenRequest() and initialize() right ?

**Comment by ApacheEx** [comment]
I've checked once more, and you were right. It's better to do in setAccessToken.
