### ISSUE TITLE
[Bug] 2.10.0 Release on a wrong commit.

### ISSUE THREAD

**Issue by asika32764** [hybridauth/hybridauth#879]
The `Release v2.10.0` commit is: https://github.com/hybridauth/hybridauth/commit/57f5a5bf677be6303cd23467e3d1d302f3f0777a

But the `v2.10.0` tag is on: https://github.com/hybridauth/hybridauth/commit/ffea27a31196aabd77ae1de49eeaf36e35f06028

Seems the tag was marked on a wrong position. This makes composer download a wrong package on v3 branch and namespaced classes. So the `Hybrid_Auth` class was missing.

![p-2017-11-30-001](https://user-images.githubusercontent.com/1639206/33438149-ed33cd14-d624-11e7-9713-005f009d5b3a.jpg)

![p-2017-11-30-002](https://user-images.githubusercontent.com/1639206/33438233-2bbb8b62-d625-11e7-99d6-06c7f8298522.jpg)

**Comment by StorytellerCZ** [comment]
Mea culpa! Will fix now.
