### ISSUE TITLE
'setUserStatus' functionality is missed for LinkedIn in v3.0

### ISSUE THREAD

**Issue by asheeshn** [hybridauth/hybridauth#884]
## Bug, feature or question?

Is this a bug, a feature request or a question?

Give us a short description.

### Version and provider

What version of Hybrid Auth does this relates to?

Is this an issue with a provider? If yes, which one?

### Reproduction

How can we replicate this issue?

**Comment by ApacheEx** [comment]
yes, it's true. Will try to add `setUserStatus` soon.

**Comment by asheeshn** [comment]
Thanks. When can we expect this feature (approximately).
Thanks in Advance.

**Comment by ApacheEx** [comment]
today in beta.3 :)

**Comment by asheeshn** [comment]
really 👍

**Comment by asheeshn** [comment]
Hi, Any idea on #885 issue ?

**Comment by ApacheEx** [comment]
don't forget to use new scope for posting `'w_share'` to your LinkedIn config like this:


```
$config = array(
    ...
    'scope' => 'r_basicprofile r_emailaddress w_share',
    ...
);
```

here is working example:
https://github.com/hybridauth/hybridauth/blob/master/docs/developer-ref-user-status.md

**Comment by asheeshn** [comment]
Thanks.
I am getting this error. Can u pls help me out to fix this.
Signed API request has returned an error. HTTP error 403. Raw Provider API response: { "errorCode": 0, "message": "Access to posting shares denied", "requestId": "C6RBDU5AG6", "status": 403, "timestamp": 1512486655024 }.

**Comment by ApacheEx** [comment]
please provide an example of your linkedin configuration and how to do the call.

**Comment by asheeshn** [comment]
$adapter = new Hybridauth\Provider\LinkedIn( $config );
    $social_media_access_token = 'AQV2Rn_S39Oiw_xS6yUhywzVdw_bQv17_Bns8VKID6_VPUe_vEQWcMLawSCR3nbRrqWH3Fgd5ZPJnSOQLs4oWXsgmSnF4uAgArucYDCD5s-pGyD2tJZ52dFe3A1_2K-4PJpDdpeRrpZgY-dP4FAndOxIHHsW9WYTqRJiqGqiDLrqAU6EhK0jrwzv0q7ZSB5xXxJSh8Tfk4d0A3vRTlnKdjhZ_oXlxZnszhpPF74K8v8kgosqfp0ccsZb0c0NU-ArBS7pGDcStrqfPScMiTXUZf-Mw_NhG6fFrjugTrDIIjQ2jMsq-9ntWGY0l4RdR1Bn8Wd2G5d0ZkvhFfX2fp-x0E_7h2nVJQ';
$social_media_access_token_secret = '';
    $adapter->setAccessToken(['access_token' => $social_media_access_token, 'access_token_secret' => $social_media_access_token_secret]);
    $userProfile = $adapter->getUserProfile();
    //dd($userProfile);
    $img_relative_path = base_path('public\images\social_media_logo.png');
    $img_absolute_path = asset('public/images/social_media_logo.png');
    //dd($img_relative_path);

    $link_url = url('externals/viewjob/57/356a192b7913b04c54574d18c28d46e6395428ab');

    $status = $adapter->setUserStatus(array("message"=>"Default Logo Shared with external link 333", "link"=>$link_url, "picture"=>$img_absolute_path));

    //$status = $adapter->setUserStatus("Default Logo Shared");


    /*$adapter->setUserStatus(
        array(
            'comment' => 'Check out developer.linkedin.com!',
            'content' => array(
                'title' => 'LinkedIn Developers Resources',
                'description' => "Leverage LinkedIn's APIs to maximize engagement",
                'submitted-url' => $link_url,
                'submitted-image-url' => $img_absolute_path,
            ),
            'visibility' => array(
                'code' => 'anyone',
            ),
        )
    );

Execution : https://beanhiredev.com/social_media/publish/5

**Comment by ApacheEx** [comment]
I don't see your config. I'm wonder why you use `setAccessToken`?

**Comment by asheeshn** [comment]
I am trying to share post offline with access token. 
Here is my config 
$config = [
    'callback'  => url('/social_media/configure'), //Hybridauth\HttpClient\Util::getCurrentUrl(),
    'keys' => [ 'key' => $social_media_key, 'secret' => $social_media_secret ],
    'scope' => 'r_basicprofile r_emailaddress w_share',
];
