### ISSUE TITLE
unable to update user status with picture for Facebook, Twitter and LinkedIn in v3.0

### ISSUE THREAD

**Issue by asheeshn** [hybridauth/hybridauth#885]
## Bug, feature or question?

Is this a bug, a feature request or a question?

Give us a short description.

### Version and provider

What version of Hybrid Auth does this relates to?

Is this an issue with a provider? If yes, which one?

### Reproduction

How can we replicate this issue?

**Comment by ApacheEx** [comment]
Hi,
- about LinkedIn - will be fixed in #884
- about Twitter - yeah, I see a problem, will be fixed soon (in beta.3).


- about Facebook -  As usual, Facebook has changed something. You can read more info here:
https://developers.facebook.com/docs/graph-api/reference/v2.11/page/feed.
In short: 

> For versions 2.10 and lower, picture, name, thumbnail, and description are deprecated. caption is deprecated for all versions.

Can you try `thumbnail` param?

**Comment by asheeshn** [comment]
Thanks. You mean in place of 'Picture', we should use 'thumbnail' for Facebook ??

**Comment by ApacheEx** [comment]
Yeah, it seems so. Something like this:

```php
$adapter->setUserStatus([
  'link' => 'Link to page',
  'message' => 'Your message',
  'thumbnail' => 'Path to image',
]);
```

**Comment by ApacheEx** [comment]
I have released `v3.0.0-beta.3` which includes all this fixes. Let me know if it works for you.

**Comment by asheeshn** [comment]
For Twitter i am getting this issue. Please help me to solve this
Signed API request has returned an error. HTTP error 401. Raw Provider API response: {"errors":[{"code":32,"message":"Could not authenticate you."}]}.

**Comment by ApacheEx** [comment]
pls provide an example how you do the call.

**Comment by asheeshn** [comment]
$config = [
    'callback'  => url('/social_media/configure'), //Hybridauth\HttpClient\Util::getCurrentUrl(),
    'keys' => [ 'key' => $social_media_key, 'secret' => $social_media_secret ],
    'scope' => 'r_basicprofile r_emailaddress w_share',
];

$adapter = new Hybridauth\Provider\Twitter( $config );

$adapter->setAccessToken(['access_token' => $social_media_access_token, 'access_token_secret' => $social_media_access_token_secret]);

$status = $adapter->setUserStatus(array("message"=>"Default Logo Shared with external link 333", "link"=>$link_url, "picture"=>$img_absolute_path));

Execution : https://beanhiredev.com/social_media/publish/4

**Comment by ApacheEx** [comment]
this scope is related to LinkedIn. Why you use `setAccessToken`? do you have any `authenticate` calls?
