### ISSUE TITLE
Please Provide an Example to share a post to Twitter, LinkedIn and Facebook Offline using Access Token.

### ISSUE THREAD

**Issue by asheeshn** [hybridauth/hybridauth#888]
## Bug, feature or question?

Is this a bug, a feature request or a question?

Give us a short description.

### Version and provider

What version of Hybrid Auth does this relates to?

Is this an issue with a provider? If yes, which one?

### Reproduction

How can we replicate this issue?

**Comment by asheeshn** [comment]
With Message Link and Picture

**Comment by ApacheEx** [comment]
All needed information you can find here:
https://github.com/hybridauth/hybridauth/blob/master/docs/developer-ref-user-status.md

for offline usage, you need to use `setAccessToken` instead of `authenticate`.
