### ISSUE TITLE
Twitter - statuses/update_with_media (deprecated). We need to use update.json only

### ISSUE THREAD

**Issue by asheeshn** [hybridauth/hybridauth#889]
## Bug, feature or question?

Is this a bug, a feature request or a question?

Give us a short description.

### Version and provider

What version of Hybrid Auth does this relates to?

Is this an issue with a provider? If yes, which one?

### Reproduction

How can we replicate this issue?

**Comment by ApacheEx** [comment]
It's aleeady fixed in v3.

Which version of HA you use?

**Comment by ApacheEx** [comment]
Fixed, will be available in v3.0.0-beta.4 soon.

if there will be any questions - just ask.

**Comment by asheeshn** [comment]
Twitter - setUserStatus with link option.

Tweet Link should go to the specific url. Please give any example.

**Comment by ApacheEx** [comment]
here it is:

```php
$twitter->setUserStatus([
  'status' => 'Hello World! https://hybridauth.github.io/',
]);
```

So, this code will add post with text Hello World and link to ttps://hybridauth.github.io/'

**Comment by asheeshn** [comment]
I am able to get the link to click in the message.
But I am looking for the functionality, Clicking on the tweet image, it will take to the url given. 
Instead of redirecting to the page, tweet image is showing bigger. Please help me to achieve this.

**Comment by ApacheEx** [comment]
What you are looking for is called Twitter Card - for more info read:

- https://developer.twitter.com/en/docs/tweets/optimize-with-cards/overview/abouts-cards
- https://developer.twitter.com/en/docs/tweets/optimize-with-cards/overview/summary
- https://developer.twitter.com/en/docs/tweets/optimize-with-cards/guides/getting-started

it means, HA should not take care about this.

**Comment by asheeshn** [comment]
Thank you.
Seems Twitter doesn't have API for the TwitterCards. I dint see it. 
If it is, can you provide me some links to integrate twitter cards through API.

**Comment by ApacheEx** [comment]
Yeah, there is no API. But, it's possible to implement if a link which is going to be posted is from YOUR site:

1) First of all, post a message with link or just link via `setUserStatus`.
2) Make sure you have added these meta tags to the associated page:
```html
<meta name="twitter:card" content="summary" />
<meta name="twitter:site" content="@YOUR_TWITTER_ACCOUNT" />
<meta name="twitter:title" content="YOUR ARTICLE TITLE" />
<meta name="twitter:description" content="YOUR SHORT ARTICLE DESCRIPTION" />
<meta name="twitter:image" content="YOUR ARTICLE IMAGE" />
```
