### ISSUE TITLE
LinkedIn - OAuth2 - AccessToken should not include in post body. Getting error if inlcudes

### ISSUE THREAD

**Issue by asheeshn** [hybridauth/hybridauth#890]
OAuth2.php:
Need to skip this while sending a post. Its already in headers.
if($this->getStoredData('access_token')) {
                $this->apiRequestParameters[$this->accessTokenName] = $this->getStoredData('access_token');
            }

            $parameters = array_replace($this->apiRequestParameters, (array) $parameters);

**Comment by ApacheEx** [comment]
Fixed, will be released with beta4 soon,
Once more thank you!
