### ISSUE TITLE
Headers Merged at wrong position

### ISSUE THREAD

**Issue by asheeshn** [hybridauth/hybridauth#892]
## Bug, feature or question?

Is this a bug, a feature request or a question?

Give us a short description.

### Version and provider

What version of Hybrid Auth does this relates to?

Is this an issue with a provider? If yes, which one?

### Reproduction

How can we replicate this issue?

**Comment by asheeshn** [comment]
v3.0 - Linkedin : 
In Curl.php, 'request' method, 
$this->requestHeader = array_merge($this->requestHeader, (array)$headers);
is placed after the comparisions. Should be before the method comparisions.

Case : 
isset($this->requestHeader['Content-Type']) && $this->requestHeader['Content-Type'] == 'application/json')

**Comment by ApacheEx** [comment]
Fixed, will be released soon with beta4, 
Thank you!
