### ISSUE TITLE
setAccessToken function is missed in OAuth2.php Which exists in OAuth1.php

### ISSUE THREAD

**Issue by asheeshn** [hybridauth/hybridauth#899]
unable to set token for LinkedIn, which is using OAuth2.
Workinig fine for Twitter, which is using OAuth1.

**Comment by ApacheEx** [comment]
@asheeshn 
which exactly version of HA you use?

perhaps it's the same problem as mentioned here #880
I will check today later

**Comment by asheeshn** [comment]
I am using version 3 latest one.

**Comment by ApacheEx** [comment]
good, will fix.

**Comment by ApacheEx** [comment]
done, now it should work for both (OAuth1 and OAuth2).
thanks for reporting.

will be available in `beta5`
