### ISSUE TITLE
How to add Description in setUserStatus for facebook, twitter and linkedin

### ISSUE THREAD

**Issue by asheeshn** [hybridauth/hybridauth#902]
Hi, 
I am able to post the status. But, i am unable to set description for the status. Can you please suggest me any example or any other way ??

**Comment by asheeshn** [comment]
Any Solution ??

**Comment by ApacheEx** [comment]
The newest Facebook API doesn't allow you to specify description or so. Here is proof from official Facebook [documentation](https://developers.facebook.com/docs/graph-api/reference/v2.11/user/feed):
![image](https://user-images.githubusercontent.com/1918108/34455232-4604635c-ed83-11e7-875d-7034fd1b78be.png)

As solution, you can add OG tags to page which is going to be posted like this:
```html
<meta property="og:url" content="https://hybridauth.github.io" />
<meta property="og:type" content="article" />
<meta property="og:title" content="Hybridauth Social Login PHP Library" />
<meta property="og:description" content="Welcome to Hybridauth documentation" />
<meta property="og:image" content="https://getstream.imgix.net/images/logo_php.svg" />
```

More info here: https://developers.facebook.com/docs/sharing/webmasters/

**Comment by ApacheEx** [comment]
For all other social networks, you can read documentation here:
https://github.com/hybridauth/hybridauth/blob/master/docs/developer-ref-user-status.md
