### ISSUE TITLE
Can't connect to Facebook Api

### ISSUE THREAD

**Issue by AyaEMahmoud** [hybridauth/hybridauth#903]
Hybridauth 2.3 is used in an old project, when trying to login with Facebook it redirects to /login on calling this part on the Facebook.php provider 
`try{ 	
$response = $this->api->api('/me/friends'); 
}`
Any idea why does this happen?

**Comment by ApacheEx** [comment]
Upgrade HA to 2.10 and problem will be resolved.

**Comment by AyaEMahmoud** [comment]
@ApacheEx Do I have to upgrade? it there any work around? Also could you please tell me the problem with this implementation?

**Comment by ApacheEx** [comment]
I'd highly recommend you to upgrade. But, if you don't have possibility to do it, check this for workaround: https://github.com/thelia-modules/TheliaHybridAuth/pull/4/commits/6f68b42279c75b13bc9cd11825ed7e5aa6e437a3
