### ISSUE TITLE
Why does v3 support PHP 5.4+?

### ISSUE THREAD

**Issue by ADmad** [hybridauth/hybridauth#904]
I am curious to know why a new major version of the library is scheduled for release supporting PHP 5.4, a version for which active support has ended [over 3 years ago](http://php.net/supported-versions.php)?

Wouldn't it be prudent to make v3 support PHP 7.0+ at least and take the advantage of new language features like improved type hinting/declarations?

**Comment by ApacheEx** [comment]
Here is a real [statistic](https://w3techs.com/technologies/details/pl-php/all/all) of php usage:
![image](https://user-images.githubusercontent.com/1918108/34512251-bf750d98-f069-11e7-90ca-96c753722e96.png)

That's the main reason. I do not see any disadvantages of supporting php 5.4 for now.

**Comment by ADmad** [comment]
Do you guys plan to drop support for v2 once v3 is released? If not those using PHP 5 can keep using hybridauth v2.

If not PHP 7, please at least consider bumping up to PHP 5.6 (which is going to have security fixes for another year) for v3.

**Comment by StorytellerCZ** [comment]
v2 is already in maintenance. With v3 out any work on v2 will pretty much be ended (plus I will be most likely unavailable from fall).
