### ISSUE TITLE
Add upgrade guide from 2.x to 3.0

### ISSUE THREAD

**Issue by ApacheEx** [hybridauth/hybridauth#906]

**Comment by crnkovic** [comment]
While on subject of upgrades, are there any breaking changes in any 2.X updates? To explain further, I'm running a 2.10.0 version and would like to update to the latest version, but I'm scared that there are some breaking changes, since there are no automated tests.

**Comment by ApacheEx** [comment]
Done. See https://github.com/hybridauth/hybridauth.github.io/pull/3
