### ISSUE TITLE
Facebook provider is ignoring scope from config

### ISSUE THREAD

**Issue by plysak** [hybridauth/hybridauth#908]
Bug report:
Whatever you write to config file, Facebook provider uses full scope from Provider/Facebook.php line 44
Tried list, tried array, nothing made the change. When I changed that line 44, it is ok, but no way to change scope from config.  

Version 3.0.0-RC1

**Comment by ApacheEx** [comment]
Hi,
just tried, works well, any examples of your config?

I'm tried with:
```
'Facebook' => [
    'enabled' => true,
    'scope' => 'email, user_about_me',
    'keys' => [
        'id' => 'FB_KEY',
        'secret' => 'FB_SECRET',
    ],
],
```

**Comment by plysak** [comment]
Jesus... I had scope in that 'keys' subarray.... sorry
