### ISSUE TITLE
Scope and photo_size defined in config are ignored

### ISSUE THREAD

**Issue by davidhill001** [hybridauth/hybridauth#909]
Bug - When using the latest v3.0.0 RC 1 and setting the scope option in the config.php file, it is ignored. I am only using the Facebook provider, it may also be affecting other providers. Here is the section from my config file:

'Facebook' => [
      'enabled' => true,
      'keys' => [
        'id' => '1221201981266248',
        'secret' => 'xxxxxxxxxxxxxxxxxxxxxxx',
        'scope'   => ['email', 'user_friends', 'public_profile'],
        'photo_size' => 200,
      ]

I have tried the following formats:
['email', 'user_friends', 'public_profile']
'email, user_friends, public_profile'

But this is overridden with the protected $scope variable in src/Provider/Facebook.php to:
email user_hometown publish_actions user_status user_about_me user_birthday user_posts user_website user_friends

Editing the protected $scope variable in src/Provider/Facebook.php to 'email, user_friends, public_profile' is what I am using as a workaround for now.

This is the URL I am directed to when I click log in with Facebook:
https://www.facebook.com/v2.11/dialog/oauth?redirect_uri=https%3A%2F%2Fxxxxxxxxxxxxxxxxxxx%3A801%2Fhybridauth%2Fexamples%2Fexample_06%2Fcallback.php&state=HA-T8JA20VXZBEHO4YFDN3I6QS9UR1WPKL5C7GM&scope=email%2C+user_hometown%2C+publish_actions%2C+user_status%2C+user_about_me%2C+user_birthday%2C+user_posts%2C+user_website%2C+user_friends&response_type=code&client_id=1221201981266248&ret=login&logger_id=f70a3103-f11d-b463-a477-cbc278762b03&ext=1516364285&hash=AeZfCd_H6oKM6wvf

**Comment by ApacheEx** [comment]
from your example, I see that `scope` is placed inside `keys` - that's completely wrong.

The same situation was here #908 😅 

p.s if works, close the issue

**Comment by davidhill001** [comment]
Thank you! It works now
