### ISSUE TITLE
question set access token when using muiltiple providers

### ISSUE THREAD

**Issue by sagudev** [hybridauth/hybridauth#913]
Is possible to set access token when using muiltiple providers.
Hybrid Auth version is 3 rc1

### Reproduction
$hybridauth = new Hybridauth\Hybridauth($config);
$hybridauth->setAccessToken($_SESSION['token']);
$userProfile = $adapter->getUserProfile();
print_r($userProfile);
$adapter->disconnect();

**Comment by ApacheEx** [comment]
Hi, 
Nope, it is not.`Hybridauth` class is kind of wrapper for social providers. Each provider has own access token. I'd recommend using:

```php
$hybridauth = new Hybridauth\Hybridauth($config);
$adapter = $hybridauth->getAdapter('Facebook');
$adapter->setAccessToken($_SESSION['token']);
$userProfile = $adapter->getUserProfile();
```

**Comment by sagudev** [comment]
ok thanks
