### ISSUE TITLE
Authentication failed! Facebook returned an invalid user id...in hybrid auth social plugin in cakephp 2.8.6

### ISSUE THREAD

**Issue by samantanabin02** [hybridauth/hybridauth#914]
Authentication failed! Facebook returned an invalid user id...in hybrid auth social plugin in cakephp 2.8.6...plugin source link  https://github.com/MayMeow/CakePHP-HybridAuth
Google plus works fine...but facebook not working...please help

**Comment by ApacheEx** [comment]
This plugin has HA library of 2.4.2 version. It's very old with many issues. That's the main reason. You have to upgrade Hybridauth to https://github.com/hybridauth/hybridauth/releases/tag/v2.10.0

**Comment by samantanabin02** [comment]
Is there any proper social plugin available for cakephp 2.8.6?

**Comment by ApacheEx** [comment]
Do not know, try to search in google or upgrade library by yourself

**Comment by samantanabin02** [comment]
Thank you...after upgrading library it works fine..
