### ISSUE TITLE
Bug Cannot modify header information - headers already sent

### ISSUE THREAD

**Issue by sagudev** [hybridauth/hybridauth#915]
Cannot modify header information - headers already sent

### Version and provider

What version of Hybrid Auth does this relates to?

HA 3 RC1 AND RC2

### Reproduction
`echo "hi";
$hybridauth = new Hybridauth\Hybridauth($config);
    $adapter = $hybridauth->getAdapter('Google');
    $adapter->authenticate();
    $userProfile = $adapter->getUserProfile();
    $adapter->disconnect();
`

**Comment by ApacheEx** [comment]
sorry, but it's not HA problem. If you see such problem, it's your issue (e.g not correctly written code)
