### ISSUE TITLE
Incorrect URL in Twitter Provider

### ISSUE THREAD

**Issue by RichardPilbery** [hybridauth/hybridauth#919]
Line 50 of the Twitter.php Provider:

`protected $authorizeUrl = 'https://api.twitter.com/oauth/authenticate';`

The url is now: https://api.twitter.com/oauth/authorize

**Comment by ApacheEx** [comment]
Why do you think it's incorrect? It's valid and correct. Do not see reasons to change something here.

**Comment by RichardPilbery** [comment]
I couldn't get Twitter authentication to work without changing the URL. Perhaps it was just me. The URLs listed on under the Applications Settings on app.twitter.com are: 
![screen shot 2018-02-18 at 20 29 01](https://user-images.githubusercontent.com/5834254/36356488-92af42ce-14ea-11e8-97f8-85114943d126.png)

**Comment by ApacheEx** [comment]
It works for me, even if URL is `oauth/authenticate`

1) have you checked this in app settings?
![image](https://user-images.githubusercontent.com/1918108/36357229-c5da7466-1503-11e8-9a28-1c30dabd42a2.png)

2) Also, try to revoke access or create a new app. It should work.

**Comment by RichardPilbery** [comment]
Ah okay, it is working for me, but it is possible I changed more than one thing (including the link) when troubleshooting. Sorry for the trouble.
