### ISSUE TITLE
Failed login through Instagram

### ISSUE THREAD

**Issue by waresz** [hybridauth/hybridauth#922]
## Bug, feature or question?

Is this a bug, a feature request or a question?

Bug

Give us a short description.

### Version and provider

What version of Hybrid Auth does this relates to?

v3.0 RC2

Is this an issue with a provider? If yes, which one?

Yes. Instagram

### Reproduction

How can we replicate this issue?

When trying to login with Instagram the following error appears:

string(133) "{"meta": {"code": 400, "error_type": "OAuthParameterException", "error_message": "Missing client_id or access_token URL parameter."}}"

**Comment by ApacheEx** [comment]
yeah, you are right. Seems a bug. 
Will fix soon and release rc3. Thanks!

**Comment by ApacheEx** [comment]
Released in 3.0.0-rc3 🎉

**Comment by waresz** [comment]
Excellent, thank you!! 🙌
