### ISSUE TITLE
Custom endpoints config

### ISSUE THREAD

**Issue by dotcostin** [hybridauth/hybridauth#927]
## Bug

From your documentation example, endpoints are array but in class AbstractAdapter on method setApiEndpoints parameter $endpoints expected as Data\Collection. 

### Version 

v3.0.0-rc.3

### Reproduction

Custom authorize_url, api_base_url or access_token_url.

**Comment by ApacheEx** [comment]
Hi, yeah, seems a bug
Will fix.

**Comment by ApacheEx** [comment]
once more checked, everything is correct.
A `setApiEndpoints` is an internal method which used inside adapter's configuration. 
It reads `endpoints` from config. So, endpoints can be changed only via config.

And config is an array which exists in adapter as `Data\Collection` like here:
`$this->config = new Data\Collection($config);`
