### ISSUE TITLE
LinkedIn setUserStatus error.

### ISSUE THREAD

**Issue by RajeshPerro** [hybridauth/hybridauth#928]
Hi,
Here is my method to post in LinkedIn but I am getting error please help!
 Fatal Error:
ArrayObject Object
(
[storage:ArrayObject:private] => Array
(
[exception] => Hybridauth\Exception\HttpRequestFailedException Object
(
[message:protected] => Signed API request has returned an error. HTTP error 401. Raw Provider API response: {
"errorCode": 0,
"message": "Empty oauth2_access_token",
"requestId": "GT3BPWBLSX",
"status": 401,
"timestamp": 1520772798106
}.

//This is my method........
public function postToLinkedin($lnAppkey,$lnAppSec,$lnToken)
{
if($lnAppkey !=null && $lnAppSec !=null && $lnToken !=null)
{
$_SESSION['app_id_linkedIn'] = $lnAppkey;
$_SESSION['app_sec_linkedIn'] = $lnAppSec;
$_SESSION['access_token_linkedIn'] = $lnToken;
}

    $config = [
        'callback' => $request->getBaseUrl().'/socialpost/application/postToLinkedin',
        "enabled" => true,
        'keys' => [
            'key' => $_SESSION['app_id_linkedIn'],
            'secret' => $_SESSION['app_sec_linkedIn']
        ],

    ];
// Instantiate LinkedIn Adapter.
$linkedin = new Hybridauth\Provider\LinkedIn($config);

// Authenticate the user.
$linkedin->setAccessToken($_SESSION['access_token_linkedIn']);

// Update the user status.
$response = $linkedin->setUserStatus([
'comment' => '',
'content' => [
'title' => 'This is a post',
'description' => "I am trying to post a demo content",
'submitted-url' => '',
'submitted-image-url' => '',
],
'visibility' => [
'code' => 'anyone',
],
]);

}

**Comment by ApacheEx** [comment]
it seems you have setted a wrong access token.

can you show me how your access token looks like:

`var_dump($_SESSION['access_token_linkedIn']);`


which exactly the version of HA you use?

**Comment by RajeshPerro** [comment]
Thank you so much for your ans. 
here is my access token : AQVLaqdfaYilBc24a5C4b8h9c3MqVyWu8s-ojpsuehrPy_GDgxy7B1EWY4X2W1nJZ3Mro42e-djjEWXIOL9A6af91L-n34TWNt9A_jQWgJDTYLUYAYGJltbF7vdcXhC7GHjjrCHGIZVv3v9OBHnRFfjqb3DwsQMRvwxdbS3DO_73Z6xWjMgZyqhxLRlVnq3WZQeLY2yhNoTSUhLxHBRF1sZvWkyY2Kb49Zp8BZTbrLzgKGjAx9MchGk2Iw7_oiBZq_UqBrHioet9C8Yzu0lGjXnBZhmjJu4ccBZ-y7AVYUaagFXShsOu3NfnnO1sphiZ9wXPuNynQ6tUI4MUlWE_ZXBWEZ871Q
HA : I just downloaded the Zip from here. It says the version is : Hybridauth 3.0 Progression

**Comment by ApacheEx** [comment]
try this:
```php
$linkedin->setAccessToken(['access_token' => $_SESSION['access_token_linkedIn']]);
```

**Comment by RajeshPerro** [comment]
No..It's not working.. even I tried like this : 
    // $linkedin->setAccessToken(['access_token' => $_SESSION['access_token_linkedIn']]);
                 $linkedin->setAccessToken('AQXWEKY6R77s4Df7EUuQYAmC9-MWMQ0xBlINM8EyxFWe8xukfYHza3majKOcAlHY7jEdJjpRAuUtyVKzkjKCgm4XGnmiaKb7phEVAOvjbnAnRnMEgZD1gDzgKnwNpNP07pvNmD4vVW5GiYWD9GpwFd9vQc9zmN9MJRz08WE53YlQWAfO45sr0uop--t_Xb3c3ook9haRblTBLcm8mRLDEChvh9yH6R3IEs1oKLtdra_Vms_7GL3kDQ3qbCKFrxBtxcXG7nOHodp_GsmpFAoImuVA3xD9vAio8bK292Ud8opNxElb17Mb5sDzQwu_46i8cBu7GPeChTefsqz9v4vcDRk0djVl-Q');

**Comment by ApacheEx** [comment]
first of all, how you get the access token?

**Comment by ApacheEx** [comment]
btw, `setAccessToken` accepts an array with keys: `access_token`, `refresh_token` and so on.

**Comment by RajeshPerro** [comment]
Hi, 
this is how I get access token.. This method is responsible to get access token and return it. Then I store it in DB.
public function linkedinAction()
    {
        $request = $this->getRequest();
        $payload2=null;
        if(isset($_POST['app_id']) && isset($_POST['app_sec'] ))
        {
            $_SESSION['app_id_linkedIn']= $_POST['app_id'];
            $_SESSION['app_sec_linkedIn']= $_POST['app_sec'];
        }
        $config = [
            'callback' => $request->getBaseUrl().'/socialpost/login/linkedin',
            "enabled" => true,
            'keys' => [
                'key' =>  $_SESSION['app_id_linkedIn'],
                'secret' =>  $_SESSION['app_sec_linkedIn']
            ],
            "scope" => "r_basicprofile,r_emailaddress"
        ];
        try {
            $li = new Hybridauth\Provider\LinkedIn($config);
            $li->authenticate();
            $profile = $li->getUserProfile();
            if (!empty($profile)) {
                $token = $li->getAccessToken();
                $payload2['token1']=$token;
                $payload2['profile']=$profile;
            }
        } catch (Exception $e) {
            (new Hybridauth\Storage\Session())->clear();
           $payload2=['error' => $e.getErrorMessage()]
        }
        $this->_sendJson($payload2);
    }

**Comment by ApacheEx** [comment]
I'd recommend you to avoid using 'scope' in config because it's already good for linkedin provider.

some code:
```php
// Config for generating access token.
$config = [
  'callback' => $request->getBaseUrl() . '/socialpost/login/linkedin',
  'enabled' => true,
  'keys' => [
    'key' => $_SESSION['app_id_linkedIn'],
    'secret' => $_SESSION['app_sec_linkedIn']
  ],
];

// Get access token.
$linkedin = new Hybridauth\Provider\LinkedIn($config);
$linkedin->authenticate();
$accessToken = $linkedin->getAccessToken();

// store in db serialized array with all tokens (access_token, refresh_token, etc):
serialize($accessToken) // this is how to serialize.

// then, select from db (e.g. from "tokens" column), and unserialize tokens.
$accessToken = unserialize($row->tokens);

// ..do magic...
$linkedin->setAccessToken($accessToken);
$linkedin->setUserStatus(....);
``` 

Make sure you have correct scope in linkedin app:
![image](https://user-images.githubusercontent.com/1918108/37291626-b0cd5a14-2617-11e8-84e7-fe713c42f639.png)

**Comment by ApacheEx** [comment]
any updates?

**Comment by RajeshPerro** [comment]
Okay, the thing is it was urgent for me, and I did the same thing and it was not working for me. So I shifted myself for other library.

**Comment by ApacheEx** [comment]
clear for me, you gave up. It works well even in production for long time - just your code is wrong.
