### ISSUE TITLE
Can this also Authenticate against an external system?

### ISSUE THREAD

**Issue by jonathanasbell** [hybridauth/hybridauth#929]
Can this also Authenticate against an external system? Does this include the workflow for login, logout, sign up, retrieve pw, create new pw, prompt for login etc? I have also seen https://wordpress.org/support/topic/does-this-include-a-workflow/

**Comment by ApacheEx** [comment]
Hybridauth provides social network login, so no passwords at all. It can be used as a library for any CMS(F). For example: https://www.drupal.org/project/hybridauth - integrates the HA library into Drupal login / register / reset password processes. That's a good example how it should be. 

Hope it's clear.
