### ISSUE TITLE
state param for Facebook always overwritten in OAuth2.php

### ISSUE THREAD

**Issue by arnoldjan** [hybridauth/hybridauth#931]
## Bug or question

In the documentation of the User Authentication I read the following:

> /**
>     * Optional: Custom Provider's Authorize Url Parameters
>     *
>     * Certain providers enables you to customize the authorization url which you can optionality pass in 
          adapter's config
>     * as an associative array.
>     */
>     'authorize_url_parameters' => [
>            'approval_prompt' => 'force',
>            'access_type'     => 'offline',
>            'hd'              => ..,
>            'state'           => ..,
>            //And so on.
>     ],
> 

But the 'state' param seems not to work. It is always overwritten in the code.
In /src/Adapter/OAuth2.php Line 435ff

>
>if ($this->supportRequestState) {
>     $state = 'HA-' . str_shuffle('ABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890');
>     $this->storeData('authorization_state', $state);
>     $this->AuthorizeUrlParameters['state'] = $state;
>}

Am I missing something or is this a wanted behavior and the state param is just not working anymore, so the documentation is missleading?

### Version and provider

I was trying to use the state param for the Facebook provider to provide a custom value for the state.

**Comment by ApacheEx** [comment]
Hi,
why do you need to provide a custom value for `state` param? 
It's already done by HA - each request with random `state` param.

Here is what `state` means:
>`state`. A string value created by your app to maintain state between the request and callback. This parameter should be used for preventing Cross-site Request Forgery and will be passed back to you, unchanged, in your redirect URI.

Here is how HA generates `state`:
```php
$state = 'HA-' . str_shuffle('ABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890');
$this->storeData('authorization_state', $state);
$this->AuthorizeUrlParameters['state'] = $state;
```

Here is how HA makes a check:
```php
if (
  $this->supportRequestState &&  
  $this->getStoredData('authorization_state') != $state
) {
  throw new InvalidAuthorizationStateException(
    'The authorization state [state=' . substr(htmlentities($state), 0, 100). '] '
    . 'of this page is either invalid or has already been consumed.'
  );
}
```


do not see any problems, it works like a charm.

**Comment by ApacheEx** [comment]
and btw in HA documentation, it says: 
> In the following example we'll demonstrate who to sign a user with Google

so, nothing related to Facebook.

**Comment by ApacheEx** [comment]
But seems you are right, if I want to provide state manually (so, own logic) 
I can't do it. Because it always overridden in OAuth2.php.

**Comment by arnoldjan** [comment]
I want to pass a custom value to the state param to pass variables to the callback URL. I know that the state param is supposed to be used for CSRF but FB also recommends it for this here:
https://developers.facebook.com/docs/facebook-login/security/#strict_mode

> For apps with dynamic redirect URIs, use the state parameter to pass back the dynamic information to a limited number of redirect URIs. Then add each of the limited redirect URIs to the Valid OAuth redirect URIs list.

**Comment by ApacheEx** [comment]
done, try to add in config:

```
  'authorize_url_parameters' => [
      'state' => 'YOUR_CUSTOM_STATE_PARAM',
   ],
```

**Comment by tamaranga** [comment]
@ApacheEx Do you know, if there was a similar `state` to prevent CSRF in Hybridauth v2?
https://github.com/hybridauth/hybridauth/blob/v2/hybridauth/Hybrid/Providers/Facebook.php#L89
