### ISSUE TITLE
Can't load URL: The domain of this URL isn't included in the app's domains. error in Facebook

### ISSUE THREAD

**Issue by nuryagdym** [hybridauth/hybridauth#932]
I have installed v2.10 version of hybridauth. Trying to login using Facebook. It redirects me to: 

https://www.facebook.com/v2.8/dialog/oauth?auth_type=rerequest&client_id=some_id&state=some_state&response_type=code&sdk=php-sdk-5.6.2&redirect_uri=https://www.some_domain.com/index.php/auth/endpoint?hauth_done=Facebook&scope=public_profile,email

and showing me this pop up error on that page: 
 "Can't load URL: The domain of this URL isn't included in the app's domains. To be able to load this URL, add all domains and sub-domains of your app to the App Domains field in your app settings." 

I added "https://www.some_domain.com/index.php/auth/endpoint" this url  to "Valid OAuth Redirect URIs" but it does not help.

I have my own implementation of integration with facebook graph sdk v5 and its working fine. But now I want to use hybridauth...

**Comment by nuryagdym** [comment]
I decided to try Hybridauth v3.0 beta version. It is working fine. I will leave as it is for now

**Comment by ApacheEx** [comment]
can you screen or type what exactly you have in Valid OAuth Redirect Uris.

check here: https://developers.facebook.com/apps/YOUR_APP_ID/fb-login/settings/

because for v2.10: valid OAuth Redirect Uris should be the following:

```
http://mywebsite.com/path_to_hybridauth/?hauth_done=Facebook
```

**Comment by ApacheEx** [comment]
I will close this issue for now, try solution from my comment above.

p.s. feel free to reopen if it still doesn't work.

**Comment by ApacheEx** [comment]
also, you have to upgrade `php-graph-sdk` to the latest stable. See https://github.com/facebook/php-graph-sdk/issues/963
