### ISSUE TITLE
Curl Options

### ISSUE THREAD

**Issue by CHrycyna** [hybridauth/hybridauth#933]
## Bug

When you get an adapter from the Hybridauth object, it will only include the providers options and the 'callback' config. It will not include 'debug_mode', 'debug_file' and 'curl_options' in the config when creating the providers adapter. I noticed this issue when trying to include the proxy option for curl.

### Version and provider

V3 - All Providers

### Reproduction

This can be reproduced by creating a Hybridauth object with the curl proxy options. Get and inspect one of the providers adapters (ie. Facebook). You should noticed that the curl proxy option is not set in the providers adapter.

**Comment by ApacheEx** [comment]
Hi,

I think for debug you need to use:
```php
$this->logger->debug('Whatever you want to debug');
```


`curl_options` will be included automatically in `HttpClient` which is CURL by default.

if you use custom http client via `setHttpClient` you need to implement `setCurlOptions` method.

is it clear ? if so, pls close the issue
