### ISSUE TITLE
Bug Can't Load Url The Domain of this url Isn't Included in the app's domain

### ISSUE THREAD

**Issue by rjrajreehan** [hybridauth/hybridauth#934]
BUG
Can't Load URL: The domain of this URL isn't included in the app's domains. To be able to load this URL, add all domains and subdomains of your app to the App Domains field in your app settings.

i had contacted the Facebook support team and they had told me to contact the script or wrapper author 
kindly look into this error am using this at https://www.jmoza.com at is wowonder script i will wait for your kind response ;)

**Comment by ApacheEx** [comment]
Hi,

1) which version of HA you have? 
2) which URL you use?

**Comment by rjrajreehan** [comment]
this is my website link https://www.jmoza.com/ try login with Facebook 
and i think i have v2.8 the screen shot from facebook app setting is also posted 
1:http://prntscr.com/ivvrm0
2:http://prntscr.com/ivvrs0

**Comment by rjrajreehan** [comment]
kindly help me out am using wowonder script you can google it inside that script they use hybridauth for facebook login

**Comment by ApacheEx** [comment]
thanks for info.

firstly, let's try to add `https://www.jmoza.com/import.php?hauth_done=Facebook` (without `scope`) to Valid OAuth Redirect URIs

**Comment by rjrajreehan** [comment]
but not sir am facing this error :( 
http://prntscr.com/ivz7yv

**Comment by rjrajreehan** [comment]
the first error was cleared now am facing the same error on my website first i was getting this error on facebook auth page now on my website page

**Comment by ApacheEx** [comment]
Ok, 
it seems the related issue https://github.com/facebook/php-graph-sdk/issues/963

To fix this, you need to update `php-graph-sdk` which is vendor library in HA. If you have composer then just `composer update`, otherwise download from [here](https://github.com/facebook/php-graph-sdk/releases/tag/5.6.2)

**Comment by rjrajreehan** [comment]
sir how can i fix it kindly tell me the both ways 1st one the way "Add your full callback url in the setting at facebook app setting"
second the update kindly please am waiting for your reply ;)

**Comment by rjrajreehan** [comment]
i go this error on here this link https://www.jmoza.com/login-with.php?provider=Facebook#_=_

**Comment by rjrajreehan** [comment]
i had done adding the callback url you gave me now what url i had to add ;(

**Comment by rjrajreehan** [comment]
i had done adding much url as much i can now tell me what i had next to do ;( 
see the screen shot http://prntscr.com/iw285r

**Comment by rjrajreehan** [comment]
Thanks a lot the issue is solved by update the sdk ;)

**Comment by ApacheEx** [comment]
cool, nice to hear that it's solved. So, as conclusion:

1) `https://www.jmoza.com/import.php?hauth_done=Facebook` should be as Valid OAuth Redirect URIs
2) `php-graph-sdk` should be upgraded to latest stable.

**Comment by fillup** [comment]
Thank you @ApacheEx , removing `&scope=email` from the "Valid OAuth Redirect URIs" url fixed it for me. I had updated php sdk and hybrid auth but that wasn't enough, also had to add the `?hauth_done=Facebook` to my url, but not include the `&email=scope` part.

**Comment by hamzazafeer** [comment]
updating the SDK solve the problem ;)
