### ISSUE TITLE
How to capture when user cancels out of login process

### ISSUE THREAD

**Issue by simmonspaul** [hybridauth/hybridauth#939]
Feature / Question

When a user in this case is sent to twitter to sign in, they are also provided an option to cancel.
If they cancel, they are taken to another screen on the social media side that states that they are not logged in and they have a button to return to my website.

I am using the basic setup with try and catch eg.
 try
    {
      $adapter = $this->hybridauth->HA->authenticate($provider_id, $params);
...
catch (Exception $e)
    {

No exception is thrown in this case.

The link from the button points directly to: 
<my webpage>/hauth/endpoint?hauth.done=Twitter&denied=cu54xgAAAAAA5UOOAAABYo6MdXA

This in turn gets digested to the expected endpoint:
<my webpage>/hauth/window/Twitter

A simple error page is thrown that I would like to capture and handle otherwise:
An Error Was Encountered
Authentication failed! Twitter returned an invalid oauth verifier.

Can anyone point me in the right direction or suggest how this can be error handled?

Hybridauth v3.0.0 RC3

Many thanks
PWS

**Comment by ApacheEx** [comment]
in v3 the easiest way is just to wrap in try/catch:

```php
 try {
            $twitter = $hybridauth->authenticate();
        }
        catch (AuthorizationDeniedException $e) {
            echo 'bu';
            exit;
        }
