### ISSUE TITLE
TwitchTV error 400 No client id specified

### ISSUE THREAD

**Issue by Theo4** [hybridauth/hybridauth#940]
Hello there,

I'm getting an error on using TwitchTV provider on HybridAuth 3.0 RC 3

```
    'TwitchTV' => [
      'enabled' => true,
      'keys' => [
        'id' => 'xxxxx',
        'secret' => 'xxxxx',
      ],
    ],
```

> Fatal error: Uncaught exception 'Hybridauth\Exception\HttpRequestFailedException' with message 'Signed API request has returned an error. HTTP error 400. Raw Provider API response: {"error":"Bad Request","status":400,"message":"No client id specified"}.' in /home/partagesuv/www/tournaments/oauth/src/Adapter/AbstractAdapter.php:360 Stack trace: #0 /home/partagesuv/www/tournaments/oauth/src/Adapter/OAuth2.php(682): Hybridauth\Adapter\AbstractAdapter->validateApiResponse('Signed API requ...') #1 /home/partagesuv/www/tournaments/oauth/src/Provider/TwitchTV.php(55): Hybridauth\Adapter\OAuth2->apiRequest('user') #2 /home/partagesuv/www/tournaments/oauth/examples/example_06/index.php(41): Hybridauth\Provider\TwitchTV->getUserProfile() #3 {main} thrown in /home/partagesuv/www/tournaments/oauth/src/Adapter/AbstractAdapter.php on line 360

Array result after login/permission given

> Array ( [TwitchTV] => Hybridauth\Provider\TwitchTV Object ( [scope:protected] => user_read channel_read [apiBaseUrl:protected] => https://api.twitch.tv/kraken/ [authorizeUrl:protected] => https://api.twitch.tv/kraken/oauth2/authorize [accessTokenUrl:protected] => https://api.twitch.tv/kraken/oauth2/token [accessTokenName:protected] => oauth_token [apiDocumentation:protected] => https://dev.twitch.tv/docs/v5/guides/authentication/ [clientId:protected] => ikp9amliqu9d23wysppu6eahqu1w6l [clientSecret:protected] => secret [accessTokenInfoUrl:protected] => [callback:protected] => http://www.shareyour.live/tournaments/oauth/examples/example_06/callback.php [AuthorizeUrlParameters:protected] => Array ( [response_type] => code [client_id] => ikp9amliqu9d23wysppu6eahqu1w6l [redirect_uri] => http://www.shareyour.live/tournaments/oauth/examples/example_06/callback.php [scope] => user_read channel_read ) [supportRequestState:protected] => 1 [tokenExchangeMethod:protected] => POST [tokenExchangeParameters:protected] => Array ( [client_id] => ikp9amliqu9d23wysppu6eahqu1w6l [client_secret] => secret [grant_type] => authorization_code [redirect_uri] => http://www.shareyour.live/tournaments/oauth/examples/example_06/callback.php ) [tokenExchangeHeaders:protected] => Array ( ) [tokenRefreshMethod:protected] => POST [tokenRefreshParameters:protected] => Array ( [grant_type] => refresh_token [refresh_token] => aueso5pw6zfxijwbytzr9zik0hkfak0s49hs7tpwhvbiodny07 ) [tokenRefreshHeaders:protected] => Array ( ) [apiRequestParameters:protected] => Array ( ) [apiRequestHeaders:protected] => Array ( [Authorization] => Bearer kquwfvdq95ruh0rzmbl1s2zg636oyl ) [providerId:protected] => TwitchTV [config:protected] => Hybridauth\Data\Collection Object ( [collection:protected] => stdClass Object ( [enabled] => 1 [keys] => Array ( [id] => ikp9amliqu9d23wysppu6eahqu1w6l [secret] => secret) [callback] => http://www.shareyour.live/tournaments/oauth/examples/example_06/callback.php ) ) [params:protected] => [storage] => Hybridauth\Storage\Session Object ( [storeNamespace:protected] => HYBRIDAUTH::STORAGE [keyPrefix:protected] => ) [httpClient] => Hybridauth\HttpClient\Curl Object ( [curlOptions:protected] => Array ( [13] => 30 [78] => 30 [64] => [81] => [19913] => 1 [52] => 1 [68] => 5 [2] => 1 [10102] => identity [10018] => HybridAuth, PHP Social Authentication Library (https://github.com/hybridauth/hybridauth) ) [requestArguments:protected] => Array ( ) [requestHeader:protected] => Array ( [Accept] => */* [Cache-Control] => max-age=0 [Connection] => keep-alive [Expect] => [Pragma] => ) [responseBody:protected] => [responseHeader:protected] => Array ( ) [responseHttpCode:protected] => 0 [responseClientError:protected] => [responseClientInfo:protected] => Array ( ) [logger:protected] => Hybridauth\Logger\Logger Object ( [level:protected] => none [file:protected] => ) ) [logger] => Hybridauth\Logger\Logger Object ( [level:protected] => none [file:protected] => ) [validateApiResponseHttpCode:protected] => 1 ) )

I'm able to permit the Twitch app, it redirect me to the index page of the example_06 and giving me this error. Can't handle user infos etc then.

How is it possible to resolve this?

Many thanks,

**Comment by ApacheEx** [comment]
yeah, urls were changed to https://id.twitch.tv/

should be easy to fix. Will take care about it a bit later

**Comment by cookieman768** [comment]
When you update this could you use the [new Twitch API](https://dev.twitch.tv/docs/api/)? The other two are going to be deprecated at the end of 2018.

**Comment by ApacheEx** [comment]
@cookieman768, why not. Should be fixed during this week. PRs are welcome.

**Comment by cookieman768** [comment]
I've tinkered around with this and got it working in my test environment. I'll upload what I have in a PR.

**Comment by ApacheEx** [comment]
should work now in the latest v3, it uses a new Twitch API 🚀
