### ISSUE TITLE
List of provider key types, and returned dataset?

### ISSUE THREAD

**Issue by neokio** [hybridauth/hybridauth#945]
1) Is there a table showing which providers use "id" and which use "key"?
2) Is there a table showing which scopes are supported by which provider, and what data/records each scope returns?

It would probably take me a day to go through the hybridauth code, compiling and double-checking this info. So I thought I'd post here to check if such a thing is buried in the docs somewhere, and if not, to suggest adding this extremely useful bit of data to the docs.

Thank you all for this excellent resource!

**Comment by ApacheEx** [comment]
can you tell me which version of Hybridauth you use?

**Comment by neokio** [comment]
The latest v3

**Comment by ApacheEx** [comment]
1. For the latest v3 doesn't matter if you use `id` or `key` - both are valid. 💯 
    _p.s._ For older versions: `key` is used for providers based on OAuth1, and `id` is used for providers based on `OAuth2`.

2. I don't think so. Currently, each provider has `$apiDocumentation` which is the link to provider documentation where you can find scope / fields and so on. This information is available in the code.

For example Facebook docs: https://github.com/hybridauth/hybridauth/blob/master/src/Provider/Facebook.php#L65
