### ISSUE TITLE
Discord UserProfile add discriminator

### ISSUE THREAD

**Issue by yamikaitou** [hybridauth/hybridauth#949]
## Bug, feature or question?

Is this a bug, a feature request or a question? **Feature Request**

Give us a short description. **Pass _discriminator_ back when using getUserProfile. Discord names are made up of their Username and a Discriminator since the Username is not guaranteed to be unique. Example is that my Discord name is _YamiKaitou#0003_ where YamiKaitou is my Username and 0003 is my Discriminator and the # is a separator used by the Discord App.**

### Version and provider

What version of Hybrid Auth does this relates to? **3.x**

Is this an issue with a provider? If yes, which one? **Discord**

### Reproduction

How can we replicate this issue? **N/A**

**Comment by ApacheEx** [comment]
good, this makes sense for me. Available in `master` / `3.0.x-dev`
