### ISSUE TITLE
Message: Authentication failed! Google returned an error: access_denied

### ISSUE THREAD

**Issue by cdmathukiya** [hybridauth/hybridauth#950]
when i am trying to login in google and i am giving permission then it's login and working fine.

![fireshot capture 9 - sign in - google accounts_ - https___accounts google com_signin_oauth_consent](https://user-images.githubusercontent.com/18529326/39127573-0a0ed14e-4723-11e8-9176-e5ccab3a42c6.png)

But, i am click on cancel button on permission popup it will give error like
![fireshot capture 7 - - http___localhost_social_hauth_login_google](https://user-images.githubusercontent.com/18529326/39127577-0eb4d27a-4723-11e8-82f9-a4a0d4371af6.png)

**Comment by ApacheEx** [comment]
yeah, you need to use try / catch for this. Something like this:

```php
try {
  $hybridauth = new Hybrid_Auth( $config );
  $adapter = $hybridauth->authenticate( "Google" );
 
  $user_profile = $adapter->getUserProfile();
}
catch (Exception $e) {
  // Handle error more friendly by $e->getCode() and $e->getMessage();
}
```
