### ISSUE TITLE
Get user data using user_token

### ISSUE THREAD

**Issue by aa-ahmed-aa** [hybridauth/hybridauth#951]
i want to get the user data like email,name,... etc using user_token returned from the api
for example iam using google login and the api redirected to the redirect uri with code parameter in thhe _GET i want to use this parameter to get the user details

**Comment by ApacheEx** [comment]
I think you should use HA for your case:

```php
// Instantiate Google Adapter.
$adapter = new Hybridauth\Provider\Google($config);

// Authenticate using Google
$adapter->authenticate();

// Retrieve User's profile.
$userProfile = $adapter->getUserProfile();

// Access User's display name
echo 'Hi ' . $userProfile->displayName;
```


if somehow this is not possible - then this library won't help you.
