### ISSUE TITLE
set different callbacks for different providers

### ISSUE THREAD

**Issue by aa-ahmed-aa** [hybridauth/hybridauth#952]
i want to set different callbacks for different providers 
i want to restructure the $config variable for this task to be like this 
```

static $config = [
		    //Location where to redirect users once they authenticate with a provider

		    //Providers specifics
		    'providers' => [
		        
		        'Twitter' => [
		            'enabled' => true,
                            'callback' => 'http://earabic.com/student/social_login/Google',
		            'keys' => [
		                'key'    => '',
		                'secret' => ''
		            ]
		        ],

		        'Google'   => [
		        	'enabled' => true,
		        	 'callback' => 'http://earabic.com/student/social_login/Google',
                                 'keys' => [ 
		        		'id'  => '211910392231-6jb3ogn83lmhnrpg28qkbplhohucjj25.apps.googleusercontent.com',
		        		'secret' => 'lNM1-ZHRQ6veJ1f3jx_KuGqE'
		        	]
		        ],

		        'Facebook' => [
		        	'enabled' => true,
                                'callback' => 'http://earabic.com/student/social_login/Google',
		        	'keys' => [
		        		'id'  => '',
		        		'secret' => ''
		        	]
		    	]
		    ]
		];

```

**Comment by ApacheEx** [comment]
are you talking about v2 or v3 ?

**Comment by aa-ahmed-aa** [comment]
v3

**Comment by aa-ahmed-aa** [comment]
i think it's a logic wise to have different callbacks for different providers, i'm working on it i'll contribute it when i'm done.

**Comment by ApacheEx** [comment]
@aa-ahmed-aa `example_06` has one callback and use multiple providers. So, it's not a problem. You can also try to use some GET param to recognize provider. Of course, if you contribute we will check it 🙂

**Comment by aa-ahmed-aa** [comment]
`example_06` is an example of multiple providers with the same callback in the `$config` array i want the structure of the `$config` array to handle different callbacks for different providers

**Comment by ApacheEx** [comment]
@aa-ahmed-aa,
I wanna say that different callbacks doesn't make sense at all. And you can use just one callback with provider as query param

**Comment by ApacheEx** [comment]
multiple callbacks will increase complexity. There is no plan to support it.
