### ISSUE TITLE
Facebook logins no longer work

### ISSUE THREAD

**Issue by MastaBaba** [hybridauth/hybridauth#957]
## Bug

Now, when trying to login with Facebook, this is the end result of the login procedure:

> Signed API request has returned an error. HTTP error 400. Raw Provider API response: {"error":{"message":"The access token is invalid since the user hasn't engaged the app in longer than 90 days.","type":"OAuthException","code":190,"error_subcode":493,"fbtrace_id":"EALaIqC7Yf2"}}

Someone else mentions getting the same response, seemingly not with Hybridauth, meaning this could be a Facebook issue, not a Hybridauth issue. Mention of same response:

https://stackoverflow.com/questions/50124462/facebook-graph-api-rejects-newly-created-access-token

### Version and provider

I'm getting this on 3.0.0-rc.5 and 3.0.0-rc.4, trying to login with Facebook.

**Comment by ApacheEx** [comment]
Seems FB bug, let's wait for response there:
https://developers.facebook.com/bugs/194772814474841/

**Comment by MastaBaba** [comment]
Bug was with Facebook and has been resolved.
