### ISSUE TITLE
Add support for OpenID Connect

### ISSUE THREAD

**Issue by filips123** [hybridauth/hybridauth#960]
Does HybridAuth (3.0) support OpenID Connect? If not, please support it.

OpenID Connect 1.0 is a simple identity layer on top of the OAuth 2.0 protocol. It allows Clients to verify the identity of the End-User based on the authentication performed by an Authorization Server, as well as to obtain basic profile information about the End-User in an interoperable and REST-like manner.
More info on http://openid.net/connect/

**Comment by CallumBrankin** [comment]
It looks like HybridAuth 3.0 supports OpenID, which is different to OpenID Connect. @ApacheEx Is this the case?

**Comment by filips123** [comment]
OpenID Connect is build on top of the OAuth 2.0, which is already supported by HybridAuth, so it should not be hard to implement it.

**Comment by chrisgraham** [comment]
Many of the provider profile APIs are actually implemented using OpenID Connect, it's just not really made explicit in the code.

**Comment by ApacheEx** [comment]
I'm closing this issue, since HA fully supports it.
