### ISSUE TITLE
[Dribbble] Dribbble adapter is using deprecated API v1

### ISSUE THREAD

**Issue by thedotedge** [hybridauth/hybridauth#962]
## Bug

All Dribbble adapter calls (i.e. `getUserProfile`) are failing with:
```
Signed API request has returned an error. HTTP error 401. Raw Provider API response: {
  "message": "This version of the API is deprecated. This application must use v2: http://developer.dribbble.com/v2/"
}.
```

### Version and provider
v3.0.0-rc5
`Hybridauth\Provider\Dribbble`

**Comment by bologer** [comment]
change `v1` to `v2` in provider and it solved the problem, but should be updated for sure

**Comment by ApacheEx** [comment]
Released in rc7 🥇
