### ISSUE TITLE
?hauth.start=Google&hauth.time=1528916580 

### ISSUE THREAD

**Issue by aavrug** [hybridauth/hybridauth#975]
## Bug, feature or question?

Is this a bug, a feature request or a question?
This is a bug.

Give us a short description.
I have provided proper base_url but still, when I am calling login and passing provider, it's redirecting to the host with "?hauth.start=Google&hauth.time=1528916580 "

### Version and provider

What version of Hybrid Auth does this relate to?
^2.11

Is this an issue with a provider? If yes, which one?
I didn't use others right now, only configured Google and facing this issue.

### Reproduction

How can we replicate this issue?
I am using Yii2. I created a method which is accessible from URL also this was in my base_url and In that method, I have written
```
public function actionSocialLogin() {
    require_once Yii::getAlias('@vendor').'/hybridauth/hybridauth/hybridauth/index.php';
}
```

**Comment by manu1222** [comment]
I got a similar issue with version 2, but with version 3 it's working.

**Comment by ApacheEx** [comment]
I'm closing this issue since v2 is under Maintenance mode.
