### ISSUE TITLE
Can't Load Url The Domain of this url Isn't Included in the app's domain

### ISSUE THREAD

**Issue by Nemra1** [hybridauth/hybridauth#979]
hello..
im using WoWonder script and i have hard problem with login with facebook
and this script used hybridauth 2.8.2 
idont know why this happend but all my setting is right and nothing miss
Subdomain: https://app.nemra-1.com
login URL:https://app.nemra-1.com/login-with.php?provider=Facebook
Redirect url : https://app.nemra-1.com/import.php?hauth.done=Facebook
and this is my live link
https://www.facebook.com/v2.8/dialog/oauth?auth_type=rerequest&client_id=810104762515966&state=a352ff8001da96b9c72375b83dce2cfb&response_type=code&sdk=php-sdk-5.4.4&redirect_uri=https%3A%2F%2Fapp.nemra-1.com%2Fimport.php%3Fhauth_done%3DFacebook&scope=email

![42291163-54fceab2-7fca-11e8-93df-beb8e315eb69 1](https://user-images.githubusercontent.com/22897987/42293040-4ef8f630-7fd7-11e8-878b-766aacb4d052.png)
![42291166-5866dd5c-7fca-11e8-8c96-94f7aba30b95 1](https://user-images.githubusercontent.com/22897987/42293045-5d95eca2-7fd7-11e8-8518-13577bd0d212.png)
![42291169-5b073052-7fca-11e8-880c-9b1617a8453d 1](https://user-images.githubusercontent.com/22897987/42293049-64f3627c-7fd7-11e8-8f51-f9001f6a353f.png)

any help about that

**Comment by ApacheEx** [comment]
Hi, pls try to add this URL to _Valid OAuth Redirect Uris_:
- https://app.nemra-1.com/import.php?hauth_done=Facebook

so, instead `hauth.done` use `hauth_done` as mentioned [here](https://hybridauth.github.io/hybridauth/userguide/IDProvider_info_Facebook.html).

**Comment by Nemra1** [comment]
im try this link but now 
Facebook Graph returned an error: Error validating client secret. Try again
![2018-07-05_121919](https://user-images.githubusercontent.com/22897987/42317866-aeff3ea6-804d-11e8-973f-206485d64a07.png)

**Comment by ApacheEx** [comment]
have you checked if your client secret is correct in the HA config? please check twice.

**Comment by Nemra1** [comment]
yes it was wrong but after fixed in panle i see this
DateTime::__construct(): It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone. Try again

**Comment by ApacheEx** [comment]
This issue is related only to your server.
Please configure `date.timezone` setting in your php.ini.
