### ISSUE TITLE
Tumblr URL enpoints need to be updated

### ISSUE THREAD

**Issue by renieravin** [hybridauth/hybridauth#980]
Tumblr returns this response: 

> oauth_signature does not match expected value.

The Tumblr endpoints in [https://github.com/hybridauth/hybridauth/blob/master/src/Provider/Tumblr.php](url) need to be updated to the https versions, as outlined here: [https://www.tumblr.com/docs/en/api/v2#auth](url)

**Comment by PowerKiKi** [comment]
This should have been closed when merging #993
