### ISSUE TITLE
Authentication failed! Twitter returned an error. 403 Forbidden: The request is understood, but it has been refused.

### ISSUE THREAD

**Issue by mansionsoftware** [hybridauth/hybridauth#981]
Hi,
In our website we have an option for users to login using twitter (Developed using hybridauth). It is working fine for the last 1 year, now it has an issue.

When I click on "Login with twitter", it returns back to the website/callBackURL without showing the twitter login page.

I debugged the script and got this error "Authentication failed! Twitter returned an error. 403 Forbidden: The request is understood, but it has been refused."

Can anyone help me on this error and provide me some suggesstions to solve this issue.

Thanks

**Comment by ApacheEx** [comment]
👋
seems server issue, but which exactly version of HA are you using?

**Comment by mansionsoftware** [comment]
I have updated the latest version 2.11.0 still facing the issue. 

Can you give me any ideas what would be the issue in server.

**Comment by ApacheEx** [comment]
can you provide a full error, there should be an explanation.

**Comment by mansionsoftware** [comment]
This is the error I am receiving.
Fatal error: Uncaught exception 'Exception' with message 'Authentication failed! Twitter returned an error. 403 Forbidden: The request is understood, but it has been refused.' in /var/www/html/hybridauth_api/vendor/hybridauth/hybridauth/hybridauth/Hybrid/Auth.php:173

**Comment by ApacheEx** [comment]
this seems your server issue or some Twitter restrictions (e.g. too many posts or so). There is nothing related to HA.

**Comment by mansionsoftware** [comment]
Hi thanks for the response.

Our customer use the Login option totally around 10 to 15 times a day. Can you provide me where to check the RATE LIMIT for the login process.

**Comment by ApacheEx** [comment]
here it is: https://developer.twitter.com/en/docs/basics/rate-limiting.html

**Comment by mansionsoftware** [comment]
Does the twitter app need any verification/review?

And in HA is there any error handling method to handle the Rate Limit exceed issue?

**Comment by ApacheEx** [comment]
Does the twitter app need any verification/review?
<<
I don't think so.

And in HA is there any error handling method to handle the Rate Limit exceed issue?
<<
use try / catch. This is v2 which is in maintenance mode. 
You can submit PR to improve it in v3. 
Currently there is no plan to do anything here.

**Comment by mansionsoftware** [comment]
okay thanks

**Comment by VitalyTrembach** [comment]
Hi! I have the same issue with Twitter oauth. I add try..catch statements and now I see the issue Geo location is not defined. Authentication failed! Twitter.

I use PHP Version 5.6.4-4ubuntu6.4
Could you give me a hint what I should change to fix it?

I use  version 2.11.0 
Thanks!

**Comment by Allan-Nava** [comment]
I got the same error!

**Comment by aotx** [comment]
Had this issue as well, was because of an incorrect callback URL for Twitter and a Consent Screen verification requiring confirmation for Google.
To see what your own issue is, enable debugging, near the bottom of the config.php file. Then check the log file it writes out to.

**Comment by ao** [comment]
Had this issue as well, was because of an incorrect callback URL for Twitter and a Consent Screen verification requiring confirmation for Google.
To see what your own issue is, enable debugging, near the bottom of the config.php file. Then check the log file it writes out to.

**Comment by sajidwaseem786** [comment]
go same error
