### ISSUE TITLE
[Facebook] URL not working, tried everything, need help

### ISSUE THREAD

**Issue by jfloury** [hybridauth/hybridauth#982]
Hello,

My website runs under domain www.handianim.fr
I don't have composer.

I use latest version 2 of HybridAuth (not version 3 but latest 2)
in my config.php, I have :

$base_url = "https://www.handianim.fr/kalon/outils/hybridauth/index.php";

        "Google" => array(
            "enabled" => true,
            "scope" => "https://www.googleapis.com/auth/userinfo.profile https://www.googleapis.com/auth/userinfo.email",
            "keys" => array(my secret keys),
        ),
        "Facebook" => array(
            "enabled" => true,
            "keys" => array(my secret keys,
            "scope"=> array("email") ,
            "trustForwarded" => false,

In google API, for URLS I have put :
https://www.handianim.fr/kalon/outils/hybridauth/index.php?hauth.done=Google
https://www.handianim.fr/kalon/outils/hybridauth/index.php?hauth_done=Google

In facebook API, I have put :
Domains for the app : handianim.fr www.handianim.fr

 And in URLs :
https://www.handianim.fr/kalon/outils/hybridauth/index.php?hauth_done=Facebook&scope=email

It works perfectly on Google

BUT facebook says :
Impossible de charger cette URL: Le domaine de cette URL n’est pas inscrit dans ceux de l’application. Pour pouvoir importer cette URL, ajoutez tous les domaines et sous-domaines de votre application au champ Domaines des paramètres de l’application.

Which in english says that the redirect URL is not listed... BUT IT IS

I have sniffed the return error URL which contains :
redirect_uri=https%3A%2F%2Fwww.handianim.fr%2Fkalon%2Foutils%2Fhybridauth%2Findex.php%3Fhauth_done%3DFacebook&scope=email

=> That's why I appened the scope to my redirect URL, but it doesn't work either

I have tried so much things that I'm begging for help
Thank you

**Comment by ApacheEx** [comment]
try to put URL without `scope` in FB App settings 🤞 
https://www.handianim.fr/kalon/outils/hybridauth/index.php?hauth_done=Facebook

**Comment by jfloury** [comment]
Thank you for your reactivity.

I tried this, but no success : I receive the same message again.

**Comment by jfloury** [comment]
Do I have to update the fb SDK ? If YES, I don't understand how to do that without composer.

**Comment by ApacheEx** [comment]
let's try, but I'm not sure if it helps:

You need to download https://github.com/facebook/php-graph-sdk/releases/tag/5.6.3 and put it under `/Hybrid/thirdparty/` directory.
- Make sure that /Hybrid/thirdparty/Facebook/autoload.php exists.
- Hybridauth will include this file and start using the classes that library provides.


can you also make a screen how /fb-login/settings/ look like

**Comment by jfloury** [comment]
I don't have to include the autoload somewhere ? it will include it ?

**Comment by ApacheEx** [comment]
yes, you don't have to include the autoload. It's done automatically by HA

**Comment by jfloury** [comment]
It is done, but unfortunately no success

**Comment by jfloury** [comment]
can you also make a screen how /fb-login/settings/ look like => what do you mean ? do you want screenshots of facebook?

**Comment by ApacheEx** [comment]
yes, I want to see OAuth Redirect Uris and other settings.

**Comment by jfloury** [comment]
![capture1](https://user-images.githubusercontent.com/40885024/42498618-edfb52ce-842c-11e8-8d6f-7deaaa4050d2.PNG)
![capture2](https://user-images.githubusercontent.com/40885024/42498619-ee128a52-842c-11e8-825b-5d19e1add756.PNG)

**Comment by ApacheEx** [comment]
please try to add this URL as well (so, without index.php):
https://www.handianim.fr/kalon/outils/hybridauth?hauth_done=Facebook

**Comment by jfloury** [comment]
It is done... same error (sorry)...

**Comment by ApacheEx** [comment]
have no idea what's wrong. I have the same settings but in my case it works well.

**Comment by jfloury** [comment]
I'm so sad !

**Comment by ApacheEx** [comment]
what is the base_url in your config?

**Comment by jfloury** [comment]
https://www.handianim.fr/kalon/outils/hybridauth/index.php

Le mar. 10 juil. 2018 à 12:09, Oleg Kuzava <notifications@github.com> a
écrit :

**Comment by ApacheEx** [comment]
try `https://www.handianim.fr/kalon/outils/hybridauth/`

forward slash at the end is required.

so, it should be like this:

HA config:
"base_url" => `https://www.handianim.fr/kalon/outils/hybridauth/`


Facebook:
Valid OAuth Uris:
`https://www.handianim.fr/kalon/outils/hybridauth/?hauth_done=Facebook`
`https://www.handianim.fr/kalon/outils/hybridauth?hauth_done=Facebook`

**Comment by jfloury** [comment]
Seems to work !
Can I send you flowers from France ?

**Comment by ApacheEx** [comment]
awesome, glad to hear that. 💪
