### ISSUE TITLE
Activate/Enable Logger not working

### ISSUE THREAD

**Issue by mansionsoftware** [hybridauth/hybridauth#983]
Hi,
  In hybridAuth config I have provided the following details,
 "debug_mode" => true,
 "debug_file" => "/tmp/hybridAuthLog.log", 

But this not generated any log file in the path. Is there any other reference to create a log file for debugging.

Please let me know.

Thanks

**Comment by ApacheEx** [comment]
does this path is writable ? do you have an access to modify it?

**Comment by mansionsoftware** [comment]
Yes the path is writable. And I have access to modify it.

**Comment by Shade-** [comment]
If you are extending `Hybridauth` class, try with the following code in your class constructor:

```$this->logger = new Logger('debug', 'file path');```

**Comment by ApacheEx** [comment]
I'm closing this issue since v2 is under Maintenance mode.
