### ISSUE TITLE
LinkedIn complains about missing "state" parameter

### ISSUE THREAD

**Issue by utrenkner** [hybridauth/hybridauth#988]
## Bug, feature or question?
This probably is a bug.

We have been using Facebook social login for some time, and yesterday we added Google and LinkedIn. Everything worked fine. But today, I cannot login to LinkedIn anymore: LinkedIn complains 'You need to pass the "state" parameter'.

I found the same behaviour on at least one other site, of which I know that they use Hybridauth + LinkedIn. The LinkedIn recommendation has included the state parameter for a long time. I assume that they have now started to handle it more strictly.

### Version and provider
2.10.0 with LinkedIn

### Reproduction
Set up social login with LinkedIn and see what happens.

**Comment by pferlito** [comment]
Seeing the same behavior in my app, using 2.10.0. LinkedIn requires the ‘state’ parameter according to their [docs](
https://developer.linkedin.com/docs/oauth2#).

**Comment by utrenkner** [comment]
Thanks @pferlito - it was your bug report at Drupal today, which made me think that this was not just *my* fault. I just created a patch which fixes the problem for me, see PR above.

You do not need to wait for a new v2 version. Just swap the LinkedIn-Provider against the patched one: https://raw.githubusercontent.com/utrenkner/hybridauth/dab0acaaf9b7e8a55cdb5fa373b0665ea8b877a3/hybridauth/Hybrid/Providers/LinkedIn.php

**Comment by ApacheEx** [comment]
here we go: https://github.com/hybridauth/hybridauth/releases/tag/v2.12.0

thanks everyone 🥇

**Comment by pferlito** [comment]
Thanks for the patch @utrenkner and @ApacheEx for the quick response.
