### ISSUE TITLE
Should this be really "Provider returned an expected response"?

### ISSUE THREAD

**Issue by magicsunday** [hybridauth/hybridauth#999]
https://github.com/hybridauth/hybridauth/blob/b515c3fae7669e9774718129754f334ebf3009e8/src/Adapter/OpenID.php#L171

https://github.com/hybridauth/hybridauth/blob/b515c3fae7669e9774718129754f334ebf3009e8/src/Adapter/OpenID.php#L270

**Comment by ApacheEx** [comment]
feel free to create a PR and provide more user friendly error message

**Comment by magicsunday** [comment]
The error stated an "expected" exception. Exception are never expected, only in unit tests. There is a typo. It should be "unexpected" is guess.
